### ISSUE TITLE
Failed to start the deck container instance using the docker-compose stack

### ISSUE THREAD

**Issue by gangchen03** [spinnaker/spinnaker#1019]
*Cloud Provider*

Docker-compose experimental.

*Environment*

Local Spinnaker installation using docker compose.
Mac OS 10.10.5
Docker version 1.10.3

*Feature Area*

Spinnaker component - deck

*Description*
Followed the docker-compose readme to set up Spinnaker on my local docker environment
https://github.com/spinnaker/spinnaker/tree/master/experimental/docker-compose
After starting the stack with command:
DOCKER_IP=`docker-machine ip default` docker-compose up -d
Couldn't get the browser open to spinnaker console.
Log trace of docker logs deck shows error:

npm info start deck@0.0.0
http://0.0.0.0:9000/webpack-dev-server/
webpack result is served from /
content is served from /deck
webpack: wait until bundle finished: /
Killed

npm info deck@0.0.0 Failed to exec start script
npm ERR! Linux 4.1.19-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! deck@0.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the deck@0.0.0 start script 'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js'.
npm ERR! This is most likely a problem with the deck package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs deck
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls deck
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /deck/npm-debug.log
npm info it worked if it ends with ok
npm info using npm@2.14.20
npm info using node@v4.4.1
npm info prestart deck@0.0.0
npm info start deck@0.0.0

Further looking at the docker deck instance npm.log, see following error:
node@acf18348df73:/deck$ cat /deck/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.20
3 info using node@v4.4.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart deck@0.0.0
6 info start deck@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info deck@0.0.0 Failed to exec start script
9 verbose stack Error: deck@0.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
9 verbose stack Exit status 137
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid deck@0.0.0
11 verbose cwd /deck
12 error Linux 4.1.19-boot2docker
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.4.1
15 error npm  v2.14.20
16 error code ELIFECYCLE
17 error deck@0.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
17 error Exit status 137
18 error Failed at the deck@0.0.0 start script 'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js'.
18 error This is most likely a problem with the deck package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs deck
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls deck
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

*Steps to Reproduce*
1. DOCKER_IP=`docker-machine ip default` docker-compose up -d
2. docker logs deck

*Additional Details*

**Comment by ajordens** [comment]
Closing due to lack of activity.

Feel free to reach out the Spinnaker slack if you're still seeing issues.
