### ISSUE TITLE
Deleting an application from UI throws error "Cannot read property 'providerType' of undefined"

### ISSUE THREAD

**Issue by grandmore** [spinnaker/spinnaker#1048]
I have a few old application that were automatically created by creating Replication Controllers using kubectl.

When I use the UI to delete an old application using the Bottom Delete button on the config screen I get the following error in the browser debug window. (in this case Chrome)

vendor.bundle.js:19729 TypeError: Cannot read property 'providerType' of undefined
    at Object.executeTask (http://localhost:9000/app.js:15453:32)
    at Object.deleteApplication (http://localhost:9000/app.js:30632:30)
    at Object.monitor.submit (http://localhost:9000/app.js:22904:14)
    at confirm (http://localhost:9000/app.js:22782:37)
    at fn (eval at <anonymous> (http://localhost:9000/vendor.bundle.js:24079:16), <anonymous>:4:263)
    at expensiveCheckFn (http://localhost:9000/vendor.bundle.js:25168:19)
    at callback (http://localhost:9000/vendor.bundle.js:35147:18)
    at Scope.$apply (http://localhost:9000/vendor.bundle.js:27044:26)
    at HTMLButtonElement.<anonymous> (http://localhost:9000/vendor.bundle.js:35152:24)
    at HTMLButtonElement.jQuery.event.dispatch (http://localhost:9000/vendor.bundle.js:4471:10) undefined

**Comment by lwander** [comment]
https://github.com/spinnaker/clouddriver/pull/972
