### ISSUE TITLE
openstack/clouddriver/server groups: Error while deleting

### ISSUE THREAD

**Issue by jcwest** [spinnaker/spinnaker#1060]
When I try to delete/destroy a server group from the UI, it fails and I see the following exception in the clouddriver log:

2016-08-11 14:35:17.624 ERROR 4758 --- [188-7002-exec-5] c.n.s.c.c.LoggingExceptionHandler        : Error occurred handling request for http://10.81.72.188:7002/openstack/ops: java.lang.IllegalArgumentException: Can not instantiate value of type [simple type, class com.netflix.spinnaker.clouddriver.openstack.security.OpenstackCredentials] from String value ('test'); no single-String constructor/factory method
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.netflix.spinnaker.clouddriver.openstack.deploy.description.servergroup.OpenstackServerGroupAtomicOperationDescription["credentials"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3530)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3449)
        at com.fasterxml.jackson.databind.ObjectMapper$convertValue$4.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
        at com.netflix.spinnaker.clouddriver.openstack.deploy.converters.OpenstackAtomicOperationConverterHelper.convertDescription(OpenstackAtomicOperationConverterHelper.groovy:32)
        at com.netflix.spinnaker.clouddriver.openstack.deploy.converters.OpenstackAtomicOperationConverterHelper$convertDescription.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
        at com.netflix.spinnaker.clouddriver.openstack.deploy.converters.servergroup.DisableOpenstackAtomicOperationConverter.convertDescription(DisableOpenstackAtomicOperationConverter.groovy:39)

We have hit this issue with load balancer and security groups before. The solution implemented was to ensure that the UI sent "account" instead of "credentials", but this requires us to perform some "unnatural acts" in the UI code as the core is coded to send "credentials".  Specifically, we have to create additional copies of objects to achieve this, consuming more memory. It would be helpful if the back-end could handle "credentials" in the same way as "account".

**Comment by drmaas** [comment]
Looks like @varikin took care of this, closing.

**Comment by varikin** [comment]
I was looking for this issue to assign to me and close, thanks for finding it for me.
