### ISSUE TITLE
OpenStack server resize retrofit bug

### ISSUE THREAD

**Issue by SteveKMin** [spinnaker/spinnaker#1073]
When resizing openstack servers, eventually it will throw the something similar to the following error.

ERROR 55776 --- [tTaskExecutor-5] c.n.s.o.c.t.i.AbstractInstancesCheckTask : Unexpected retrofit error (Response{timestamp=Tue Aug 16 16:04:20 CDT 2016, exceptionType='RetrofitError', operation='null', details=[error:Internal Server Error, errors:[Cannot get property 'zone' on null object], rootException:java.lang.NullPointerException, responseBody:{
  "error" : "Internal Server Error",
  "exception" : "java.lang.NullPointerException",
  "message" : "Cannot get property 'zone' on null object",
  "status" : 500,
  "timestamp" : "2016-08-16T21:04:20.069+0000"
}

Unknown cause and not consistently reproducible. It does eventually happen after resizing the same server multiple times. To return to a functioning state, I've had to restart redis.

**Comment by SteveKMin** [comment]
Here is a the stacktrace from gate.

retrofit.RetrofitError: 500 Internal Server Error
	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy73.getServerGroups(Unknown Source)
	at com.netflix.spinnaker.gate.services.ServerGroupService$_getForApplication_closure1.doCall(ServerGroupService.groovy:46)
	at com.netflix.spinnaker.gate.services.ServerGroupService$_getForApplication_closure1.doCall(ServerGroupService.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at com.netflix.spinnaker.security.AuthenticatedRequest$_propagate_closure2.doCall(AuthenticatedRequest.groovy:56)
	at com.netflix.spinnaker.security.AuthenticatedRequest$_propagate_closure2.doCall(AuthenticatedRequest.groovy)
	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Mevoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:919)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:902)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:168)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeClosure(ScriptBytecodeAdapter.java:574)
	at com.netflix.spinnaker.gate.services.commands.AbstractHystrixCommand.run(AbstractHystrixCommand.groovy:57)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable.unsafeSubscribe(Observable.java:7710)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:520)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:495)
	at rx.Observable.unsafeSubscribe(Observable.java:7710)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdall(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
