### ISSUE TITLE
(Openstack) Enable server group fails

### ISSUE THREAD

**Issue by jcwest** [spinnaker/spinnaker#1160]
Enabling a server group results in the following exception in the clouddriver log:

2016-09-20 18:49:17.328  INFO 29160 --- [ool-2-thread-22] c.n.s.c.data.task.jedis.JedisTask        : [ORCHESTRATION] - Orchestration failed: EnableOpen
stackAtomicOperation | OpenstackOperationException: [enableServerGroup failed: Cannot get property 'addr' on null object]
2016-09-20 18:49:17.329 ERROR 29160 --- [ool-2-thread-22] c.n.s.c.o.DefaultOrchestrationProcessor  : com.netflix.spinnaker.clouddriver.openstack.deploy
.exception.OpenstackOperationException: enableServerGroup failed: Cannot get property 'addr' on null object
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
        at com.netflix.spinnaker.clouddriver.openstack.deploy.ops.servergroup.AbstractEnableDisableOpenstackAtomicOperation.operate(AbstractEnableDisab
leOpenstackAtomicOperation.groovy:74)
        at com.netflix.spinnaker.clouddriver.openstack.deploy.ops.servergroup.AbstractEnableDisableOpenstackAtomicOperation.operate(AbstractEnableDisab
leOpenstackAtomicOperation.groovy)
        at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate.call(Unknown Source)
        at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1_closure2.doCall(DefaultOrchestrationProcesso
r.groovy:70)
        at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1_closure2.doCall(DefaultOrchestrationProcesso
r.groovy)
        at sun.reflect.GeneratedMethodAccessor994.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:417)
        at com.netflix.spinnaker.clouddriver.metrics.TimedCallable$ClosureWrapper.call(TimedCallable.groovy:55)
        at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82)
        at java_util_concurrent_Callable$call.call(Unknown Source)
        at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy:69)
        at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy)
        at sun.reflect.GeneratedMethodAccessor991.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:417)
        at com.netflix.spinnaker.clouddriver.metrics.TimedCallable$ClosureWrapper.call(TimedCallable.groovy:55)
        at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Cannot get property 'addr' on null object
        at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:57)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:168)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:44)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
        at com.netflix.spinnaker.clouddriver.openstack.deploy.ops.servergroup.EnableOpenstackAtomicOperation.addOrRemoveInstancesFromLoadBalancer(EnableOpenstackAtomicOperation.groovy:72)
        at com.netflix.spinnaker.clouddriver.openstack.deploy.ops.servergroup.EnableOpenstackAtomicOperation$addOrRemoveInstancesFromLoadBalancer.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at com.netflix.spinnaker.clouddriver.openstack.deploy.ops.servergroup.DisableOpenstackAtomicOperation$addOrRemoveInstancesFromLoadBalancer.callCurrent(Unknown Source)
        at com.netflix.spinnaker.clouddriver.openstack.deploy.ops.servergroup.AbstractEnableDisableOpenstackAtomicOperation.operate(AbstractEnableDisableOpenstackAtomicOperation.groovy:65)
        ... 35 more

**Comment by drmaas** [comment]
This will be fixed via #1158 and #1159.
