### ISSUE TITLE
(Openstack) Pipeline - Resize Server Group -Scale down fails

### ISSUE THREAD

**Issue by jcwest** [spinnaker/spinnaker#1161]
The resize pipeline stage with the option to scale down the server group with either increment or percentage fails in the "Resize Server Group" task with "resizeOpenstackServerGroupAtomicOperationDescription.capacity.min.notPositive".

Pipeline definition:

{"application":"jeffwpune1","id":"13ac8040-802b-11e6-89d9-6d12efee0025","index":2,"keepWaitingPipelines":false,"limitConcurrent":true,"name":"Resize Test","parallel":true,"stages":[{"action":"scale_down","capacity":{},"cloudProvider":"openstack","cloudProviderType":"openstack","cluster":"jeffwpune1-0921-1122","credentials":"my-openstack-account","name":"Resize Server Group","refId":"1","regions":["RegionOne"],"requisiteStageRefIds":[],"resizeType":"incr","target":"current_asg_dynamic","type":"resizeServerGroup","scaleNum":1}],"triggers":[]}

From orca log:

2016-09-21 18:21:27.754  INFO 8830 --- [TaskExecutor-33] c.n.s.o.b.StageStatusPropagationListener : Task SUCCEEDED but not all other tasks are complete
 (stageId: 6bd0629a-24ef-4263-9c0a-56861544422f, nonBookEndTaskStatus: NOT_STARTED) ... tasks: [{"id":"2","name":"determineHealthProviders","startTime"
:1474496487637,"endTime":1474496487753,"status":"SUCCEEDED"}, {"id":"3","name":"resizeServerGroup","startTime":null,"endTime":null,"status":"NOT_STARTE
D"}, {"id":"4","name":"monitorServerGroup","startTime":null,"endTime":null,"status":"NOT_STARTED"}, {"id":"5","name":"forceCacheRefresh","startTime":nu
ll,"endTime":null,"status":"NOT_STARTED"}, {"id":"6","name":"waitForCapacityMatch","startTime":null,"endTime":null,"status":"NOT_STARTED"}]
2016-09-21 18:21:27.788  INFO 8830 --- [TaskExecutor-33] o.s.batch.core.job.SimpleStepHandler     : Executing step: [6bd0629a-24ef-4263-9c0a-5686154442
2f.resizeServerGroup.resizeServerGroup.3]
2016-09-21 18:21:27.790  INFO 8830 --- [TaskExecutor-33] c.n.s.o.b.StageTaskPropagationListener   : Setting task status to RUNNING (stageId: 6bd0629a-2
4ef-4263-9c0a-56861544422f, taskId: 3) [beforeTask]
2016-09-21 18:21:27.791  INFO 8830 --- [TaskExecutor-33] c.n.s.o.b.StageStatusPropagationListener : Marking Stage as RUNNING (stageId: 6bd0629a-24ef-42
63-9c0a-56861544422f)
2016-09-21 18:21:27.794  INFO 8830 --- [TaskExecutor-33] c.n.spinnaker.orca.echo.EchoService      : ---> HTTP POST http://10.209.9.155:8089/
2016-09-21 18:21:27.837  INFO 8830 --- [TaskExecutor-33] c.n.spinnaker.orca.echo.EchoService      : <--- HTTP 200 http://10.209.9.155:8089/ (42ms)
2016-09-21 18:21:27.853  INFO 8830 --- [TaskExecutor-33] c.n.s.orca.clouddriver.OortService       : ---> HTTP GET http://10.209.9.155:7002/applications
/jeffwpune1/clusters/my-openstack-account/jeffwpune1-0921-1122/openstack/serverGroups/jeffwpune1-0921-1122-v001
2016-09-21 18:21:27.862  INFO 8830 --- [TaskExecutor-33] c.n.s.orca.clouddriver.OortService       : <--- HTTP 200 http://10.209.9.155:7002/applications
/jeffwpune1/clusters/my-openstack-account/jeffwpune1-0921-1122/openstack/serverGroups/jeffwpune1-0921-1122-v001 (8ms)
2016-09-21 18:21:27.870  INFO 8830 --- [-/openstack/ops] c.n.s.orca.clouddriver.KatoService       : ---> HTTP POST http://10.209.9.155:7002/openstack/o
ps?clientRequestId=ad0ad80d-9e68-45fd-bf73-6d29a8e23561
2016-09-21 18:21:27.907  INFO 8830 --- [-/openstack/ops] c.n.s.orca.clouddriver.KatoService       : <--- HTTP 400 http://10.209.9.155:7002/openstack/op
s?clientRequestId=ad0ad80d-9e68-45fd-bf73-6d29a8e23561 (37ms)
2016-09-21 18:21:27.911 ERROR 8830 --- [TaskExecutor-33] c.n.s.security.AuthenticatedRequest      : Error occurred propagating authentication context

retrofit.RetrofitError: 400 Bad Request
        at retrofit.RetrofitError.httpError(RetrofitError.java:40)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
        at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
        at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
        at retrofit.RxSupport$2.run(RxSupport.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at retrofit.Platform$Base$2$1.run(Platform.java:94)
        at java.lang.Thread.run(Thread.java:745)

2016-09-21 18:21:27.923  INFO 8830 --- [TaskExecutor-33] c.n.s.o.c.t.s.ResizeServerGroupTask      : Pipeline:88815080-ff67-46be-b037-1b0b348a3d9c:1 resizeServerGroup TERMINAL -- Batch step id: 414,  Task Outputs: {
  "exception" : {
    "exceptionType" : "RetrofitError",
    "operation" : "stageEnd",
    "details" : {
      "error" : "Validation Failed",
      "errors" : [ "resizeOpenstackServerGroupAtomicOperationDescription.capacity.min.notPositive" ],
      "responseBody" : "{\n  \"error\" : \"Validation Failed\",\n  \"errors\" : [ \"resizeOpenstackServerGroupAtomicOperationDescription.capacity.min.notPositive\" ],\n  \"status\" : \"BAD_REQUEST\"\n}",
      "kind" : "HTTP",
      "status" : 400,
      "url" : "http://10.209.9.155:7002/openstack/ops?clientRequestId=ad0ad80d-9e68-45fd-bf73-6d29a8e23561"
    },
    "shouldRetry" : false
  }
},  Stage Context: {
  "action" : "scale_down",
  "capacity" : { },
  "cloudProvider" : "openstack",
  "cloudProviderType" : "openstack",
  "cluster" : "jeffwpune1-0921-1122",
  "credentials" : "my-openstack-account",
  "resizeType" : "incr",
  "target" : "current_asg_dynamic",
  "scaleNum" : 1,
  "region" : "RegionOne",
  "targetLocation" : {
    "type" : "REGION",
    "value" : "RegionOne"
  },
  "stageDetails" : {
    "name" : "Resize Server Group",
    "type" : "resizeServerGroup",
    "startTime" : 1474496487469,
    "isSynthetic" : false
  },
  "batch.task.id.stageStart" : 412,
  "batch.task.id.determineHealthProviders" : 413
}

**Comment by drmaas** [comment]
Looks to be working as expected - step was run with a current min of 1. 1 cannot be reduced to 0.
