### ISSUE TITLE
Jenkins jobs are not populated if Jenkins master name contains a dot

### ISSUE THREAD

**Issue by cllunsford** [spinnaker/spinnaker#1165]
*Cloud Provider*

Kubernetes

*Environment*

docker-compose running locally

*Feature Area*

Jenkins

*Description*

Configuring the Jenkins defaultMaster with a name containing a dot (`.`), the Jenkins trigger does not populate the jobs from Jenkins.  Changing the name to remove the dot fixes the issue; I can use just `jenkins` or `jenkins-domain-com` without issues.  I would like to use the fqdn of the jenkins server to distinguish between multiple jenkins installations.  There's an easy workaround and it's only a minor annoyance, but I figured I'd report it since others might run into it.

*Steps to Reproduce*

Configure in spinnaker-local.yml:
```
  jenkins:
    defaultMaster:
      name: jenkins.domain.com
```
or
```
  jenkins:
    defaultMaster:
      name: jenkins.net
```

In UI, attempt to add a Jenkins trigger to a pipeline.  Build master populates but jobs do not.

![screenshot from 2016-09-23 11-22-45](https://cloud.githubusercontent.com/assets/1678727/18791302/2b9c34c4-8180-11e6-836c-c1f17ccfc2a5.png)

*Additional Details*

See exception in gate logs when selecting the Jenkins build master in the UI:

```
gate           | 2016-09-23 15:18:04.510  INFO 1 --- [ystrix-builds-3] c.n.s.g.services.internal.IgorService    : ---> HTTP GET http://igor:8088/masters
gate           | 2016-09-23 15:18:04.522  INFO 1 --- [ystrix-builds-3] c.n.s.g.services.internal.IgorService    : <--- HTTP 200 http://igor:8088/masters (12ms)
gate           | 2016-09-23 15:18:10.036  INFO 1 --- [ystrix-builds-4] c.n.s.g.services.internal.IgorService    : ---> HTTP GET http://igor:8088/jobs/jenkins.net
gate           | 2016-09-23 15:18:10.051  INFO 1 --- [ystrix-builds-4] c.n.s.g.services.internal.IgorService    : <--- HTTP 404 http://igor:8088/jobs/jenkins.net (14ms)
gate           | 2016-09-23 15:18:10.056 ERROR 1 --- [ystrix-builds-4] c.n.s.security.AuthenticatedRequest      : Error occurred propagating authentication context
gate           | 
gate           | com.netflix.spinnaker.gate.services.BuildService$BuildMasterNotFound: Build master 'jenkins.net' not found
gate           | 	at com.netflix.spinnaker.gate.services.BuildService$_getJobsForBuildMaster_closure2.doCall(BuildService.groovy:63)
gate           | 	at com.netflix.spinnaker.gate.services.BuildService$_getJobsForBuildMaster_closure2.doCall(BuildService.groovy)
gate           | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gate           | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
gate           | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gate           | 	at java.lang.reflect.Method.invoke(Method.java:498)
gate           | 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
gate           | 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
gate           | 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
gate           | 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
gate           | 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
gate           | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
gate           | 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57)
gate           | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
gate           | 	at com.netflix.spinnaker.security.AuthenticatedRequest$_propagate_closure2.doCall(AuthenticatedRequest.groovy:56)
gate           | 	at com.netflix.spinnaker.security.AuthenticatedRequest$_propagate_closure2.doCall(AuthenticatedRequest.groovy)
gate           | 	at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
gate           | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gate           | 	at java.lang.reflect.Method.invoke(Method.java:498)
gate           | 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
gate           | 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
gate           | 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
gate           | 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
gate           | 	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:919)
gate           | 	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:902)
gate           | 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:168)
gate           | 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeClosure(ScriptBytecodeAdapter.java:574)
gate           | 	at com.netflix.spinnaker.gate.services.commands.AbstractHystrixCommand.run(AbstractHystrixCommand.groovy:57)
gate           | 	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
gate           | 	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289)
gate           | 	at rx.Observable$2.call(Observable.java:162)
gate           | 	at rx.Observable$2.call(Observable.java:154)
gate           | 	at rx.Observable$2.call(Observable.java:162)
gate           | 	at rx.Observable$2.call(Observable.java:154)
gate           | 	at rx.Observable$2.call(Observable.java:162)
gate           | 	at rx.Observable$2.call(Observable.java:154)
gate           | 	at rx.Observable.unsafeSubscribe(Observable.java:7710)
gate           | 	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:520)
gate           | 	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:495)
gate           | 	at rx.Observable.unsafeSubscribe(Observable.java:7710)
gate           | 	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
gate           | 	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
gate           | 	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
gate           | 	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
gate           | 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
gate           | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
gate           | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
gate           | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
gate           | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
gate           | 	at java.lang.Thread.run(Thread.java:745)
gate           | 
```

**Comment by jeyrschabu** [comment]
@cllunsford This should now be fixed

**Comment by cllunsford** [comment]
Thanks! Working now in Igor v1.53.0
