### ISSUE TITLE
Kubernetes cloud provider does not handle named ports for http get probes

### ISSUE THREAD

**Issue by philsttr** [spinnaker/spinnaker#1210]
*Title*

Kubernetes cloud provider does not handle named ports for http get probes

*Cloud Provider*

Kubernetes

*Environment*

I'm running  all spinnaker components on a local Ubuntu 14.04 vm to try it out.

*Feature Area*

Kubernetes Cloud Provider 

*Description*

The Kubernetes Cloud provider does not properly handle named ports for container http get probes.

Specifically, [this line of code](https://github.com/spinnaker/clouddriver/blob/v1.362.0/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/api/KubernetesApiConverter.groovy#L591) incorrectly assumes that the port is always an integer value.

Kubernetes [allows named ports](http://kubernetes.io/docs/user-guide/liveness/) to be used, instead of port numbers.  (e.g. `http` instead of `80`)

The Kubernetes Cloud provider should handle named ports.

When a named port is used, the stacktrace below is output by the cloud driver.

When a numeric port is used, no problems occur.

*Steps to Reproduce*

In kubernetes, define a container with an http probe that uses a named port.  For example:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foobar
spec:
  replicas: 4
  template:
      containers:
      - name: foobar
        image: blah blah blah
        ports:
          - name: http
            containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: http
```

Configure the kubernetes cloud provider to point to the kubernetes cluster containing the above container

Start the cloud driver process.

Examine logs to find the stacktrace below.

*Additional Details*

```
java.lang.IllegalArgumentException: null
        at sun.reflect.GeneratedMethodAccessor881.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2661)
        at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3701)
        at com.netflix.spinnaker.clouddriver.kubernetes.deploy.description.servergroup.KubernetesHttpGetAction.setProperty(DeployKubernetesAtomicOperationDescription.groovy)
        at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:191)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:482)
        at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiConverter.fromHttpGetAction(KubernetesApiConverter.groovy:591)
        at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiConverter$fromHttpGetAction$0.callStatic(Unknown Source)
        at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiConverter.fromProbe(KubernetesApiConverter.groovy:556)
        at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiConverter$fromProbe.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
        at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiConverter$fromProbe.callStatic(Unknown Source)
        at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiConverter.fromContainer(KubernetesApiConverter.groovy:393)
        at sun.reflect.GeneratedMethodAccessor551.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:382)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
        at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiConverter$_fromReplicaSet_closure12.doCall(KubernetesApiConverter.groovy:476)
        at sun.reflect.GeneratedMethodAccessor599.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:2348)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:2318)
        at org.codehaus.groovy.runtime.dgm$63.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:82)
        at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiConverter.fromReplicaSet(KubernetesApiConverter.groovy:475)
        at com.netflix.spinnaker.clouddriver.kubernetes.model.KubernetesServerGroup.<init>(KubernetesServerGroup.groovy:80)
        at sun.reflect.GeneratedConstructorAccessor149.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:202)
        at com.netflix.spinnaker.clouddriver.kubernetes.provider.agent.KubernetesServerGroupCachingAgent$_buildCacheResult_closure19.doCall(KubernetesServerGroupCachingAgent.groovy:358)
        at sun.reflect.GeneratedMethodAccessor549.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:235)
        at org.codehaus.groovy.runtime.dgm$616.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:248)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at com.netflix.spinnaker.clouddriver.kubernetes.provider.agent.KubernetesServerGroupCachingAgent.buildCacheResult(KubernetesServerGroupCachingAgent.groovy:354)
        at com.netflix.spinnaker.clouddriver.kubernetes.provider.agent.KubernetesServerGroupCachingAgent.this$2$buildCacheResult(KubernetesServerGroupCachingAgent.groovy)
        at com.netflix.spinnaker.clouddriver.kubernetes.provider.agent.KubernetesServerGroupCachingAgent$this$2$buildCacheResult$1.callCurrent(Unknown Source)
        at com.netflix.spinnaker.clouddriver.kubernetes.provider.agent.KubernetesServerGroupCachingAgent.loadData(KubernetesServerGroupCachingAgent.groovy:242)
        at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:66)
        at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:59)
        at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:193)
        at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:167)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by philsttr** [comment]
Note that it would also be nice if named ports could be used when configuring probes on a new server group.  Currently only numeric ports are supported.

![image](https://cloud.githubusercontent.com/assets/7027966/19245513/6995bc38-8ed6-11e6-8d3c-5d8a92d7e47e.png)
