### ISSUE TITLE
Deck is not showing accounts when create application

### ISSUE THREAD

**Issue by tingzhang1210** [spinnaker/spinnaker#1283]
*Cloud Provider*

docker-compose locally

*Environment*

ubuntu14.04

*Feature Area*

UI

*Description*

refer to https://github.com/spinnaker/spinnaker/tree/master/experimental/docker-compose
i have put config file but still can't see accounts in Deck

*Steps to Reproduce*

![image](https://cloud.githubusercontent.com/assets/20940338/19922009/8e3552d6-a11b-11e6-95d7-f55239ed6f65.png)

*Additional Details*

~# cat compose.env 
~# embedded cassandra
CASSANDRA_HOST=127.0.0.1
CASSANDRA_EMBEDDED=true
REDIS_CONNECTION=redis://redis:6379
SERVER_ADDRESS=0.0.0.0
REDIS_PORT=6379
REDIS_HOST=redis
SPRING_CONFIG_LOCATION=/opt/spinnaker/config/

```
~# cat spinnaker-local.yml 
# This file is intended to override the default configuration in the
# spinnaker.yml file while providing guidance on the mostly likely
# configuration parameters to be changed.
#
# In order for Spinnaker to discover it, it must be copied to a file named
# "spinnaker-local.yml" and placed in /opt/spinnaker/config
# (or when running from source code, in the $HOME/.spinnaker directory.)
#
# A better practice could be to create the spinnaker-local.yml file by
# hand with only the particular attributes that you want to override
# and use the spinnaker.yml file as your guide since it is spinnaker.yml
# that we are overriding here in the first place.

global:
  spinnaker:
    timezone: 'America/Los_Angeles'

providers:
  # See http://www.spinnaker.io/v1.0/docs/target-deployment-setup
  # for general information about configuring spinnaker platform providers.

  # Each of the following providers can be enabled independent of all other
  # providers unless otherwise noted.
  #
  # Each provider can be enabled by setting its 'enabled' attribute to true.
  # As a rule of thumb, each provider defines a 'primaryCredentials' block
  # that configures a default account for Spinnaker to use on that platform.
  # If additional accounts are desired, then add those accounts to a
  # custom clouddriver-local.yml file and consult clouddriver.yml for more
  # information on what to add there.

  aws:
    # For more information on configuring Amazon Web Services (aws), see
    # http://www.spinnaker.io/v1.0/docs/target-deployment-setup#section-amazon-web-services-setup

    enabled: ${SPINNAKER_AWS_ENABLED:false}
    defaultRegion: ${SPINNAKER_AWS_DEFAULT_REGION:us-west-2}
    defaultIAMRole: BaseIAMRole
    primaryCredentials:
      name: my-aws-account
      # Store actual credentials in $HOME/.aws/credentials. See spinnaker.yml
      # for more information, including alternatives.

    # {{name}} will be interpolated with the aws account name (e.g. "my-aws-account-keypair").
    defaultKeyPairTemplate: "{{name}}-keypair"

  azure:
    # For more information on configuring Microsoft Azure (azure), see
    # http://www.spinnaker.io/v1.0/docs/target-deployment-setup#section-azure-cloud-platform-setup

    enabled: ${SPINNAKER_AZURE_ENABLED:false}
    defaultRegion: ${SPINNAKER_AZURE_DEFAULT_REGION:westus}
    primaryCredentials:
      name: my-azure-account

      # To set Azure credentials, enter your Azure supscription values for:
      # clientId, appKey, tenantId, and subscriptionId.
      clientId:
      appKey:
      tenantId:
      subscriptionId:

  google:
    # For more information on configuring Google Cloud Platform (google), see
    # http://www.spinnaker.io/v1.0/docs/target-deployment-setup#section-google-cloud-platform-setup

    enabled: ${SPINNAKER_GOOGLE_ENABLED:false}
    defaultRegion: ${SPINNAKER_GOOGLE_DEFAULT_REGION:us-central1}
    defaultZone: ${SPINNAKER_GOOGLE_DEFAULT_ZONE:us-central1-f}

    primaryCredentials:
      name: my-google-account
      # The project is the Google Project ID for the project to manage with
      # Spinnaker.
      # The jsonPath is a path to the JSON service credentials downloaded
      # from the Google Developer's Console.
      project: ${SPINNAKER_GOOGLE_PROJECT_ID:}
      jsonPath: ${SPINNAKER_GOOGLE_PROJECT_CREDENTIALS_PATH:}
      consul:
        enabled: ${SPINNAKER_GOOGLE_CONSUL_ENABLED:false}

  cf:
    # For more information on configuring Cloud Foundry (cf) support, see
    # http://www.spinnaker.io/v1.0/docs/target-deployment-setup#section-cloud-foundry-platform-setup

    enabled: false
    defaultOrg: spinnaker-cf-org
    defaultSpace: spinnaker-cf-space

    primaryCredentials:
      name: my-cf-account
      api: my-cf-api-uri
      console: my-cf-console-base-url
      # Either uncomment and plugin credentials here, or supply as
      # environment variables for maximum security.
      # account:
      #   name: my-cf-username
      #   password: my-cf-password

  kubernetes:
    # For more information on configuring Kubernetes clusters (kubernetes), see
    # http://www.spinnaker.io/v1.0/docs/target-deployment-setup#section-kubernetes-cluster-setup

    # NOTE: enabling kubernetes also requires enabling dockerRegistry.
    enabled: ${SPINNAKER_KUBERNETES_ENABLED:false}
    primaryCredentials:
      # These credentials use authentication information at ~/.kube/config
      # by default.
      name: my-kubernetes-account
      dockerRegistryAccount: ${providers.dockerRegistry.primaryCredentials.name}

  dockerRegistry:
    # For more information on configuring Docker registries, see
    # http://www.spinnaker.io/v1.0/docs/target-deployment-configuration#section-docker-registry

    # NOTE: Enabling dockerRegistry is independent of other providers.
    # However, for convienience, we tie docker and kubernetes together
    # since kubernetes (and only kubernetes) depends on this docker provider
    # configuration.
    enabled: ${SPINNAKER_KUBERNETES_ENABLED:false}

    primaryCredentials:
      name: my-docker-registry
      address: ${SPINNAKER_DOCKER_REGISTRY:https://index.docker.io/}
      repository: ${SPINNAKER_DOCKER_REPOSITORY:library/nginx}
      username: ${SPINNAKER_DOCKER_USERNAME}
      # A path to a plain text file containing the user's password
      passwordFile: ${SPINNAKER_DOCKER_PASSWORD_FILE}

  openstack:
    # For more information on configuring Openstack clusters, see
    # http://www.spinnaker.io/v1.0/docs/target-deployment-configuration#section-openstack

    enabled: ${SPINNAKER_OPENSTACK_ENABLED:false}
    primaryCredentials:
      name: my-openstack-account
      authUrl: ${OS_AUTH_URL}
      username: ${OS_USERNAME}
      password: ${OS_PASSWORD}
      projectName: ${OS_PROJECT_NAME}
```

**Comment by tingzhang1210** [comment]
resolved offline on slack

**Comment by emperorente** [comment]
the same question,how did you slove it...?

**Comment by jweyrich** [comment]
Same here. Azure account doesn't show up in the combo. @tingzhang1210 can you give us a hint? I already enabled Azure in `/etc/defaults/spinnaker` and copied `spinnaker-local.yml` to `/home/spinnaker/.spinnaker/spinnaker-local.yml` and filled the required Azure properties: clientId, appKey, tenantId, and subscriptionId.

**Comment by techmng** [comment]
how this issue was resolved. I am also not seeing aws account after adding application

**Comment by baijupadmanabhan** [comment]
@tingzhang1210 could you please provide the solution here?

**Comment by baijupadmanabhan** [comment]
@tingzhang1210 I am getting this when I create try to create application.

![screenshot from 2017-12-05 11 13 26](https://user-images.githubusercontent.com/24491303/33625906-1ecf9e9a-da1f-11e7-8e98-01fb180dde0e.png)

**Comment by ashsrira** [comment]
I am seeing the same as @baijupadmanabhan 
<img width="616" alt="screen shot 2018-01-05 at 4 37 53 pm" src="https://user-images.githubusercontent.com/21186956/34634224-c851fe16-f236-11e7-9343-8e8b3aac9c36.png">

**Comment by anotherchrisberry** [comment]
The account field is no longer part of the application creation process, so the account field is not part of this modal dialog. Application accounts are inferred by the whatever server groups are deployed into the application.

**Comment by krmayankk** [comment]
i added a new k8s provider and it fails to show up in the UI. It shows in /opt/spinnaker/config/clouddriver.yml and i already ran `hal deploy apply` anything else i need to do ?

**Comment by adrian-gierakowski** [comment]
@krmayankk have you resolved your problem? I've added a second k8s account but can only see the primary in the dropdown of the deployment stage

**Comment by madsonic** [comment]
account not showing up too and i suspect it is causing authorisation problems when trying to deploy to my GKE cluster

**Comment by hareku** [comment]
I have same problem.

I can list accounts and I found added account `eks-my-cluster`.

```
$ hal config provider kubernetes account list
+ Get current deployment
  Success
+ Get the kubernetes provider
  Success
+ Accounts for kubernetes:
  - eks-my-cluster
```

```
$ hal config provider kubernetes account get eks-my-cluster
+ Get current deployment
  Success
+ Get eks-my-cluster account
  Success
+ Account eks-my-cluster: 
KubernetesAccount(context=eks-my-cluster, cluster=null, user=null, configureImagePullSecrets=true, serviceAccount=null, cacheThreads=1, namespaces=[], omitNamespaces=[kube-system, kube-public], kinds=[], omitKinds=[], customResources=[], cachingPolicies=[], kubeconfigFile=/opt/kube/kubeconfig-for-spinnaker, kubeconfigContents=null, kubectlPath=null, kubectlRequestTimeoutSeconds=null, checkPermissionsOnStartup=null, liveManifestCalls=null, oAuthServiceAccount=null, oAuthScopes=[], namingStrategy=null, skin=null, onlySpinnakerManaged=false, debug=null, secretSessionManager=null)
+ EKS-MY-CLUSTER

KubernetesAccount(context=eks-my-cluster, cluster=null, user=null,
configureImagePullSecrets=true, serviceAccount=null, cacheThreads=1,
namespaces=[], omitNamespaces=[kube-system, kube-public], kinds=[],
omitKinds=[], customResources=[], cachingPolicies=[],
kubeconfigFile=/opt/kube/kubeconfig-for-spinnaker, kubeconfigContents=null,
kubectlPath=null, kubectlRequestTimeoutSeconds=null,
checkPermissionsOnStartup=null, liveManifestCalls=null,
oAuthServiceAccount=null, oAuthScopes=[], namingStrategy=null, skin=null,
onlySpinnakerManaged=false, debug=null, secretSessionManager=null)
```

Additionally, I can access eks-my-cluster by config, but Deck is not showing any accounts.

**Comment by hareku** [comment]
I solved above my issue.
I delete all spinnaker components (s3, redis, halyard, etc...) and I recreate these, Deck shows my added accounts.

**Comment by thomasjyoung** [comment]
Hi @adrian-gierakowski did you manage to solve this issue?

**Comment by adrian-gierakowski** [comment]
> Hi @adrian-gierakowski did you manage to solve this issue?

Yes. Although I don’t remember how exactly as it was long time ago.

**Comment by thomasjyoung** [comment]
Ok, I will leave this here incase anyone else runs into it. I managed to solve this issue by checking my hal config file, for the kubernetes accounts. 

It appears my primary account was missing the "context" field. I added the context field and the correct context value, then ran hal deploy apply. This solved the problem and all my service accounts are now listed.

**Comment by oslobodian** [comment]
similar issue here:

```
/ $ hal config provider kubernetes account list
+ Get current deployment
  Success
+ Get the kubernetes provider
  Success
+ Accounts for kubernetes:
  - default
  - toy-spot
  - toy-sandbox
```

clouddriver error:
```
spin-clouddriver-69bbc9876d-gm8sh clouddriver 2020-02-06 17:48:31.980 ERROR 1 --- [     Thread-168] c.n.s.c.k.v.s.KubernetesV2Credentials    : Could not list namespaces for account toy-spot: Failed to read [namespace] from : error: context "***:***:***:***:***:cluster/toy-spot" does not exist
```
any ideas?

**Comment by balajipothula** [comment]
Spinnaker Deck Not Populating AWS Account Details
[setup-spinnaker.txt](https://github.com/spinnaker/spinnaker/files/4250120/setup-spinnaker.txt)


<img width="799" alt="AWS_Account_No-results-found" src="https://user-images.githubusercontent.com/2758356/75250574-a46ae500-57fe-11ea-8e84-805eb8d31f15.png">

**Comment by ponceps** [comment]
@baijupadmanabhan did you manage to solve this issue?

**Comment by aleon1220** [comment]
> @balajipothula did you manage to solve this issue?

i think this is a very old issuse. Plus it got mixed with newer versions of Spinnaker. 

In my case i was deploying Docker image artifacts found in an AWS ECR account.
I configured the AWS EC2 and ECS provider with Halyard. 
I followed this guide on setting up the [AWS IAM structure](https://docs.armory.io/spinnaker-install-admin-guides/add-aws-account/) from armory.io
Then i created the app in Spinnaker and selected both AWS and AWS ECS accounts
I created a simple pipeline to deploy to an already ECS cluster
one stage would obtain the latest docker image from AWS ECR
another stage would deploy
in Spinnaker > App > Infrastructure > Server groups. I saw my ECS services being populated with tasks automatically.

Of course there is lots more detail in there. But basically the cluster and server groups were populated after i deployed my ECS service. 
Is like implicit to Spinnaker.

I would have to ask what Spinnaker version are you running? and What scenario are you trying to achieve?

1. Deploy to AWS EC2
2. Deploy containers to ECS?
3. Deploy Kubernetes objects to any cloud provider??
4. deploy a monolith image to some cloud provider??

Thanks

**Comment by balajipothula** [comment]
> @balajipothula did you manage to solve this issue?

We are not using Spinnaker now, We want to do Chaos Engineering on AWS Fargate Service,
We realize Spinnaker will not fit. So We are developing Our own Python Scripts 
using Boto3  :-)

**Comment by balajipothula** [comment]
> > @balajipothula did you manage to solve this issue?
> 
> i think this is a very old issue. Plus it got mixed with newer versions of Spinnaker.
> 
> In my case i was deploying Docker image artifacts found in an AWS ECR account.
> 
> * I configured the AWS EC2 and ECS provider with Halyard.
> * I followed this guide on setting up the [AWS IAM structure](https://docs.armory.io/spinnaker-install-admin-guides/add-aws-account/) from armory.io
> * Then i created the app in Spinnaker and selected both AWS and AWS ECS accounts
> * I created a simple pipeline to deploy to an already ECS cluster
>   -one stage would obtain the latest docker image from AWS ECR
> * another stage would deploy
> * in Spinnaker > App > Infrastructure > Server groups. I saw my ECS services being populated with tasks automatically.
> 
> Of course there is lots more detail in there. But basically the cluster and server groups were populated after i deployed my ECS service.
> Is like implicit to Spinnaker.
> 
> I would have to ask what Spinnaker version are you running? and What scenario are you trying to achieve?
> 
> 1. Deploy to AWS EC2
> 2. Deploy containers to ECS?
> 3. Deploy Kubernetes objects to any cloud provider??
> 4. deploy a monolith image to some cloud provider??
> 
> Thanks

We are not using Spinnaker now, We want to do Chaos Engineering on AWS Fargate Service,
We realize Spinnaker will not fit. So We are developing Our own Python Scripts
using Boto3 :-)

**Comment by nardoguy14** [comment]
I'm running into this issue. I see that this error in the cloud driver log. I'm not sure hwat to do. 

```
2023-06-20 06:56:35.929  WARN 1 --- [           main] c.n.s.c.k.s.KubernetesCredentialsParser  : Skipping invalid account definition account=my-k8s-account

com.netflix.spinnaker.kork.configserver.ConfigFileLoadingException: File "/root/.hal/default/staging/dependencies/1342040884-config" not found or is not readable
	at com.netflix.spinnaker.kork.configserver.ConfigFileService.verifyLocalPath(ConfigFileService.java:73) ~[kork-cloud-config-server-7.146.2.jar:7.146.2]
	at com.netflix.spinnaker.kork.configserver.ConfigFileService.getLocalPath(ConfigFileService.java:44) ~[kork-cloud-config-server-7.146.2.jar:7.146.2]
	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesCredentials$Factory.getKubeconfigFile(KubernetesCredentials.java:815) ~[clouddriver-kubernetes-5.78.6.jar:5.78.6]
	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesCredentials$Factory.build(KubernetesCredentials.java:807) ~[clouddriver-kubernetes-5.78.6.jar:5.78.6]
	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesNamedAccountCredentials.<init>(KubernetesNamedAccountCredentials.java:75) ~[clouddriver-kubernetes-5.78.6.jar:5.78.6]
	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesCredentialsParser.parse(KubernetesCredentialsParser.java:41) ~[clouddriver-kubernetes-5.78.6.jar:5.78.6]
	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesCredentialsParser.parse(KubernetesCredentialsParser.java:31) ~[clouddriver-kubernetes-5.78.6.jar:5.78.6]
	at com.netflix.spinnaker.credentials.definition.BasicCredentialsLoader.parse(BasicCredentialsLoader.java:84) ~[kork-credentials-api-7.146.2.jar:7.146.2]
	at com.netflix.spinnaker.credentials.definition.BasicCredentialsLoader.load(BasicCredentialsLoader.java:68) ~[kork-credentials-api-7.146.2.jar:7.146.2]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1791) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:540) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1341) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1181) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1525) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1489) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1378) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1265) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1361) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1208) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder$run$0.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.14.jar:2.5.14]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-2.5.14.jar:2.5.14]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) ~[groovy-2.5.14.jar:2.5.14]
	at com.netflix.spinnaker.clouddriver.Main.main(Main.groovy:76) ~[clouddriver-web-5.78.6.jar:5.78.6]

```

How can i be sure it copies this file into the pod?
