### ISSUE TITLE
Support for Redis ElasticCache

### ISSUE THREAD

**Issue by sheinbergon** [spinnaker/spinnaker#1312]
*Title*

AWS ElasticCache  Redis ( Standalone node ) is not supported by Gate ( and probably other services )

*Cloud Provider*

AWS

*Environment*

I am running Spinnaker using the Pre-made Ubuntu images based  to deploy into AWS  (ELBs & ASGs)

*Feature Area*

Gate ( and probably other services

*Description*

Redis developer(s) recommend disabling the CONFIG command for remote access for security reasons. AWS ElasticCache Redis does so without any option of chaning this feature. Gate , as it seems, rely on the CONFIG command for initialization. Though a work around seems to exist  (https://github.com/spring-projects/spring-session/issues/124) , this should probably be fixed

*Steps to Reproduce*

Just try and configure spinnaker to work with ElasticCache Redis instead of local/remote standalone Redis

*Additional Details*

Here's the complete stacktrace

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer' defined in class path resource [com/netflix/spinnaker/gate/config/GateConfig.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Unable to configure Redis to keyspace notifications. See http://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-sessiondestroyedevent
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1572)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:690)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at org.springframework.boot.builder.SpringApplicationBuilder$run$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.netflix.spinnaker.gate.Main.main(Main.groovy:52)
Caused by: java.lang.IllegalStateException: Unable to configure Redis to keyspace notifications. See http://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-sessiondestroyedevent
	at org.springframework.session.data.redis.config.ConfigureNotifyKeyspaceEventsAction.getNotifyOptions(ConfigureNotifyKeyspaceEventsAction.java:75)
	at org.springframework.session.data.redis.config.ConfigureNotifyKeyspaceEventsAction.configure(ConfigureNotifyKeyspaceEventsAction.java:50)
	at org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration$EnableRedisKeyspaceNotificationsInitializer.afterPropertiesSet(RedisHttpSessionConfiguration.java:176)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1631)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1568)
	... 18 common frames omitted
Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: ERR unknown command 'CONFIG'; nested exception is redis.clients.jedis.exceptions.JedisDataException: ERR unknown command 'CONFIG'
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:44)
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:36)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:210)
	at org.springframework.data.redis.connection.jedis.JedisConnection.getConfig(JedisConnection.java:571)
	at org.springframework.session.data.redis.config.ConfigureNotifyKeyspaceEventsAction.getNotifyOptions(ConfigureNotifyKeyspaceEventsAction.java:69)
	... 22 common frames omitted
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR unknown command 'CONFIG'
	at redis.clients.jedis.Protocol.processError(Protocol.java:117)
	at redis.clients.jedis.Protocol.process(Protocol.java:151)
	at redis.clients.jedis.Protocol.read(Protocol.java:205)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:233)
	at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:226)
	at redis.clients.jedis.Jedis.configGet(Jedis.java:2541)
	at org.springframework.data.redis.connection.jedis.JedisConnection.getConfig(JedisConnection.java:569)
	... 23 common frames omitted
```

**Comment by sheinbergon** [comment]
Notice that the workaround is not working and  I'm still getting this error...

**Comment by baguasquirrel** [comment]
AWS does not currently support Redis very well in CacheCluster or ReplicationGroup. No snapshots for CacheCluster, for example, and you can't get the PrimaryEndpoint.Address programmatically. Just saying.

**Comment by tomaslin** [comment]
This is the same as #1309 I believe. You need to add ```redis:
    configuration:
         secure:
              true``` to the gate.yml

**Comment by sheinbergon** [comment]
@tomaslin  it works. Thanks

**Comment by camilosantana** [comment]
this didn't work for me when using the latest redis engine (currently at 3.2.4)
when i switched to Engine Version Compatibility 2.8.24, it worked fine.

**Comment by sheinbergon** [comment]
@camilosantana  did you by any chance marked the "cluster" mode  flag when using 3.2.4 ? 
Spring-data-redis (which uses jedis under the hood ) needs to be configured for cluster mode when doing so, which definitely not the current situation with Front50

**Comment by tavisca-himani** [comment]
worked for me as well. Thankyou !!
