### ISSUE TITLE
When I install spinnaker from scratch using GCE ,not able to create an application in spinnaker its keep on rendring

### ISSUE THREAD

**Issue by phanikumarp** [spinnaker/spinnaker#1393]
*Spinnaker application not created *

Spinnaker application not created in GCE

*GCP*

   In echo.log haveing error like this

  ---- ERROR http://localhost:8080/pipelines?restricted=false
java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8080
        at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
        at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
        at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
        at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:283)
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.squareup.okhttp.Call.getResponse(Call.java:286)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.execute(Call.java:80)
        at retrofit.client.OkClient.execute(OkClient.java:53)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
        at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
        at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
        at retrofit.RxSupport$2.run(RxSupport.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at retrofit.Platform$Base$2$1.run(Platform.java:94)
        at java.lang.Thread.run(Thread.java:745)
---- END ERROR

AND 
---> HTTP GET http://localhost:8080/pipelines?restricted=false
---- ERROR http://localhost:8080/pipelines?restricted=false
java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8080
        at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
        at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
        at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
        at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:283)
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.squareup.okhttp.Call.getResponse(Call.java:286)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.execute(Call.java:80)
        at retrofit.client.OkClient.execute(OkClient.java:53)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
        at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
        at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
        at retrofit.RxSupport$2.run(RxSupport.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at retrofit.Platform$Base$2$1.run(Platform.java:94)
        at java.lang.Thread.run(Thread.java:745)
---- END ERROR

and  
 curl  http://localhost:8084/applications  
responsbody is like []

in  GCP
*GCE lunched instance*

As much information about your spinnaker environment as possible, for example: ```I am running Spinnaker using the GCE images to deploy into  GCP. ```

even i enabled firewall rules 8080 port also..

**Comment by phanikumarp** [comment]
issue fixed ,it about tunnel issue
