### ISSUE TITLE
Spinnaker deploye stage exception  Path parameter "app"  value must not be null.

### ISSUE THREAD

**Issue by phanikumarp** [spinnaker/spinnaker#1395]
Path parameter "app" value must not be null.

Please provide:GCP

*Spinnaker deploy stage*

*GCP Cloud Provider*

[tTaskExecutor-1] c.n.s.orca.clouddriver.OortService       : [anonymous] ---- ERROR 
2017-02-01 15:01:00.490 - INFO 12189 --- [tTaskExecutor-1] c.n.s.orca.clouddriver.OortService       : [anonymous] java.lang.IllegalArgumentException: Path parameter "app" value must not be null.
        at retrofit.RequestBuilder.setArguments(RequestBuilder.java:242)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:298)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
        at com.sun.proxy.$Proxy75.getTargetServerGroup(Unknown Source)
        at com.netflix.spinnaker.orca.clouddriver.OortService$getTargetServerGroup.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at com.netflix.spinnaker.orca.clouddriver.pipeline.servergroup.support.TargetServerGroupResolver$_resolveByTarget_closure2.doCall(TargetServerGroupResolver.groovy
:67)   ......

**Comment by duftler** [comment]
Can you please provide steps to reproduce?

Also, please include your service version numbers (assuming you're not running from source):

`$ sudo dpkg -l | grep spinnaker`

**Comment by phanikumarp** [comment]
sure , and i am runing from GCP cloud lunch (1 click install ) and 
 sudo dpkg -l | grep spinnaker
ii  spinnaker                              0.75.0-3                   all          spinnaker
ii  spinnaker-clouddriver          1.499.0                     all          spinnaker-clouddriver
ii  spinnaker-deck                     2.968.0-3                 all          spinnaker-deck
ii  spinnaker-echo                     1.130.0                    all          spinnaker-echo
ii  spinnaker-fiat                        0.20.0                     all          spinnaker-fiat
ii  spinnaker-front50                 1.70.0                     all          spinnaker-front50
ii  spinnaker-gate                      3.2.0                       all          spinnaker-gate
ii  spinnaker-igor                      1.61.0                     all          spinnaker-igor
ii  spinnaker-orca                      1.312.0                   all          spinnaker-orca
ii  spinnaker-rosco                    0.81.0                     all          spinnaker-rosco

**Comment by duftler** [comment]
Thanks. And what are the steps to recreate?

If it is a pipeline, can you please include the pipeline config JSON,
omitting any sensitive bits?

**Comment by duftler** [comment]
Can you please give the steps to recreate and include the pipeline config json if it is caused by a pipeline?

Will be hard to troubleshoot the followup issues you are filing unless we first ensure there isn't something fundamentally off with your baseline configuration.

**Comment by duftler** [comment]
We believe this is the same issue described here: https://spinnakerteam.slack.com/archives/general/p1486308998004657
Fix is to upgrade to the latest services and to dump your redis cache.
Please re-open with steps to reproduce if this is still an issue.
