### ISSUE TITLE
AmazonReservationReport does not support Region-scoped RIs

### ISSUE THREAD

**Issue by robzienert** [spinnaker/spinnaker#1435]
The AmazonReservationReport currently only supports AZ-scoped reservations. If a region-scoped RI is purchased, the entire region will fail to cache with an NPE. The report should probbaly be updated to support allocating region-scoped RIs equally across AZs.

```
java.lang.NullPointerException: Cannot invoke method getAt() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.netflix.spinnaker.clouddriver.aws.model.AmazonReservationReport$OverallReservationDetail.region(AmazonReservationReport.groovy:72)
	at com.netflix.spinnaker.clouddriver.aws.model.AmazonReservationReport$OverallReservationDetail$region$0.call(Unknown Source)
	at com.netflix.spinnaker.clouddriver.aws.provider.agent.ReservationReportCachingAgent$_loadData_closure7.doCall(ReservationReportCachingAgent.groovy:207)
	at sun.reflect.GeneratedMethodAccessor994.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.BooleanReturningMethodInvoker.invoke(BooleanReturningMethodInvoker.java:51)
	at org.codehaus.groovy.runtime.callsite.BooleanClosureWrapper.call(BooleanClosureWrapper.java:53)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4281)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4153)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4138)
	at org.codehaus.groovy.runtime.dgm$202.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.netflix.spinnaker.clouddriver.aws.provider.agent.ReservationReportCachingAgent.loadData(ReservationReportCachingAgent.groovy:206)
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:66)
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:59)
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:193)
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:167)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ajordens** [comment]
Might be problematic to allocate a regional RI to AZs ... maybe simpler to have additional reservation objects w/ '`*`' for `availabilityZone` (or something along those lines)?

The AZ agnostic RIs are purely for billing benefit so not sure if there's value in tracking `totalUsed` or `totalSurplus` (_or even how those values could be calculated_).

**Comment by robzienert** [comment]
`*` would be a good call. Maybe we just create a new `RegionOverview` class that has `total`, but no usage parameters?

**Comment by ajordens** [comment]
Are you thinking this new class of reservation would still be serialized under `reservations`?

```
{
  "reservations": [
    { ... us-west-2a reservation ... },
    { ... us-west-2 reservation ... }
  ]
}
```

**Comment by robzienert** [comment]
Did a little poking at the agent this morning, I think the best course would be to use `*` for the availabilityZone like you suggested, then just list the regional reservations alongside availability zones, setting only `reserved` & `reservedVpc` to the value and setting `used`, `usedVpc` to 0. I don't think downstream clients would break with this.
