### ISSUE TITLE
Failing to update/delete project

### ISSUE THREAD

**Issue by igcherkaev** [spinnaker/spinnaker#1520]
Cannot update or delete a project after removing pipelines from the applications in the project.

The project had those pipelines in the configuration to display on the right side.

*Cloud Provider*

Self-hosted Kubernetes cluster.

*Environment*

Running latest (almost) images with the "master" tag.

*Feature Area*

UI, orca.

*Description*

I wanted to remove the deleted pipelines from showing up on the right side, but could not do it. Receiving error message when trying to update the project.

```
 Upsert Project (00:00)
 Error:

There was an unknown server error.

View this failed task in the tasks pane.
```

Expected behavior: the project gets updated or deleted, whichever is requested.

*Steps to Reproduce*

Create a project.
Add pipelines to it so it displays them on the right side.
Go to applications and remove some of them.
Then try to update/delete the project.

*Additional Details*

Exception in orca:
```
2017-03-29 23:20:33.354  INFO 1 --- [TaskExecutor-39] c.n.s.o.l.StageStatusPropagationListener : [] Marking Stage as RUNNING (stageId: fb16c626-8f0f-4465-8efe-7fc291ac6bf0)
2017-03-29 23:20:33.358  INFO 1 --- [TaskExecutor-39] c.n.s.o.l.StageTaskPropagationListener   : [] Setting task status to RUNNING (stageId: fb16c626-8f0f-4465-8efe-7fc291ac6bf0, taskId: 1) [beforeTask]
2017-03-29 23:20:33.376 ERROR 1 --- [TaskExecutor-39] o.s.batch.core.step.AbstractStep         : [] Encountered an error executing step fb16c626-8f0f-4465-8efe-7fc291ac6bf0.upsertProject.upsertProject.1 in job Orchestration:proquote4:19428505-7744-451d-8b5e-8e8f473b3c64
java.lang.IllegalAccessError: tried to access method com.netflix.spinnaker.orca.pipeline.model.Stage.mapTo(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object; from class com.netflix.spinnaker.orca.applications.pipelines.UpsertProjectStage$UpsertProjectTask
        at com.netflix.spinnaker.orca.applications.pipelines.UpsertProjectStage$UpsertProjectTask.execute(UpsertProjectStage.groovy:59)
        at com.netflix.spinnaker.orca.batch.TaskTasklet.doExecuteTask(TaskTasklet.groovy:192)
        at sun.reflect.GeneratedMethodAccessor573.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:923)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:906)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:74)
        at com.netflix.spinnaker.orca.batch.TaskTasklet$_executeTask_closure9.doCall(TaskTasklet.groovy:213)
        at com.netflix.spinnaker.orca.batch.TaskTasklet$_executeTask_closure9.doCall(TaskTasklet.groovy)
        at sun.reflect.GeneratedMethodAccessor376.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at com.netflix.spinnaker.security.AuthenticatedRequest$_propagate_closure2.doCall(AuthenticatedRequest.groovy:57)
        at com.netflix.spinnaker.security.AuthenticatedRequest$_propagate_closure2.doCall(AuthenticatedRequest.groovy)
        at sun.reflect.GeneratedMethodAccessor375.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at com.netflix.spinnaker.orca.batch.TaskTasklet.executeTask(TaskTasklet.groovy:212)
        at com.netflix.spinnaker.orca.batch.TaskTasklet.execute(TaskTasklet.groovy:92)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:271)
        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:198)
        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
        at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
        at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:67)
        at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:165)
        at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
        at org.springframework.batch.core.job.flow.support.state.FlowState.handle(FlowState.java:55)
        at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:165)
        at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
        at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:134)
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:304)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-03-29 23:20:33.378  INFO 1 --- [TaskExecutor-39] c.n.s.o.l.StageTaskPropagationListener   : [] Setting task status to null (stageId: fb16c626-8f0f-4465-8efe-7fc291ac6bf0, taskId: 1, taskName: upsertProject) [afterTask]
```

**Comment by anotherchrisberry** [comment]
We fixed this a week ago but forgot to close this issue - sorry for the late reply.
