### ISSUE TITLE
[k8s][Clouddriver] Clouddriver fails to start if k8s api server is unavailable

### ISSUE THREAD

**Issue by edwinavalos** [spinnaker/spinnaker#1653]
*Title*

Clouddriver fails to start if k8s api server is unavailable. It might also make clouddriver unhealthy after clouddriver has succesfully started up in the past, this one is unconfirmed, but I'm pretty certain

*Cloud Provider*
kubernetes

*Environment*

Clouddriver v1.617.0

*Feature Area*

Clouddriver namespace caching

*Description*

What I see
If the API server becomes inaccessible or if the token is bad, the namespace crawl will cause Spinnaker to go unhealthy.

What I would like to see
If there's other accounts listed in Clouddriver settings, it shouldn't mark the whole instance as unhealthy, maybe someway to indicate one of the accounts is down and passover it gracefully? This opens a can of worms. I'm very much open to discussion about how to 'fix' this.

*Steps to Reproduce*

1. Add k8s clouddriver account to clouddriver settings
2. make sure the k8s apiserver is inaccesible
3. Start clouddriver
4. Clouddriver fails to ever become healthy

*Additional Details*

```
[spinnaker-clouddriver-3509855485-gfcxm] 2017-05-17 16:21:14.055  WARN 8 --- [tionAction-4639] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.kubernetes.provider.KubernetesProvider:k8s-lab/KubernetesInstanceCachingAgent[1/1] completed
[spinnaker-clouddriver-3509855485-gfcxm]
[spinnaker-clouddriver-3509855485-gfcxm] com.netflix.spinnaker.clouddriver.kubernetes.deploy.exception.KubernetesOperationException: Get Namespaces for account k8s-lab failed: An error has occurred.
[spinnaker-clouddriver-3509855485-gfcxm] at sun.reflect.GeneratedConstructorAccessor572.newInstance(Unknown Source)
[spinnaker-clouddriver-3509855485-gfcxm] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[spinnaker-clouddriver-3509855485-gfcxm] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[spinnaker-clouddriver-3509855485-gfcxm] at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
[spinnaker-clouddriver-3509855485-gfcxm] at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
[spinnaker-clouddriver-3509855485-gfcxm] at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
[spinnaker-clouddriver-3509855485-gfcxm] at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiAdaptor.formatException(KubernetesApiAdaptor.groovy:64)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiAdaptor$formatException$23.callCurrent(Unknown Source)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiAdaptor.exceptionWrapper(KubernetesApiAdaptor.groovy:102)
[spinnaker-clouddriver-3509855485-gfcxm] at sun.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
[spinnaker-clouddriver-3509855485-gfcxm] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[spinnaker-clouddriver-3509855485-gfcxm] at java.lang.reflect.Method.invoke(Method.java:498)
[spinnaker-clouddriver-3509855485-gfcxm] at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
[spinnaker-clouddriver-3509855485-gfcxm] at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
[spinnaker-clouddriver-3509855485-gfcxm] at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiAdaptor.getNamespacesByName(KubernetesApiAdaptor.groovy:383)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesCredentials.getNamespaces(KubernetesCredentials.java:77)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesCredentials$getNamespaces.call(Unknown Source)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.clouddriver.kubernetes.provider.agent.KubernetesCachingAgent.reloadNamespaces(KubernetesCachingAgent.groovy:55)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.clouddriver.kubernetes.provider.agent.KubernetesCachingAgent$reloadNamespaces$0.callCurrent(Unknown Source)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.clouddriver.kubernetes.provider.agent.KubernetesInstanceCachingAgent.loadData(KubernetesInstanceCachingAgent.groovy:57)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:66)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:59)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:193)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:167)
[spinnaker-clouddriver-3509855485-gfcxm] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[spinnaker-clouddriver-3509855485-gfcxm] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[spinnaker-clouddriver-3509855485-gfcxm] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[spinnaker-clouddriver-3509855485-gfcxm] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[spinnaker-clouddriver-3509855485-gfcxm] at java.lang.Thread.run(Thread.java:745)
[spinnaker-clouddriver-3509855485-gfcxm] Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
[spinnaker-clouddriver-3509855485-gfcxm] at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:61)
[spinnaker-clouddriver-3509855485-gfcxm] at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:52)
[spinnaker-clouddriver-3509855485-gfcxm] at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:538)
[spinnaker-clouddriver-3509855485-gfcxm] at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:64)
[spinnaker-clouddriver-3509855485-gfcxm] at io.fabric8.kubernetes.client.dsl.Listable$list.call(Unknown Source)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiAdaptor$_getNamespacesByName_closure39.doCall(KubernetesApiAdaptor.groovy:384)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiAdaptor$_getNamespacesByName_closure39.doCall(KubernetesApiAdaptor.groovy)
[spinnaker-clouddriver-3509855485-gfcxm] at sun.reflect.GeneratedMethodAccessor1374.invoke(Unknown Source)
[spinnaker-clouddriver-3509855485-gfcxm] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[spinnaker-clouddriver-3509855485-gfcxm] at java.lang.reflect.Method.invoke(Method.java:498)
[spinnaker-clouddriver-3509855485-gfcxm] at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[spinnaker-clouddriver-3509855485-gfcxm] at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[spinnaker-clouddriver-3509855485-gfcxm] at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
[spinnaker-clouddriver-3509855485-gfcxm] at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
[spinnaker-clouddriver-3509855485-gfcxm] at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
[spinnaker-clouddriver-3509855485-gfcxm] at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
[spinnaker-clouddriver-3509855485-gfcxm] at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57)
[spinnaker-clouddriver-3509855485-gfcxm] at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
[spinnaker-clouddriver-3509855485-gfcxm] at com.netflix.spinnaker.clouddriver.kubernetes.api.KubernetesApiAdaptor.exceptionWrapper(KubernetesApiAdaptor.groovy:97)
[spinnaker-clouddriver-3509855485-gfcxm] ... 21 common frames omitted
[spinnaker-clouddriver-3509855485-gfcxm] Caused by: javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
[spinnaker-clouddriver-3509855485-gfcxm] at sun.security.ssl.ClientHandshaker.handshakeAlert(ClientHandshaker.java:1441)
[spinnaker-clouddriver-3509855485-gfcxm] at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2016)
[spinnaker-clouddriver-3509855485-gfcxm] at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
[spinnaker-clouddriver-3509855485-gfcxm] at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
[spinnaker-clouddriver-3509855485-gfcxm] at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
[spinnaker-clouddriver-3509855485-gfcxm] at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[spinnaker-clouddriver-3509855485-gfcxm] at io.fabric8.kubernetes.client.utils.HttpClientUtils$3.intercept(HttpClientUtils.java:97)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
[spinnaker-clouddriver-3509855485-gfcxm] at okhttp3.RealCall.execute(RealCall.java:60)
[spinnaker-clouddriver-3509855485-gfcxm] at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:235)
[spinnaker-clouddriver-3509855485-gfcxm] at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
[spinnaker-clouddriver-3509855485-gfcxm] at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:536)
[spinnaker-clouddriver-3509855485-gfcxm] ... 37 common frames omitted
[spinnaker-clouddriver-3509855485-gfcxm]
```

**Comment by lwander** [comment]
AFAIK this is a problem all cloud providers have - worth thinking about how best to fix this, or if this should be fixed at all. The health indicator for broken accounts is often useful.

**Comment by milsonian** [comment]
Updated findings on start behavior:
1) K8s API made unreachable (before starting)
2) When clouddriver starts, regular ```unable to add account``` is logged and account is omitted. 
 Other accounts/clusters appear and function fine.
3) Restored K8s API connectivity.  Account does not return/appear (expected, it was skipped at start)
4) Restarted clouddriver, account added and functions fine

So, in terms of start behavior this issue can potentially be closed - clouddriver no longer fails to start.
See [1775](https://github.com/spinnaker/spinnaker/issues/1775) however for details on behavior when backend APIs are interrupted while running, which causes bigger issues.
