### ISSUE TITLE
Spinnaker not started in AWS

### ISSUE THREAD

**Issue by phanikumarp** [spinnaker/spinnaker#1673]
*Spinnaker not started in aws instances*

*AWS*

*ubuntu14.04*

Spinnaker in AWS instances not started, i tried , i got following error 

Spinnaker subsystem=clouddriver is up.
Waiting for front50 to start accepting requests on port 8080...
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
        ... 134 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.netflix.spinnaker.front50.model.pipeline.PipelineTemplateDAO] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        ... 147 more

**Comment by sveniu** [comment]
This is likely due to trying to use Cassandra as a backing store for front50 after the change in #222 (which would include front50 version 1.93.0 and up). Downgrading to front50 1.92.1 will make it work again. Upgrading to 1.95.2 or newer will probably work, too; it includes the commit in #223, which should help.

This was also referenced by @robzienert on the [Spinnaker Slack](https://spinnakerteam.slack.com/archives/C091CCWRJ/p1495487439999926).

**Comment by robzienert** [comment]
The latest front50 version has this fixed.

**Comment by robzienert** [comment]
The latest front50 version has this fixed.
