### ISSUE TITLE
ALB Caching Failing in govcloud

### ISSUE THREAD

**Issue by rogerswingle** [spinnaker/spinnaker#1698]
*Cloud Provider*
AWS GovCloud

*Environment*
We're running spinnaker in GovCloud, which was originally installed via `bash <(curl --silent https://spinnaker.bintray.com/scripts/InstallSpinnaker.sh)`  but has been upgraded over the months via `apt-get upgrade`

*Description*
Application Load Balancers aren't showing up in in Spinnaker for GovCloud.  We're currently using spinnaker to deploy services to Classic ELBs and we're hoping to cutover to ALBs.

*Additional Details*
```
2017-05-30 19:42:08.955  WARN 28863 --- [cutionAction-27] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.aws.provider.AwsProvider:default/us-gov-west-1/AmazonApplicationLoadBalancerCachingAgent completed

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at java_util_Optional$get$1.call(Unknown Source)
	at com.netflix.spinnaker.clouddriver.aws.provider.agent.AmazonApplicationLoadBalancerCachingAgent.buildCacheResult(AmazonApplicationLoadBalancerCachingAgent.groovy:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at com.netflix.spinnaker.clouddriver.aws.provider.agent.AmazonApplicationLoadBalancerCachingAgent.loadDataInternal(AmazonApplicationLoadBalancerCachingAgent.groovy:110)
	at com.netflix.spinnaker.clouddriver.aws.provider.agent.AmazonApplicationLoadBalancerCachingAgent$loadDataInternal.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at com.netflix.spinnaker.clouddriver.aws.provider.agent.AmazonLoadBalancerCachingAgent$loadDataInternal.callCurrent(Unknown Source)
	at com.netflix.spinnaker.clouddriver.aws.provider.agent.AbstractAmazonLoadBalancerCachingAgent.loadData(AbstractAmazonLoadBalancerCachingAgent.groovy:138)
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:66)
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:59)
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:193)
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:167)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

```
2017-05-30 19:39:08.897  WARN 28863 --- [cutionAction-29] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.aws.provider.AwsProvider:default/us-gov-west-1/AmazonTargetGroupCachingAgent completed

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at java_util_Optional$get$1.call(Unknown Source)
	at com.netflix.spinnaker.clouddriver.aws.provider.agent.AmazonTargetGroupCachingAgent.buildCacheResult(AmazonTargetGroupCachingAgent.groovy:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.netflix.spinnaker.clouddriver.aws.provider.agent.AmazonTargetGroupCachingAgent.loadData(AmazonTargetGroupCachingAgent.groovy:138)
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:66)
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:59)
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:193)
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:167)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rogerswingle** [comment]
From creeping around the code I'm pretty sure the problem is with
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/data/ArnUtils.groovy#L22
govcloud ALB arns look like this `arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:{{accountid}}:loadbalancer/app/{{alb-name}}/{{randomstring}}`
