### ISSUE TITLE
Not able to start Spinnaker. 

### ISSUE THREAD

**Issue by rakesh-joshi** [spinnaker/spinnaker#1703]
Hi, I'm getting below error, can someone help me here.   

../spinnaker/dev/run_dev.sh [service]
Traceback (most recent call last):
  File "../spinnaker/dev/dev_runner.py", line 299, in <module>
    DevRunner.main()
  File "/Users/rakesh.joshi/SpinnakerHome/spinnaker/pylib/spinnaker/spinnaker_runner.py", line 611, in main
#     runner.run(options)
  File "/Users/rakesh.joshi/SpinnakerHome/spinnaker/pylib/spinnaker/spinnaker_runner.py", line 583, in run
    self.maybe_start_job(self.get_all_java_subsystem_jobs(), component)
  File "/Users/rakesh.joshi/SpinnakerHome/spinnaker/pylib/spinnaker/spinnaker_runner.py", line 279, in maybe_start_job
    subsystem, environ=self.get_subsystem_environ(subsystem))
  File "/Users/rakesh.joshi/SpinnakerHome/spinnaker/pylib/spinnaker/spinnaker_runner.py", line 213, in start_subsystem_if_local
    if not is_local(host):
  File "/Users/rakesh.joshi/SpinnakerHome/spinnaker/pylib/spinnaker/spinnaker_runner.py", line 61, in is_local
    return __ifconfig_lines.find(ip) >= 0
TypeError: expected a string or other character buffer object

**Comment by skim1420** [comment]
This script should be run from the parent directory containing each of the spinnaker services as well as spinnaker/spinnaker. So for example, I have a `~/build` directory which contains the subdirs `spinnaker`, `deck`, `orca`, `clouddriver`, etc. From the `~/build` directory, I run `./spinnaker/dev/run_dev.sh`

Is that what you're doing as well?

**Comment by lwander** [comment]
The rundev script are made obsolete by https://www.spinnaker.io/community/contributing/#how-to-run-spinnaker-locally-for-development
