### ISSUE TITLE
Clouddriver gets unhealthy when kubernetes account API is unreachable

### ISSUE THREAD

**Issue by milsonian** [spinnaker/spinnaker#1775]
*Title*
Clouddriver gets unhealthy when kubernetes account API is unreachable

*Cloud Provider*
Kubernetes

*Environment*
Clouddriver 1.637.0

*Feature Area*
Accounts

*Description*
When a k8s apiserver for a single account/cluster becomes unhealthy/unreachable, clouddriver goes to an unusable state.

Observed:
1) Clouddriver is running, with a number of k8s accounts (clusters)
2) Connectivity is interrupted to one account
3) Clouddriver degrades (but doesn't exit), which has various effects - we see deck timeouts for authenticated users, and auth failures/whitelabel error page for unauthenticated users (unable to auth on return from saml), rendering spinnaker unusable.  Applications referencing the failed account also no longer appeared in deck (e.g. via search).
4) Restored connectivity to the account
5) Clouddriver recovers immediately - deck is fine, users can authenticate, and missing applications searchable/visible.  Note no restart of clouddriver was necessary.

Expected:
Ideally, if a backend API is unavailable, clouddriver should disable/ignore it and other accounts should continue to function.
At a minimum, it should crash/panic and not continue running in an unusable state - so that on restart the account will be disabled and spinnaker will continue functioning otherwise normally (obviously, the former would be preferred).

Related:  See [this](https://github.com/spinnaker/spinnaker/issues/1653) issue - I will add a comment soon with latest findings on startup behavior.

*Steps to Reproduce*
1) Add an account that references a k8s cluster and start clouddriver
2) Create an app and loadbalancer/some resource for that account
3) Break network connectivity to the k8s API via method of your choice
4) Attempt to interact with application; attempt to saml authenticate
5) Restore network connectivity to the k8s API
6) Observe app and other functionality returning

*Additional Details*
Clouddriver log after disconnection - these keep logging at a furious pace:
```
2017-06-20 19:17:42.690 ERROR 8 --- [0.0-7002-exec-4] c.n.s.c.LoggingHandlerExceptionResolver  : Error occurred handling request for http://(ip)/credentials
java.lang.IllegalArgumentException: Get Namespaces for account (account) failed: Operation: [list]  for kind: [Namespace]  with name: [null]  in namespace: [null]  failed. (through reference chain: com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesNamedAccountCredentials["namespaces"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3589)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3508)
        at com.fasterxml.jackson.databind.ObjectMapper$convertValue$3.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at com.fasterxml.jackson.databind.ObjectMapper$convertValue$3.call(Unknown Source)
        at com.netflix.spinnaker.clouddriver.controllers.CredentialsController.render(CredentialsController.groovy:77)
        at com.netflix.spinnaker.clouddriver.controllers.CredentialsController$render.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
        at com.netflix.spinnaker.clouddriver.controllers.CredentialsController$render.callCurrent(Unknown Source)
        at com.netflix.spinnaker.clouddriver.controllers.CredentialsController.renderSummary(CredentialsController.groovy:66)
        at sun.reflect.GeneratedMethodAccessor477.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:430)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3170)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3140)
        at org.codehaus.groovy.runtime.dgm$66.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
```

After saml redirect, for unauthed users:
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Tue Jun 20 19:36:34 UTC 2017
There was an unexpected error (type=Internal Server Error, status=500).
503 Service Unavailable
```

**Comment by johnrengelman** [comment]
I believe the underlying issue is here - https://github.com/spinnaker/clouddriver/blob/8a6ec0ec9f1fcd17418c2a600b25743842dcf125/clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/CredentialsController.groovy#L52

This should have `try/catch` logic such that the returned list contains valid & reachable accounts. Currently, if any account is not reachable, the whole object mapping operation fails and the controller responds 500.
This is specifically happening for kubernetes accounts because when passing a `KubernetesNamedAccountCredentials` to the `objectMapper` it resolves all the `get...` methods (https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesNamedAccountCredentials.groovy#L85) one of which makes an API call to k8s.

**Comment by johnrengelman** [comment]
This is fixed with https://github.com/spinnaker/clouddriver/commit/ae2c04f37a0cadfe920e2d50a2de019464b05563 and the subsequent cloud driver release
