### ISSUE TITLE
(orca) pipeline stages cannot require successful webhook stage with json string body

### ISSUE THREAD

**Issue by erran** [spinnaker/spinnaker#1842]
# Description
It is not possible to have a pipeline that calls the Find Images stage *after* a webhook stage that returns 200 on success and 404 on failure. This webhook stage cannot be used as a requisite stage on success if it responds with a JSON string body (we've since refactored our api to return a json object as it should have been).

It took me creating the below reproduction steps to realise this is limited to a `application/json` `Content-Type` and a JSON string body but I'll still open the related orca PR for discussion. I validated the error occurs when you use a JSON array body as well.

# Steps to Reproduce
## Failure condition
1. Create a pipeline including a "Find Images" stage that is successful.
2. Add a requisite ("Depends On") webhook stage.
3. Set the webhook url to [mockbin - 200 OK json string body](http://mockbin.com/bin/2b2cca79-497d-49a5-b1cc-23b647da1f97)
    * Leave monitoring disabled.
4. `tail -f orca.log`
5. Run the pipeline.
6. Observe the success of the webhook stage.
7. Observe the failure to start other stages.
8. Observe the stack trace in `orca.log`.

If you take the above steps and use http://httpbin.org/status/404 as the webhook url the pipeline will fail as expected on the webhook stage.

## Work around
We're currently relying on the webhook stage succeeding in parallel to the Find Images stage. We have set failure of this stage to halt the entire pipeline.

If you control the API you can also update the response to use a JSON Object body instead.

# Additional details
JSON string body:
```
Caused by: groovy.lang.MissingPropertyException: No such property: scm for class: java.lang.String
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:66)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetPropertySafe(AbstractCallSite.java:410)
        at com.netflix.spinnaker.orca.pipeline.util.ContextParameterProcessor.precomputeValues(ContextParameterProcessor.groovy:98)
        at com.netflix.spinnaker.orca.pipeline.util.ContextParameterProcessor$precomputeValues$0.callCurrent(Unknown Source)
        at com.netflix.spinnaker.orca.pipeline.util.ContextParameterProcessor.process(ContextParameterProcessor.groovy:75)
        at com.netflix.spinnaker.orca.pipeline.util.ContextParameterProcessor$process.call(Unknown Source)
        at com.netflix.spinnaker.orca.batch.ExecutionContextManager.processEntries(ExecutionContextManager.groovy:52)
        at sun.reflect.GeneratedMethodAccessor3048.invoke(Unknown Source)
```

JSON Array body:
```
Caused by: groovy.lang.MissingPropertyException: Exception evaluating property 'scm' for java.util.ArrayList, Reason: groovy.lang.MissingPropertyException: No such property:
 scm for class: java.lang.String
```

# Environment 
We use AWS as our cloud provider. We're running the following versions of Spinnaker packages (I can expand on this if required:

```
ii  spinnaker                        0.81.0                            all          spinnaker
ii  spinnaker-clouddriver            1.627.0                           all          spinnaker-clouddriver
ii  spinnaker-deck                   2.1121.0                          all          spinnaker-deck
ii  spinnaker-orca                   2.8.1                             all          spinnaker-orca
```

**Comment by jervi** [comment]
I'm unable to reproduce this.
![webhook](https://user-images.githubusercontent.com/155558/31654099-33924f2e-b325-11e7-8bc2-e1e698ea6cc9.png)

**Comment by erran** [comment]
@jervi we discussed in https://github.com/spinnaker/orca/pull/1467 I'll try to reproduce this on a later spinnaker version in a couple of weeks once back from paternity. 👌 It's possible this is no longer an issue.

**Comment by erran** [comment]
Sorry @jervi, was just going through my issues on GitHub and noticed I never closed this out. This was resolved in a later version of orca. 🙆‍♂️
