### ISSUE TITLE
Orca 3.1.1 breaks webhook stages using JSON for validation

### ISSUE THREAD

**Issue by ryan-mf** [spinnaker/spinnaker#1876]
*Cloud Provider*
 * GCP, GKE, GCR

*Environment:*
* Started with Google Cloud Launcher Spinnaker template (jessie/sid) and have maintained/customized from there. Generally use Apt to upgrade Spinnaker-related packages every few days.
* 100% Container/Kubernetes-based pipelines, with an API verification stage in the deployment pipeline that checks a URL that gives JSON output and has field mappings.
* Field mappings in JSON response to HTTP GET are:
  * Status JsonPath: class
  * SUCCESS status mapping: pass
  * TERMINAL status mapping: fail

*Feature Area*
Pipelines, Webhook Stage

*Description*
Before Orca 3.1.1, going back around 4 weeks since setup, the webhook stage in our deployment pipeline was able to successfully hit the configured URL with an HTTP GET, and parse the JSON response to determine the Status (pass/fail per above). Since Orca 3.1.1, the Webhook stage always fails with error:
```No StageDefinitionBuilder implementation for webhook found```

*Steps to Reproduce*
Create a pipeline that deploys anything that then answers an HTTP query with a JSON response with the desired field mappings. Add a stage to the pipeline that queries this URL to look for pass/fail to determine if the deployment steps up until that point are working as expected before proceeding to further stages in the pipeline.

*Additional Details*
Orca Log:
```
2017-08-01 18:53:51.895  WARN 8633 --- [eHandlerPool-28] c.n.s.o.e.DefaultExceptionHandler        : [] Error ocurred during task Check API in stage
com.netflix.spinnaker.orca.pipeline.ExecutionRunner$NoSuchStageDefinitionBuilder: No StageDefinitionBuilder implementation for webhook found
        at com.netflix.spinnaker.orca.q.handler.StageBuilderAware$DefaultImpls.builder(StageBuilderAware.kt:29)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.builder(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.plan(StartStageHandler.kt:103)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.access$plan(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:69)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.handler.AuthenticationAwareKt$sam$Callable$29387641.call(AuthenticationAware.kt)
        at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$1(AuthenticatedRequest.java:66)
        at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:42)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withAuth(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:68)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.MessageHandler$withStage$1.invoke(MessageHandler.kt:69)
        at com.netflix.spinnaker.orca.q.MessageHandler$withStage$1.invoke(MessageHandler.kt:27)
        at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.withExecution(MessageHandler.kt:84)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withExecution(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.withStage(MessageHandler.kt:62)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withStage(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:56)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.invoke(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.QueueProcessor$pollOnce$1$1$1.run(QueueProcessor.kt:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2017-08-01 18:53:51.897 ERROR 8633 --- [eHandlerPool-28] c.n.s.orca.q.handler.StartStageHandler   : [] Error running webhook stage for Pipeline[304a11b6-fcef-47ae-b29d-e42bccb1ede2]
com.netflix.spinnaker.orca.pipeline.ExecutionRunner$NoSuchStageDefinitionBuilder: No StageDefinitionBuilder implementation for webhook found
        at com.netflix.spinnaker.orca.q.handler.StageBuilderAware$DefaultImpls.builder(StageBuilderAware.kt:29)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.builder(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.plan(StartStageHandler.kt:103)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.access$plan(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:69)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.handler.AuthenticationAwareKt$sam$Callable$29387641.call(AuthenticationAware.kt)
        at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$1(AuthenticatedRequest.java:66)
        at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:42)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withAuth(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:68)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.MessageHandler$withStage$1.invoke(MessageHandler.kt:69)
        at com.netflix.spinnaker.orca.q.MessageHandler$withStage$1.invoke(MessageHandler.kt:27)
        at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.withExecution(MessageHandler.kt:84)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withExecution(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.withStage(MessageHandler.kt:62)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withStage(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:56)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
        at com.netflix.spinnaker.orca.q.handler.StartStageHandler.invoke(StartStageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.QueueProcessor$pollOnce$1$1$1.run(QueueProcessor.kt:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by cfieber** [comment]
fix coming in spinnaker/orca#1519

**Comment by cfieber** [comment]
fix in orca 3.1.5 release (building now)

**Comment by ryan-mf** [comment]
Awesome thanks for the quick response!

**Comment by ryan-mf** [comment]
Upgraded to Orca 3.1.5 and confirmed fixed.
