### ISSUE TITLE
GCP authentication fails

### ISSUE THREAD

**Issue by 030** [spinnaker/spinnaker#1939]
the steps from this tutorial have been followed https://www.spinnaker.io/setup/providers/gce/

/var/log/spinnaker/clouddriver/clouddriver.log

```
2017-09-06 14:39:23.110 ERROR 32260 --- [           main] c.n.s.c.g.s.GoogleCredentialsInitializer : Could not load account my-account-name for Google.

2017-09-06 14:39:20.130  INFO 32260 --- [           main] c.n.s.c.security.ProviderUtils           : Adding accounts [my-account-name] of type GoogleNamedAccountCredentials...
java.lang.NullPointerException: Cannot invoke method max() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)

...

2017-09-06 14:39:23.763  WARN 32260 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : Inconsistent constructor declaration on bean with name 'entityTagsController': single autowire-marked constructor flagged as optional - this constructor is effectively required since there is no default constructor to fall back to: public com.netflix.spinnaker.clouddriver.controllers.EntityTagsController(org.springframework.context.MessageSource,java.util.Optional)

```

while accoriding to hal the authentication should be successful

```
$ hal config provider google account list
+ Get current deployment
  Success
+ Get the google provider
  Success
Problems in default:
- WARNING You have not yet selected a version of Spinnaker to
  deploy.
? Options include:
  - 1.1.2
  - 1.2.2

+ Accounts for google:
  - my-gce-account
```

**Comment by 030** [comment]
@duftler Thank you. It turned out that the spinnaker version was outdated.

Running

```
sudo apt-get update
sudo apt-get upgrade spinnaker-clouddriver \
                   spinnaker-deck spinnaker-echo spinnaker-front50 \
                   spinnaker-gate spinnaker-igor spinnaker-orca \
                   spinnaker-rosco spinnaker
sudo restart spinnaker
```

solved the issue

https://cloud.google.com/solutions/spinnaker-on-compute-engine
