### ISSUE TITLE
CloudDriver error in error handling: 'groovy.lang.MissingPropertyException: No such property: error'

### ISSUE THREAD

**Issue by dalvizu** [spinnaker/spinnaker#1971]
*Title*

CloudDriver error in error handling: 'groovy.lang.MissingPropertyException: No such property: error'

*Cloud Provider*

AWS

*Environment*

I am evaluating spinnaker - I've installed it to Amazon ec2 and am using it to deploy applications in ec2. I'm attempting to create a application load balancer (ALB) in amazon  using spinnaker UI. The version of clouddriver I am using iss:

```
clouddriver-web-0.6.2-20170821194112.jar
```

(Is there a better way to find out the version?)

*Feature Area*

Creating load balancer - anything that errors our in clouddriver

*Description*

The behavior you expect to see, and the actual behavior.

*Steps to Reproduce*

1. Install spinnaker
2. Configure AWS as cloud provider
3. Create ALB, select 'no vpc' as option

* Expected behavior*

1. ALB created
2. If error in ALB creation, some informative error

* Observed behavior *
1. Error in clouddriver ui: `Exception: Failed for unknown reason.` (screenshot below)

![image](https://user-images.githubusercontent.com/731899/30605527-a9957dd2-9d2b-11e7-8f1b-88474e9c13fe.png)

*Additional Details*

Error log of clouddriver has more info (apache trace logging on to show root error from amazon which we expect to bubble up):

`/var/log/clouddriver/clouddriver.log`:

```
2017-09-19 16:33:50.889 DEBUG 7058 --- [pool-3-thread-1] org.apache.http.wire                     : http-outgoing-54 << "    <Code>ValidationError</Code>[\n]"
2017-09-19 16:33:50.889 DEBUG 7058 --- [pool-3-thread-1] org.apache.http.wire                     : http-outgoing-54 << "    <Message>At least two subnets in two different Availability Zones must be speciff
ied</Message>[\n]"
2017-09-19 16:33:50.889 DEBUG 7058 --- [pool-3-thread-1] org.apache.http.wire                     : http-outgoing-54 << "  </Error>[\n]"
2017-09-19 16:33:50.889 DEBUG 7058 --- [pool-3-thread-1] org.apache.http.wire                     : http-outgoing-54 << "  <RequestId>51801239-9d58-11e7-b31c-eb5ff9033efa</RequestId>[\n]"
2017-09-19 16:33:50.889 DEBUG 7058 --- [pool-3-thread-1] org.apache.http.wire                     : http-outgoing-54 << "</ErrorResponse>[\n]"
2017-09-19 16:33:50.959  INFO 7058 --- [pool-3-thread-1] com.amazonaws.latency                    : ServiceName=[AmazonElasticLoadBalancing], AWSErrorCode=[ValidationError], StatusCode=[400], ServiceEndpoii
nt=[https://elasticloadbalancing.us-west-2.amazonaws.com], Exception=[com.amazonaws.services.elasticloadbalancingv2.model.AmazonElasticLoadBalancingException: At least two subnets in two different Availabii
lity Zones must be specified (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Code: ValidationError; Request ID: 51801239-9d58-11e7-b31c-eb5ff9033efa)], RequestType=[CreateLoadBalancerRequest]]
, AWSRequestID=[51801239-9d58-11e7-b31c-eb5ff9033efa], HttpClientPoolPendingCount=0, RetryCapacityConsumed=0, HttpClientPoolAvailableCount=1, RequestCount=1, Exception=1, HttpClientPoolLeasedCount=0, Requee
stMarshallTime=[0.658], ClientExecuteTime=[79.796], HttpClientSendRequestTime=[0.427], HttpRequestTime=[8.59], RequestSigningTime=[0.237], CredentialsRequestTime=[0.012, 0.003], HttpClientReceiveResponseTii
me=[7.627],
2017-09-19 16:33:51.038  INFO 7058 --- [pool-3-thread-1] c.n.s.c.data.task.jedis.JedisTask        : [INIT] - Unknown failure -- groovy.lang.MissingPropertyException: No such property: error for class: com.netflix.spinnaker.clouddriver.orchestration.AtomicOperationException
Possible solutions: errors
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
        at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy:104)
        at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$1(AuthenticatedRequest.java:66)
        at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by dalvizu** [comment]
The root error appears to be https://github.com/spinnaker/spinnaker.github.io/issues/336

**Comment by dalvizu** [comment]
Looks to be fixed by:

https://github.com/spinnaker/clouddriver/pull/1793

**Comment by dalvizu** [comment]
Upgrading from `1.2.2 (Stanley)` to `1.3.1 (Ozark)` fixed this issue
