### ISSUE TITLE
GCP Clouddriver unable to parse Load balancers

### ISSUE THREAD

**Issue by edwinavalos** [spinnaker/spinnaker#2040]
*Title*

GCP Clouddriver unable to parse Load Balancers

*Cloud Provider*

GCP

*Environment*

clouddriver v1.688.1

*Feature Area*

Load Balancing caching

*Description*

Runs into java.lang.IllegalArgumentException: no JSON input found when reading load balancers

*Steps to Reproduce*

Updated from v1.683.1 -> v1.688.1 and load balancers are no longer parsed.

*Additional Details*

```
spinnaker-clouddriver-green-3786523417-6lw0t] 2017-10-17 16:06:02.776  WARN 8 --- [tionAction-7242] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.google.provider.GoogleInfrastructureProvider:lab/us-east1/GoogleInternalLoadBalancerCachingAgent completed
[spinnaker-clouddriver-green-3786523417-6lw0t]
[spinnaker-clouddriver-green-3786523417-6lw0t] java.lang.IllegalArgumentException: no JSON input found
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[google-http-client-1.23.0.jar:1.23.0]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:49) ~[google-http-client-1.23.0.jar:1.23.0]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.google.api.client.json.JsonParser.startParsing(JsonParser.java:223) ~[google-http-client-1.23.0.jar:1.23.0]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.google.api.client.json.JsonParser.parse(JsonParser.java:380) ~[google-http-client-1.23.0.jar:1.23.0]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.google.api.client.json.JsonParser.parse(JsonParser.java:355) ~[google-http-client-1.23.0.jar:1.23.0]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:87) ~[google-http-client-1.23.0.jar:1.23.0]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81) ~[google-http-client-1.23.0.jar:1.23.0]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.google.api.client.googleapis.batch.BatchUnparsedResponse.getParsedDataClass(BatchUnparsedResponse.java:234) ~[google-api-client-1.23.0.jar:1.23.0]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseAndCallback(BatchUnparsedResponse.java:196) ~[google-api-client-1.23.0.jar:1.23.0]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseNextResponse(BatchUnparsedResponse.java:155) ~[google-api-client-1.23.0.jar:1.23.0]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:253) ~[google-api-client-1.23.0.jar:1.23.0]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.google.api.client.googleapis.batch.BatchRequest$execute$0.call(Unknown Source) ~[na:na]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.netflix.spinnaker.clouddriver.google.GoogleExecutorTraits$Trait$Helper.timeExecuteBatch(GoogleExecutorTraits.groovy:50) ~[clouddriver-google-1.689.0-SNAPSHOT.jar:1.689.0-SNAPSHOT]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.netflix.spinnaker.clouddriver.google.GoogleExecutorTraits$Trait$Helper$timeExecuteBatch$10.call(Unknown Source) ~[na:na]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.netflix.spinnaker.clouddriver.google.provider.agent.AbstractGoogleCachingAgent.timeExecuteBatch(AbstractGoogleCachingAgent.groovy) ~[clouddriver-google-1.689.0-SNAPSHOT.jar:1.689.0-SNAPSHOT]
[spinnaker-clouddriver-green-3786523417-6lw0t] at sun.reflect.GeneratedMethodAccessor161.invoke(Unknown Source) ~[na:na]
[spinnaker-clouddriver-green-3786523417-6lw0t] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
[spinnaker-clouddriver-green-3786523417-6lw0t] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
[spinnaker-clouddriver-green-3786523417-6lw0t] at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:169) ~[groovy-all-2.4.7.jar:2.4.7]
[spinnaker-clouddriver-green-3786523417-6lw0t] at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59) ~[groovy-all-2.4.7.jar:2.4.7]
[spinnaker-clouddriver-green-3786523417-6lw0t] at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174) ~[groovy-all-2.4.7.jar:2.4.7]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.netflix.spinnaker.clouddriver.google.provider.agent.AbstractGoogleCachingAgent.executeIfRequestsAreQueued(AbstractGoogleCachingAgent.groovy:75) ~[clouddriver-google-1.689.0-SNAPSHOT.jar:1.689.0-SNAPSHOT]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.netflix.spinnaker.clouddriver.google.provider.agent.AbstractGoogleCachingAgent$executeIfRequestsAreQueued$0.callCurrent(Unknown Source) ~[na:na]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleInternalLoadBalancerCachingAgent.constructLoadBalancers(GoogleInternalLoadBalancerCachingAgent.groovy:88) ~[clouddriver-google-1.689.0-SNAPSHOT.jar:1.689.0-SNAPSHOT]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleInternalLoadBalancerCachingAgent.constructLoadBalancers(GoogleInternalLoadBalancerCachingAgent.groovy) ~[clouddriver-google-1.689.0-SNAPSHOT.jar:1.689.0-SNAPSHOT]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.netflix.spinnaker.clouddriver.google.provider.agent.AbstractGoogleLoadBalancerCachingAgent.getLoadBalancers(AbstractGoogleLoadBalancerCachingAgent.groovy:206) ~[clouddriver-google-1.689.0-SNAPSHOT.jar:1.689.0-SNAPSHOT]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.netflix.spinnaker.clouddriver.google.provider.agent.AbstractGoogleLoadBalancerCachingAgent.loadData(AbstractGoogleLoadBalancerCachingAgent.groovy:181) ~[clouddriver-google-1.689.0-SNAPSHOT.jar:1.689.0-SNAPSHOT]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:79) ~[cats-core-1.689.0-SNAPSHOT.jar:1.689.0-SNAPSHOT]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:72) ~[cats-core-1.689.0-SNAPSHOT.jar:1.689.0-SNAPSHOT]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:231) ~[cats-redis-1.689.0-SNAPSHOT.jar:1.689.0-SNAPSHOT]
[spinnaker-clouddriver-green-3786523417-6lw0t] at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:205) ~[cats-redis-1.689.0-SNAPSHOT.jar:1.689.0-SNAPSHOT]
[spinnaker-clouddriver-green-3786523417-6lw0t] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_111]
[spinnaker-clouddriver-green-3786523417-6lw0t] at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111]
[spinnaker-clouddriver-green-3786523417-6lw0t] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
[spinnaker-clouddriver-green-3786523417-6lw0t] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
[spinnaker-clouddriver-green-3786523417-6lw0t] at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
[spinnaker-clouddriver-green-3786523417-6lw0t]
```

**Comment by jtk54** [comment]
`GoogleInternalLoadBalancerCachingAgent.groovy:88` is where the batch request for `backendServiceGroupHealth` is executed. The callback that handles those calls implements `FailedSubjectChronicler`, so any of the batched `backendServiceGroupHealth` calls execute and fail, you would see log entries that look like [this](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/FailedSubjectChronicler.groovy#L45).

Do you see any of those types of log entries? If so, can you post them?

If you don't see any of those log entries, then likely the batch call couldn't fire properly and we'll have to dig around more.

**Comment by edwinavalos** [comment]
I see log entries like that for healthchecks

```
2017-10-17 21:42:19.587  WARN 7 --- [tionAction-7508] g.p.a.GoogleHttpLoadBalancerCachingAgent : Failed to read a component of subject ssdclaps-righthand36-gcp-lab-default-https-frontend. The platform error message was:
 The resource 'projects/lab/global/httpsHealthChecks/ssdclaps-righthand36-gcp-lab-default-https-healthcheck' was not found.
Reporting it as 'Failed' to the caching agent.
2017-10-17 21:42:19.587  WARN 7 --- [tionAction-7508] g.p.a.GoogleHttpLoadBalancerCachingAgent : Failed to read a component of subject ssdclaps-righthand37-gcp-lab-default-https-frontend. The platform error message was:
 The resource 'projects/lab/global/httpsHealthChecks/ssdclaps-righthand37-gcp-lab-default-https-healthcheck' was not found.
Reporting it as 'Failed' to the caching agent.
2017-10-17 21:42:19.588  WARN 7 --- [tionAction-7508] g.p.a.GoogleHttpLoadBalancerCachingAgent : Failed to read a component of subject ssdclaps-righthand53-gcp-lab-default-https-frontend. The platform error message was:
 The resource 'projects/lab/global/httpsHealthChecks/ssdclaps-righthand53-gcp-lab-default-http-healthcheck' was not found.
Reporting it as 'Failed' to the caching agent.
2017-10-17 21:42:19.588  WARN 7 --- [tionAction-7508] g.p.a.GoogleHttpLoadBalancerCachingAgent : Failed to read a component of subject ssdclaps-rigthhand31-gcp-lab-default-https-frontend. The platform error message was:
 The resource 'projects/lab/global/httpsHealthChecks/ssdclaps-rigthhand31-gcp-lab-default-https-healthcheck' was not found.
Reporting it as 'Failed' to the caching agent.
2017-10-17 21:42:19.588  WARN 7 --- [tionAction-7508] g.p.a.GoogleHttpLoadBalancerCachingAgent : Failed to read a component of subject ssdclaps-rigthhand33-gcp-lab-default-https-frontend. The platform error message was:
 The resource 'projects/lab/global/httpsHealthChecks/ssdclaps-rigthhand33-gcp-lab-default-https-healthcheck' was not found.
Reporting it as 'Failed' to the caching agent.
2017-10-17 21:42:19.588  WARN 7 --- [tionAction-7508] g.p.a.GoogleHttpLoadBalancerCachingAgent : Failed to read a component of subject ssdclaps-rigthhand34-gcp-lab-default-https-frontend. The platform error message was:
 The resource 'projects/lab/global/httpsHealthChecks/ssdclaps-rigthhand34-gcp-lab-default-https-healthcheck' was not found.
Reporting it as 'Failed' to the caching agent.
2017-10-17 21:42:19.589  WARN 7 --- [tionAction-7508] g.p.a.GoogleHttpLoadBalancerCachingAgent : Failed to read a component of subject ssdclaps-rigthhand41-gcp-lab-default-https-frontend. The platform error message was:
 The resource 'projects/lab/global/httpsHealthChecks/ssdclaps-rigthhand41-gcp-lab-default-tcp-healthcheck' was not found.
Reporting it as 'Failed' to the caching agent.
2017-10-17 21:42:19.589  WARN 7 --- [tionAction-7508] g.p.a.GoogleHttpLoadBalancerCachingAgent : Failed to read a component of subject ssdclaps-rigthhand42-gcp-lab-default-https-frontend. The platform error message was:
 The resource 'projects/lab/global/httpsHealthChecks/ssdclaps-rigthhand42-gcp-lab-default-tcp-healthcheck' was not found.
Reporting it as 'Failed' to the caching agent.
2017-10-17 21:42:19.589  WARN 7 --- [tionAction-7508] g.p.a.GoogleHttpLoadBalancerCachingAgent : Failed to read a component of subject ssdclaps2-rigthhand43-gcp-lab-default-https-frontend. The platform error message was:
 The resource 'projects/lab/global/httpsHealthChecks/ssdclaps2-rigthhand43-gcp-lab-default-tcp-healthcheck' was not found.
Reporting it as 'Failed' to the caching agent.
2017-10-17 21:42:19.589  WARN 7 --- [tionAction-7508] g.p.a.GoogleHttpLoadBalancerCachingAgent : Failed to read a component of subject tapsampleapp-api4-gcp-lab-default-https-frontend. The platform error message was:
 The resource 'projects/lab/global/httpsHealthChecks/tapsampleapp-api4-gcp-lab-default-http-healthcheck' was not found.
Reporting it as 'Failed' to the caching agent.
```

these healthchecks are weird as we have been making them via gcp calls in another tool we have.

The health checks actually look like TCP ones, dont know why they end up in https-health-checks

```
➜  EdwinAvalos gcloud compute health-checks list --project lab
NAME                                                    PROTOCOL
...
ssdclaps-righthand36-gcp-lab-default-https-healthcheck  TCP
ssdclaps-righthand37-gcp-lab-default-https-healthcheck  TCP
ssdclaps-righthand53-gcp-lab-default-http-healthcheck   HTTP
ssdclaps-rigthhand27-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand28-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand29-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand31-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand32-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand33-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand34-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand35-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand41-gcp-lab-default-tcp-healthcheck    TCP
ssdclaps-rigthhand42-gcp-lab-default-tcp-healthcheck    TCP
ssdclaps2-rigthhand43-gcp-lab-default-tcp-healthcheck   TCP
```

one of these looks like

```
➜  EdwinAvalos gcloud compute health-checks describe ssdclaps2-rigthhand43-gcp-lab-default-tcp-healthcheck
checkIntervalSec: 6
creationTimestamp: '2017-10-16T08:29:54.510-07:00'
healthyThreshold: 2
id: '6332406084485607069'
kind: compute#healthCheck
name: ssdclaps2-rigthhand43-gcp-lab-default-tcp-healthcheck
selfLink: https://www.googleapis.com/compute/v1/projects/lab/global/healthChecks/ssdclaps2-rigthhand43-gcp-lab-default-tcp-healthcheck
tcpHealthCheck:
  port: 443
  proxyHeader: NONE
timeoutSec: 5
type: TCP
unhealthyThreshold: 2
```

**Comment by jtk54** [comment]
Seems that all of those log entries are coming from `GoogleHttpLoadBalancerCachingAgent`, where the first stack trace is coming from caching internal load balancers.

`GoogleHttpLoadBalancerCachingAgent` only supports `HttpsHealthCheck` and `HttpHealthCheck` objects, not the more generic, nested `HealthCheck` objects yet, which is why you would see those failures.

I noticed you have several closely-named health checks. 

Do you have health checks with the same name for more than one type of health check type? E.g. 

```
NAME                                                    PROTOCOL
...
ssdclaps-righthand36-gcp-lab-default-https-healthcheck  TCP
ssdclaps-righthand36-gcp-lab-default-https-healthcheck  HTTPS
```
That might cause the internal LB caching agent failure as well. Can you find similar log statements for the internal LB agent?

**Comment by edwinavalos** [comment]
```
➜  EdwinAvalos gcloud compute health-checks list --project tgt-pe-lab | grep 'ssdclaps-.*-gcp-lab'
ssdclaps-righthand36-gcp-lab-default-https-healthcheck  TCP
ssdclaps-righthand37-gcp-lab-default-https-healthcheck  TCP
ssdclaps-righthand53-gcp-lab-default-http-healthcheck   HTTP
ssdclaps-rigthhand27-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand28-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand29-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand31-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand32-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand33-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand34-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand35-gcp-lab-default-https-healthcheck  TCP
ssdclaps-rigthhand41-gcp-lab-default-tcp-healthcheck    TCP
ssdclaps-rigthhand42-gcp-lab-default-tcp-healthcheck    TCP
```

I don't see any repeating here, I downgraded to v1.687.3 and the `java.lang.IllegalArgumentException: no JSON input found` errors went away, I see see the issue with the ssd-claps healthcheck parsing, but I think those are graceful errors that you made graceful a while ago.

Load balancers in the account are now showing up when they were before, so I think you were right to think it might be something in the client library.

**Comment by jtk54** [comment]
Ok, good to know -- thanks for the info.

**Comment by jtk54** [comment]
I did some experimentation around the stack traces reported above. There are two distinct issues here.

1. GCE platform API throwing spurious `java.lang.IllegalArgumentException: no JSON input found`  exceptions on `GroupHealth` calls.

2. Spinnaker attempting to cache load balancers with the new [UHCs (unified health checks)](https://cloud.google.com/compute/docs/load-balancing/health-checks) **in load balancing types where the UHCs are not supported yet**, e.g. HTTP LBs.

I confirmed that (1) occurs when I update Clouddriver to > v1.687.*, **but I can still see all my load balancers**. These exceptions do not seem to actually cause any failures in Spinnaker.

(2) is occurring because UHCs are being created outside of Spinnaker and new LBs are created with the UHCs even though Spinnaker cannot currently handle that LB configuration.

There are two fixes, short term and long term:

* Short Term: Create and manage all GCE infrastructure through Spinnaker so there are no misconfigurations. Spinnaker does not create infrastructure it can't read.
* Long Term: Support UHCs in all load balancing types consistently with `gcloud` and the Cloud Console so users can configure infrastructure anywhere and have Spinnaker manage it.

**Comment by edwinavalos** [comment]
The short term won't work for us as we have a lot automation outside of just Spinnaker, but we will try the new version and see if we can replicate the problems we saw.

**Comment by jtk54** [comment]
@edwinavalos removed all the offending HCs in (2) but still sees `no JSON input...` exceptions preventing LBs from loading. I can reproduce the `no JSON input...` exceptions but my LBs load. I'll continue to work with our internal API teams to get some clarity on the reason (1) is occurring.

**Comment by jtk54** [comment]
Never updated this -- we bumped the GCE API version to get rid of the `no JSON input...` exceptions here: https://github.com/spinnaker/spinnaker-dependencies/pull/141.
