### ISSUE TITLE
Clouddriver error while fetching GCE Network

### ISSUE THREAD

**Issue by amitgera** [spinnaker/spinnaker#2060]
facing same issue : https://github.com/spinnaker/spinnaker/issues/1910
As per above cases it shows closed ,but still facing similar issue , Please help
Above spinnaker setup via instruction in url : https://www.spinnaker.io/guides/tutorials/codelabs/gce-source-to-prod/

Trace logs for ref:
2017-10-26 02:35:03.285  INFO 23934 --- [pool-2-thread-6] c.n.s.c.data.task.jedis.JedisTask        : [ORCHESTRATION] - Orchestration failed: DeployAtomicOperation | IllegalArgumentExce
ption: [Can not set com.google.api.services.compute.model.NetworkRoutingConfig field com.google.api.services.compute.model.Network.routingConfig to java.util.LinkedHashMap (through reference chain: com.google.api.services.compute.model.Network["routingConfig"])]
2017-10-26 02:35:03.286 ERROR 23934 --- [pool-2-thread-6] c.n.s.c.o.DefaultOrchestrationProcessor  : java.lang.IllegalArgumentException: Can not set com.google.api.services.compute.mod
el.NetworkRoutingConfig field com.google.api.services.compute.model.Network.routingConfig to java.util.LinkedHashMap (through reference chain: com.google.api.services.compute.model.Net
work["routingConfig"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3589)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3508)
        at com.fasterxml.jackson.databind.ObjectMapper$convertValue$3.call(Unknown Source)
        at com.netflix.spinnaker.clouddriver.google.provider.view.GoogleNetworkProvider.fromCacheData(GoogleNetworkProvider.groovy:68)
        at sun.reflect.GeneratedMethodAccessor638.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:430)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3170)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3140)
        at org.codehaus.groovy.runtime.dgm$66.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at com.netflix.spinnaker.clouddriver.google.provider.view.GoogleNetworkProvider.loadResults(GoogleNetworkProvider.groovy:58)
        at com.netflix.spinnaker.clouddriver.google.provider.view.GoogleNetworkProvider$loadResults$0.callCurrent(Unknown Source)
        at com.netflix.spinnaker.clouddriver.google.provider.view.GoogleNetworkProvider.getAllMatchingKeyPattern(GoogleNetworkProvider.groovy:53)
        at com.netflix.spinnaker.clouddriver.google.provider.view.GoogleNetworkProvider$getAllMatchingKeyPattern.call(Unknown Source)
        at com.netflix.spinnaker.clouddriver.google.deploy.GCEUtil.queryNetwork(GCEUtil.groovy:131)
        at com.netflix.spinnaker.clouddriver.google.deploy.GCEUtil$queryNetwork$6.call(Unknown Source)
        at com.netflix.spinnaker.clouddriver.google.deploy.handlers.BasicGoogleDeployHandler.handle(BasicGoogleDeployHandler.groovy:161)
        at com.netflix.spinnaker.clouddriver.google.deploy.handlers.BasicGoogleDeployHandler$handle.call(Unknown Source)
        at com.netflix.spinnaker.clouddriver.deploy.DeployAtomicOperation.operate(DeployAtomicOperation.groovy:60)
        at com.netflix.spinnaker.clouddriver.deploy.DeployAtomicOperation.operate(DeployAtomicOperation.groovy)
        at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate.call(Unknown Source)
        at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy:89)
        at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at com.netflix.spinnaker.clouddriver.metrics.TimedCallable$ClosureWrapper.call(TimedCallable.groovy:55)
        at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82)
        at java_util_concurrent_Callable$call.call(Unknown Source)
        at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy:88)
        at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$1(AuthenticatedRequest.java:66)
        at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not set com.google.api.services.compute.model.NetworkRoutingConfig field com.google.api.services.compute.model.Network.routingConfig to java.util.LinkedHashMap (through reference chain: com.google.api.services.compute.model.Network["routingConfig"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)
        at com.fasterxml.jackson.databind.deser.std.ContainerDeserializerBase.wrapAndThrow(ContainerDeserializerBase.java:83)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:529)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:362)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:27)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3584)
        ... 63 more
Caused by: java.lang.IllegalArgumentException: Can not set com.google.api.services.compute.model.NetworkRoutingConfig field com.google.api.services.compute.model.Network.routingConfig to java.util.LinkedHashMap
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
        at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
        at java.lang.reflect.Field.set(Field.java:764)
        at com.google.api.client.util.FieldInfo.setFieldValue(FieldInfo.java:245)
        at com.google.api.client.util.FieldInfo.setValue(FieldInfo.java:206)
        at com.google.api.client.util.GenericData.put(GenericData.java:103)
        at com.google.api.client.util.GenericData.put(GenericData.java:47)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:524)
        ... 66 more

**Comment by amitgera** [comment]
resolved by upgrading spinnaker-clouddriver version  , Please get update image as its older in image
