### ISSUE TITLE
Pipelines for all already existing applications can no longer be manually executed

### ISSUE THREAD

**Issue by mazen-ammar** [spinnaker/spinnaker#2137]
*Cloud Provider*

Kubernetes running on AWS

*Environment*

Spinnaker v1.5.0
Hosted in my own cluster
Images sourced from DockerHub

*Feature Area*

Pipelines

*Description*

As of a day or two ago (11/28 - 11/29), I am unable to manual execute any of my pipelines for existing applications. When I click "Start Manual Execution", it attempts to run the pipeline, but fails. This is for all pipelines in my previously existing applications. If I create a new application, I am able to add a pipeline and manually run it successfully.

When attempting to manually run these pipelines, I get back a 400:
```
Request URL:https://spin-gate.r.u/pipelines/behavioralrisk/COM:%20Deploy%20Behavioral%20Risk%20Microservice
Request Method:OPTIONS
Status Code:400 
Remote Address:34.224.48.64:443
Referrer Policy:no-referrer-when-downgrade
```

In `spin-gate`, I see the following error:
```
java.lang.IllegalArgumentException: Invalid character found in the HTTP protocol
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:529) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:683) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
```

I've tried re-deploying as well as a full clean, but neither had any effect.

**Comment by mazen-ammar** [comment]
After debugging some more, it looks like any pipeline where the name contains a space (and therefore the request url contains `%20`) is broken. Still investigating why that's the case.

**Comment by mazen-ammar** [comment]
This turned out to be an issue with our Apache rules, where we needed to re-encode the spaces when passing the request through to spin-gate. No Spinnaker issues.
