### ISSUE TITLE
Spinnaker ui fails to load when using version 1.5.1

### ISSUE THREAD

**Issue by TomerCo** [spinnaker/spinnaker#2147]
Title:

Spinnaker ui fails to load when using version 1.5.1

*Cloud Provider*

Kubernetes
*Environment*

Running spinnaker on tectonic 

*Feature Area*

UI and clouddriver

*Description*

When accessing the UI screen stuck on the hello banner

*Steps to Reproduce*

Install spinnaker version 1.5.1 using hal 

*Additional Details*

I have been running version 1.4.2 on the same setup with no problem, more over rolling back to 1.4.2 is working fine. Also i tried a fresh installation of 1.5.1 and i am encountering the same issue

The JS console shows the following error : 

`
http://errors.angularjs.org/1.6.4/$injector/modulerr?p0=netflix.spinnaker&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'netflix.spinnaker'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.4%2F%24injector%2Fnomod%3Fp0%3Dnetflix.spinnaker%0A%20%20%20%20at%20http%3A%2F%2Fspinnaker.dummy.com%2Fvendor.bundle.js%3A85483%3A12%0A%20%20%20%20at%20http%3A%2F%2Fspinnaker.dummy.com%2Fvendor.bundle.js%3A87679%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Fspinnaker.dummy.com%2Fvendor.bundle.js%3A87600%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Fspinnaker.dummy.com%2Fvendor.bundle.js%3A87677%3A14)%0A%20%20%20%20at%20http%3A%2F%2Fspinnaker.dummy.com%2Fvendor.bundle.js%3A90313%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Fspinnaker.dummy.com%2Fvendor.bundle.js%3A85820%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Fspinnaker.dummy.com%2Fvendor.bundle.js%3A90297%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Fspinnaker.dummy.com%2Fvendor.bundle.js%3A90219%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Fspinnaker.dummy.com%2Fvendor.bundle.js%3A87331%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Fspinnaker.dummy.com%2Fvendor.bundle.js%3A87352%3A12)
`
Also, I am not sure if its related or not as it doesn't appear in sync with ui refresh but , there is the following exception in the clouddriver log:

`
groovy.lang.MissingPropertyException: No such property: e for class: com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiAdapter
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307) ~[groovy-all-2.4.7.jar:2.4.7]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiAdapter$_getDaemonSets_closure2.doCall(KubernetesClientApiAdapter.groovy:176) ~[clouddriver-kubernetes-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiAdapter$_getDaemonSets_closure2.doCall(KubernetesClientApiAdapter.groovy) ~[clouddriver-kubernetes-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor1484.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) ~[groovy-all-2.4.7.jar:2.4.7]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiAdapter.exceptionWrapper(KubernetesClientApiAdapter.groovy:116) ~[clouddriver-kubernetes-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor1273.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190) ~[groovy-all-2.4.7.jar:2.4.7]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiAdapter.getDaemonSets(KubernetesClientApiAdapter.groovy:165) ~[clouddriver-kubernetes-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiAdapter$getDaemonSets$0.call(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.agent.KubernetesControllersCachingAgent$_loadDaemonSets_closure12.doCall(KubernetesControllersCachingAgent.groovy:218) ~[clouddriver-kubernetes-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor1483.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.Closure.call(Closure.java:414) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.Closure.call(Closure.java:430) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3170) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3140) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.dgm$66.invoke(Unknown Source) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-all-2.4.7.jar:2.4.7]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.agent.KubernetesControllersCachingAgent.loadDaemonSets(KubernetesControllersCachingAgent.groovy:217) ~[clouddriver-kubernetes-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.agent.KubernetesControllersCachingAgent.loadData(KubernetesControllersCachingAgent.groovy:174) ~[clouddriver-kubernetes-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:79) ~[cats-core-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:72) ~[cats-core-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:231) ~[cats-redis-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:205) ~[cats-redis-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_111-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
`

Additional information such as screenshots and exception logs.

**Comment by ethanfrogers** [comment]
ping @chlung, this looks related to DaemonSet caching.

**Comment by chlung** [comment]
In 1.5.x branch, I see the problem "groovy.lang.MissingPropertyException: No such property: e for class: ".  This is a typo, and I am not sure if it will impact the UI function.  
...
catch (ApiException ex) {
        log.debug(e.message.toString())
}
...
You can try to add a DaemonSet that the problem has been resolved.

**Comment by TomerCo** [comment]
@chlung  thanks for your reply..
I tried creating daemon set, in the spinnaker namespace, test namespace (the one that spinnaker manages) and in the default namespace , still i am seeing the same exception.

**Comment by chlung** [comment]
Do you mind to post exception?

**Comment by TomerCo** [comment]
sure:

`
groovy.lang.MissingPropertyException: No such property: e for class: com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiAdapter
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307) ~[groovy-all-2.4.7.jar:2.4.7]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiAdapter$_getDaemonSets_closure2.doCall(KubernetesClientApiAdapter.groovy:176) ~[clouddriver-kubernetes-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiAdapter$_getDaemonSets_closure2.doCall(KubernetesClientApiAdapter.groovy) ~[clouddriver-kubernetes-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) ~[groovy-all-2.4.7.jar:2.4.7]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiAdapter.exceptionWrapper(KubernetesClientApiAdapter.groovy:116) ~[clouddriver-kubernetes-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor1029.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190) ~[groovy-all-2.4.7.jar:2.4.7]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiAdapter.getDaemonSets(KubernetesClientApiAdapter.groovy:165) ~[clouddriver-kubernetes-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiAdapter$getDaemonSets$0.call(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.agent.KubernetesControllersCachingAgent$_loadDaemonSets_closure12.doCall(KubernetesControllersCachingAgent.groovy:218) ~[clouddriver-kubernetes-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.Closure.call(Closure.java:414) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.Closure.call(Closure.java:430) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3170) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3140) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.dgm$66.invoke(Unknown Source) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-all-2.4.7.jar:2.4.7]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.agent.KubernetesControllersCachingAgent.loadDaemonSets(KubernetesControllersCachingAgent.groovy:217) ~[clouddriver-kubernetes-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.agent.KubernetesControllersCachingAgent.loadData(KubernetesControllersCachingAgent.groovy:174) ~[clouddriver-kubernetes-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:79) ~[cats-core-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:72) ~[cats-core-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:231) ~[cats-redis-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:205) ~[cats-redis-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_111-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
`

**Comment by chlung** [comment]
@TomerCo The error will be across each namespace.  let me fix 1.5

**Comment by chlung** [comment]
Please reference https://github.com/spinnaker/clouddriver/pull/2211.  thanks.
