### ISSUE TITLE
Instructions to set up Spinnaker for development on Mac OS are not fully correct

### ISSUE THREAD

**Issue by wheleph** [spinnaker/spinnaker#2168]
I'm trying to run Spinnaker for development on Mac OS following the [instructions](https://github.com/spinnaker/spinnaker/blob/master/README.adoc) but at some point I get errors and the services are not started.

**Steps to reproduce**

- Make sure that Java, Cassandra, Redis are installed and the last two are running
- Bootstrap the repo
```
#export SPINNAKER_HOME=/path/to/your/Spinnaker/workspace
mkdir -p $SPINNAKER_HOME
cd $SPINNAKER_HOME
git clone git@github.com:spinnaker/spinnaker.git
```
- Fetch the source code of modules
```
cd $SPINNAKER_HOME
mkdir build
cd build
../spinnaker/dev/refresh_source.sh --pull_origin --use_ssh --github_user default
```
- Configure Spinnaker
```
cd $SPINNAKER_HOME
mkdir -p $HOME/.spinnaker
touch $HOME/.spinnaker/spinnaker-local.yml
chmod 600 $HOME/.spinnaker/spinnaker-local.yml

# Ideally you only need to add the properties you want to override.
# However if you are not comfortable editing yml, you can copy the
# entire file. The difference is that you may be overriding future
# changes to default values that you otherwise would not care about.
cp spinnaker/config/spinnaker.yml $HOME/.spinnaker/spinnaker-local.yml
```
- Start a service (Igor in this case)
```
cd $SPINNAKER_HOME/build
../spinnaker/dev/run_dev.sh [service]
```
- Observe the error
```
/tmp/spinnaker/build → ../spinnaker/dev/run_dev.sh igor
This script needs to be run from the root of your build directory.
```
- Of `run_dev.sh` is triggered from the parent directory there's another error
```
/tmp/spinnaker → spinnaker/dev/run_dev.sh igor
Starting igor
path = /private/tmp/spinnaker/igor/start_dev.sh
Traceback (most recent call last):
  File "spinnaker/dev/dev_runner.py", line 299, in <module>
    DevRunner.main()
  File "/private/tmp/spinnaker/spinnaker/pylib/spinnaker/spinnaker_runner.py", line 612, in main
    runner.run(options)
  File "/private/tmp/spinnaker/spinnaker/pylib/spinnaker/spinnaker_runner.py", line 584, in run
    self.maybe_start_job(self.get_all_java_subsystem_jobs(), component)
  File "/private/tmp/spinnaker/spinnaker/pylib/spinnaker/spinnaker_runner.py", line 280, in maybe_start_job
    subsystem, environ=self.get_subsystem_environ(subsystem))
  File "/private/tmp/spinnaker/spinnaker/pylib/spinnaker/spinnaker_runner.py", line 219, in start_subsystem_if_local
    return self.start_subsystem(subsystem, environ)
  File "spinnaker/dev/dev_runner.py", line 192, in start_subsystem
    return self.run_daemon(command, [command], environ=environ)
  File "/private/tmp/spinnaker/spinnaker/pylib/spinnaker/spinnaker_runner.py", line 191, in run_daemon
    os.execve(path, args, environ or os.environ)
OSError: [Errno 2] No such file or directory
```

**Workaround**

- Bootstrap Spinnaker from the home directory like so
```
cd $SPINNAKER_HOME
spinnaker/dev/refresh_source.sh --pull_origin --use_ssh --github_user default
```
- Run the service from the parent directory
```
cd $SPINNAKER_HOME
spinnaker/dev/run_dev.sh igor
```

**Possible root cause**

The issue might be related to this change https://github.com/spinnaker/spinnaker/pull/2140. @ewiseblatt , @lwander , @jtk54 can you confirm?

**Comment by sbwsg** [comment]
I'm going to close out this issue since it's stale. We have developer instructions available here: https://www.spinnaker.io/guides/developer/getting-set-up/ and, at least for the time being, we don't really support developing on mac - I don't know anyone who does it. If anyone is actively doing so and would like to submit instructions to https://github.com/spinnaker/spinnaker.github.io then that would be a welcome addition.
