### ISSUE TITLE
Jenkins job selection timeouts when fetching large number of jobs 

### ISSUE THREAD

**Issue by rebalag** [spinnaker/spinnaker#2206]
Spinnaker is running on-prem connecting to Jenkins server also on-prem with thousands of jobs configured. Jenkins stage job selection takes considerable time and then fails to show jobs in the dropdown. 

Logs seem to show the jobs are being fetched and then times out before completion.

Expected to see a filter string before start fetching the jobs from Jenkins server - similar to process followed for docker repositories for querying for containers or AMI query for deployment configuration from AWS. Deck maybe the place to resolve the issue.

Following is the error from logs:

ERROR 3052 --- [readScheduler-1] c.n.s.igor.jenkins.JenkinsBuildMonitor   : Error processing builds for my-jenkins-master
com.netflix.hystrix.exception.HystrixRuntimeException: jenkins-my-jenkins-master-getBuilds failed and no fallback available.
at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:801) ~[hystrix-core-1.4.21.jar:1.4.21]
at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:785) ~[hystrix-core-1.4.21.jar:1.4.21]
at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:99) ~[rxjava-1.0.16.jar:1.0.16]
at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71) ~[rxjava-1.0.16.jar:1.0.16]
at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71) ~[rxjava-1.0.16.jar:1.0.16]
at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71) ~[rxjava-1.0.16.jar:1.0.16]
at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1514) ~[hystrix-core-1.4.21.jar:1.4.21]
at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1404) ~[hystrix-core-1.4.21.jar:1.4.21]
at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:314) ~[hystrix-core-1.4.21.jar:1.4.21]
at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:306) ~[hystrix-core-1.4.21.jar:1.4.21]
at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable.unsafeSubscribe(Observable.java:8171) ~[rxjava-1.0.16.jar:1.0.16]
at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:100) ~[rxjava-1.0.16.jar:1.0.16]
at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71) ~[rxjava-1.0.16.jar:1.0.16]
at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71) ~[rxjava-1.0.16.jar:1.0.16]
at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:1005) ~[hystrix-core-1.4.21.jar:1.4.21]
at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71) ~[rxjava-1.0.16.jar:1.0.16]
at rx.internal.operators.OperatorSubscribeOn$1$1$1.onError(OperatorSubscribeOn.java:71) ~[rxjava-1.0.16.jar:1.0.16]
at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71) ~[rxjava-1.0.16.jar:1.0.16]
at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onError(AbstractCommand.java:1473) ~[hystrix-core-1.4.21.jar:1.4.21]
at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onError(AbstractCommand.java:1369) ~[hystrix-core-1.4.21.jar:1.4.21]
at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:297) ~[hystrix-core-1.4.21.jar:1.4.21]
at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289) ~[hystrix-core-1.4.21.jar:1.4.21]
at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
at rx.Observable.unsafeSubscribe(Observable.java:8171) ~[rxjava-1.0.16.jar:1.0.16]
at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:517) ~[hystrix-core-1.4.21.jar:1.4.21]
at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:495) ~[hystrix-core-1.4.21.jar:1.4.21]
at rx.Observable.unsafeSubscribe(Observable.java:8171) ~[rxjava-1.0.16.jar:1.0.16]
at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62) ~[rxjava-1.0.16.jar:1.0.16]
at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) ~[hystrix-core-1.4.21.jar:1.4.21]
at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) ~[hystrix-core-1.4.21.jar:1.4.21]
at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) ~[hystrix-core-1.4.21.jar:1.4.21]
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.0.16.jar:1.0.16]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_141]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_141]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_141]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_141]
at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
Caused by: retrofit.RetrofitError: timeout
at retrofit.RetrofitError.networkError(RetrofitError.java:27) ~[retrofit-1.9.0.jar:na]
at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395) ~[retrofit-1.9.0.jar:na]
at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
at com.sun.proxy.$Proxy88.getBuilds(Unknown Source) ~[na:na]
at com.netflix.spinnaker.igor.jenkins.client.JenkinsClient$getBuilds$0.call(Unknown Source) ~[na:na]
at com.netflix.spinnaker.igor.jenkins.service.JenkinsService$_getBuilds_closure3.doCall(JenkinsService.groovy:87) ~[igor-web-0.7.0-20170922163003.jar:0.7.0-20170922163003]
at com.netflix.spinnaker.igor.jenkins.service.JenkinsService$_getBuilds_closure3.doCall(JenkinsService.groovy) ~[igor-web-0.7.0-20170922163003.jar:0.7.0-20170922163003]
at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source) ~[na:na]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_141]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_141]
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-all-2.4.7.jar:2.4.7]
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-all-2.4.7.jar:2.4.7]
at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-all-2.4.7.jar:2.4.7]
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024) ~[groovy-all-2.4.7.jar:2.4.7]
at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:923) ~[groovy-all-2.4.7.jar:2.4.7]
at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:906) ~[groovy-all-2.4.7.jar:2.4.7]
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:168) ~[groovy-all-2.4.7.jar:2.4.7]
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeClosure(ScriptBytecodeAdapter.java:574) ~[groovy-all-2.4.7.jar:2.4.7]
at com.netflix.spinnaker.hystrix.SimpleHystrixCommand.run(SimpleHystrixCommand.groovy:53) ~[kork-hystrix-1.98.2.jar:1.98.2]
at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294) ~[hystrix-core-1.4.21.jar:1.4.21]
... 21 common frames omitted
Caused by: java.net.SocketTimeoutException: timeout
at okio.Okio$3.newTimeoutException(Okio.java:207) ~[okio-1.6.0.jar:na]
at okio.AsyncTimeout.exit(AsyncTimeout.java:261) ~[okio-1.6.0.jar:na]
at okio.AsyncTimeout$2.read(AsyncTimeout.java:215) ~[okio-1.6.0.jar:na]
at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306) ~[okio-1.6.0.jar:na]
at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300) ~[okio-1.6.0.jar:na]
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196) ~[okio-1.6.0.jar:na]
at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186) ~[okhttp-2.7.0.jar:na]
at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) ~[okhttp-2.7.0.jar:na]
at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:739) ~[okhttp-2.7.0.jar:na]
at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87) ~[okhttp-2.7.0.jar:na]
at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:724) ~[okhttp-2.7.0.jar:na]
at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:578) ~[okhttp-2.7.0.jar:na]
at com.squareup.okhttp.Call.getResponse(Call.java:287) ~[okhttp-2.7.0.jar:na]
at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243) ~[okhttp-2.7.0.jar:na]
at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205) ~[okhttp-2.7.0.jar:na]
at com.squareup.okhttp.Call.execute(Call.java:80) ~[okhttp-2.7.0.jar:na]
at retrofit.client.OkClient.execute(OkClient.java:53) ~[retrofit-1.9.0.jar:na]
at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326) ~[retrofit-1.9.0.jar:na]
... 39 common frames omitted
Caused by: java.net.SocketException: Socket closed
at java.net.SocketInputStream.read(SocketInputStream.java:204) ~[na:1.8.0_141]
at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_141]
at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_141]
at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_141]
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983) ~[na:1.8.0_141]
at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940) ~[na:1.8.0_141]
at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_141]
at okio.Okio$2.read(Okio.java:139) ~[okio-1.6.0.jar:na]
at okio.AsyncTimeout$2.read(AsyncTimeout.java:211) ~[okio-1.6.0.jar:na]
... 54 common frames omitted

**Comment by rebalag** [comment]
The problem seems to be with permissions to the account connecting to Jenkins. Could not reproduce timeout problem after the authorization was configured correctly.

**Comment by JamieChe** [comment]
Hello, @rebalag 
We met similar error in backend igor log. In general, the connected jenkins are working  except reporting this exception from time to time, during jenkinsPolling process.  
Our account permission should be correct: can read, run jobs.. Could you show us how you config the permission?
Thanks

**Comment by rebalag** [comment]
@JamieChe If the problem is intermittent, then it may not be permission issue. 

Default limit for number of jobs is set to 1000. Are you closer to the limit? 

If so, then you can increase the job fetch limit by setting 
spinnaker.pollingSafegaurd.itemUpperThreshold: 1500
in igor-local.yml and update the igor service
