### ISSUE TITLE
bug(orca): Exception ( Start Pipeline ) Cannot get property 'id' on null object

### ISSUE THREAD

**Issue by ikemonn** [spinnaker/spinnaker#2243]
### bug(orca): Exception ( Start Pipeline ) Cannot get property 'id' on null object

*Cloud Provider*

AWS and GCP

*Environment*

I am running Spinnaker using the Cloud Launcher at GCP.

*Feature Area*

Pipelines

*Description*

When executing deploy pipeline, `Exception ( Start Pipeline ) Cannot get property 'id' on null object` error happened at random and cancel deploy.

This error happened both AWS and GCP.
At AWS 2/10 pipeline failed because of this and at GCP 2/10 pipeline failed too.

![ss_2018-01-12_12_34_12](https://user-images.githubusercontent.com/2867833/34858691-165fb856-f795-11e7-9251-125b89afdf88.png)

After we retry, this error did not happen and success.

*Steps to Reproduce*

I do not know how to reproduce but this happen at random.

*Additional Details*

<details>
<summary> stack trace </summary>

```
exception: {
details: {
error: "Unexpected Task Failure",
errors: [
"Cannot get property 'id' on null object"
],
stackTrace: "java.lang.NullPointerException: Cannot get property 'id' on null object 
at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60) 
at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174) 
at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:47) 
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296) 
at com.netflix.spinnaker.orca.front50.DependentPipelineStarter.trigger(DependentPipelineStarter.groo
vy:122) 
at com.netflix.spinnaker.orca.front50.DependentPipelineStarter$trigger.call(Unknown Source) 
at 
com.netflix.spinnaker.orca.front50.tasks.StartPipelineTask.execute(StartPipelineTask.groovy:82) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$1.invoke(RunTaskHandler.kt:66) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$1.invoke(RunTaskHandler.kt:43) 
at com.netflix.spinnaker.orca.q.handler.AuthenticationAwareKt$sam$Callable$ed5b050b.call(AuthenticationAware.kt) 
at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$1(AuthenticatedRequest.java:75) 
at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:51) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:43) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:65) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:43) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:151) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:43) 
at com.netflix.spinnaker.orca.q.MessageHandler$withTask$1.invoke(MessageHandler.kt:56) 
at com.netflix.spinnaker.orca.q.MessageHandler$withTask$1.invoke(MessageHandler.kt:27) 
at com.netflix.spinnaker.orca.q.MessageHandler$withStage$1.invoke(MessageHandler.kt:66) 
at com.netflix.spinnaker.orca.q.MessageHandler$withStage$1.invoke(MessageHandler.kt:27) 
at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.withExecution(MessageHandler.kt:82) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:43) 
at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.withStage(MessageHandler.kt:62) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:43) 
at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.withTask(MessageHandler.kt:49) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:43) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:144) 
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:55)
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:43)
at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:43) 
at com.netflix.spinnaker.orca.q.QueueProcessor$pollOnce$1$1$1.run(QueueProcessor.kt:64) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
at java.lang.Thread.run(Thread.java:748) "
},
exceptionType: "NullPointerException",
operation: "startPipeline",
shouldRetry: false,
timestamp: 1515722987254
}
```
</details>

**Comment by ezimanyi** [comment]
@ikemonn : This should be fixed by https://github.com/spinnaker/orca/pull/2193.  We were sharing a non-thread-safe library across threads, which led to a race condition that intermittently resulted in the issue you observed.   The fix is in spinnaker 1.7.2 and later.  Please re-open or create a new issue if you observe this while running a version containing the fix.  Thanks!
