### ISSUE TITLE
Read timed out when deploying server groups to K8s clusters

### ISSUE THREAD

**Issue by zivbaz** [spinnaker/spinnaker#2251]
Read timed out when deploying server groups to K8s clusters.

Running Spinnaker 1.5.4 with Halyard on K8s clusters (1.6.5) based on AWS.

I have several pipelines with deploy stages to several different k8s clusters.
In some of the stages, I deploy 8 different server groups concurrently.

Every several runs of the relevant pipelines the deploy stage fail with the error:
`Exception ( Monitor Deploy )
connect timed out`
or
`Exception ( Force Cache Refresh )
java.net.SocketTimeoutException: Read timed out`

I looked at Spinnaker logs (Clouddriver) and see Redis timeout:
`redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
    at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202) ~[jedis-2.9.0.jar:na]
    at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40) ~[jedis-2.9.0.jar:na]
    at redis.clients.jedis.Protocol.process(Protocol.java:151) ~[jedis-2.9.0.jar:na]
    at redis.clients.jedis.Protocol.read(Protocol.java:215) ~[jedis-2.9.0.jar:na]
    at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340) ~[jedis-2.9.0.jar:na]
    at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:276) ~[jedis-2.9.0.jar:na]
    at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:269) ~[jedis-2.9.0.jar:na]
    at redis.clients.jedis.Jedis.mget(Jedis.java:407) ~[jedis-2.9.0.jar:na]
    at com.netflix.spinnaker.cats.redis.cache.RedisCache.lambda$getItems$3(RedisCache.java:254) ~[cats-redis-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
    at com.netflix.spinnaker.cats.redis.JedisClientDelegate.withMultiClient(JedisClientDelegate.java:55) ~[cats-redis-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
    at com.netflix.spinnaker.cats.redis.cache.RedisCache.getItems(RedisCache.java:250) ~[cats-redis-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
    at com.netflix.spinnaker.cats.redis.cache.AbstractRedisCache.getAll(AbstractRedisCache.java:146) ~[cats-redis-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
    at com.netflix.spinnaker.cats.provider.DefaultProviderCache.getAll(DefaultProviderCache.java:93) ~[cats-core-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
    at com.netflix.spinnaker.cats.provider.DefaultProviderCache.getAll(DefaultProviderCache.java:87) ~[cats-core-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
    at com.netflix.spinnaker.cats.provider.ProviderCache$getAll.call(Unknown Source) ~[na:na]
    at com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.agent.KubernetesLoadBalancerCachingAgent.loadData(KubernetesLoadBalancerCachingAgent.groovy:186) ~[clouddriver-kubernetes-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
    at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:79) ~[cats-core-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
    at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:72) ~[cats-core-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
    at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:231) ~[cats-redis-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
    at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:205) ~[cats-redis-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_111-internal]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111-internal]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]`

When I deploy only one server group in the deploy stage I don't have this problem.
This is a blocker for me.

**Comment by zivbaz** [comment]
Can I get some help here guys?
