### ISSUE TITLE
Clouddriver fails to authenticate to private Docker Registry when using JWT Auth

### ISSUE THREAD

**Issue by mikn** [spinnaker/spinnaker#2252]
*Cloud Provider* Kubernetes

*Environment* Running Spinnaker 1.5.4 on top of Kubernetes in AWS.

*Feature Area* Clouddriver + Docker Registry

*Description*
Whilst trying to set up spinnaker with an authenticated private repository I get an error message.
```
2018-01-17 10:05:14.708 ERROR 1 --- [ecutionAction-3] c.n.s.c.d.r.a.v.c.DockerRegistryClient   : Error authenticating with registry [REDACTED], for request '[REDACTED]': Authentication failed: connect timed out
2018-01-17 10:05:14.738 ERROR 1 --- [ecutionAction-3] .d.r.p.a.DockerRegistryImageCachingAgent : Could not load tags for [REDACTED]

com.netflix.spinnaker.clouddriver.docker.registry.api.v2.exception.DockerRegistryAuthenticationException: Authentication failed: connect timed out
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_111-internal]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_111-internal]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_111-internal]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_111-internal]
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:255) [groovy-all-2.4.7.jar:2.4.7]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.auth.DockerBearerTokenService.getToken(DockerBearerTokenService.groovy:206) ~[clouddriver-docker-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.auth.DockerBearerTokenService$getToken$0.call(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient.request(DockerRegistryClient.groovy:425) ~[clouddriver-docker-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$request$0.callCurrent(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182) [groovy-all-2.4.7.jar:2.4.7]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient.getTags(DockerRegistryClient.groovy:335) ~[clouddriver-docker-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient.getTags(DockerRegistryClient.groovy) ~[clouddriver-docker-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$getTags$1.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-all-2.4.7.jar:2.4.7]
	at com.netflix.spinnaker.clouddriver.docker.registry.provider.agent.DockerRegistryImageCachingAgent$_loadTags_closure2.doCall(DockerRegistryImageCachingAgent.groovy:97) ~[clouddriver-docker-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024) ~[groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.Closure.call(Closure.java:414) [groovy-all-2.4.7.jar:2.4.7]
	at groovy.lang.Closure.call(Closure.java:430) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectEntries(DefaultGroovyMethods.java:3632) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectEntries(DefaultGroovyMethods.java:3539) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectEntries(DefaultGroovyMethods.java:3564) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.dgm$73.invoke(Unknown Source) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-all-2.4.7.jar:2.4.7]
	at com.netflix.spinnaker.clouddriver.docker.registry.provider.agent.DockerRegistryImageCachingAgent.loadTags(DockerRegistryImageCachingAgent.groovy:89) [clouddriver-docker-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.docker.registry.provider.agent.DockerRegistryImageCachingAgent.loadData(DockerRegistryImageCachingAgent.groovy:73) [clouddriver-docker-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:79) [cats-core-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:72) [cats-core-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:231) [cats-redis-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:205) [cats-redis-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
Caused by: retrofit.RetrofitError: connect timed out
	at retrofit.RetrofitError.networkError(RetrofitError.java:27) ~[retrofit-1.9.0.jar:na]
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395) ~[retrofit-1.9.0.jar:na]
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.auth.$Proxy134.getToken(Unknown Source) ~[na:1.0.4-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:233) ~[groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-all-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:58) [groovy-all-2.4.7.jar:2.4.7]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.auth.DockerBearerTokenService.getToken(DockerBearerTokenService.groovy:198) ~[clouddriver-docker-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
	... 43 common frames omitted
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_111-internal]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_111-internal]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_111-internal]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_111-internal]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_111-internal]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_111-internal]
	at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:120) ~[okhttp-2.7.5.jar:na]
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141) ~[okhttp-2.7.5.jar:na]
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112) ~[okhttp-2.7.5.jar:na]
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184) ~[okhttp-2.7.5.jar:na]
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126) ~[okhttp-2.7.5.jar:na]
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95) ~[okhttp-2.7.5.jar:na]
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281) ~[okhttp-2.7.5.jar:na]
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224) ~[okhttp-2.7.5.jar:na]
	at com.squareup.okhttp.Call.getResponse(Call.java:286) ~[okhttp-2.7.5.jar:na]
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243) ~[okhttp-2.7.5.jar:na]
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205) ~[okhttp-2.7.5.jar:na]
	at com.squareup.okhttp.Call.execute(Call.java:80) ~[okhttp-2.7.5.jar:na]
	at retrofit.client.OkClient.execute(OkClient.java:53) ~[retrofit-1.9.0.jar:na]
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326) ~[retrofit-1.9.0.jar:na]
	... 54 common frames omitted
```
However, if I look at the logs for the registry, this is the error message I see:
```
time="2018-01-17T10:08:32Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.6 http.request.host=[REDACTED] http.request.id=7bd65a24-a09e-454c-a2b2-b4a39ea159ba http.request.method=GET http.request.remoteaddr=172.21.95.187 http.request.uri="/v2/[REDACTED]/tags/list" http.request.useragent="Spinnaker/1.0.4-SNAPSHOT" instance.id=5731f9ad-ca29-4515-a490-4488cd5bcba6 vars.name="[REDACTED]" version=v2.6.2 
100.96.6.214 - - [17/Jan/2018:10:08:32 +0000] "GET /v2/[REDACTED]/tags/list HTTP/1.1" 401 170 "" "Spinnaker/1.0.4-SNAPSHOT"
```

*Additional Details*
The credentials provided work during the verification process so Halyard successfully authenticates.
I get the same error message on 1.5.4 and master-latest-unvalidated.
Curl works successfully from within the container to the specified repository and domain.
I'll try on earlier versions tomorrow and report back.

**Comment by mikn** [comment]
Verified not working on 1.4.2 either...

**Comment by mikn** [comment]
So, this turns out to be because our Docker Registry is set up with this https://docs.docker.com/registry/spec/auth/jwt/ authentication mechanism. I'm still digging into why it fails to properly authenticate however.

**Comment by mikn** [comment]
Ah! It seems that the timeout error message was the correct response, it times out trying to authenticate against our auth endpoint that is different from the registry endpoint. Closing whilst slightly embarrassed...
