### ISSUE TITLE
Receiving a 404 for the K8 V2 provider doesn't terminate the pipeline

### ISSUE THREAD

**Issue by imosquera** [spinnaker/spinnaker#2254]
I'm trying to deploy a configMap using artifacts and when it reaches manifest deploy stage it gets stuck on ` Wait For Manifest To Stabilize`.  This is potentially happening due to a 404 error happening in orca trying to reach clouddriver for a manifest that doesn't exists.  The pipeline eventually times out but this error should likely error out the pipeline and bubble up the error to the user.  Below is the stack trace I received.

```
2018-01-17 18:00:37.063  INFO 1 --- [eHandlerPool-20] c.n.s.orca.clouddriver.OortService       : [] <--- HTTP 404 http://[REDACTED]:7002/manifests/k8s-v2/default/configMap%20dev-configmap-v000 (19ms)
2018-01-17 18:00:37.063  WARN 1 --- [eHandlerPool-20] c.n.s.o.c.t.m.WaitForManifestStableTask  : [] Unable to read manifest 'configMap dev-configmap-v000' in 'default' for account k8s-v2
retrofit.RetrofitError: 404 
	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy100.getManifest(Unknown Source)
	at com.netflix.spinnaker.orca.clouddriver.DelegatingOortService.getManifest(DelegatingOortService.java:41)
	at com.netflix.spinnaker.orca.clouddriver.tasks.manifest.WaitForManifestStableTask.execute(WaitForManifestStableTask.java:77)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$1.invoke(RunTaskHandler.kt:66)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$1.invoke(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAwareKt$sam$Callable$599eb315.call(AuthenticationAware.kt)
	at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:59)
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:65)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:151)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.MessageHandler$withTask$1.invoke(MessageHandler.kt:59)
	at com.netflix.spinnaker.orca.q.MessageHandler$withTask$1.invoke(MessageHandler.kt:30)
	at com.netflix.spinnaker.orca.q.MessageHandler$withStage$1.invoke(MessageHandler.kt:69)
	at com.netflix.spinnaker.orca.q.MessageHandler$withStage$1.invoke(MessageHandler.kt:30)
	at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.withExecution(MessageHandler.kt:78)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.withStage(MessageHandler.kt:65)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.withTask(MessageHandler.kt:52)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:144)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:55)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:39)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.QueueProcessor$pollOnce$1$1$1.invoke(QueueProcessor.kt:60)
	at com.netflix.spinnaker.orca.q.QueueProcessor$pollOnce$1$1$1.invoke(QueueProcessor.kt:32)
	at com.netflix.spinnaker.orca.q.QueueProcessor$executeWithContext$1.run(QueueProcessor.kt:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lwander** [comment]
This is OK - some manifests might take a little while to appear after they've been submitted, and this is just being tolerant of that. The fact that the manifest isn't even being found sounds like a symptom of something more serious.

**Comment by lwander** [comment]
Going to close for now, feel free to reopen
