### ISSUE TITLE
Spinnaker is not running on my GCE instance. 

### ISSUE THREAD

**Issue by kapilkumar04** [spinnaker/spinnaker#2265]
We are using spinnaker VM instance provided by GCE. I have checked halyard is working fine, but not able to connect to spinnaker. 

deploy Spinnaker with the following command:
**hal deploy apply**
**Output :** 
"+ Get current deployment
  Success
+ Prep deployment
  Success
+ Preperation complete... deploying Spinnaker
+ Get current deployment
  Success
+ Apply deployment
  Success
+ Run `hal deploy connect` to connect to Spinnaker.
! ERROR Error encountered running script. See above output for more
  details."_

**hal deploy connect :** 
**Output:**
+ Get current deployment
  Success
- Connect to Spinnaker deployment.
  Failure
Problems in Global:
! ERROR This type of deployment cannot be run or connected to.

- Failed to generate connection script.

**Comment by kapilkumar04** [comment]
when run the hal deploy connect : 

> 2018-01-22 06:45:37.330  INFO 1591 --- [      Thread-72] c.n.s.h.core.tasks.v1.TaskRepository     : Task [Connect to Spinnaker deployment.] (07a89255-ebab-46b1-9c64-706cbf5bc6e9) - RUNNING failed with HalException:

com.netflix.spinnaker.halyard.core.error.v1.HalException: This type of deployment cannot be run or connected to.
        at com.netflix.spinnaker.halyard.deploy.deployment.v1.BakeDeployer.connectCommand(BakeDeployer.java:88) ~[halyard-deploy-0.41.0-20180121063052.jar:0.41.0-20180121063052]
        at com.netflix.spinnaker.halyard.deploy.deployment.v1.BakeDeployer.connectCommand(BakeDeployer.java:36) ~[halyard-deploy-0.41.0-20180121063052.jar:0.41.0-20180121063052]
        at com.netflix.spinnaker.halyard.deploy.services.v1.DeployService.connectCommand(DeployService.java:144) ~[halyard-deploy-0.41.0-20180121063052.jar:0.41.0-20180121063052]
        at com.netflix.spinnaker.halyard.controllers.v1.DeploymentController.lambda$connect$14(DeploymentController.java:187) ~[halyard-web-0.41.0-20180121063052.jar:0.41.0-20180121063052]
        at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:125) ~[halyard-core-0.41.0-20180121063052.jar:0.41.0-20180121063052]
        at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core-0.41.0-20180121063052.jar:0.41.0-20180121063052]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]

2018-01-22 06:45:37.330  INFO 1591 --- [      Thread-72] c.n.s.halyard.core.tasks.v1.DaemonTask   : [Connect to Spinnaker deployment.] (07a89255-ebab-46b1-9c64-706cbf5bc6e9) - FAILED killing all jobs created by this task
2018-01-22 06:45:37.330  INFO 1591 --- [      Thread-72] c.n.s.h.core.tasks.v1.TaskRepository     : Task [Connect to Spinnaker deployment.] (07a89255-ebab-46b1-9c64-706cbf5bc6e9) - FAILED completed
2018-01-22 06:46:36.617  INFO 1591 --- [      Thread-71] c.n.s.h.core.tasks.v1.TaskRepository     : Interrupter has no work to do, [Get current deployment] (3cc28608-2842-4fe7-9cc7-186d939dbd35) - SUCCEEDED already completed.
2018-01-22 06:46:36.748  INFO 1591 --- [      Thread-73] c.n.s.h.core.tasks.v1.TaskRepository     : Interrupter has no work to do, [Connect to Spinnaker deployment.] (07a89255-ebab-46b1-9c64-706cbf5bc6e9) - FAILED already completed.
2018-01-22 06:46:41.523  INFO 1591 --- [      Thread-65] c.n.s.h.core.tasks.v1.TaskRepository     : Interrupter has no work to do, [Prep deployment] (f5bcffdc-98c2-456c-9a99-308c23b60d96) - SUCCEEDED already completed.
shailendra.vashistha@chaos-monkey-dev1:/var/log/spinnaker/halyard$

**Comment by nicholasgcoles** [comment]
I had the exact same issue.

I realised that the easiest way for me to fix it was to just do a fresh install.

Instead of using the standard GCE solution for spinnaker I instead followed this tutorial:
https://www.spinnaker.io/setup/quickstart/halyard-gke/

**Comment by lwander** [comment]
It seems you're running commands against an instance of spinnaker that was configured by halyard to be "baked" into a VM image. Following @nicholasgcoles advice doing an installation on a machine where spinnaker isn't already installed is best.
