### ISSUE TITLE
Error thrown when trying to create a security group ( kubernetes GKE 1.8.6 )

### ISSUE THREAD

**Issue by camechis** [spinnaker/spinnaker#2271]
Spinnaker version 1.5.4, GKE 1.8.6

`2018-01-25 09:06:22.136 ERROR 8853 --- [eHandlerPool-19] c.n.s.orca.q.handler.RunTaskHandler      : [] Error running WaitForUpsertedSecurityGroupTask for Orchestration[23102b62-245d-4b27-83a7-326b44357a43]
retrofit.RetrofitError: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: retrofit.ExceptionCatchingTypedInput$ExceptionCatchingInputStream@447aa998; line: 1, column: 206] (through reference chain: com.netflix.spinnaker.orca.clouddriver.MortService$SecurityGroup["description"])
	at retrofit.RetrofitError.conversionError(RetrofitError.java:33)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:383)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy116.getSecurityGroup(Unknown Source)
	at com.netflix.spinnaker.orca.clouddriver.DelegatingMortService.getSecurityGroup(DelegatingMortService.java:35)
	at com.netflix.spinnaker.orca.clouddriver.MortService$getSecurityGroup.call(Unknown Source)
	at com.netflix.spinnaker.orca.clouddriver.tasks.providers.kubernetes.KubernetesSecurityGroupUpserter.isSecurityGroupUpserted(KubernetesSecurityGroupUpserter.groovy:49)
	at com.netflix.spinnaker.orca.clouddriver.tasks.securitygroup.SecurityGroupUpserter$isSecurityGroupUpserted$0.call(Unknown Source)
	at com.netflix.spinnaker.orca.clouddriver.tasks.securitygroup.WaitForUpsertedSecurityGroupTask$_execute_closure2.doCall(WaitForUpsertedSecurityGroupTask.groovy:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2040)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2025)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2066)
	at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.netflix.spinnaker.orca.clouddriver.tasks.securitygroup.WaitForUpsertedSecurityGroupTask.execute(WaitForUpsertedSecurityGroupTask.groovy:47)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$1.invoke(RunTaskHandler.kt:66)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$1.invoke(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAwareKt$sam$Callable$ed5b050b.call(AuthenticationAware.kt)
	at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$1(AuthenticatedRequest.java:75)
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:51)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:65)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:151)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.MessageHandler$withTask$1.invoke(MessageHandler.kt:56)
	at com.netflix.spinnaker.orca.q.MessageHandler$withTask$1.invoke(MessageHandler.kt:27)
	at com.netflix.spinnaker.orca.q.MessageHandler$withStage$1.invoke(MessageHandler.kt:66)
	at com.netflix.spinnaker.orca.q.MessageHandler$withStage$1.invoke(MessageHandler.kt:27)
	at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.withExecution(MessageHandler.kt:82)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.withStage(MessageHandler.kt:62)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.withTask(MessageHandler.kt:49)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:144)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:55)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:43)
	at com.netflix.spinnaker.orca.q.QueueProcessor$pollOnce$1$1$1.run(QueueProcessor.kt:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: retrofit.converter.ConversionException: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: retrofit.ExceptionCatchingTypedInput$ExceptionCatchingInputStream@447aa998; line: 1, column: 206] (through reference chain: com.netflix.spinnaker.orca.clouddriver.MortService$SecurityGroup["description"])
	at retrofit.converter.JacksonConverter.fromBody(JacksonConverter.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:367)
	... 54 common frames omitted
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: retrofit.ExceptionCatchingTypedInput$ExceptionCatchingInputStream@447aa998; line: 1, column: 206] (through reference chain: com.netflix.spinnaker.orca.clouddriver.MortService$SecurityGroup["description"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:60)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:357)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2922)
	at retrofit.converter.JacksonConverter.fromBody(JacksonConverter.java:36)
	... 55 common frames omitted`

**Comment by ethanfrogers** [comment]
@camechis this is a known issue. i'm not sure if anyone has been able to track it down though. :/

**Comment by camechis** [comment]
Thanks for the reply!  It seems like I can just create the ingress outside of spinnaker and have spinnaker manage the R/B Deployment at the service level

**Comment by ethanfrogers** [comment]
When I've run into that issue, the Ingress actually gets created so I tend to ignor

**Comment by ethanfrogers** [comment]
duplicate of spinnaker/spinnaker#2149
