### ISSUE TITLE
Exception when deploying an expected artifact

### ISSUE THREAD

**Issue by hodgesmr** [spinnaker/spinnaker#2292]
When triggering a pipeline on an **Expected Artifact** orca receives a `500`, raises an exception, and the pipeline fails.

The UI displays an error:

>**Exception ( Deploy Manifest )**
>Required String parameter 'reference' is not present

Here is an example stack trace and screen shots when attempting to pull an artifact from a public GCS bucket:

```
2018-02-02 17:58:04.548  INFO 9836 --- [    handlers-19] c.n.s.orca.clouddriver.OortService       : [ryan.rigdon@datadoghq.com] ---> HTTP GET http://localhost:7002/artifacts/fetch/?artifactAccount=spinnaker-kubernetes&type=gcs%2Fobject
2018-02-02 17:58:04.553  INFO 9836 --- [    handlers-19] c.n.s.orca.clouddriver.OortService       : [ryan.rigdon@datadoghq.com] <--- HTTP 500 http://localhost:7002/artifacts/fetch/?artifactAccount=spinnaker-kubernetes&type=gcs%2Fobject (4ms)
2018-02-02 17:58:06.553  INFO 9836 --- [    handlers-19] c.n.s.orca.clouddriver.OortService       : [ryan.rigdon@datadoghq.com] ---> HTTP GET http://localhost:7002/artifacts/fetch/?artifactAccount=spinnaker-kubernetes&type=gcs%2Fobject
2018-02-02 17:58:06.560  INFO 9836 --- [    handlers-19] c.n.s.orca.clouddriver.OortService       : [ryan.rigdon@datadoghq.com] <--- HTTP 500 http://localhost:7002/artifacts/fetch/?artifactAccount=spinnaker-kubernetes&type=gcs%2Fobject (6ms)
2018-02-02 17:58:10.561  INFO 9836 --- [    handlers-19] c.n.s.orca.clouddriver.OortService       : [ryan.rigdon@datadoghq.com] ---> HTTP GET http://localhost:7002/artifacts/fetch/?artifactAccount=spinnaker-kubernetes&type=gcs%2Fobject
2018-02-02 17:58:10.565  INFO 9836 --- [    handlers-19] c.n.s.orca.clouddriver.OortService       : [ryan.rigdon@datadoghq.com] <--- HTTP 500 http://localhost:7002/artifacts/fetch/?artifactAccount=spinnaker-kubernetes&type=gcs%2Fobject (3ms)
2018-02-02 17:58:18.565  INFO 9836 --- [    handlers-19] c.n.s.orca.clouddriver.OortService       : [ryan.rigdon@datadoghq.com] ---> HTTP GET http://localhost:7002/artifacts/fetch/?artifactAccount=spinnaker-kubernetes&type=gcs%2Fobject
2018-02-02 17:58:18.570  INFO 9836 --- [    handlers-19] c.n.s.orca.clouddriver.OortService       : [ryan.rigdon@datadoghq.com] <--- HTTP 500 http://localhost:7002/artifacts/fetch/?artifactAccount=spinnaker-kubernetes&type=gcs%2Fobject (4ms)
2018-02-02 17:58:18.571 ERROR 9836 --- [    handlers-19] c.n.s.orca.q.handler.RunTaskHandler      : [] Error running DeployManifestTask for pipeline[64db32cb-8a67-42c8-9ddd-2fc4575eff21]
retrofit.RetrofitError: 500
	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy103.fetchArtifact(Unknown Source)
	at com.netflix.spinnaker.orca.clouddriver.DelegatingOortService.fetchArtifact(DelegatingOortService.java:92)
	at com.netflix.spinnaker.orca.clouddriver.tasks.manifest.DeployManifestTask.lambda$execute$0(DeployManifestTask.java:88)
	at com.netflix.spinnaker.kork.core.RetrySupport.retry(RetrySupport.java:26)
	at com.netflix.spinnaker.orca.clouddriver.tasks.manifest.DeployManifestTask.execute(DeployManifestTask.java:88)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$1.invoke(RunTaskHandler.kt:68)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$1.invoke(RunTaskHandler.kt:45)
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAwareKt$sam$Callable$ed5b050b.call(AuthenticationAware.kt)
	at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$1(AuthenticatedRequest.java:75)
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:45)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:67)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:45)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:153)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:45)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:46)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:30)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:56)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:30)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:65)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:45)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:52)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:45)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:39)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:45)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:146)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:57)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:45)
	at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:45)
	at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47)
	at com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1$1.run(QueueProcessor.kt:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

<img width="746" alt="screen shot 2018-02-02 at 11 05 40 am" src="https://user-images.githubusercontent.com/1208575/35748960-1dcef65a-080d-11e8-812a-972019a7a09b.png">

<img width="438" alt="error1" src="https://user-images.githubusercontent.com/1208575/35748945-089a90d2-080d-11e8-817d-d973ce344635.png">

**Comment by lwander** [comment]
Did you supply "reference"? If you're not sure, under "Default Artifact", change the kind to "Custom" and enter the reference there. Here's some background: https://www.spinnaker.io/reference/artifacts/#format

**Comment by hodgesmr** [comment]
@lwander thanks for the tip! That appeared to work!

Does this indicate, though, that the UI around pulling from GCS is broken, since I had to set up via custom?

**Comment by lwander** [comment]
Nice! I think I should update the "Default Artifact" helper to use reference instead, that would prevent this from happening again. I'll file an issue for that and close this.

**Comment by lwander** [comment]
#2294
