### ISSUE TITLE
GCE : Orca Exception while running pipeline via jenkins trigger

### ISSUE THREAD

**Issue by sweetib** [spinnaker/spinnaker#2321]
*Title*
Orca Exception while running pipeline via jenkins trigger

*Cloud Provider*
GCP

*Environment*
OS: Ubuntu Xenial 16.04
Version of Spinnaker sub-services used:
```
spinnaker                        0.83.0   
spinnaker-clouddriver            1.773.0  
spinnaker-deck                   2.1176.0 
spinnaker-echo                   1.543.0  
spinnaker-fiat                   0.39.0   
spinnaker-front50                1.120.0  
spinnaker-gate                   4.18.0   
spinnaker-igor                   1.87.7   
spinnaker-keel                   0.8.0    
spinnaker-orca                   6.2.8    
spinnaker-rosco                  0.103.0  
spinnaker-rush                   1.25.0-3 
```

*Feature Area*
Triggers, Pipelines, Jenkins,Orca

*Description*
I have upgrade spinnaker today to above mentioned version. After this upgrade I started observing issues in Orca. All the triggered pipeline that are configure to triggered by jenkins jobs are failing to be triggered hence pipeline never get executed. Though Manual execution works fine.

*Steps to Reproduce*
- Install above mention version of spinnaker on GCE
- Integrate it with Jenkins
- Create a dummy jenkins job with some `build_info.yml` artifact
- Create a test pipeline that use above jenkins job as automated trigger under pipeline configuration
- Use the above `build_info.yml` as property file of the trigger

*Additional Details*

Orca error log:
```
2018-02-08 14:17:11.088  INFO 27331 --- [0.0-8083-exec-6] c.n.s.o.c.OperationsController           : [] received pipeline f3f705c8-c92c-44d8-bc03-8b7d4fb15bd2:{
  "application" : "test",
  "config" : null,
  "name" : "test-setup",
  "id" : "f3f705c8-c92c-44d8-bc03-8b7d4fb15bd2",
  "executionEngine" : null,
  "parallel" : false,
  "disabled" : false,
  "limitConcurrent" : true,
  "triggers" : [ {
    "enabled" : true,
    "id" : null,
    "type" : "jenkins",
    "master" : "Jenkins",
    "job" : "image_common",
    "buildNumber" : null,
    "propertyFile" : "build_info.yml",
    "cronExpression" : null,
    "source" : null,
    "project" : null,
    "slug" : null,
    "hash" : null,
    "parameters" : null,
    "account" : null,
    "repository" : null,
    "tag" : null,
    "digest" : null,
    "payloadConstraints" : null,
    "payload" : null,
    "attributeConstraints" : null,
    "branch" : null,
    "runAsUser" : null,
    "secret" : null,
    "subscriptionName" : null,
    "pubsubSystem" : null,
    "expectedArtifactIds" : null,
    "lastSuccessfulExecution" : null
  } ],
  "type" : null,
  "stages" : [ {
    "cloudProvider" : "gce",
    "cloudProviderType" : "gce",
    "continuePipeline" : false,
    "credentials" : null,
    "failPipeline" : true,
    "name" : "Find Image from Tags",
    "onlyEnabled" : true,
    "packageName" : "${ trigger.properties['image_name']}",
    "refId" : "1",
    "regions" : [ ],
    "requisiteStageRefIds" : [ ],
    "selectionStrategy" : "LARGEST",
    "tags" : { },
    "type" : "findImageFromTags"
  } ],
  "notifications" : null,
  "receivedArtifacts" : null,
  "expectedArtifacts" : null,
  "parameterConfig" : null,
  "appConfig" : null,
  "trigger" : {
    "enabled" : true,
    "id" : null,
    "type" : "jenkins",
    "master" : "Jenkins",
    "job" : "image_common",
    "buildNumber" : 102,
    "propertyFile" : "build_info.yml",
    "cronExpression" : null,
    "source" : null,
    "project" : null,
    "slug" : null,
    "hash" : null,
    "parameters" : { },
    "account" : null,
    "repository" : null,
    "tag" : null,
    "digest" : null,
    "payloadConstraints" : null,
    "payload" : null,
    "attributeConstraints" : null,
    "branch" : null,
    "runAsUser" : null,
    "secret" : null,
    "subscriptionName" : null,
    "pubsubSystem" : null,
    "expectedArtifactIds" : null,
    "lastSuccessfulExecution" : null,
    "user" : "[anonymous]",
    "buildInfo" : {
      "building" : false,
      "fullDisplayName" : "image_common #1",
      "name" : "image_common",
      "number" : 1,
      "duration" : 104184,
      "timestamp" : "1518099305354",
      "result" : "SUCCESS",
      "artifacts" : [ {
        "fileName" : "build_info.yml",
        "displayPath" : "build_info.yml",
        "relativePath" : "build_info.yml"
      } ],
      "url" : "https://testjenkins.test.com/job/image_common/1/",
      "scm" : [ {
        "name" : "origin/master",
        "branch" : "master",
        "sha1" : "yyyyyy"
      } ]
    },
    "properties" : {
      "image_name" : "test-image",
      "new_cluster_build" : "1",
      "service_git_commit" : "xxxxxxxx",
      "git_commit" : "yyyyyy"
    }
  }
}
2018-02-08 14:37:21.108 ERROR 2752 --- [0.0-8083-exec-6] c.n.s.k.w.e.GenericExceptionHandlers     : [] Internal Server Error
java.lang.IllegalArgumentException: Unrecognized field "displayPath" (class com.netflix.spinnaker.orca.pipeline.model.JenkinsTrigger$JenkinsArtifact), not marked as ignorable (2 known properties: "relativePath", "fileName"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.netflix.spinnaker.orca.pipeline.model.JenkinsTrigger["buildInfo"]->com.netflix.spinnaker.orca.pipeline.model.JenkinsTrigger$BuildInfo["artifacts"]->java.util.ArrayList[0]->com.netflix.spinnaker.orca.pipeline.model.JenkinsTrigger$JenkinsArtifact["displayPath"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3605)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3524)
	at com.netflix.spinnaker.orca.pipeline.util.ContextParameterProcessor.precomputeValues(ContextParameterProcessor.java:105)
	at com.netflix.spinnaker.orca.pipeline.util.ContextParameterProcessor.process(ContextParameterProcessor.java:68)
	at com.netflix.spinnaker.orca.pipeline.util.ContextParameterProcessor$process.call(Unknown Source)
	at com.netflix.spinnaker.orca.controllers.OperationsController.orchestrate(OperationsController.groovy:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.netflix.spinnaker.orca.web.config.WebConfiguration$1.doFilter(WebConfiguration.groovy:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.netflix.spinnaker.fiat.shared.FiatAuthenticationFilter.doFilter(FiatAuthenticationFilter.java:54)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at javax.servlet.FilterChain$doFilter.call(Unknown Source)
	at com.netflix.spinnaker.filters.AuthenticatedRequestFilter.doFilter(AuthenticatedRequestFilter.groovy:135)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

Echo Error log:
```
2018-02-08 14:37:00.610  WARN 2723 --- [readScheduler-6] c.n.s.e.p.orca.PipelineInitiator         : Triggering Pipeline(test, test-setup, f3f705c8-c92c-44d8-bc03-8b7d4fb15bd2) due to Trigger(jenkins, Jenkins, image_common, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
2018-02-08 14:37:00.613  INFO 2723 --- [readScheduler-6] c.n.s.e.p.monitor.GitEventMonitor        : e = com.netflix.spinnaker.echo.model.Event@2cffebeb
2018-02-08 14:37:00.922 ERROR 2723 --- [  Retrofit-Idle] c.n.s.e.p.orca.PipelineInitiator         : Retrying pipeline trigger, attempt 1/5
2018-02-08 14:37:02.141  INFO 2723 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : ---> HTTP GET http://0.0.0.0:8080/pipelines?restricted=false
2018-02-08 14:37:02.184  INFO 2723 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : <--- HTTP 200 http://0.0.0.0:8080/pipelines?restricted=false (42ms)
2018-02-08 14:37:02.186  INFO 2723 --- [  Retrofit-Idle] c.n.s.e.pipelinetriggers.PipelineCache   : Refreshing pipelines
2018-02-08 14:37:05.974 ERROR 2723 --- [  Retrofit-Idle] c.n.s.e.p.orca.PipelineInitiator         : Retrying pipeline trigger, attempt 2/5
2018-02-08 14:37:11.020 ERROR 2723 --- [  Retrofit-Idle] c.n.s.e.p.orca.PipelineInitiator         : Retrying pipeline trigger, attempt 3/5
2018-02-08 14:37:12.142  INFO 2723 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : ---> HTTP GET http://0.0.0.0:8080/pipelines?restricted=false
2018-02-08 14:37:12.184  INFO 2723 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : <--- HTTP 200 http://0.0.0.0:8080/pipelines?restricted=false (42ms)
2018-02-08 14:37:12.185  INFO 2723 --- [  Retrofit-Idle] c.n.s.e.pipelinetriggers.PipelineCache   : Refreshing pipelines
2018-02-08 14:37:16.069 ERROR 2723 --- [  Retrofit-Idle] c.n.s.e.p.orca.PipelineInitiator         : Retrying pipeline trigger, attempt 4/5
2018-02-08 14:37:21.116 ERROR 2723 --- [  Retrofit-Idle] c.n.s.e.p.orca.PipelineInitiator         : Error triggering pipeline: Pipeline(test, test-setup, f3f705c8-c92c-44d8-bc03-8b7d4fb15bd2)

retrofit.RetrofitError: 500
        at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265) ~[retrofit-1.9.0.jar:na]
        at retrofit.RxSupport$2.run(RxSupport.java:55) ~[retrofit-1.9.0.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
        at retrofit.Platform$Base$2$1.run(Platform.java:94) ~[retrofit-1.9.0.jar:na]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
```

Looking forward for the fix for this issue.

**Comment by sweetib** [comment]
@jtk54 and @lwander can you guys help me with most recent functional version of Orca, which is not having this issue? Apparently I cannot use the previous version that I was using(3.x) which is very very old. It will be great if you could help me with latest stable version. Our deployments are blocked currently due to this issue. Thanks

**Comment by jtk54** [comment]
@sweetib Are you wondering how to acquire the latest Orca? Just to clarify, is this issue fixed in 6.x?

**Comment by sweetib** [comment]
@jtk54 I juggled with few versions of orca few days back as it was blocking me. I used 6.0.0 that seems to be working fine. Looks like above issue is been closed now. I might try the latest version later. Thanks @lwander for the fix.

**Comment by manyagoyal12** [comment]
@jtk54 
I am experiencing the same issue when i have my trigger enabled for docker repository.
my echo logs has the error-
2019-01-09 05:23:01.023  INFO 4968 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : ---> HTTP GET http://localhost:8080/pipelines?restricted=false
2019-01-09 05:23:01.034  INFO 4968 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : <--- HTTP 200 http://localhost:8080/pipelines?restricted=false (10ms)
2019-01-09 05:23:01.223  INFO 4968 --- [  Retrofit-Idle] c.n.s.e.pipelinetriggers.PipelineCache   : Refreshing pipelines
2019-01-09 05:23:03.466 ERROR 4968 --- [  Retrofit-Idle] c.n.s.e.p.orca.PipelineInitiator         : Retrying pipeline trigger, attempt 2/5
2019-01-09 05:23:08.511 ERROR 4968 --- [  Retrofit-Idle] c.n.s.e.p.orca.PipelineInitiator         : Retrying pipeline trigger, attempt 3/5
2019-01-09 05:23:11.023  INFO 4968 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : ---> HTTP GET http://localhost:8080/pipelines?restricted=false
2019-01-09 05:23:11.053  INFO 4968 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : <--- HTTP 200 http://localhost:8080/pipelines?restricted=false (29ms)
2019-01-09 05:23:11.169  INFO 4968 --- [  Retrofit-Idle] c.n.s.e.pipelinetriggers.PipelineCache   : Refreshing pipelines
2019-01-09 05:23:13.581 ERROR 4968 --- [  Retrofit-Idle] c.n.s.e.p.orca.PipelineInitiator         : Retrying pipeline trigger, attempt 4/5
2019-01-09 05:23:18.626 ERROR 4968 --- [  Retrofit-Idle] c.n.s.e.p.orca.PipelineInitiator         : Error triggering pipeline: Pipeline(vxpbookvoyage, Publish to DEV, ad452e0b-7180-41a8-b75f-ab21857d66e2)
retrofit.RetrofitError: 403
        at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265) ~[retrofit-1.9.0.jar:na]
        at retrofit.RxSupport$2.run(RxSupport.java:55) ~[retrofit-1.9.0.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
        at retrofit.Platform$Base$2$1.run(Platform.java:94) ~[retrofit-1.9.0.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
