### ISSUE TITLE
Exception (Deploy Manifest): Required String parameter 'version' is not present

### ISSUE THREAD

**Issue by hodgesmr** [spinnaker/spinnaker#2468]
When deploying a manifest from an artifact, the stage fails with the error:

>**Exception ( Deploy Manifest )**
>Required String parameter 'version' is not present

<img width="734" alt="screen shot 2018-02-26 at 2 14 28 pm" src="https://user-images.githubusercontent.com/1208575/36695741-676741be-1aff-11e8-95c1-a77b4c4fddb4.png">

The **About Spinnaker Artifacts** [documentation](https://www.spinnaker.io/reference/artifacts/#format) says `version` is optional:

```
  "version":    // (Optional) The version of this artifact. By convention, the
                // "version" should be compared against other artifacts with
                // the same "type" and "name".
```

and there's no UI field to specify `version`.

**Comment by lwander** [comment]
Thanks @hodgesmr - can you see if orca has a stack trace from this execution? You're right that field should be `optional`.

**Comment by hodgesmr** [comment]
Here's a recent run:

```
2018-02-26 21:49:46.986  INFO 32518 --- [    handlers-20] c.n.s.orca.clouddriver.OortService       : [matt.hodges@datadoghq.com] <--- HTTP 500 http://localhost:7002/artifacts/fetch/?artifactAccount=spinnaker-kube
rnetes&type=gcs%2Fobject&reference=gs%3A%2F%2F[MY-BUCKET]%2Fmatt_test_9 (3ms)
2018-02-26 21:49:46.987 ERROR 32518 --- [    handlers-20] c.n.s.orca.q.handler.RunTaskHandler      : [] Error running DeployManifestTask for pipeline[51b24061-a8de-40b9-997c-10a1ae736153]
retrofit.RetrofitError: 500
        at retrofit.RetrofitError.httpError(RetrofitError.java:40)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
        at com.sun.proxy.$Proxy106.fetchArtifact(Unknown Source)
        at com.netflix.spinnaker.orca.clouddriver.DelegatingOortService.fetchArtifact(DelegatingOortService.java:92)
        at com.netflix.spinnaker.orca.clouddriver.tasks.manifest.DeployManifestTask.lambda$execute$0(DeployManifestTask.java:94)
        at com.netflix.spinnaker.kork.core.RetrySupport.retry(RetrySupport.java:26)
        at com.netflix.spinnaker.orca.clouddriver.tasks.manifest.DeployManifestTask.execute(DeployManifestTask.java:94)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$1.invoke(RunTaskHandler.kt:68)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$1.invoke(RunTaskHandler.kt:45)
        at com.netflix.spinnaker.orca.q.handler.AuthenticationAwareKt$sam$Callable$7d29dd26.call(AuthenticationAware.kt)
        at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$1(AuthenticatedRequest.java:75)
        at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:45)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:67)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:45)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:153)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:45)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:46)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:30)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:56)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:30)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:65)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:45)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:52)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:45)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:39)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:45)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:146)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:57)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:45)
        at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:45)
        at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47)
        at com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1$1.run(QueueProcessor.kt:54)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-02-26 21:49:46.994  INFO 32518 --- [    scheduler-9] com.netflix.spinnaker.q.QueueProcessor   : [] Received message CompleteTask(executionType=pipeline, executionId=51b24061-a8de-40b9-997c-10a1ae736153, application=echoserver, stageId=31fe8649-a8d1-41d8-aecf-8fc5d241c0d8, taskId=1, status=TERMINAL)
```

**Comment by lwander** [comment]
Thanks!

**Comment by hodgesmr** [comment]
I tried to edit the stage json to include: `"version": "0.1"` but it didn't help. 

I also think my original note about Artifact Decoration may be irrelevant to this problem?

**Comment by lwander** [comment]
I think the resolved artifact is still missing a version field, which explains why this breaks even when the stage json contains the artifact - does that make sense?
