### ISSUE TITLE
n.s.c.k.v.a.KubernetesClientApiConverter : Port number is not Integer  java.lang.NumberFormatException: For input string: "web"

### ISSUE THREAD

**Issue by saravanakkumar** [spinnaker/spinnaker#2559]
** Title : ** cloudriver issue after upgrade to 2.1.0-20180319132609
** Cloud provider: ** GCE
** Description: ** After upgraded cloudriver to 2.1.0-20180319132609, getting the below error and gate (0.10.0-20180221133510) health check failed, but no exceptions are traceback in gate log. 

2018-03-21 09:19:33.648  INFO 1 --- [ecutionAction-5] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.KubernetesV1Provider:cloud-services/KubernetesSecretCachingAgent[1/1] completed in 1.034s
2018-03-21 09:19:33.959  INFO 1 --- [cutionAction-17] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.KubernetesV1Provider:cloud-services/KubernetesInstanceCachingAgent[1/1] completed in 2.347s
2018-03-21 09:19:34.211  INFO 1 --- [ecutionAction-9] .v.p.a.KubernetesControllersCachingAgent : Describing items in cloud-services/KubernetesControllersCachingAgent[1/1]
2018-03-21 09:19:34.696  WARN 1 --- [ecutionAction-9] n.s.c.k.v.a.KubernetesClientApiConverter : Port number is not Integer

java.lang.NumberFormatException: For input string: "web"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_151]
	at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_151]
	at java.lang.Integer.valueOf(Integer.java:766) ~[na:1.8.0_151]
	at org.codehaus.groovy.runtime.StringGroovyMethods.toInteger(StringGroovyMethods.java:3312) ~[groovy-all-2.4.12.jar:2.4.12]
	at org.codehaus.groovy.runtime.dgm$1160.invoke(Unknown Source) ~[groovy-all-2.4.12.jar:2.4.12]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274) [groovy-all-2.4.12.jar:2.4.12]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) [groovy-all-2.4.12.jar:2.4.12]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) [groovy-all-2.4.12.jar:2.4.12]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:80) [groovy-all-2.4.12.jar:2.4.12]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiConverter.fromHttpGetAction(KubernetesClientApiConverter.groovy:298) [clouddriver-kubernetes-1.775.0-SNAPSHOT.jar:1.775.0-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiConverter$fromHttpGetAction$1.callStatic(Unknown Source) [clouddriver-kubernetes-1.775.0-SNAPSHOT.jar:1.775.0-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiConverter.fromV1Probe(KubernetesClientApiConverter.groovy:343) [clouddriver-kubernetes-1.775.0-SNAPSHOT.jar:1.775.0-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiConverter$fromV1Probe.callStatic(Unknown Source) [clouddriver-kubernetes-1.775.0-SNAPSHOT.jar:1.775.0-SNAPSHOT]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56) [groovy-all-2.4.12.jar:2.4.12]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiConverter$fromV1Probe.callStatic(Unknown Source) [clouddriver-kubernetes-1.775.0-SNAPSHOT.jar:1.775.0-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiConverter.fromContainer(KubernetesClientApiConverter.groovy:197) [clouddriver-kubernetes-1.775.0-SNAPSHOT.jar:1.775.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-all-2.4.12.jar:2.4.12]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-all-2.4.12.jar:2.4.12]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384) [groovy-all-2.4.12.jar:2.4.12]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022) [groovy-all-2.4.12.jar:2.4.12]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69) [groovy-all-2.4.12.jar:2.4.12]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166) [groovy-all-2.4.12.jar:2.4.12]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesClientApiConverter$_fromStatefulSet_closure2.doCall(KubernetesClientApiConverter.groovy:82) [clouddriver-kubernetes-1.775.0-SNAPSHOT.jar:1.775.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]

**Comment by saravanakkumar** [comment]
Message in the above comment keep repeats in clouddriver log.
Below is the health check for gate 
$ curl http://10.36.2.65:8084/health
curl: (52) Empty reply from server
$
Halyard is in latest version
SSL and SAML is enabled in our setup.

**Comment by ethanfrogers** [comment]
@saravanakkumar based on the call stack it looks like you have a `StatefulSet` somewhere in your environment using the word `web` as a port number for a Probe (Liveness or Readiness). It seems like this is happening in a caching cycle but I'd expect to see logs in Gate indicating that Clouddriver isn't healthy.

**Comment by saravanakkumar** [comment]
@ethanfrogers 
I don't see any statefulset
$ kubectl  get statefulset --all-namespaces
No resources found.
$ kubectl -n spinnaker get pods
NAME                                    READY     STATUS    RESTARTS   AGE
spin-clouddriver-bootstrap-v000-dv83k   1/1       Running   0          2h
spin-clouddriver-v046-v4zpt             1/1       Running   0          2h
spin-deck-v073-fqhrc                    1/1       Running   0          2h
spin-echo-v074-p6qgv                    1/1       Running   0          2h
spin-fiat-v020-vf7h8                    1/1       Running   0          2h
spin-front50-v074-gsc5l                 1/1       Running   0          2h
spin-gate-v006-k1d68                    0/1       Running   0          2h
spin-igor-v074-s9mw9                    1/1       Running   0          2h
spin-orca-bootstrap-v000-sdltw          1/1       Running   0          2h
spin-orca-v074-fkcjs                    1/1       Running   0          2h
spin-redis-bootstrap-v000-xctmw         1/1       Running   0          2h
spin-redis-v000-k8vph                   1/1       Running   1          19h
spin-rosco-v073-7rhkn                   1/1       Running   0          2h
$

In gate logs, i can see cloud driver response as 200 and that keeps repeated, but gate health is fails, below is the logs.

2018-03-21 10:26:24.459  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: cancelPipelineUsingPUT_1
2018-03-21 10:26:24.564  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: deletePipelineUsingDELETE_1
2018-03-21 10:26:25.079  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: invokePipelineConfigUsingPOST_1
2018-03-21 10:26:25.749  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: allUsingGET_2
2018-03-21 10:26:26.014  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: allByCloudProviderUsingGET_1
2018-03-21 10:26:26.043  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: cancelTaskUsingPUT_1
2018-03-21 10:26:26.136  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getTaskUsingGET_1
2018-03-21 10:26:26.161  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getTaskDetailsUsingGET_1
2018-03-21 10:26:26.185  INFO 1 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: taskUsingPOST_1
2018-03-21 10:26:26.522  INFO 1 --- [           main] s.a.ScheduledAnnotationBeanPostProcessor : No TaskScheduler/ScheduledExecutorService bean found for scheduled processing
2018-03-21 10:26:27.873  INFO 1 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8084 (https)
2018-03-21 10:26:27.948  INFO 1 --- [           main] com.netflix.spinnaker.gate.Main          : Started Main in 73.231 seconds (JVM running for 78.709)
2018-03-21 10:27:10.623  INFO 1 --- [-applications-1] c.n.s.g.s.internal.Front50Service        : ---> HTTP GET http://spin-front50.spinnaker:8080/v2/applications
2018-03-21 10:27:10.625  INFO 1 --- [-applications-2] c.n.s.g.s.internal.ClouddriverService    : ---> HTTP GET http://spin-clouddriver.spinnaker:7002/applications?expand=true
2018-03-21 10:27:11.584  INFO 1 --- [-applications-1] c.n.s.g.s.internal.Front50Service        : <--- HTTP 200 http://spin-front50.spinnaker:8080/v2/applications (958ms)
2018-03-21 10:27:11.914  INFO 1 --- [-applications-2] c.n.s.g.s.internal.ClouddriverService    : <--- HTTP 200 http://spin-clouddriver.spinnaker:7002/applications?expand=true (1286ms)
2018-03-21 10:28:12.233  INFO 1 --- [-applications-3] c.n.s.g.s.internal.Front50Service        : ---> HTTP GET http://spin-front50.spinnaker:8080/v2/applications
2018-03-21 10:28:12.243  INFO 1 --- [-applications-4] c.n.s.g.s.internal.ClouddriverService    : ---> HTTP GET http://spin-clouddriver.spinnaker:7002/applications?expand=true
2018-03-21 10:28:12.438  INFO 1 --- [-applications-3] c.n.s.g.s.internal.Front50Service        : <--- HTTP 200 http://spin-front50.spinnaker:8080/v2/applications (199ms)
2018-03-21 10:28:12.466  INFO 1 --- [-applications-4] c.n.s.g.s.internal.ClouddriverService    : <--- HTTP 200 http://spin-clouddriver.spinnaker:7002/applications?expand=true (217ms)
2018-03-21 10:29:12.535  INFO 1 --- [-applications-5] c.n.s.g.s.internal.Front50Service        : ---> HTTP GET http://spin-front50.spinnaker:8080/v2/applications
2018-03-21 10:29:12.542  INFO 1 --- [-applications-6] c.n.s.g.s.internal.ClouddriverService    : ---> HTTP GET http://spin-clouddriver.spinnaker:7002/applications?ex

**Comment by saravanakkumar** [comment]
I have modified the spin-gate-vxxx.yml and removed the /health from readiness probe, then did "sudo hal deploy apply" after that system got recovered 
**from:** 
readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8084
            scheme: HTTP
**to:**
readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8084
          timeoutSeconds: 1

Is the probe settings got changed in the latest version (gate:0.9.0-20171108151529)?
Original error reported "Port number is not Integer java.lang.NumberFormatException: For input string: "web"" is still bugging in the clouddriver log

**Comment by wjoel** [comment]
You probably have a manifest (my guess would be a manifest for a Kubernetes Service) with something like `- port: web` instead of something like `- port: 80`. clouddriver should be better at handling those, either by accepting them, or ignoring them with a warning.

Not sure if that's related to the gate health check.

**Comment by ethanfrogers** [comment]
@saravanakkumar were you able to figure anything out?

**Comment by saravanakkumar** [comment]
I have checked all the manifest, no where found something "web".

$ kubectl  -n spinnaker describe pod |grep -i port
    Port:       7002/TCP
    Port:           7002/TCP
    Port:         7002/TCP
    Port:         7002/TCP
    Port:           7002/TCP
    Port:         7002/TCP
    Port:           9000/TCP
      DECK_PORT:     9000
    Port:           8089/TCP
    Port:           8089/TCP
    Port:           7003/TCP
    Port:           8080/TCP
    Port:           8080/TCP
    Port:           8084/TCP
    Port:           8084/TCP
    Port:           8084/TCP
    Port:           8088/TCP
    Port:           8083/TCP
    Port:           8083/TCP
    Port:           8083/TCP
    Port:           8083/TCP
    Port:           8083/TCP
    Port:           6379/TCP
    Port:           6379/TCP
    Port:           8087/TCP
    Port:           8087/TCP
    Port:           8087/TCP
    Port:           8087/TCP
$

**Comment by ethanfrogers** [comment]
It possible that the offending manifest is somewhere other than the `spinnaker` namespace.

**Comment by ethanfrogers** [comment]
@wjoel i agree, spinnaker should handle that more gracefully. according to the documentation, a probe port for `httpGet` can be either a string or an int. If it's a string, the reference is to a named container port.

in this case, i imagine there is an object taking advantage of this that Spinnaker is trying to index (looks like a `StatefulSet` from the stack trace).

**Comment by saravanakkumar** [comment]
checked string "web" in all namespaces
$ kubectl  describe pod --all-namespaces|grep -i web|wc -l
0
$

**Comment by wjoel** [comment]
Could you try `kubectl get all --all-namespaces -o yaml | grep web`?

**Comment by saravanakkumar** [comment]
$ kubectl get all --all-namespaces -o yaml | grep web|wc -l
0
$

**Comment by wjoel** [comment]
Thanks! One more, if you don't mind. Ingresses aren't included in `get all` for some reason. I think that's what I had last time I saw this: `kubectl get ingress --all-namespaces -o yaml | grep web` (that is, if you're still seeing this error).

**Comment by saravanakkumar** [comment]
$ kubectl get ingress --all-namespaces -o yaml | grep web|wc -l
0
$
Thanks @wjoel , please let me know if you want to try some more options

**Comment by ethanfrogers** [comment]
@saravanakkumar do you have this spinnaker instance configured against multiple kubernetes clusters?

**Comment by ethanfrogers** [comment]
also, now that i review the stack trace (and the code) more closely this error is just a warning. you can see it here: https://github.com/spinnaker/clouddriver/blob/7e5396f20b8d65d72929fad911649fd573281a51/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesClientApiConverter.groovy#L331-L349

since this is expected, albeit confusing, behavior i'm going to close for now and open a new issue for that specifically.

**Comment by optimuspaul** [comment]
I see this as well, I also see the same exception on the word "transport". I can't find anything with those values for anything. Would be nice to have some details in the logs as to where it is finding those values.
