### ISSUE TITLE
(clouddriver) Spinnaker 1.7.x slow on updating on demand cache requests

### ISSUE THREAD

**Issue by emptywee** [spinnaker/spinnaker#2747]
### Issue Summary:

After upgrading to 1.7.0 and 1.7.2 clouddriver is extremely slow on updating on demand entries, making deployments slower up to 3-4 times compared to release 1.6.1

### Cloud Provider(s):
Kubernetes v1

### Environment:
Self-hosted Kubernetes cluster running on v1.9.6

### Feature Area: 
clouddriver

### Description:
We are having hundreds of applications and keeping up to 10 versions of each replicas in history and mostly using red/black strategies. After upgrade to Spinnaker 1.7.x, deployments became very slow and force cache refresh started to take about 4-6 minutes, before it would always be under 2 min.

### Steps to Reproduce:
Upgrade from 1.6.1 to 1.7.x.

### Additional Details:
Despite having 8 clouddriver instances running, seeing only 1 or 2 taking care of on demand requests from orca. Besides, noticed this kind of exceptions being thrown from time to time:
```
spin-clouddriver-7795f6d985-l665z clouddriver 2018-05-04 20:26:53.059  WARN 1 --- [0.0-7002-exec-1] c.n.s.c.cache.CatsOnDemandCacheUpdater   : com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.KubernetesV1Provider/rnp-cluster/KubernetesControllersCachingAgent[1/1]-OnDemand failed to handle on demand update for ServerGroup
spin-clouddriver-7795f6d985-l665z clouddriver 
spin-clouddriver-7795f6d985-l665z clouddriver java.lang.NullPointerException: Cannot invoke method countOnDemand() on null object
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91) ~[groovy-all-2.4.13.jar:2.4.13]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48) ~[groovy-all-2.4.13.jar:2.4.13]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-all-2.4.13.jar:2.4.13]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35) ~[groovy-all-2.4.13.jar:2.4.13]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-all-2.4.13.jar:2.4.13]
spin-clouddriver-7795f6d985-l665z clouddriver 	at com.netflix.spinnaker.clouddriver.cache.OnDemandMetricsSupport$countOnDemand.call(Unknown Source) ~[na:na]
spin-clouddriver-7795f6d985-l665z clouddriver 	at com.netflix.spinnaker.clouddriver.cache.CatsOnDemandCacheUpdater.handle(CatsOnDemandCacheUpdater.groovy:75) ~[clouddriver-core-2.22.0-SNAPSHOT.jar:2.22.0-SNAPSHOT]
spin-clouddriver-7795f6d985-l665z clouddriver 	at com.netflix.spinnaker.clouddriver.cache.CatsOnDemandCacheUpdater$handle.callCurrent(Unknown Source) ~[na:na]
spin-clouddriver-7795f6d985-l665z clouddriver 	at com.netflix.spinnaker.clouddriver.cache.CatsOnDemandCacheUpdater.handle(CatsOnDemandCacheUpdater.groovy:61) ~[clouddriver-core-2.22.0-SNAPSHOT.jar:2.22.0-SNAPSHOT]
spin-clouddriver-7795f6d985-l665z clouddriver 	at com.netflix.spinnaker.clouddriver.cache.OnDemandCacheUpdater$handle$1.call(Unknown Source) ~[na:na]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:101) ~[groovy-all-2.4.13.jar:2.4.13]
spin-clouddriver-7795f6d985-l665z clouddriver 	at com.netflix.spinnaker.clouddriver.controllers.CacheController.handleOnDemand(CacheController.groovy:39) [clouddriver-web-2.22.0-SNAPSHOT.jar:2.22.0-SNAPSHOT]
spin-clouddriver-7795f6d985-l665z clouddriver 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
spin-clouddriver-7795f6d985-l665z clouddriver 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
spin-clouddriver-7795f6d985-l665z clouddriver 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
spin-clouddriver-7795f6d985-l665z clouddriver 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [spring-webmvc-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [spring-webmvc-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [spring-webmvc-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.ShallowEtagHeaderFilter.doFilterInternal(ShallowEtagHeaderFilter.java:110) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110) [spring-boot-actuator-1.5.7.RELEASE.jar:1.5.7.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at com.netflix.spinnaker.fiat.shared.FiatAuthenticationFilter.doFilter(FiatAuthenticationFilter.java:54) [fiat-api-0.29.0-rc.1-springBoot154.jar:0.29.0-rc.1-springBoot154]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106) [spring-boot-actuator-1.5.7.RELEASE.jar:1.5.7.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at javax.servlet.FilterChain$doFilter.call(Unknown Source) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at com.netflix.spinnaker.filters.AuthenticatedRequestFilter.doFilter(AuthenticatedRequestFilter.groovy:135) [kork-web-1.126.0.jar:1.126.0]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
spin-clouddriver-7795f6d985-l665z clouddriver 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
spin-clouddriver-7795f6d985-l665z clouddriver 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.20.jar:8.5.20]
spin-clouddriver-7795f6d985-l665z clouddriver 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```

**Comment by emptywee** [comment]
Also, my observation of clouddriver and on demand requests: despite there are 6 to 8 instances, those log entries about  pending on demand requests are generated mostly by 1 instance (sometimes, very rarely another instance would print it too). Does it mean that those requests are handled by 1 instance all the time? Would it make more sense to share that load across multiple clouddriver instances?

**Comment by emptywee** [comment]
I believe we need to profile those on demand requests performance and make it faster. Sometimes I see pods are up in the UI, but orca is still waiting for those requests to be processed. Something is not moving fast. And as I have rolled back clouddriver to the one in the 1.6.1 release, I am still seeing sometimes it takes ridiculous amount of time for the Force Cache Refresh task to complete. May take 4, 5 or 6 minutes, while it's clear already everywhere that everything is up or has been disabled/scaled down.

Please, take a look at this. This is a major blocker for large k8s clusters.

**Comment by lwander** [comment]
Seems the bad NPE is causing the cache refresh to get thrown out, until the stage either times out or no NPE is hit.

**Comment by lwander** [comment]
Will be released in 1.7.4 next week

**Comment by emptywee** [comment]
Thanks! Much appreciated!

**Comment by emptywee** [comment]
Just wanted to share with anyone suffering from the same slowness of the force cache update task. What helped me was installing one of the latest nightly build of Clouddriver (tagged as v2.41.3) and define cacheThreads for each account in the clouddriver-local.yml. Values like 10 or 20 worked just fine for me and the time it takes now to refresh cache typically near 5-10s and under some rare circumstances it takes longer but still typically under a minute. 

I accidentally ran into this commit and carefully read what it said: https://github.com/spinnaker/clouddriver/commit/160aca409e202ed1f3ecbc5478ca4e821849df7a

**Comment by emptywee** [comment]
Hoping that this PR is going to be included into the next release as soon as possible: https://github.com/spinnaker/clouddriver/pull/2535

**Comment by lwander** [comment]
That PR will be released in 1.8 -- it's kind of invasive & not exactly a "fix" so it's gated on being in the next feature release.

**Comment by emptywee** [comment]
I took the risk to install it in our env and be a beta tester for some time :)

**Comment by antoooks** [comment]
I'm experiencing the same issue on Spinnaker 1.9.0, the time spent on force cache refresh increased significantly from 00:40 seconds on 1.6.x to 08:26 on 1.9.0.

**Comment by faizalkassamalisc** [comment]
see this on v1.9.3.  possibly fixed in https://github.com/spinnaker/orca/pull/2422 ?
