### ISSUE TITLE
Automated trigger from Google Container Registry to Spinnaker stops working a day after Spinnaker install

### ISSUE THREAD

**Issue by jraj002** [spinnaker/spinnaker#2762]
### Issue Summary:
I deployed Spinnaker v 1.7.2 on a GKE cluster using Halyard. I built a pipeline that would pull from GCR as soon as a new image was pushed out and deploy to Kubernetes. The trigger worked fine for less than a day. And then the automated trigger stopped. I have not made any changes to the cluster.

### Cloud Provider(s):
GKE 1.8.8

### Feature Area: 
Automated triggers from container registry

### Additional Details:
I see this in the cloud driver log:
WARN 1 --- [utionAction-530] c.n.s.c.d.r.a.v.c.DockerRegistryClient   : Error encountered during catalog of null401 Unauthorized

---

**Comment by briananderson1222** [comment]
I just experienced this today on a instance running LocalDebian and using PubSub for the GCR trigger. Everything had been working for a day or two, this morning though the triggers are not firing and I am seeing this in my clouddriver logs:

```
2018-05-17 14:08:47.735 ERROR 17145 --- [tionAction-6594] .d.r.p.a.DockerRegistryImageCachingAgent : Could not load tags for MY_PROJECT/MY_SERVICE in https://gcr.io

retrofit.RetrofitError: 401 Unauthorized
	at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[retrofit-1.9.0.jar:na]
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[retrofit-1.9.0.jar:na]
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
	at com.sun.proxy.$Proxy119.getTags(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$DockerRegistryService$getTags$0.call(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$_getTags_closure12.doCall(DockerRegistryClient.groovy:340) ~[clouddriver-docker-3.1.0-20180507112917.jar:3.1.0-20180507112917]
	at sun.reflect.GeneratedMethodAccessor733.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-all-2.4.13.jar:2.4.13]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-all-2.4.13.jar:2.4.13]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022) [groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42) ~[groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-all-2.4.13.jar:2.4.13]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient.request(DockerRegistryClient.groovy:400) ~[clouddriver-docker-3.1.0-20180507112917.jar:3.1.0-20180507112917]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$request$0.callCurrent(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient.getTags(DockerRegistryClient.groovy:335) ~[clouddriver-docker-3.1.0-20180507112917.jar:3.1.0-20180507112917]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient.getTags(DockerRegistryClient.groovy) ~[clouddriver-docker-3.1.0-20180507112917.jar:3.1.0-20180507112917]
	at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$getTags$1.call(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.clouddriver.docker.registry.provider.agent.DockerRegistryImageCachingAgent$_loadTags_closure2.doCall(DockerRegistryImageCachingAgent.groovy:97) ~[clouddriver-docker-3.1.0-20180507112917.jar:3.1.0-20180507112917]
	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-all-2.4.13.jar:2.4.13]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-all-2.4.13.jar:2.4.13]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022) [groovy-all-2.4.13.jar:2.4.13]
	at groovy.lang.Closure.call(Closure.java:414) [groovy-all-2.4.13.jar:2.4.13]
	at groovy.lang.Closure.call(Closure.java:430) [groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectEntries(DefaultGroovyMethods.java:3664) [groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectEntries(DefaultGroovyMethods.java:3571) [groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectEntries(DefaultGroovyMethods.java:3596) [groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.dgm$74.invoke(Unknown Source) [groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274) [groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) [groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-all-2.4.13.jar:2.4.13]
	at com.netflix.spinnaker.clouddriver.docker.registry.provider.agent.DockerRegistryImageCachingAgent.loadTags(DockerRegistryImageCachingAgent.groovy:89) [clouddriver-docker-3.1.0-20180507112917.jar:3.1.0-20180507112917]
	at com.netflix.spinnaker.clouddriver.docker.registry.provider.agent.DockerRegistryImageCachingAgent.loadData(DockerRegistryImageCachingAgent.groovy:73) [clouddriver-docker-3.1.0-20180507112917.jar:3.1.0-20180507112917]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:80) [cats-core-3.1.0-20180507112917.jar:3.1.0-20180507112917]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:73) [cats-core-3.1.0-20180507112917.jar:3.1.0-20180507112917]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:272) [cats-redis-3.1.0-20180507112917.jar:3.1.0-20180507112917]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:246) [cats-redis-3.1.0-20180507112917.jar:3.1.0-20180507112917]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
```

**Comment by ezimanyi** [comment]
@jraj002 @briananderson1222:
Do you mind sharing some more details about your environment and the pipeline(s) that are experiencing this issue?

I'm taking a closer look at the stack trace above to see what's causing it (looks like it may be an error with refreshing tokens, but I'm not completely sure yet), but I also want to make sure I understand the broader workflow.

Some questions:
-Which version of the Kubernetes provider are you using (V1/V2)?
-Which particular pipeline trigger are you using?  Is it a docker trigger, or a PubSub trigger?  I ask because the above code is from polling the docker registry for updated tags...an error there should not affect whether the PubSub trigger runs.  If you have a PubSub trigger, do you mind checking the logs in Echo to see if there are any errors.

Thanks!

**Comment by briananderson1222** [comment]
I'll try to provide my details. Maybe I should've opened a different issue given that it doesn't look like the error he got was exactly the same.

- We are using the v2 K8s provider
- We are using a PubSub Trigger on the `gcr` topic/message format
- We do have the GCR registry configured (but moved away from this as we were told the recommended approach would be PubSub going forward) -- thought this might be a useful tidbit but ignore it if it's not.
- I can try and backtrack through the logs and see if I see anything in particular from echo.

I agree the log output above didn't seem related to PubSub exactly, but the interesting part was that the pipelines weren't even triggering at all (maybe the subscription to the topic was somehow lost?) I was able to `pull` messages from that subscription which I didn't think was possible because up until this point spinnaker always sent the 'ack' before I could actually see messages stacked up. I'll update this message with the logs when I find them.

**Comment by briananderson1222** [comment]
`cat /var/log/spinnaker/echo/echo.log | grep "05-17 14:08"  -B 50 -A 50`

abbreviated version below... essentially this message is repeated over and over.. don't see anything out of the ordinary

```
2018-05-17 14:07:52.104  INFO 17158 --- [pool-5-thread-1] .s.e.s.a.p.i.PipelineConfigsPollingAgent : Running the pipeline configs polling agent...
2018-05-17 14:07:58.816  INFO 17158 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : ---> HTTP GET http://localhost:8080/pipelines?restricted=false
2018-05-17 14:07:58.840  INFO 17158 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : <--- HTTP 200 http://localhost:8080/pipelines?restricted=false (24ms)
2018-05-17 14:07:58.843  INFO 17158 --- [  Retrofit-Idle] c.n.s.e.pipelinetriggers.PipelineCache   : Refreshing pipelines
2018-05-17 14:08:08.815  INFO 17158 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : ---> HTTP GET http://localhost:8080/pipelines?restricted=false
2018-05-17 14:08:08.859  INFO 17158 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : <--- HTTP 200 http://localhost:8080/pipelines?restricted=false (43ms)
2018-05-17 14:08:08.861  INFO 17158 --- [  Retrofit-Idle] c.n.s.e.pipelinetriggers.PipelineCache   : Refreshing pipelines
2018-05-17 14:08:18.815  INFO 17158 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : ---> HTTP GET http://localhost:8080/pipelines?restricted=false
2018-05-17 14:08:18.840  INFO 17158 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : <--- HTTP 200 http://localhost:8080/pipelines?restricted=false (24ms)
2018-05-17 14:08:18.843  INFO 17158 --- [  Retrofit-Idle] c.n.s.e.pipelinetriggers.PipelineCache   : Refreshing pipelines
```

**Comment by ezimanyi** [comment]
Summary of current findings:
* It looks like there are some cases where Echo will drop the connection to a particular PubSub subscriber after receiving an error back from the API and will not retry connecting until Echo is restarted.  I believe that's what's happening there.  The `echo` log entry to look for is `StreamingSubscriberConnection  : terminated streaming with exception` after which Echo stops listening to that particular subscriber.
* The two avenues to look into are:
   * What is causing these errors to be returned (ones that I've seen in the past are `NOT_FOUND` and `PERMISSION_DENIED` in cases where the subscription does exist and the user has permission), so the error itself can be stopped.
   * If we can make Echo more resilient to these errors, by either re-trying the connection or at least surfacing in the UI that a particular connection has been dropped
* The issue with connecting to the docker registry appears to be a separate issue, but still worth looking into

**Comment by wjoel** [comment]
Possibly related issue: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3083

I can confirm that we've seen spurious `PERMISSION_DENIED` errors and echo stops receiving pubsub messages until restarted (and logs `c.g.c.p.v.StreamingSubscriberConnection : terminated streaming with exception`, as you say).

FWIW, this may not be the only issue, because we've seen messages from GCR either not being sent or not being received, but that one is difficult to troubleshoot.

**Comment by lwander** [comment]
@wjoel 

> because we've seen messages from GCR either not being sent or not being received, but that one is difficult to troubleshoot.

have you been able to rule out the possibility that the permissions for the service account submitting builds were maybe changed while operating? If so I'll pass that back to the GCR team

**Comment by wjoel** [comment]
@lwander yes, but the last time was a month ago, and we've had instances when notifications weren't delivered since then (last week). The `PERMISSION_DENIED` issue seems to be a general pubsub thing (https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3083 doesn't mention GCR).

I'm going to try making some changes to echo, updating its pubsub dependency to the latest release, and see how it goes before pointing fingers at GCR again. ;)

**Comment by wjoel** [comment]
@lwander we'll be running with the changes in https://github.com/spinnaker/echo/pull/263 for now, I'll update this thread with the results by the end of the week, or sooner if we see notifications being missed.

**Comment by wjoel** [comment]
I've set up some monitoring to allow us to compare the pubsub events received by echo with what images are uploaded to GCR, and it looks good so far. We've also added `Pub/Sub Publisher` permissions to the account used for uploading the images.

I'd like to give it a few more days and compare again on Tuesday (2018-05-29) when we have a full work day of records for Monday.

**Comment by lwander** [comment]
Awesome, thanks!

**Comment by lwander** [comment]
Nice work! Will close for now...

**Comment by briananderson1222** [comment]
Thanks for the quick turn around guys! Just for my own curiosity is there a place I can read more about the Spinnaker release cycle? How can I know what version of spinnaker this fix got into.

**Comment by lwander** [comment]
Sure thing, here it is: https://www.spinnaker.io/community/releases/release-cadence/
