### ISSUE TITLE
[FIAT] - LDAP Authorization Error (RetrofitError)

### ISSUE THREAD

**Issue by maiconbaumx** [spinnaker/spinnaker#2773]
### Issue Summary:

Hi guys! 
I'm trying to configurate LDAP as a role provider of my Spinnaker deployment, although the docs isn't clear, I read about and I've tried to change my configuration many times before create this issue, but at this point I don't know what is wrong.

### Cloud Provider(s):
AWS

### Environment:

I'm running Spinnaker with Debian Packages, in a EC2 with Ubuntu 16.04 for testing.

### Feature Area:
FIAT

### Description:

The authentication is working like a charm with LDAP, but when I enable FIAT with same configuration that I use for authentication (plus groups configuration) and try to authenticate with same user that I has authenticated before, I get this error in browser:

`{"error":"Internal Server Error","exception":"retrofit.RetrofitError","message":"500 ","status":500,"timestamp":1526072173108}`

At the FIAT log files, I get this error:

> 2018-05-11 17:56:13.039 ERROR 27401 --- [0.1-7003-exec-3] c.n.s.k.w.e.GenericExceptionHandlers     : [] Internal Server Error
> java.lang.NullPointerException: null
> 	at java.util.Hashtable.put(Hashtable.java:460)
> 	at org.springframework.ldap.core.support.SimpleDirContextAuthenticationStrategy.setupEnvironment(SimpleDirContextAuthenticationStrategy.java:42)
> 	at org.springframework.security.ldap.DefaultSpringSecurityContextSource$1.setupEnvironment(DefaultSpringSecurityContextSource.java:94)
> 	at org.springframework.ldap.core.support.AbstractContextSource.setupAuthenticatedEnvironment(AbstractContextSource.java:194)
> 	at org.springframework.ldap.core.support.AbstractContextSource.getAuthenticatedEnv(AbstractContextSource.java:582)
> 	at org.springframework.ldap.core.support.AbstractContextSource.doGetContext(AbstractContextSource.java:134)
> 	at org.springframework.ldap.core.support.AbstractContextSource.getReadOnlyContext(AbstractContextSource.java:158)
> 	at org.springframework.ldap.core.LdapTemplate.executeReadOnly(LdapTemplate.java:802)
> 	at org.springframework.security.ldap.SpringSecurityLdapTemplate.searchForSingleEntry(SpringSecurityLdapTemplate.java:316)
> 	at com.netflix.spinnaker.fiat.roles.ldap.LdapUserRolesProvider.getUserFullDn(LdapUserRolesProvider.java:116)
> 	at com.netflix.spinnaker.fiat.roles.ldap.LdapUserRolesProvider.loadRoles(LdapUserRolesProvider.java:66)
> 	at com.netflix.spinnaker.fiat.permissions.DefaultPermissionsResolver.resolveAndMerge(DefaultPermissionsResolver.java:87)
> 	at com.netflix.spinnaker.fiat.controllers.RolesController.putUserPermission(RolesController.java:85)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
> 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
> 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
> 	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:883)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:664)
> 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at javax.servlet.FilterChain$doFilter$0.call(Unknown Source)
> 	at com.netflix.spinnaker.filters.AuthenticatedRequestFilter.doFilter(AuthenticatedRequestFilter.groovy:135)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:748)
> 

If I disable FIAT, everything works fine (less, obviously, the authorization feature).

### Steps to Reproduce:

My Spinnaker version is: 1.7.3 

My authentication file looks like:

> 
>      authn:
>       oauth2:
>         enabled: false
>         client: {}
>         resource: {}
>         userInfoMapping: {}
>       saml:
>         enabled: false
>       ldap:
>         enabled: true
>         url: ldap://myldap.mycompany.mydomain:389/xx=xxxxx,dc=xxx,dc=xxx
>         userSearchBase: xx=xxxxx
>         userSearchFilter: (&(objectclass=inetorgperson)(groupMembership=xx=zzzzzzzzzzz,xx=zzzzzzzzzz,xx=zzzzzzzzzz,xx=zzzzzzzzzz,dc=xx,dc=xx)(uid={0}))
> 

And my authorization file looks like:

> auth:
>   groupMembership:
>     service: ldap
>     ldap:
>       url: ldap://myldap.mycompany.mydomain:389/zz=xxxxxx,dc=xxxxxxx,dc=xxxxxx
>       userSearchBase: xx=xxxxxx
>       userSearchFilter: (&(objectclass=inetorgperson)(groupMembership=xx=zzzzzzzzzzz,xx=zzzzzzzzzz,xx=zzzzzzzzzz,xx=zzzzzzzzzz,dc=xx,dc=xx)(uid={0}))
>       groupSearchBase: zz=xxxxxx
>       groupSearchFilter: (objectclass=inetorgperson)
>       groupRoleAttributes: cn

### Additional Details:

This configuration is basically copied from my Jenkins Server. 

---

**Comment by maiconbaumx** [comment]
Guys, please close this issue. This is not an issue itself, just a lack of documentation plus wrong assumption. I will explain

** Lack of documentation: ** The documentation of LDAP as a role provider in Fiat is poor (in fact, I can help with that now that I have tried xD) and was not clear to me why the log prints "userDn is not set" as INFO, even filling the managerDn field.

** Wrong assumption **: I was trying to search as anonymous, without credentials because my LDAP allow this. A lot of programs that I use to do this kind of search, I can do that as anonymous.
