### ISSUE TITLE
Clouddriver Kubernetes v1 provider failure

### ISSUE THREAD

**Issue by chz8494** [spinnaker/spinnaker#2981]
### Issue Summary:
Error log shows `Get Services in default for account dev failed: Operation: [list]  for kind: [Service]  with name: [null]  in namespace: [default]  failed.`

### Cloud Provider(s):
k8s

### Environment:
Openstack

### Feature Area: 
Clouddriver

### Description:
I have both V1/V2 k8s provider configured. I can see Accounts with namespace and everything in trigger settings of a pipeline and in application's server group view(you get an option to choose v1 or v2 to proceed when create a server group). But I can't see deploy(manifest) related option in pipeline view.

### Steps to Reproduce:
Clouddriver-local.yml
```
server:
  port: ${services.clouddriver.port:7002}
  address: 0.0.0.0

default:
  account:
    env: ${providers.kubernetes.primaryCredentials.name}

kubernetes:
  enabled: true
  accounts:
    - name: prod
      kubeconfigFile: /tmp/kube/config
      providerVersion: V1
      context: prod
      namespaces:
        - default
        - xxx
      dockerRegistries:
      - accountName: xxx
      
      - accountName: yyy
      
    
    - name: dev
      kubeconfigFile: /tmp/kube/config
      providerVersion: V1
      context: dev
      namespaces:
        - default
      dockerRegistries:
      - accountName: xxx
      
      - accountName: yyy
      
    - name: prod-v2
      kubeconfigFile: /tmp/kube/config
      providerVersion: V2
      context: prod
      namespaces:
        - default
        - xxx
      dockerRegistries:
      - accountName: xxx
      
      - accountName: yyy
      
    
    - name: dev-v2
      kubeconfigFile: /tmp/kube/config
      providerVersion: V2
      context: dev
      namespaces:
        - default
      dockerRegistries:
      - accountName: xxx
      
      - accountName: yyy
      
    
dockerRegistry:
  enabled: true
  accounts:
    - name: xxx
      address: https://xxx:5000
      username: admin
      email: 
      passwordFile: /tmp/registry/password-xxx
      
    - name: yyy
      address: https://xxx:5001
      username: admin
      email: 
      passwordFile: /tmp/registry/password-yyy
      
credentials:
  primaryAccountTypes: ${providers.kubernetes.primaryCredentials.name}
  challengeDestructiveActionsEnvironments: ${providers.kubernetes.primaryCredentials.name}
```

### Additional Details:
error logs:
```
2018-06-29 17:15:20.055  INFO 1 --- [cutionAction-51] c.n.s.c.cache.LoggingInstrumentation     : kubernetes:prod-v2/KubernetesCoreCachingAgent[1/1] completed in 27.81s
2018-06-29 17:15:21.799  WARN 1 --- [cutionAction-69] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.KubernetesV1Provider:dev/KubernetesServerGroupCachingAgent[1/1] completed with one or more failures

com.netflix.spinnaker.clouddriver.kubernetes.v1.deploy.exception.KubernetesOperationException: Get Replication Controllers in default for account dev failed: Operation: [list]  for kind: [ReplicationController]  with name: [null]  in namespace: [default]  failed.
        at sun.reflect.GeneratedConstructorAccessor151.newInstance(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_171]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_171]
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263) ~[groovy-all-2.4.13.jar:2.4.13]
        at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor.formatException(KubernetesApiAdaptor.groovy:74) ~[clouddriver-kubernetes-2.60.0-SNAPSHOT.jar:2.60.0-SNAPSHOT]
        at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor$formatException$5.callCurrent(Unknown Source) ~[na:na]
        at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor.exceptionWrapper(KubernetesApiAdaptor.groovy:115) ~[clouddriver-kubernetes-2.60.0-SNAPSHOT.jar:2.60.0-SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190) ~[groovy-all-2.4.13.jar:2.4.13]
        at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor.getReplicationControllers(KubernetesApiAdaptor.groovy:269) ~[clouddriver-kubernetes-2.60.0-SNAPSHOT.jar:2.60.0-SNAPSHOT]
        at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor$getReplicationControllers$8.call(Unknown Source) ~[na:na]
        at com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.agent.KubernetesServerGroupCachingAgent$_loadReplicationControllers_closure7.doCall(KubernetesServerGroupCachingAgent.groovy:199) ~[clouddriver-kubernetes-2.60.0-SNAPSHOT.jar:2.60.0-SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor1029.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-all-2.4.13.jar:2.4.13]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-all-2.4.13.jar:2.4.13]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022) ~[groovy-all-2.4.13.jar:2.4.13]
        at groovy.lang.Closure.call(Closure.java:414) ~[groovy-all-2.4.13.jar:2.4.13]
        at groovy.lang.Closure.call(Closure.java:430) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3202) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3172) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.dgm$67.invoke(Unknown Source) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-all-2.4.13.jar:2.4.13]
        at com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.agent.KubernetesServerGroupCachingAgent.loadReplicationControllers(KubernetesServerGroupCachingAgent.groovy:198) ~[clouddriver-kubernetes-2.60.0-SNAPSHOT.jar:2.60.0-SNAPSHOT]
        at com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.agent.KubernetesServerGroupCachingAgent.loadData(KubernetesServerGroupCachingAgent.groovy:225) ~[clouddriver-kubernetes-2.60.0-SNAPSHOT.jar:2.60.0-SNAPSHOT]
        at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:80) ~[cats-core-2.60.0-SNAPSHOT.jar:2.60.0-SNAPSHOT]
        at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:73) ~[cats-core-2.60.0-SNAPSHOT.jar:2.60.0-SNAPSHOT]
        at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:299) ~[cats-redis-2.60.0-SNAPSHOT.jar:2.60.0-SNAPSHOT]
        at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:273) ~[cats-redis-2.60.0-SNAPSHOT.jar:2.60.0-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [ReplicationController]  with name: [null]  in namespace: [default]  failed.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62) ~[kubernetes-client-3.0.3.jar:na]
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71) ~[kubernetes-client-3.0.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:609) ~[kubernetes-client-3.0.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70) ~[kubernetes-client-3.0.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.Listable$list.call(Unknown Source) ~[na:na]
        at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor$_getReplicationControllers_closure21.doCall(KubernetesApiAdaptor.groovy:270) ~[clouddriver-kubernetes-2.60.0-SNAPSHOT.jar:2.60.0-SNAPSHOT]
        at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor$_getReplicationControllers_closure21.doCall(KubernetesApiAdaptor.groovy) ~[clouddriver-kubernetes-2.60.0-SNAPSHOT.jar:2.60.0-SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor1031.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-all-2.4.13.jar:2.4.13]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-all-2.4.13.jar:2.4.13]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57) ~[groovy-all-2.4.13.jar:2.4.13]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) ~[groovy-all-2.4.13.jar:2.4.13]
        at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor.exceptionWrapper(KubernetesApiAdaptor.groovy:112) ~[clouddriver-kubernetes-2.60.0-SNAPSHOT.jar:2.60.0-SNAPSHOT]
        ... 35 common frames omitted
Caused by: java.net.UnknownHostException: [Sensored:k8s-fqdn address]: Try again
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_171]
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_171]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_171]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[na:1.8.0_171]
        at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_171]
        at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_171]
        at okhttp3.Dns$1.lookup(Dns.java:40) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.10.0.jar:na]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:95) ~[kubernetes-client-3.0.3.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.10.0.jar:na]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[okhttp-3.10.0.jar:na]
        at okhttp3.RealCall.execute(RealCall.java:77) ~[okhttp-3.10.0.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377) ~[kubernetes-client-3.0.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343) ~[kubernetes-client-3.0.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327) ~[kubernetes-client-3.0.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605) ~[kubernetes-client-3.0.3.jar:na]
        ... 51 common frames omitted
```

**Comment by lwander** [comment]
This is a known limitation of the client library the v1 provider uses. If you're on GKE you can follow these steps: https://www.spinnaker.io/setup/install/providers/kubernetes/#if-your-cluster-is-running-on-gke to get working creds. If not, you can just create a service account and mount the token in your ~/.kube/config Instructions on how to do that are here: https://www.spinnaker.io/setup/install/providers/kubernetes-v2/#optional-create-a-kubernetes-service-account

**Comment by chz8494** [comment]
@lwander Can you explain what limitation you are talking about? Isn't creating k8s service account optional? My config uses k8s config context, and it was working with older version of clouddriver. And also why I can't see `Deploy(Manifest)` options?

**Comment by lwander** [comment]
Creating a service account is optional because you can also rely on certs + basic auth. Anything like an auth-provider (what GCP relies on with gcloud) won't work. See the auth methods allowed here: https://github.com/fabric8io/kubernetes-client

**Comment by chz8494** [comment]
@lwander I'm using Certs, the same config file that K8S master uses to control its cluster. The thing is that this kind of error was not there before, and I have no problem with running my pipelines, then why it throws error?

**Comment by lwander** [comment]
Based on [this comment](https://github.com/spinnaker/spinnaker/issues/2363#issuecomment-398248224) it seems like maybe your k8s node OS has troubles with host resolution?
