### ISSUE TITLE
Clouddriver fails to honor the kubeconfig cluster->server setting if it ends in a slash

### ISSUE THREAD

**Issue by mdirkse** [spinnaker/spinnaker#3005]
### Issue Summary:
Yes, you read that right, "if it ends in a slash" :) If the cluster->server setting of a kubeconfig file ends in a slash Clouddriver will ignore the server setting and attempt to connect to `kubernetes.default.svc` instead, which is the [default master set by the fabric8 k8s client lib](https://github.com/fabric8io/kubernetes-client/blob/8454e2811f9c3d0b96a220529200a2812ae20e50/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L118). Strip the slash and things work as intended. Hit me up on Slack if you want the harrowing tale of how it took us 3 days to figure this out :grimacing:

### Cloud Provider(s):
Kubernetes v1

### Feature Area: 
Clouddriver

### Steps to Reproduce:

-  Install [minikube](https://github.com/kubernetes/minikube) and start the local cluster.
- Create a directory called `config` (or whatever) and create the following files in it:
`clouddriver.yml` ->
```yaml
dockerRegistry:
  enabled: true
  accounts:
  - name: gcr
    providerVersion: V1
    permissions: {}
    address: https://gcr.io
    username: _json_key
    email: fake.email@spinnaker.io
    cacheIntervalSeconds: 600
    clientTimeoutMillis: 60000
    cacheThreads: 1
    paginateSize: 100
    sortTagsByDate: false
    trackDigests: false
    insecureRegistry: false
    repositories:
    - google-containers/busybox
  primaryAccount: gcr
kubernetes:
  enabled: true
  accounts:
  - name: minikube
    providerVersion: V1
    permissions: {}
    dockerRegistries:
    - accountName: gcr
      namespaces: []
    namespace: default
    omitNamespaces: []
    kinds: []
    omitKinds: []
    customResources: []
    kubeconfigFile: /opt/spinnaker/config/kubeconfig
  primaryAccount: minikube
```
`kubeconfig` ->
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /opt/spinnaker/config/ca.crt
    server: https://<INSERT YOUR MINIKUBE IP AND PORT HERE>/ # << note the slash at the end!
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /opt/spinnaker/config/client.crt
    client-key: /opt/spinnaker/config/client.key
```
- copy the `ca.crt`, `client.crt` and `client.key` files from the `${HOME}/.minikube` directory into your `config` directory. You now have the necessary config in place to run Clouddriver with a single k8s account that points to your minikube instance.
- Start Redis (Clouddriver needs it): `docker run -d --net=host
- Finally, run clouddriver with the config you've just assembled: `docker run -ti --net=host -v "$(pwd):/opt/spinnaker/config" gcr.io/spinnaker-marketplace/clouddriver:3.3.0-20180703115601` (and make sure to start it from your `config` directory)

During startup, and after it's initialized, Clouddriver will complain that it can't connect to `kubernetes.default.svc` with stacktraces like the following:

```
com.netflix.spinnaker.clouddriver.kubernetes.v1.deploy.exception.KubernetesOperationException: Get Namespaces for account minikube failed: Operation: [list]  for kind: [Namespace]  with name: [null]  in namespace: [null]  failed.
	at sun.reflect.GeneratedConstructorAccessor65.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_171]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_171]
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83) ~[groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77) ~[groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84) ~[groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263) [groovy-all-2.4.13.jar:2.4.13]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor.formatException(KubernetesApiAdaptor.groovy:79) ~[clouddriver-kubernetes-2.61.0-SNAPSHOT.jar:2.61.0-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor$formatException.callCurrent(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor.exceptionWrapper(KubernetesApiAdaptor.groovy:117) ~[clouddriver-kubernetes-2.61.0-SNAPSHOT.jar:2.61.0-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210) ~[groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59) ~[groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190) [groovy-all-2.4.13.jar:2.4.13]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor.getNamespacesByName(KubernetesApiAdaptor.groovy:422) ~[clouddriver-kubernetes-2.61.0-SNAPSHOT.jar:2.61.0-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.security.KubernetesV1Credentials.getDeclaredNamespaces(KubernetesV1Credentials.java:139) ~[clouddriver-kubernetes-2.61.0-SNAPSHOT.jar:2.61.0-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesCredentials$getDeclaredNamespaces.call(Unknown Source) [clouddriver-kubernetes-2.61.0-SNAPSHOT.jar:2.61.0-SNAPSHOT]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) [groovy-all-2.4.13.jar:2.4.13]
	at com.netflix.spinnaker.clouddriver.kubernetes.health.KubernetesHealthIndicator.checkHealth(KubernetesHealthIndicator.groovy:67) [clouddriver-kubernetes-2.61.0-SNAPSHOT.jar:2.61.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Namespace]  with name: [null]  in namespace: [null]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:609) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.Listable$list.call(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor$_getNamespacesByName_closure43.doCall(KubernetesApiAdaptor.groovy:423) ~[clouddriver-kubernetes-2.61.0-SNAPSHOT.jar:2.61.0-SNAPSHOT]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor$_getNamespacesByName_closure43.doCall(KubernetesApiAdaptor.groovy) ~[clouddriver-kubernetes-2.61.0-SNAPSHOT.jar:2.61.0-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-all-2.4.13.jar:2.4.13]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-all-2.4.13.jar:2.4.13]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022) ~[groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42) ~[groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) [groovy-all-2.4.13.jar:2.4.13]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.api.KubernetesApiAdaptor.exceptionWrapper(KubernetesApiAdaptor.groovy:112) ~[clouddriver-kubernetes-2.61.0-SNAPSHOT.jar:2.61.0-SNAPSHOT]
	... 26 common frames omitted
Caused by: java.net.UnknownHostException: kubernetes.default.svc
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[na:1.8.0_171]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_171]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_171]
	at okhttp3.Dns$1.lookup(Dns.java:40) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.10.0.jar:na]
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:95) ~[kubernetes-client-3.0.3.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.10.0.jar:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[okhttp-3.10.0.jar:na]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[okhttp-3.10.0.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605) ~[kubernetes-client-3.0.3.jar:na]
	... 40 common frames omitted
```
However, if you remove the trailing slash from the `server` key in `kubeconfig` everything will work as expected.

**Comment by lwander** [comment]
Thanks for the writeup and the fix!

**Comment by kazihuo** [comment]
> [``](_**### 

- 

- [ ] @

- [ ] 

- [url](`

_**### url**_

`)

**_)
