### ISSUE TITLE
CloudDriver throwing "No qualifying bean of type"

### ISSUE THREAD

**Issue by nixgadget** [spinnaker/spinnaker#3054]
Locally installed Spinnaker with `minio` on Ubuntu 16.04.

However I keep seeing the following error,
```
Jul 17 03:50:06 riro-build gate[15091]: 2018-07-17 03:50:06.134  INFO 15091 --- [TaskScheduler-5] c.n.s.g.s.internal.ClouddriverService    : ---- ERROR http://localhost:7002/credentials?expand=true
Jul 17 03:50:06 riro-build gate[15091]: 2018-07-17 03:50:06.135  INFO 15091 --- [TaskScheduler-5] c.n.s.g.s.internal.ClouddriverService    : java.net.ConnectException: Failed to connect to localhost/127.0.0.1:7002
Jul 17 03:50:06 riro-build gate[15091]: #011at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:283)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.squareup.okhttp.Call.getResponse(Call.java:286)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.squareup.okhttp.Call.execute(Call.java:80)
Jul 17 03:50:06 riro-build gate[15091]: #011at retrofit.client.OkClient.execute(OkClient.java:53)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.netflix.spinnaker.gate.retrofit.EurekaOkClient.super$2$execute(EurekaOkClient.groovy)
Jul 17 03:50:06 riro-build gate[15091]: #011at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source)
Jul 17 03:50:06 riro-build gate[15091]: #011at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jul 17 03:50:06 riro-build gate[15091]: #011at java.lang.reflect.Method.invoke(Method.java:498)
Jul 17 03:50:06 riro-build gate[15091]: #011at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
Jul 17 03:50:06 riro-build gate[15091]: #011at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
Jul 17 03:50:06 riro-build gate[15091]: #011at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
Jul 17 03:50:06 riro-build gate[15091]: #011at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:132)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.netflix.spinnaker.gate.retrofit.EurekaOkClient.execute(EurekaOkClient.groovy:82)
Jul 17 03:50:06 riro-build gate[15091]: #011at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
Jul 17 03:50:06 riro-build gate[15091]: #011at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.sun.proxy.$Proxy106.getAccountDetails(Unknown Source)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.netflix.spinnaker.gate.services.internal.ClouddriverService$getAccountDetails.call(Unknown Source)
Jul 17 03:50:06 riro-build gate[15091]: #011at com.netflix.spinnaker.gate.services.DefaultProviderLookupService.refreshCache(DefaultProviderLookupService.groovy:56)
Jul 17 03:50:06 riro-build gate[15091]: #011at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
Jul 17 03:50:06 riro-build gate[15091]: #011at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jul 17 03:50:06 riro-build gate[15091]: #011at java.lang.reflect.Method.invoke(Method.java:498)
Jul 17 03:50:06 riro-build gate[15091]: #011at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
Jul 17 03:50:06 riro-build gate[15091]: #011at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
Jul 17 03:50:06 riro-build gate[15091]: #011at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Jul 17 03:50:06 riro-build gate[15091]: #011at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
Jul 17 03:50:06 riro-build gate[15091]: #011at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
Jul 17 03:50:06 riro-build gate[15091]: #011at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
Jul 17 03:50:06 riro-build gate[15091]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Jul 17 03:50:06 riro-build gate[15091]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Jul 17 03:50:06 riro-build gate[15091]: #011at java.lang.Thread.run(Thread.java:748)
Jul 17 03:50:06 riro-build gate[15091]: 2018-07-17 03:50:06.135  INFO 15091 --- [TaskScheduler-5] c.n.s.g.s.internal.ClouddriverService    : ---- END ERROR
Jul 17 03:50:06 riro-build gate[15091]: 2018-07-17 03:50:06.135 ERROR 15091 --- [TaskScheduler-5] c.n.s.g.s.DefaultProviderLookupService   : Unable to refresh account details cache, reason: Failed to connect to localhost/127.0.0.1:7002
```

When starting CloudDriver I can see,
```
2018-07-17 03:51:33.218  WARN 16661 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'searchController': Unsatisfied dependency expressed through field 'searchProviders'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'catsSearchProvider' defined in com.netflix.spinnaker.clouddriver.cache.CacheConfig: Unsatisfied dependency expressed through method 'catsSearchProvider' parameter 2; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<com.netflix.spinnaker.clouddriver.cache.SearchableProvider>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2018-07-17 03:51:33.236  INFO 16661 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-07-17 03:51:33.251  WARN 16661 --- [ost-startStop-1] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [spectator-gauge-polling-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
2018-07-17 03:51:33.292  INFO 16661 --- [           main] utoConfigurationReportLoggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-07-17 03:51:33.644 ERROR 16661 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'searchController': Unsatisfied dependency expressed through field 'searchProviders'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'catsSearchProvider' defined in com.netflix.spinnaker.clouddriver.cache.CacheConfig: Unsatisfied dependency expressed through method 'catsSearchProvider' parameter 2; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<com.netflix.spinnaker.clouddriver.cache.SearchableProvider>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) ~[spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) ~[spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder$run$0.call(Unknown Source) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-all-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-all-2.4.13.jar:2.4.13]
	at com.netflix.spinnaker.clouddriver.Main.main(Main.groovy:108) [clouddriver-web-3.2.1-20180702044906.jar:3.2.1-20180702044906]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'catsSearchProvider' defined in com.netflix.spinnaker.clouddriver.cache.CacheConfig: Unsatisfied dependency expressed through method 'catsSearchProvider' parameter 2; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<com.netflix.spinnaker.clouddriver.cache.SearchableProvider>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1316) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1282) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1180) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1096) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	... 22 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<com.netflix.spinnaker.clouddriver.cache.SearchableProvider>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1493) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1104) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	... 38 common frames omitted
```

What could be causing this issue ?

**Comment by nixgadget** [comment]
This appears to be caused by missing kubernetes v2 configuration. After following https://www.spinnaker.io/setup/install/providers/kubernetes-v2/ its working as expected.
