### ISSUE TITLE
Apply changes to exist Spinnaker cluster throw an error

### ISSUE THREAD

**Issue by zivbaz** [spinnaker/spinnaker#3074]
### Summary:
Getting an error when running `hal deploy apply`, can only use `hal deploy clean` and then  `hal deploy apply`

### Cloud Provider(s):
K8s 1.9.0 on AWS

### Environment:
Spinnaker version - 1.8.1
Hal version - 1.5.0-20180713143726

### Description:

When I try to update an existing Spinnaker cluster using Halyard I'm getting the error:
```
! ERROR Clone server group: (Bad Request) unknown is not authorized (account: new-tools, description: CloneKubernetesAtomicOperationDescription)
```

This is the log when running Halyard in debug mode:
```
RUNNING failed with unexpected reason:

io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:229) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:182) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:773) ~[kubernetes-client-3.0.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356) ~[kubernetes-client-3.0.3.jar:na]
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.service.distributed.kubernetes.v1.KubernetesV1ProviderUtils.upsertSecret(KubernetesV1ProviderUtils.java:171) ~[halyard-deploy-1.5.0-20180713143726.jar:1.5.0-20180713143726]
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.service.distributed.kubernetes.v1.KubernetesV1DistributedService.stageProfiles(KubernetesV1DistributedService.java:313) ~[halyard-deploy-1.5.0-20180713143726.jar:1.5.0-20180713143726]
	at com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer.deployServiceWithOrca(DistributedDeployer.java:277) ~[halyard-deploy-1.5.0-20180713143726.jar:1.5.0-20180713143726]
	at com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer.lambda$deploy$4(DistributedDeployer.java:214) ~[halyard-deploy-1.5.0-20180713143726.jar:1.5.0-20180713143726]
	at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:127) ~[halyard-core-1.5.0-20180713143726.jar:1.5.0-20180713143726]
	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core-1.5.0-20180713143726.jar:1.5.0-20180713143726]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: java.io.InterruptedIOException: thread interrupted
	at okio.Timeout.throwIfReached(Timeout.java:145) ~[okio-1.13.0.jar:na]
	at okio.Okio$2.read(Okio.java:136) ~[okio-1.13.0.jar:na]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[okio-1.13.0.jar:na]
	at okio.RealBufferedSource.read(RealBufferedSource.java:46) ~[okio-1.13.0.jar:na]
	at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:352) ~[okhttp-3.9.0.jar:na]
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:442) ~[okhttp-3.9.0.jar:na]
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:430) ~[okio-1.13.0.jar:na]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_171]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_171]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_171]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMore(UTF8StreamJsonParser.java:204) ~[jackson-core-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMoreGuaranteed(UTF8StreamJsonParser.java:2404) ~[jackson-core-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2489) ~[jackson-core-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2469) ~[jackson-core-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:315) ~[jackson-core-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:36) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:517) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:362) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:27) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2915) ~[jackson-databind-2.8.8.jar:2.8.8]
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:227) ~[kubernetes-client-3.0.3.jar:na]
	... 13 common frames omitted
```

**Comment by nvndnl** [comment]
@spinnakerbot add-label component/halyard

**Comment by mdirkse** [comment]
I've tog the same issue, the initial deploy goes well but then subsequent deploy attempts fail. It seems to be due to the fact that we've enabled fiat, set restrictions on what roles can access the account that kubernetes itself runs in, and on all deploys after the inital one clouddriver-bootstrap consults fiat as to whether the user that halyard uses ("unknown") can use the account. And of course it can't (see log). I'm not really sure though why clouddriver-bootstrap consults fiat about anything.

```
2018-08-03 11:58:17.263  WARN 1 --- [0.0-7002-exec-3] .n.s.c.s.DefaultAllowedAccountsValidator : unknown is not authorized (account: spinnaker-bolcom-stg-spinnaker-6b3, description: CloneKubernetesAtomicOperationDescription, allowedAccounts: [], requiredGroups: [team dpi],
```

**Comment by mdirkse** [comment]
And indeed, Halyard doesn't seem to clear the permissions, but does clear the requiredGroupMembership:

https://github.com/spinnaker/halyard/blob/master/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Account.java#L47
