### ISSUE TITLE
[GCE][Clouddriver] something like timestamp is added to instance group name when instance group created

### ISSUE THREAD

**Issue by ikemonn** [spinnaker/spinnaker#3449]
### Issue Summary:

When we deployed the following setting instance group,  cluster name becomes `productionkarte-analyzeusertobq-asia-northeast1-a-v000-1539587338619` and we have name length exceeded error.

```
application: productionkarte
stack: analyzeusertobq
freeFromDetails: asia-northeast1-a
```

I think it is strange that `1539587338619` is added.

- Expected: `productionkarte-analyzeusertobq-asia-northeast1-a-v000`
- Actual: `productionkarte-analyzeusertobq-asia-northeast1-a-v000-1539587338619`

![image](https://user-images.githubusercontent.com/2867833/46941449-1a592b00-d0a6-11e8-8d0b-b494db59ec12.png)
![image](https://user-images.githubusercontent.com/2867833/46942695-d7e51d80-d0a8-11e8-89da-03c3d05ad13f.png)

### Cloud Provider(s):
GCP

### Environment:
Spinnaker v1.9.0
We are using Spinnaker which was launched by GCP Marketplace.

### Steps to Reproduce:
Make the following string length more than 64 characters.
`{application}-{stack}-{freeFormDetails}-{version}-{timestamp}` 

### Additional Details:

If the length of  `{application}-{stack}-{freeFormDetails}-{version}-{timestamp?}` < 63, this error does not occur.
In addition, if the length < 63, instance group name which is created successfully does not have timestamp? character.
The name is `{application}-{stack}-{freeFormDetails}-{version}`, not `{application}-{stack}-{freeFormDetails}-{version}-{timestamp}`.

**Comment by jtk54** [comment]
It's unclear from the screenshots whether it's the server *group* name or the *instance* name that is >64 characters, can you clarify which one it is? The stack trace from clouddriver would also help debug this.

**Comment by ikemonn** [comment]
@jtk54 
This is stack trace.

<details>
<summary> stack </summary>

```
2018-10-15 07:05:50.045  INFO 12479 --- [l-3-thread-2707] c.n.s.c.data.task.jedis.JedisTask        : [ORCHESTRATION] - Orchestration failed: DeployAtomicOperation | GoogleJsonResponseException: [400 Bad Requ
est
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid value for field 'resource.name': 'productionkarte-analyzeusertobq-asia-northeast1-a-v000-1539587149977'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'",
    "reason" : "invalid"
  } ],
  "message" : "Invalid value for field 'resource.name': 'productionkarte-analyzeusertobq-asia-northeast1-a-v000-1539587149977'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'"
}]
2018-10-15 07:05:50.046 ERROR 12479 --- [l-3-thread-2707] c.n.s.c.o.DefaultOrchestrationProcessor  : com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid value for field 'resource.name': 'productionkarte-analyzeusertobq-asia-northeast1-a-v000-1539587149977'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'",
    "reason" : "invalid"
  } ],
  "message" : "Invalid value for field 'resource.name': 'productionkarte-analyzeusertobq-asia-northeast1-a-v000-1539587149977'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$execute$241.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$execute.call(Unknown Source)
        at com.netflix.spinnaker.clouddriver.googlecommon.GoogleExecutor.timeExecute(GoogleExecutor.groovy:113)
        at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:46)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:96)
        at com.netflix.spinnaker.clouddriver.google.GoogleExecutorTraits$Trait$Helper.timeExecute(GoogleExecutorTraits.groovy:53)
        at com.netflix.spinnaker.clouddriver.google.GoogleExecutorTraits$Trait$Helper$timeExecute$15.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at com.netflix.spinnaker.clouddriver.google.GoogleExecutorTraits$Trait$Helper$timeExecute$15.call(Unknown Source)
        at com.netflix.spinnaker.clouddriver.google.deploy.handlers.BasicGoogleDeployHandler.timeExecute(BasicGoogleDeployHandler.groovy)
        at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:169)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190)
        at com.netflix.spinnaker.clouddriver.google.deploy.handlers.BasicGoogleDeployHandler.handle(BasicGoogleDeployHandler.groovy:354)
        at com.netflix.spinnaker.clouddriver.google.deploy.handlers.BasicGoogleDeployHandler$handle.call(Unknown Source)
        at com.netflix.spinnaker.clouddriver.deploy.DeployAtomicOperation.operate(DeployAtomicOperation.groovy:58)
        at com.netflix.spinnaker.clouddriver.deploy.DeployAtomicOperation.operate(DeployAtomicOperation.groovy)
        at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate.call(Unknown Source)
        at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy:89)
        at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy)
        at sun.reflect.GeneratedMethodAccessor37365.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at com.netflix.spinnaker.clouddriver.metrics.TimedCallable$ClosureWrapper.call(TimedCallable.groovy:55)
        at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82)
        at java_util_concurrent_Callable$call$0.call(Unknown Source)
        at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy:88)
        at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy)
        at sun.reflect.GeneratedMethodAccessor37364.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$1(AuthenticatedRequest.java:79)
        at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
</details>

**Comment by jtk54** [comment]
Which Spinnaker version are you running? At HEAD that looks like a call to insert an instance template, but I'm not convinced that's what it is yet.

**Comment by ikemonn** [comment]
> ### Environment:
> Spinnaker v1.9.0
> We are using Spinnaker which was launched by GCP Marketplace.

We are using this version and using roer & pipeline template to mange pipeline.

**Comment by ikemonn** [comment]
@jtk54

**Comment by jtk54** [comment]
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/handlers/BasicGoogleDeployHandler.groovy#L302 We need to do some validation around the instance template name. Not sure exactly how we can make these unique yet.

**Comment by ikemonn** [comment]
@jtk54 
Thank you for fixing!
