### ISSUE TITLE
Spinnaker 1.10.2 fails to bind artifacts

### ISSUE THREAD

**Issue by wjoel** [spinnaker/spinnaker#3583]
### Issue Summary:

Artifacts do not get bound in Spinnaker 1.10.2. Downgrading to 1.10.1 fixes the problem.

### Cloud Provider(s):

Only tried Kubernetes, but likely affects all cloud providers.

### Environment:

Spinnaker deployed to GKE using Halyard

### Feature Area: 

Artifacts, pipeline execution

### Description:

Pipelines using artifacts, which work fine in all previous versions of Spinnaker, now fail with errors similar to this one:

```
java.lang.IllegalArgumentException: No artifact could be bound to 'manifestsArtifact' at
com.netflix.spinnaker.orca.clouddriver.tasks.manifest.DeployManifestTask.execute(DeployManifestTask.java:97) at
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:97) at
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:55) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withLoggingContext(RunTaskHandler.kt:308) at 
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$withLoggingContext(RunTaskHandler.kt:55) at 
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:96) at 
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:55) at 
com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt) at 
com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:94) at
com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49) at
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:55) at 
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:95) at
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:55) at 
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:179) at 
com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:55) at 
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:48) at 
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:32) at 
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:58) at 
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:32) at 
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:67) at
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:55) at 
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:54) at 
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:55) at 
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:41) at 
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:55) at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:172) at 
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:68) at 
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:55) at 
com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36) at 
com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt) at
com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:55) at 
com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47) at 
com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82) at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at 
java.lang.Thread.run(Thread.java:748)
```

### Steps to Reproduce:

Create a pipeline using a GitHub artifact for a Kubernetes manifests.yaml file, and use it in a "deploy manifest" stage using the Kubernetes v2 provider.

### Additional Details:

I suspect this is related to https://github.com/spinnaker/echo/pull/383 but note that while we first noticed this on pipelines using pipeline templates, we were able to easily reproduce it without pipeline templates by just creating a new pipeline using a GitHub manifest and a GitHub trigger and a single "deploy manifest" stage.

**Comment by ezimanyi** [comment]
I just tried the non-templated version by using a `manifest.yaml` file in a git repo.  I was able to trigger a pipeline by pushing a commit to the repo, and the artifact was correctly bound.  @wjoel : Are there any other details of the pipeline that might help me reproduce?

**Comment by wjoel** [comment]
@ezimanyi yes, @psalaberria002 just told me I'm remembering this wrong. The non-templated version did work.

Please try `roer pipeline-template convert <your-app> <that-working-pipeline>`, upload the resulting template and create a pipeline using that template. That's what didn't work for us.

**Comment by ezimanyi** [comment]
Thanks for the additional info @wjoel.  I'll probably wait for @jtk54 to take a look on Monday as he's much more familiar with pipeline templates and has this all set up.

**Comment by jtk54** [comment]
Nevermind, I have a base pipeline crafted in the UI that I can template. Update shortly.

**Comment by wjoel** [comment]
Thanks @jtk54! Looking forward to try this out in the next release.
