### ISSUE TITLE
Unable to manually run templated child pipeline if parent pipeline was auto-triggered by another pipeline.

### ISSUE THREAD

**Issue by jonsie** [spinnaker/spinnaker#3676]
### Issue Summary:

Unable to manually run templated child pipeline if parent pipeline was auto-triggered by another pipeline.

### Cloud Provider(s):

AWS - n/a

### Environment:

We produce our own debian packages of Spinnaker and deploy them to EC2.

Verified on halyard release 1.10.5 as well as Orca 6.112.0

### Feature Area: 

Pipeline triggers, pipeline templates

### Description:

Assume a workflow wherein CI triggers `pipeline A` via REST (using an x509 cert with a service account principal).  All pipelines are templated.

`Pipeline A` then triggers `pipeline B`, which burns an AMI.

Finally, if `pipeline C` (the third in the chain) is not set to auto-trigger off the AMI burn (`pipeline B`), but instead requires a manual execution the user will be unable to manually run the pipeline.

Gate will see a 500 error from Orca (which manifests as a 422 in Deck).  The Orca exception is as follows:

```
2018-11-28 03:49:14.075 ERROR 1072 --- [0.0-8080-exec-2] c.n.s.k.w.e.GenericExceptionHandlers     : [chris.smalley] Internal Server Error
java.lang.IllegalArgumentException: No _valueDeserializer assigned
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.netflix.spinnaker.orca.pipeline.model.Execution["trigger"]->com.netflix.spinnaker.orca.pipeline.model.Execution["stages"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3605)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3524)
	at com.fasterxml.jackson.databind.ObjectMapper$convertValue$0.call(Unknown Source)
	at com.netflix.spinnaker.orca.controllers.OperationsController.orchestrate(OperationsController.groovy:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.netflix.spinnaker.orca.web.config.WebConfiguration$1.doFilter(WebConfiguration.groovy:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.netflix.spinnaker.fiat.shared.FiatAuthenticationFilter.doFilter(FiatAuthenticationFilter.java:66)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at javax.servlet.FilterChain$doFilter.call(Unknown Source)
	at com.netflix.spinnaker.filters.AuthenticatedRequestFilter.doFilter(AuthenticatedRequestFilter.groovy:134)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No _valueDeserializer assigned
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.netflix.spinnaker.orca.pipeline.model.Execution["trigger"]->com.netflix.spinnaker.orca.pipeline.model.Execution["stages"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
	at com.fasterxml.jackson.databind.deser.impl.FailingDeserializer.deserialize(FailingDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:432)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3786)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2115)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2612)
	at com.netflix.spinnaker.orca.pipeline.model.support.TriggerDeserializer.deserialize(TriggerDeserializer.kt:144)
	at com.netflix.spinnaker.orca.pipeline.model.support.TriggerDeserializer.deserialize(TriggerDeserializer.kt:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:432)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3786)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2115)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2612)
	at com.netflix.spinnaker.orca.pipeline.model.support.TriggerDeserializer.deserialize(TriggerDeserializer.kt:144)
	at com.netflix.spinnaker.orca.pipeline.model.support.TriggerDeserializer.deserialize(TriggerDeserializer.kt:25)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3600)
	... 106 common frames omitted
```

I have logged out both the groovy `Map` that the `OperationsController` passes to `objectMapper.convertValue(processedPipeline.trigger, Trigger)` as well as the JSON that is parsed via `TriggerDeserializer` before building the `Trigger` object and I have passed these data structures to an instance of `objectMapper` in hopes of reproducing this deserialization issue but I have had no luck - all my attempts have been without failure. 🤔 

Note that if this final pipeline, `pipeline C`, is not built from a template but rather manually managed (a normal pipeline) then everything works as expected and the user is able to run the pipeline.
 
### Steps to Reproduce:

(All pipelines here are templated)

1) Create a `pipeline A` with a wait stage
2) Create `pipeline B` that burns an AMI, which will auto-trigger off the success of `pipeline A`
3) Create `pipeline C` that deploys the AMI, which has `pipeline B` as a trigger but it is `disabled`
4) Trigger `pipeline A` via REST
5) Watch as `pipeline B` is triggered and the AMI burns
6) Finally, attempt to kick off `pipeline C` manually - nothing will happen and you should be able to find the exception posted above.

**Comment by ezimanyi** [comment]
@jtk54 has been fixing some bugs related to templated piplelines, and may have already fixed this, or may have more insight.

**Comment by jonsie** [comment]
This appears to be a race condition, specifically with the use of `JsonManagedReference` here:

https://github.com/spinnaker/orca/blob/master/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Execution.java#L171

I believe this is a race condition bug in Jackson Databind, but I still need to do a bit more digging.  Simply removing `JsonManagedReference` annotation resolves this specific issue.

The only minor mention of this issue I was able to find is here:

https://github.com/FasterXML/jackson-databind/issues/1769

**Comment by jonsie** [comment]
For posterity, `JsonManagedReference` was added here:

https://github.com/spinnaker/orca/pull/1772

**Comment by jtk54** [comment]
@jonsie The linked issue sounds very similar, but I think we're using a version of the jackson-databind library which has that fix.

From orca's dependencies at HEAD (incidentally I think there are similar to what's on 1.10.x):

```
+--- project :orca-pipelinetemplate
|    +--- project :orca-extensionpoint
...
|    +--- com.fasterxml.jackson.core:jackson-databind:2.9.2 (*)
```

Though I do see an [an explicit import of the `jacksonDatabind` dependency](https://github.com/spinnaker/orca/blob/master/orca-pipelinetemplate/orca-pipelinetemplate.gradle#L18) in orca-pipelinetemplate.gradle. Not sure if that may be causing issues or not, might be something to look into.

@robfletcher Is there any good way to get around using the two way binding annotations in Execution?

**Comment by jonsie** [comment]
@jtk54 Yeah, I noticed Orca uses 2.9.2, however the issue is still there.  I forced all of Orca to use 2.9.7 (except for `jackson-module-kotlin` which needs to be at 2.9.2), but the exception still occurs.

I'm also curious if there is another way to achieve this two way binding between `Execution` and `Stage`.
