### ISSUE TITLE
Cannot access OpenShift Docker Registry

### ISSUE THREAD

**Issue by abergmeier** [spinnaker/spinnaker#3770]
### Issue Summary:
When trying to connect to our OpenShift Docker registry:
```
hal config provider docker-registry account edit foo-registry --add-repository foo/bar -d
```
I get
```
com.netflix.spinnaker.halyard.cli.services.v1.ExpectedDaemonFailureException: Failed to edit account foo-registry for provider dockerRegistry.
	at com.netflix.spinnaker.halyard.cli.services.v1.OperationHandler.get(OperationHandler.java:45)
	at com.netflix.spinnaker.halyard.cli.command.v1.config.providers.account.AbstractEditAccountCommand.executeThis(AbstractEditAccountCommand.java:179)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.safeExecuteThis(NestableCommand.java:201)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:149)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:152)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:152)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:152)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:152)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:152)
	at com.netflix.spinnaker.halyard.cli.Main.main(Main.java:46)
Caused by: java.lang.Exception: Unable to reach repository: 401 Unauthorized.
	at com.netflix.spinnaker.halyard.core.problem.v1.ProblemSet.throwifSeverityExceeds(ProblemSet.java:102)
	at com.netflix.spinnaker.halyard.core.DaemonResponse$UpdateRequestBuilder.build(DaemonResponse.java:157)
	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48)
	at java.lang.Thread.run(Thread.java:748)
```

Not sure how to debug this any further. Or where I should be able to see the actual http result of the Docker registry.

### Cloud Provider(s):
Kubernetes

### Environment:
OpenShift 3.9+

### Feature Area: 
Provider

**Comment by ethanfrogers** [comment]
@abergmeier did you provide a username/password when you added the registry?

**Comment by abergmeier** [comment]
> did you provide a username/password when you added the registry?

And triple checked that it is correct.

**Comment by ethanfrogers** [comment]
The only other reason I can see that happening is if you didn't supply the address of the Docker registry. It defaults to Dockerhub (`docker.io`).

**Comment by abergmeier** [comment]
The problem was, that I was sending the wrong password.
The OpenShift Docker Registry does not use plain passwords but tokens, that you derive from the OpenShift login. And you need to use these tokens.

**Comment by abergmeier** [comment]
Problem is that the error message was a bit misleading and I did not see the actual response from the Docker registry.

**Comment by ethanfrogers** [comment]
👍 nice catch!
