### ISSUE TITLE
Cannot login to Jenkins

### ISSUE THREAD

**Issue by abergmeier** [spinnaker/spinnaker#3802]
### Issue Summary:
When I try to access Jenkins, I get
```
Caused by: retrofit.RetrofitError: 401 Invalid password/token for user: builder
at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[retrofit-1.9.0.jar:na]
at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[retrofit-1.9.0.jar:na]
at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
at com.sun.proxy.$Proxy90.getProjects(Unknown Source) ~[na:na]
at com.netflix.spinnaker.igor.jenkins.client.JenkinsClient$getProjects.call(Unknown Source) ~[na:na]
```
Not sure yet, how Igor tries to authenticate against Jenkins.

### Cloud Provider(s):
Kubernetes V2

**Comment by abergmeier** [comment]
Not really sure, which ways of authentication Jenkins is supporting.

**Comment by xacaxulu** [comment]
+1
