### ISSUE TITLE
Patch deployment fails: Cannot deserialize instance of com.netflix.spinnaker.clouddriver.kubernetes.v2.description.manifest.KubernetesManifest

### ISSUE THREAD

**Issue by max-rocket-internet** [spinnaker/spinnaker#3810]
### Issue Summary:

A patch deployment stage in a pipeline fails with this error shown in the Spinnaker UI:

```
Exception ( Monitor Patch )
Cannot deserialize instance of com.netflix.spinnaker.clouddriver.kubernetes.v2.description.manifest.KubernetesManifest out of START_ARRAY token at [Source: UNKNOWN; line: -1, column: -1]
```

And here's the clouddriver log output:

```
2019-01-04 10:45:55.889 ERROR 1 --- [ool-6-thread-35] c.n.s.c.o.DefaultOrchestrationProcessor  : java.lang.IllegalArgumentException: Cannot deserialize instance of `com.netflix.spinnaker.clouddriver.kubernetes.v2.description.manifest.KubernetesManifest` out of START_ARRAY token
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3750)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3668)
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.manifest.KubernetesPatchManifestOperation.replaceArtifacts(KubernetesPatchManifestOperation.java:109)
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.manifest.KubernetesPatchManifestOperation.operate(KubernetesPatchManifestOperation.java:88)
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.manifest.KubernetesPatchManifestOperation.operate(KubernetesPatchManifestOperation.java:45)
	at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate.call(Unknown Source)
	at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy:89)
	at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at com.netflix.spinnaker.clouddriver.metrics.TimedCallable$ClosureWrapper.call(TimedCallable.groovy:55)
	at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy:88)
	at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:97)
	at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.netflix.spinnaker.clouddriver.kubernetes.v2.description.manifest.KubernetesManifest` out of START_ARRAY token
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1093)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromEmpty(StdDeserializer.java:600)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:360)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3745)
	... 40 more
```

### Cloud Provider(s):

Kubernetes.

### Environment:

Spinnaker installed by Helm Chart version `1.9.1`.

Here's the container image tags:

```
spin-clouddriver:  gcr.io/spinnaker-marketplace/clouddriver:4.1.0-20181211134536, gcr.io/spinnaker-marketplace/monitoring-daemon:0.10.0-20181207032510,
spin-deck:  gcr.io/spinnaker-marketplace/deck:2.6.0-20181213100452,
spin-echo:  gcr.io/spinnaker-marketplace/echo:2.2.1-20181217192627, gcr.io/spinnaker-marketplace/monitoring-daemon:0.10.0-20181207032510,
spin-front50:  gcr.io/spinnaker-marketplace/front50:0.14.0-20181207134351, gcr.io/spinnaker-marketplace/monitoring-daemon:0.10.0-20181207032510,
spin-gate:  gcr.io/spinnaker-marketplace/gate:1.4.0-20181217192627, gcr.io/spinnaker-marketplace/monitoring-daemon:0.10.0-20181207032510,
spin-igor:  gcr.io/spinnaker-marketplace/igor:1.0.0-20181207134351, gcr.io/spinnaker-marketplace/monitoring-daemon:0.10.0-20181207032510,
spin-orca:  gcr.io/spinnaker-marketplace/orca:2.0.0-20181212160734, gcr.io/spinnaker-marketplace/monitoring-daemon:0.10.0-20181207032510,
spin-rosco:  gcr.io/spinnaker-marketplace/rosco:0.8.1-20181207134351, gcr.io/spinnaker-marketplace/monitoring-daemon:0.10.0-20181207032510,
```

### Feature Area: 

Kuberntes, deployments, etc

### Steps to Reproduce:

Trigger our deployment pipeline and wait for that stage to fail. This pipeline simply patches a deployment with a new docker image tag.

**Comment by lwander** [comment]
Are you using the JSON patch? I believe @maggieneterval fixed this in 1.11: https://github.com/spinnaker/clouddriver/pull/3047

**Comment by max-rocket-internet** [comment]
@lwander I'm not sure, I don't really understand the versioning! I am using docker image `gcr.io/spinnaker-marketplace/clouddriver:4.1.0-20181211134536` but the versioning in that repo looks like `2.xx.xxx`?

**Comment by lwander** [comment]
Good question -- this explains why the versions don't seem to line up: https://www.spinnaker.io/community/faqs/#why-dont-the-versions-used-in-each-subcomponent-in-the-new-top-level-versioned-spinnaker-match-those-in-the-github-releases,

And this explains how the versions are tied together: https://www.spinnaker.io/guides/operator/custom-boms/

In short -- you can check which version of an image is needed at a given release using `hal version bom X.Y.Z`, but I wouldn't recommend running versions of images spanning different releases at once, since we never test this.

**Comment by max-rocket-internet** [comment]
OK so it says this:

```
services:
  clouddriver:
    version: 4.1.0-20181211134536
    commit: 784dbe723ad7b600985d5f9cb6d8442d5b19bc37
```

That commit in clouddriver repo is from 11.12.2018 and that PR from @maggieneterval was merged on 17.10.2018. So my current version doesn't include that fix. So I need to upgrade?

**Comment by lwander** [comment]
Maybe I'm misunderstanding but those dates don't seem to line up -- what exactly was in your patch body?

**Comment by lwander** [comment]
It should, but I think a part of that fix includes the ability to select what kind of patch you are sending, which informs how it's deserialized. What is your patch body?

**Comment by max-rocket-internet** [comment]
> What is your patch body?

Ahh, sorry, I didn't get this question. From `Patch (Manifest) Configuration > Patch Content` It looks like this:

```
- spec:
    template:
      spec:
        containers:
          - image: '${parameters.image_repo}:${parameters.image_tag}'
            imagePullPolicy: Always
            name: app
```

**Comment by teyamagu** [comment]
I have a same problem.

-----
```
$hal version bom
version: 1.11.4
timestamp: '2019-01-05 08:25:23'
services:
  echo:
    version: 2.2.3-20190104153242
    commit: 22a704dc9dcfcea2566b62e231d95982bd387745
  clouddriver:
    version: 4.2.2-20190105032508
    commit: 3f03d3e15cedf7a3de0fee43990ecf374b426b0a
  deck:
    version: 2.6.1-20181220153244
    commit: 599372c294bc5dec56cf32f0f5a429217d58aee3
  fiat:
    version: 1.3.0-20181207134351
    commit: 2e4c3bbfcae27f37fe15d591adee0479d40fe841
  front50:
    version: 0.14.0-20181207134351
    commit: 94ad9540f6b079155ae7a7b36d4dc78635c87943
  gate:
    version: 1.4.0-20181217192627
    commit: b83dea9f35024f18592f1741dcb62b3a7b82c086
  igor:
    version: 1.0.0-20181207134351
    commit: 0b3a637e199ee1ac030a7a7fe7bf44139a41668a
  kayenta:
    version: 0.5.1-20190104141519
    commit: 8a49a32291fc139d4772fdf45efd832c28b7d171
  orca:
    version: 2.1.0-20190104141519
    commit: 3899e7a1018480b2ae338676bf1c9fbf83fc7d2a
  rosco:
    version: 0.8.2-20181221095200
    commit: 0e336fcba0a56dcd93f4692c4cc798b9b887fc7f
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.10.1-20190103032510
    commit: be804036991174052cfe006e39dbbaf6ecc28736
  monitoring-daemon:
    version: 0.10.1-20190103032510
    commit: be804036991174052cfe006e39dbbaf6ecc28736
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
```

**Comment by charlieegan3** [comment]
I have the same versions as teyamagu and am seeing this irrespective of the patch I apply.

**Comment by jcurlier** [comment]
+1 same problem here

**Comment by jcurlier** [comment]
@teyamagu that's great - what did you have in your `Patch Content` ?

**Comment by teyamagu** [comment]
@jcurlier My Patch Content is below. I needed "-" before 1st "spec" when it worked wrong, but didn't need it have when it worked correctly.

```
spec:
  template:
    spec:
      containers:
        - image: hoge
          name: hogeapp
```

**Comment by louisvernon** [comment]
I ran into this issue today, updated the patch stage and started seeing the error above. Comparing the working json to the broken stage I see:
```diff
118,127c127,138
<       "patchBody": {
<         "spec": {
<           "template": {
<             "spec": {
<               "containers": [
<                 {
<                   "image": "${ trigger['payload']['digest']}",
<                   "name": "gateway"
<                 }
<               ]
---
>       "patchBody": [
>         {
>           "spec": {
>             "template": {
>               "spec": {
>                 "containers": [
>                   {
>                     "image": "${parameters[\"image\"]}",
>                     "name": "gateway"
>                   }
>                 ]
>               }
```

I removed the outermost `[]` and the stage started working again.

**Comment by jcurlier** [comment]
Thanks @louisvernon - this works for me too

**Comment by louisvernon** [comment]
OK did a little more digging. Editing just the image line is enough to inject `[]`s around the patchBody block in the pipeline JSON. There is no way to undo this in the GUI, when you come back to the stage in the GUI `spec` is now prefixed with `- ` and there is no way to remove it, you can't save the changes. You have to edit as JSON to fix.

**Comment by lwander** [comment]
Sorry for the wait, I've been out on vacation. 

@maggieneterval could you take a look at this?

**Comment by maggieneterval** [comment]
Same, have also been out on vacation. I will take a look!

**Comment by maggieneterval** [comment]
Thanks so much for investigating and identifying a workaround, @louisvernon, and apologies to all for the regression -- I believe this originated when we added handling for multi-docs in the YAML editor. Will submit a fix shortly!
