### ISSUE TITLE
Manual Judgement Stage failed

### ISSUE THREAD

**Issue by lluu** [spinnaker/spinnaker#3860]
### Issue Summary:
When running a Manual Judgement stage, stage is not executing.  It immediately go into TERMINAL state

### Cloud Provider(s):
AWS

### Environment:
Spinnaker 1.10

### Feature Area: 
Manual Judgement Stage

### Description:
I have two spinnaker swimlanes, running the same exact code.  Manual Judgement stage works on one, but not the other.  The only difference between the two is their external redis cache.  I, however, cleared the redis cache on the problematic swimlane, and manual judgement stage still fails with the same exact stacktrace/error.

### Steps to Reproduce:

Create a new pipeline
Add a Manual Judgement stage
Add a Wait stage, depends on Manual Judgement stage (for testing purposes)
Save pipeline
Invoke pipeline

### Additional Details:
The Maul Judgment stage immediately failed
com.netflix.spinnaker.orca.pipeline.ExecutionRunner$NoSuchStageDefinitionBuilder: No StageDefinitionBuilder implementation for manualJudgment found\n\tat com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.lambda$builderFor$1(DefaultStageDefinitionBuilderFactory.java:43)\n\tat java.util.Optional.orElseThrow(Optional.java:290)\n\tat com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.builderFor(DefaultStageDefinitionBuilderFactory.java:43)\n\tat com.netflix.spinnaker.orca.q.handler.StageBuilderAware$DefaultImpls.builder(StageBuilderAware.kt:28)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.builder(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.plan(StartStageHandler.kt:139)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.access$plan(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:81)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)\n\tat com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:94)\n\tat com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.withAuth(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:80)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:58)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:32)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:67)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.withExecution(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:54)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.withStage(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:65)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)\n\tat com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)\n\tat com.netflix.spinnaker.orca.q.handler.StartStageHandler.invoke(StartStageHandler.kt:48)\n\tat com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47)\n\tat com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n

Orca log shows:

2019-01-16 22:46:28.208 INFO 7495 --- [ scheduler-7] com.netflix.spinnaker.q.QueueProcessor : [] Received message StartStage(executionType=pipeline, executionId=01D1CDGAJWA89VD529T4W9T36X, application=regression, stageId=01D1CDGAJW9V304S96NTYKM3KB)
2019-01-16 22:46:28.211 WARN 7495 --- [ handlers-20] c.n.s.o.e.DefaultExceptionHandler : [] Error occurred during task Manual Judgment
com.netflix.spinnaker.orca.pipeline.ExecutionRunner$NoSuchStageDefinitionBuilder: No StageDefinitionBuilder implementation for manualJudgment found
at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.lambda$builderFor$1(DefaultStageDefinitionBuilderFactory.java:43)
at java.util.Optional.orElseThrow(Optional.java:290)
at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.builderFor(DefaultStageDefinitionBuilderFactory.java:43)
at com.netflix.spinnaker.orca.q.handler.StageBuilderAware$DefaultImpls.builder(StageBuilderAware.kt:28)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler.builder(StartStageHandler.kt:48)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler.plan(StartStageHandler.kt:139)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler.access$plan(StartStageHandler.kt:48)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:81)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:48)
at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)
at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:94)
at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withAuth(StartStageHandler.kt:48)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:80)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:48)
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:58)
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:32)
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:67)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withExecution(StartStageHandler.kt:48)
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:54)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withStage(StartStageHandler.kt:48)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:65)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:48)
at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler.invoke(StartStageHandler.kt:48)
at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47)
at com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
2019-01-16 22:46:28.211 ERROR 7495 --- [ handlers-20] c.n.s.orca.q.handler.StartStageHandler : [] Error running manualJudgment stage for pipeline[01D1CDGAJWA89VD529T4W9T36X]
com.netflix.spinnaker.orca.pipeline.ExecutionRunner$NoSuchStageDefinitionBuilder: No StageDefinitionBuilder implementation for manualJudgment found
at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.lambda$builderFor$1(DefaultStageDefinitionBuilderFactory.java:43)
at java.util.Optional.orElseThrow(Optional.java:290)
at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.builderFor(DefaultStageDefinitionBuilderFactory.java:43)
at com.netflix.spinnaker.orca.q.handler.StageBuilderAware$DefaultImpls.builder(StageBuilderAware.kt:28)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler.builder(StartStageHandler.kt:48)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler.plan(StartStageHandler.kt:139)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler.access$plan(StartStageHandler.kt:48)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:81)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:48)
at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)
at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:94)
at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withAuth(StartStageHandler.kt:48)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:80)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:48)
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:58)
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:32)
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:67)
at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withExecution(StartStageHandler.kt:48)
at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:54)

**Comment by lluu** [comment]
yes, each swimlane has its own microservices.

I tried restarted orca multiple times, that didn't help.

**Comment by lluu** [comment]
i found this issue https://github.com/spinnaker/spinnaker/issues/2845, which appears to be similar and bfarrell resolved it by going to an internal redis..and lwander commented that an overloaded redis causes all sorts of problems ..  so that gave me the idea of perhaps i need to clear redis cache.. but that didn't help..  my redis cache is now tiny..

**Comment by sbwsg** [comment]
The error implies that there is some issue in the way the manual judgement stage is registered.  I have only a very limited understanding of the Spring framework but this seems like some kind of dependency injection problem.

**Comment by lluu** [comment]
ok, i'll pickup these changes, and provide you more info.

**Comment by lluu** [comment]
here's what i got:
2019-01-17 23:05:33.357 ERROR 7218 --- [    handlers-20] c.n.s.orca.q.handler.StartStageHandler   : [] Error running manualJudgment stage for pipeline[01D1F0ZZVXSVWQ3YZJB12SG811]
com.netflix.spinnaker.orca.pipeline.ExecutionRunner$NoSuchStageDefinitionBuilder: No StageDefinitionBuilder implementation for manualJudgment found. Known stage types: acquireLock,releaseLock,restrictExecutionDuringTimeWindow,wait,noop,checkPreconditions,bakeManifest,bake,updatePipeline,pipeline,savePipeline,associateElasticIp,disassociateElasticIp,restoreSnapshot,saveSnapshot,shrinkCluster,rollbackCluster,scaleDownCluster,findImage,disableCluster,findArtifactFromExecution,deleteEntityTags,upsertEntityTags,bulkUpsertEntityTags,deleteScalingPolicy,upsertScalingPolicy,migratePipeline,startAppEngineServerGroup,upsertAppEngineLoadBalancers,stopAppEngineServerGroup,modifyAwsScalingProcess,captureSourceServerGroupCapacity,applySourceServerGroupCapacity,deployManifest,pauseRolloutManifest,deleteManifest,undoRolloutManifest,resumeRolloutManifest,findArtifactsFromResource,patchManifest,scaleManifest,upsertLoadBalancers,deleteLoadBalancer,migrateLoadBalancer,upsertLoadBalancer,deleteService,deployService,upsertImageTags,findImageFromTags,deleteImage,updateLaunchConfig,disableServerGroup,destroyServerGroup,bulkDestroyServerGroup,rollbackServerGroup,enableServerGroup,serverGroupForceCacheRefresh,deleteSecurityGroup,migrateServerGroup,determineTargetServerGroup,createServerGroup,upsertServerGroupTags,cloneServerGroup,resizeServerGroup,registerInstancesWithLoadBalancer,terminateInstanceAndDecrementServerGroup,terminateInstances,deregisterInstancesFromLoadBalancer,rebootInstances,runJob,destroyJob,upsertSecurityGroup,migrateSecurityGroup,modifyScalingProcess,upsertAsgTags,detachInstances,enableInstancesInDiscovery,copyAmazonLoadBalancer,rollingPush,modifyAsg,upsertAsgScheduledActions,upsertAmazonDNS,copySecurityGroup,copyLastAsg,updateSecurityGroupsForServerGroup,disableInstancesInDiscovery,linearDeploy,quickPatch,terminateInstanceAndDecrementAsg,modifyAsgLaunchConfiguration,disableAsg,upsertAmazonLoadBalancer,enableAsg,determineTargetReference,bulkQuickPatch,destroyAsg,deleteAmazonLoadBalancer,deploy,resizeAsg,travis,wercker,script,jenkins,createApplication,updateApplication,deleteProject,upsertProject,upsertApplication,deleteApplication,updatePipelineTemplate,deletePipelineTemplate,createPipelineTemplate,preconfiguredWebhook,webhook
        at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.lambda$builderFor$2(DefaultStageDefinitionBuilderFactory.java:48)
        at java.util.Optional.orElseThrow(Optional.java:290)

**Comment by lluu** [comment]
This is very weird.. because the same exact code (built into an ami) continues to work on the other swimlane.. it shows it found the class.. "implementingClass":"com.netflix.spinnaker.orca.echo.pipeline.ManualJudgmentStage$WaitForManualJudgmentTask". This makes me think it's not the code.. it's the data.. something threw this one off..

**Comment by ajordens** [comment]
Is echo enabled for both of your environments? The Manual Judgment stage is only enabled when echo is and from the stacktrace above it appears to be missing.

**Comment by lluu** [comment]
Geez... that was it.. i never had echo enabled on that env, just turned it on and the Manual Judgment stage is working now.  Is this new in 1.10?  also, should there be any concern with the events generated.. this env is a much heavier used one..  Thx.

**Comment by ajordens** [comment]
To the best of my knowledge, it's been this way for a _long_ time. 

The belief being that a `Manual Judgment` without the ability to notify anyone (because echo is disabled) is somewhat less valuable. Would be a separate conversation as to whether this is still legitimate or worth reconsidering.

I don't know anything about your environment or what notifications you might have set up, generally I wouldn't think having echo in the mix would be concerning.
