### ISSUE TITLE
spinnaker upgrade to 1.13.1 has gate returning 500's

### ISSUE THREAD

**Issue by anishp55** [spinnaker/spinnaker#4241]
### Issue Summary:
I upgraded my spinnaker from 1.13.0 to 1.13.1 in hopes that an issue with the CF clouddriver was addressed.  This resulted in my spinnaker deployment becoming unusable, api endpoints like /applications, /subnets, /firewalls would all return 500's.  rolling back to 1.13.0 solved most issues, but i still cant see the cluster for a AWS resource that was applied through a pipeline.

### Cloud Provider(s):
Amazon

### Description:
upgrade to 1.13.1 made the spinnaker platform un-usable

### Steps to Reproduce:
unknown.  i updated from 1.13.0 to 1.13.1 with 3 CF accounts configured and 1 AWS account.  I can pair w/ someone over slack to troubleshoot the issue in more depth.

### Additional Details:
2019-04-03 18:28:43.460  WARN 1 --- [.0-8084-exec-22] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [com.netflix.spinnaker.gate.services.commands.ServerErrorException: Internal Server Error]
2019-04-03 18:28:43.542  INFO 1 --- [utionHistory-10] c.n.s.g.services.internal.OrcaService    : ---> HTTP GET http://spin-orca.spinnaker:8083/v2/applications/awstesting/pipelines?limit=30&statuses=RUNNING%2CSUSPENDED%2CPAUSED%2CNOT_STARTED&expand=true
2019-04-03 18:28:43.557  INFO 1 --- [utionHistory-10] c.n.s.g.services.internal.OrcaService    : <--- HTTP 200 http://spin-orca.spinnaker:8083/v2/applications/awstesting/pipelines?limit=30&statuses=RUNNING%2CSUSPENDED%2CPAUSED%2CNOT_STARTED&expand=true (15ms)
2019-04-03 18:28:43.564  INFO 1 --- [utionHistory-10] c.n.s.g.services.internal.OrcaService    : ---> HTTP GET http://spin-orca.spinnaker:8083/applications/awstesting/tasks?statuses=RUNNING%2CSUSPENDED%2CNOT_STARTED
2019-04-03 18:28:43.572  INFO 1 --- [utionHistory-10] c.n.s.g.services.internal.OrcaService    : <--- HTTP 200 http://spin-orca.spinnaker:8083/applications/awstesting/tasks?statuses=RUNNING%2CSUSPENDED%2CNOT_STARTED (8ms)
2019-04-03 18:28:43.608  INFO 1 --- [utionHistory-10] c.n.s.g.services.internal.OrcaService    : ---> HTTP GET http://spin-orca.spinnaker:8083/v2/applications/halyard/pipelines?limit=30&statuses=RUNNING%2CSUSPENDED%2CPAUSED%2CNOT_STARTED&expand=true
2019-04-03 18:28:43.624  INFO 1 --- [utionHistory-10] c.n.s.g.services.internal.OrcaService    : <--- HTTP 200 http://spin-orca.spinnaker:8083/v2/applications/halyard/pipelines?limit=30&statuses=RUNNING%2CSUSPENDED%2CPAUSED%2CNOT_STARTED&expand=true (16ms)
2019-04-03 18:28:43.627  INFO 1 --- [0.0-8084-exec-6] c.n.s.g.s.internal.ClouddriverService    : ---> HTTP GET http://spin-clouddriver.spinnaker:7002/applications/halyard/serverGroupManagers
2019-04-03 18:28:43.673  INFO 1 --- [utionHistory-10] c.n.s.g.services.internal.OrcaService    : ---> HTTP GET http://spin-orca.spinnaker:8083/applications/halyard/tasks?statuses=RUNNING%2CSUSPENDED%2CNOT_STARTED
2019-04-03 18:28:43.679  INFO 1 --- [utionHistory-10] c.n.s.g.services.internal.OrcaService    : <--- HTTP 200 http://spin-orca.spinnaker:8083/applications/halyard/tasks?statuses=RUNNING%2CSUSPENDED%2CNOT_STARTED (4ms)
2019-04-03 18:28:43.728  INFO 1 --- [trix-clusters-8] c.n.s.g.s.internal.ClouddriverService    : ---> HTTP GET http://spin-clouddriver.spinnaker:7002/applications/halyard/clusters
2019-04-03 18:28:48.152  INFO 1 --- [TaskScheduler-8] c.n.s.g.s.internal.ClouddriverService    : ---- ERROR http://spin-clouddriver.spinnaker:7002/credentials?expand=true
2019-04-03 18:28:48.152  INFO 1 --- [TaskScheduler-8] c.n.s.g.s.internal.ClouddriverService    : java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:101)
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:137)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:283)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.netflix.spinnaker.okhttp.OkHttpMetricsInterceptor.intercept(OkHttpMetricsInterceptor.java:44)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at retrofit.client.OkClient.execute(OkClient.java:53)
	at com.netflix.spinnaker.gate.retrofit.EurekaOkClient.super$2$execute(EurekaOkClient.groovy)
	at sun.reflect.GeneratedMethodAccessor141.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
	at com.netflix.spinnaker.gate.retrofit.EurekaOkClient.execute(EurekaOkClient.groovy:82)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy95.getAccountDetails(Unknown Source)
	at com.netflix.spinnaker.gate.services.internal.ClouddriverService$getAccountDetails.call(Unknown Source)
	at com.netflix.spinnaker.gate.services.DefaultProviderLookupService.refreshCache(DefaultProviderLookupService.groovy:56)
	at sun.reflect.GeneratedMethodAccessor231.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 2019-04-03 18:28:48.152  INFO 1 --- [TaskScheduler-8] c.n.s.g.s.internal.ClouddriverService    : ---- END ERROR
2019-04-03 18:28:48.153 ERROR 1 --- [TaskScheduler-8] c.n.s.g.s.DefaultProviderLookupService   : Unable to refresh account details cache, reason: connect timed out

![image](https://user-images.githubusercontent.com/395692/55505454-22d7fa80-5621-11e9-890f-333c91dc37d3.png)

---

**Comment by anishp55** [comment]
i cleared my cache after the downgrade, and upgraded again and cleared the cache again.
this seemed to resolve the issue.

**Comment by sbwsg** [comment]
Thankyou for updating with the resolution!
