### ISSUE TITLE
Red/Black rollback deployment fails in AWS ECS cloud provider

### ISSUE THREAD

**Issue by abhijaju** [spinnaker/spinnaker#4330]
### Issue Summary:
Not able to do a Rollback in Deploy type stage using Red/Black deployment strategy when using AWS ECS as cloud provider.

### Cloud Provider(s):
AWS ECS

### Environment:
localdebian mode running on a standalone AWS EC2 instance

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Red/black deployment strategy

### Description:
Not able to do a Rollback in Deploy type stage using Red/Black deployment strategy when using AWS ECS as cloud provider.
I was expecting that when a new server group failed to deploy with healthy status checks, it should disable the new server group and enable to old server group with the same capacity as it was prior to the deployment stage.

### Steps to Reproduce:
You can deploy any hello-world docker image to ECS and check if Red/Black deployments are being handled properly.

### Additional Details:

<img width="1050" alt="Screenshot 2019-04-24 at 3 19 23 PM" src="https://user-images.githubusercontent.com/2181348/56653962-839ca500-66ac-11e9-91a6-302b8cbfc6de.png">

**Comment by clareliguori** [comment]
@spinnakerbot add-label provider/ecs

**Comment by clareliguori** [comment]
Hi @abhijaju, can you provide some more details for reproducing this issue?
* What version of Spinnaker are you running?
* Do you have any additional logs generated for this error, for example from clouddriver or orca?
* What was failing in your ECS service when you deployed?  LB health checks failing, or failure to launch containers, etc?
* An anonymized output (remove account numbers, etc) of your pipeline JSON would be helpful to see how you set up your stage configuration.  In the Configure Pipeline view, Pipeline Actions -> Edit as JSON

**Comment by clareliguori** [comment]
I was able to reproduce this:
```
ERROR 27385 --- [    handlers-20] c.n.s.orca.q.handler.RunTaskHandler      : [] Error running DetermineRollbackCandidatesTask for pipeline[01DB0X6SB7T49SW8ZWR1A8TT1Q]
java.lang.NullPointerException: null value in entry: image=null
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34)
        at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:175)
        at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:252)
        at com.netflix.spinnaker.orca.clouddriver.tasks.cluster.DetermineRollbackCandidatesTask.execute(DetermineRollbackCandidatesTask.java:220)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:100)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:56)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withLoggingContext(RunTaskHandler.kt:316)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$withLoggingContext(RunTaskHandler.kt:56)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:99)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:56)
        at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)
        at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:97)
        at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:50)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:56)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:98)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:56)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:182)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:56)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:49)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:33)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:59)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:33)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:68)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:56)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:55)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:56)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:42)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:56)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:175)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:69)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:56)
        at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
        at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:56)
        at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:58)
        at com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by abhijaju** [comment]
@clareliguori thank you for looking into this
