### ISSUE TITLE
pipelineConfigs return 500 via deck, 200 via curl

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spinnaker#4359]
### Issue Summary:

When trying to configure a project in the UI, deck seems to request pipelineConfigs for all of the applications in the project (`/applications/<app-name>/pipelineConfigs`), and some of them return a 500. However, when using Chrome's "copy as cURL" feature and running the curl locally, 200 is returned.

### Cloud Provider(s):

GKE, Kubernetes V2

### Environment:

Spinnaker 1.13.1 on GKE

### Description:

Some of the applications have pipelines, and some of them don't. Some of them have never had anything deployed through them. The applications vary in the type of deployments they deploy (ex: Job, Deployment, ReplicaSet, etc.)

### Additional Details:

~~May be related to #4358, but doesn't appear to on first glance, but it is the same instance.~~

One interesting find: if you curl several of these at the same time, 500s can be reproduced.

**Comment by maggieneterval** [comment]
Hey Miles! Would you mind checking the Gate and Front50 logs from when you're getting the 500s?

**Comment by WillBeebe** [comment]
gate exception, for [this](https://github.com/spinnaker/gate/blob/master/gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/ApplicationService.groovy#L126) method

```com.netflix.spinnaker.gate.services.commands.ServerErrorException: Internal Server Error
	at com.netflix.spinnaker.gate.services.commands.AbstractHystrixCommand.handleDownstreamException(AbstractHystrixCommand.groovy:110) ~[gate-core.jar:na]
	at com.netflix.spinnaker.gate.services.commands.AbstractHystrixCommand.execute(AbstractHystrixCommand.groovy:71) ~[gate-core.jar:na]
	at com.netflix.spinnaker.gate.services.ApplicationService.getPipelineConfigsForApplication(ApplicationService.groovy:127) ~[gate-web.jar:na]
	at com.netflix.spinnaker.gate.services.ApplicationService$getPipelineConfigsForApplication.call(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.gate.controllers.ApplicationController.getPipelineConfigsForApplication(ApplicationController.groovy:141) ~[gate-web.jar:na]
	at sun.reflect.GeneratedMethodAccessor208.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849) ~[spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760) ~[spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.34.jar:8.5.34]```

**Comment by WillBeebe** [comment]
front logs

```
2019-05-09 10:17:54.921  WARN 1 --- [0.0-8080-exec-9] .m.m.a.ExceptionHandlerExceptionResolver : Failed to invoke @ExceptionHandler method: public void com.netflix.spinnaker.kork.web.exceptions.GenericExceptionHandlers.handleException(java.lang.Exception,javax.servlet.http.HttpServletResponse,javax.servlet.http.HttpServletRequest) throws java.io.IOException

java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
        at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:456) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
        at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:120) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
        at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:120) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
        at org.springframework.security.web.util.OnCommittedResponseWrapper.sendError(OnCommittedResponseWrapper.java:119) ~[spring-security-web-4.2.9.RELEASE.jar:4.2.9.RELEASE]
        at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:120) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
        at org.springframework.security.web.util.OnCommittedResponseWrapper.sendError(OnCommittedResponseWrapper.java:119) ~[spring-security-web-4.2.9.RELEASE.jar:4.2.9.RELEASE]
        at com.netflix.spinnaker.kork.web.exceptions.GenericExceptionHandlers.handleException(GenericExceptionHandlers.java:124) ~[kork-web-3.9.2.jar:3.9.2]
        at sun.reflect.GeneratedMethodAccessor347.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.20.RELEASE.jar:4.3.20.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.20.RELEASE.jar:4.3.20.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:381) ~[spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
        at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:59) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
        at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:132) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
        at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:76) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1222) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1034) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [tomcat-embed-core-8.5.34.jar:8.5.34]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.34.jar:8.5.34]
```

**Comment by maggieneterval** [comment]
Hey there @WillBeebe, I haven't been able to reproduce this locally, about how many applications and how many pipelines per application are you working with? And does this issue make the Configure Project modal totally unusable or do the available pipelines just fail to populate?

One possible alternative to requesting each application's pipelines immediately when the Configure Project modal is opened is to only request them as needed, i.e. only for each application already selected in the Pipelines section, and then if a new application is selected, request its pipelines just in time to populate the dropdown - cc @christopherthielen for thoughts since he built the Configure Project modal, also curious if you've seen these types of 500s at Netflix when many pipeline configs are being requested simultaneously?

**Comment by milesmatthias** [comment]
This project has 15 applications, 4-7 pipelines per application.

It makes the configure project modal totally unusable. The progress bar just hangs.

**Comment by christopherthielen** [comment]
> if you've seen these types of 500s at Netflix when many pipeline configs are being requested simultaneously?

Nope, haven't seen this before.  We definitely have apps of all those different types as well.

**Comment by christopherthielen** [comment]
I would like to better understand how to reproduce this 500 error

**Comment by maggieneterval** [comment]
Hey @christopherthielen, I was never actually able to reproduce this error so I don't have any pointers, but figured the change to request the configs just in time couldn't hurt and hopefully resolves this :crossed_fingers:

**Comment by milesmatthias** [comment]
We were able to reproduce it with a script that runs a bunch of curl commands in parallel.

**Comment by milesmatthias** [comment]
Following up here for the public -- this did actually fix the issue, so thanks a bunch @maggieneterval and @christopherthielen 👏
