### ISSUE TITLE
Orca redis error message is incorrect

### ISSUE THREAD

**Issue by milesmatthias** [spinnaker/spinnaker#4375]
### Issue Summary:

If you put an unreachable hostname in `~/.hal/config/default/service-settings/redis.yml`, Orca will complain the redis hostname is null, when in fact it's present, but unreachable.

Exact error: `java.lang.IllegalArgumentException: hostname can't be null`

### Cloud Provider(s):

GKE

### Environment:

Halyard 1.18.0
Spinnaker 1.13.1

### Steps to Reproduce:

1. Put an unreachable hostname in `redis.yml` and do a `hal deploy apply`

**Comment by ezimanyi** [comment]
@milesmatthias : Where are you seeing this error?  Is this in the orca logs?

I just tried this on 1.13.1 and got a long stacktrace ending in:
```
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
        at redis.clients.jedis.Connection.connect(Connection.java:207)
        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
        at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767)
        at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
        at redis.clients.util.Pool.getResource(Pool.java:49)
        ... 81 common frames omitted
```
When I put a non-existent host I get:
```
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.UnknownHostException: [host-name]
```
I must not be reproducing exactly what led to the incorrect error message in your case.  What fields are you setting in `redis.yml`?  I'm setting the two documented [here](https://www.spinnaker.io/setup/productionize/caching/externalize-redis/#configure-a-spinnaker-wide-redis):
```
overrideBaseUrl: $REDIS_ENDPOINT
skipLifeCycleManagement: true
```

**Comment by milesmatthias** [comment]
Closing this as it was a race condition in our configuration code that was actually producing some null redis hostname values, sorry about that!
