### ISSUE TITLE
fail to create pipeline template

### ISSUE THREAD

**Issue by lnformer** [spinnaker/spinnaker#4408]
### Issue Summary:
I have tried to create pipeline template which I copied from here https://www.spinnaker.io/reference/pipeline/templates/
and applied with
```
spin pt save -f ./a.json
Pipeline template save succeeded
```
but then I list my templates and I get an empty list
```
spin pt ls
```

### Cloud Provider(s):
K8s
AWS

### Environment:
spinnaker 1.13.6
Hal 1.16.0-20190222154056
install with the helm chart

### Additional Details:
I see this error in the orca log
```
2019-05-15 10:57:19.568 ERROR 1 --- [    handlers-17] com.netflix.spinnaker.q.QueueProcessor   : [] Unhandled throwable from CancelStage(executionType=orchestration, executionId=01DAXJ1QDSV0NV3J2DASCY4VC0, application=global, stageId=01DAXJ1QDSVTZ1QYAXRMKQNKNH)
com.netflix.spinnaker.orca.pipeline.ExecutionRunner$NoSuchStageDefinitionBuilder: No StageDefinitionBuilder implementation for createV2PipelineTemplate found.  Known stage types: acquireLock,applySourceServerGroupCapacity,bake,bakeManifest,bulkDestroyServerGroup,bulkQuickPatch,bulkUpsertEntityTags,captureSourceServerGroupCapacity,checkPreconditions,cloneServerGroup,copyAmazonLoadBalancer,copyLastAsg,copySecurityGroup,createApplication,createServerGroup,deleteAmazonLoadBalancer,deleteApplication,deleteDeliveryConfig,deleteEntityTags,deleteImage,deleteLoadBalancer,deleteManifest,deleteProject,deleteScalingPolicy,deleteSecurityGroup,deploy,deployCloudFormation,deployManifest,deployService,deregisterInstancesFromLoadBalancer,destroyAsg,destroyJob,destroyServerGroup,destroyService,detachInstances,determineTargetReference,determineTargetServerGroup,disableAsg,disableCluster,disableInstancesInDiscovery,disableManifest,disableServerGroup,enableAsg,enableInstancesInDiscovery,enableManifest,enableServerGroup,evaluateVariables,findArtifactFromExecution,findArtifactsFromResource,findImage,findImageFromTags,jenkins,jira,linearDeploy,manualJudgment,mapLoadBalancers,migrateLoadBalancer,migratePipeline,migrateSecurityGroup,migrateServerGroup,modifyAsg,modifyAsgLaunchConfiguration,modifyAwsScalingProcess,modifyGceAutoscalingPolicy,modifyScalingProcess,noop,pageApplicationOwner,patchManifest,pauseRolloutManifest,pipeline,preconfiguredJob,preconfiguredWebhook,quickPatch,rebootInstances,registerInstancesWithLoadBalancer,releaseLock,reorderPipelines,resizeAsg,resizeServerGroup,restoreSnapshot,restrictExecutionDuringTimeWindow,resumeRolloutManifest,rollbackCluster,rollbackServerGroup,rollingPush,runJob,savePipeline,savePipelinesFromArtifact,saveSnapshot,scaleDownCluster,scaleManifest,script,serverGroupForceCacheRefresh,shareService,shrinkCluster,startAppEngineServerGroup,stopAppEngineServerGroup,terminateInstanceAndDecrementAsg,terminateInstanceAndDecrementServerGroup,terminateInstances,travis,undoRolloutManifest,unmapLoadBalancers,unshareService,updateApplication,updateLaunchConfig,updatePipeline,updateSecurityGroupsForServerGroup,upsertAmazonDNS,upsertAmazonLoadBalancer,upsertAppEngineLoadBalancers,upsertApplication,upsertAsgScheduledActions,upsertAsgTags,upsertDeliveryConfig,upsertEntityTags,upsertImageTags,upsertLoadBalancer,upsertLoadBalancers,upsertProject,upsertScalingPolicy,upsertSecurityGroup,upsertServerGroupTags,wait,waitUntil,webhook,wercker
        at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.lambda$builderFor$2(DefaultStageDefinitionBuilderFactory.java:48)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.netflix.spinnaker.orca.pipeline.DefaultStageDefinitionBuilderFactory.builderFor(DefaultStageDefinitionBuilderFactory.java:46)
        at com.netflix.spinnaker.orca.q.handler.StageBuilderAware$DefaultImpls.builder(StageBuilderAware.kt:28)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler.builder(CancelStageHandler.kt:34)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler$handle$1.invoke(CancelStageHandler.kt:79)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler$handle$1.invoke(CancelStageHandler.kt:34)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:59)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:33)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:68)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler.withExecution(CancelStageHandler.kt:34)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:55)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler.withStage(CancelStageHandler.kt:34)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler.handle(CancelStageHandler.kt:44)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler.handle(CancelStageHandler.kt:34)
        at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
        at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
        at com.netflix.spinnaker.orca.q.handler.CancelStageHandler.invoke(CancelStageHandler.kt:34)
        at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47)
        at com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by lnformer** [comment]
the issue was that the pipeline templates feature was off,  but
and I have enabled it using:
```
hal config features edit --pipeline-templates true
hal deploy apply
```
the misleading part is the hal config command always returned
```
templatesEnabled: true
```
