### ISSUE TITLE
Deploy stage stuck at Waiting for 1 instance to appear healthy

### ISSUE THREAD

**Issue by abhijaju** [spinnaker/spinnaker#4466]
### Issue Summary:
I’ve been using Spinnaker for last 1 month for ECS deployments and it has been working fine until now. We have two AWS accounts, one for Staging and one for Production.

I’ve been using spinnaker for deploying services in our Staging account and it’s working perfectly and as expected. But when we’re trying to deploy the same service in our Production AWS account I’m facing the following problem:
The deploy step is stuck at *Waiting for 1 instance to appear healthy*, but the same deployment is working fine in Staging account.

Just to mention here that our Staging account doesn’t have so many resources while on the other hand our Production account is running 7500+ ECS tasks on 3000+ AWS instances with 20+ Load balancers.

After further looking into Clouddriver logs, it seems that clouddriver is getting throttled by AWS APIs for Elastic Load Balancing (same is confirmed after looking into CloudTrail logs), so then we implemented API rate limiting as mentioned in this link: https://docs.armory.io/spinnaker-install-admin-guides/rate-limit/

Now, after implementing the rate limiting, the overall response time **is delayed** but it is still stuck at *com.netflix.spinnaker.orca.clouddriver.tasks.instance.WaitForUpInstancesTask*

```
May 30 15:46:59 ip-172-16-13-6 orca[21135]: 2019-05-30 15:46:59.308  INFO 21135 --- [    handlers-20] c.n.s.orca.clouddriver.OortService       : [anonymous] ---> HTTP GET http://localhost:7002/serverGroups/ecs-production/ap-south-1/abhijajutesting-v000
May 30 15:46:59 ip-172-16-13-6 clouddriver[21108]: 2019-05-30 15:46:59.539  INFO 21108 --- [0.1-7002-exec-8] c.n.s.c.e.p.v.EcsServerClusterProvider   : No ECS Server Groups were found with the name abhijajutesting-v000
```
the above gets resolved after couple of minutes.

I can see two errors in the Clouddriver logs:

Error type 1:
```
May 30 15:47:06 ip-172-16-13-6 clouddriver[21108]: 2019-05-30 15:47:06.147  WARN 21108 --- [utionAction-278] c.n.s.c.a.p.agent.ClusterCachingAgent    : Failed to cache Silverleaf EC2 Autoscaling in aws-production/ap-south-1
May 30 15:47:06 ip-172-16-13-6 clouddriver[21108]: java.lang.NullPointerException: null
```
full stack trace of the same error from Kubernetes environment:
```
2019-05-30 16:35:00.544  WARN 1 --- [ecutionAction-7] c.n.s.c.a.p.agent.ClusterCachingAgent    : Failed to cache Silverleaf EC2 Autoscaling in ecs-production/ap-south-1

java.lang.NullPointerException: null
	at com.netflix.spinnaker.clouddriver.aws.data.Keys.getApplicationKey(Keys.groovy:186) ~[clouddriver-aws.jar:na]
	at com.netflix.spinnaker.clouddriver.aws.data.Keys$getApplicationKey$9.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.6.jar:2.5.6]
	at com.netflix.spinnaker.clouddriver.aws.data.Keys$getApplicationKey$9.call(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.clouddriver.aws.provider.agent.ClusterCachingAgent$AsgData.<init>(ClusterCachingAgent.groovy:724) ~[clouddriver-aws.jar:na]
	at sun.reflect.GeneratedConstructorAccessor150.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_212]
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80) ~[groovy-2.5.6.jar:2.5.6]
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105) ~[groovy-2.5.6.jar:2.5.6]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59) ~[groovy-2.5.6.jar:2.5.6]
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:110) ~[groovy-2.5.6.jar:2.5.6]
	at com.netflix.spinnaker.clouddriver.aws.provider.agent.ClusterCachingAgent.buildCacheResult(ClusterCachingAgent.groovy:516) ~[clouddriver-aws.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) ~[groovy-2.5.6.jar:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190) ~[groovy-2.5.6.jar:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58) ~[groovy-2.5.6.jar:2.5.6]
	at com.netflix.spinnaker.clouddriver.aws.provider.agent.ClusterCachingAgent.loadData(ClusterCachingAgent.groovy:436) ~[clouddriver-aws.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:85) [cats-core.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:75) [cats-core.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:335) [cats-redis.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:305) [cats-redis.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
```

Error type 2:
```
May 30 15:49:52 ip-172-16-13-6 clouddriver[21108]: 2019-05-30 15:49:52.684  WARN 21108 --- [utionAction-127] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.ecs.provider.EcsProvider:ecs-production/ap-south-1/TaskHealthCachingAgent completed with one or more failures
May 30 15:49:52 ip-172-16-13-6 clouddriver[21108]: java.lang.NullPointerException: null
```
full stack trace from Kubernetes environment:
```
2019-05-30 16:35:31.934  WARN 1 --- [cutionAction-19] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.ecs.provider.EcsProvider:ecs-production/ap-south-1/TaskHealthCachingAgent completed with one or more failures

java.lang.NullPointerException: null
	at com.netflix.spinnaker.clouddriver.ecs.provider.agent.TaskHealthCachingAgent.inferHealthNetworkBindedContainer(TaskHealthCachingAgent.java:244) ~[clouddriver-ecs.jar:na]
	at com.netflix.spinnaker.clouddriver.ecs.provider.agent.TaskHealthCachingAgent.getItems(TaskHealthCachingAgent.java:144) ~[clouddriver-ecs.jar:na]
	at com.netflix.spinnaker.clouddriver.ecs.provider.agent.AbstractEcsCachingAgent.loadData(AbstractEcsCachingAgent.java:98) ~[clouddriver-ecs.jar:na]
	at com.netflix.spinnaker.clouddriver.ecs.provider.agent.TaskHealthCachingAgent.loadData(TaskHealthCachingAgent.java:63) ~[clouddriver-ecs.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:85) ~[cats-core.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:75) ~[cats-core.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:335) ~[cats-redis.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:305) ~[cats-redis.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
```

I believe the latter error is the one causing the deploy stage to be stuck at waiting for instances to be healthy.

I’ve been stuck at this for more than a week now and I’ve tried every other approach that I can think of to mitigate this.
Kindly help me with this.

<img width="702" alt="Screenshot 2019-05-30 at 9 23 11 PM" src="https://user-images.githubusercontent.com/2181348/58646870-f0e2cc00-8323-11e9-86c0-60a1b35d2aa5.png">

### Cloud Provider(s):
AWS, ECS

### Environment:
Both localdebian and Kubernetes manifest based

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
clouddriver

**Comment by abhijaju** [comment]
@clareliguori kindly look into this

**Comment by abhijaju** [comment]
@jkschneider please take a look

**Comment by clareliguori** [comment]
```
java.lang.NullPointerException: null
	at com.netflix.spinnaker.clouddriver.ecs.provider.agent.TaskHealthCachingAgent.inferHealthNetworkBindedContainer(TaskHealthCachingAgent.java:244) ~[clouddriver-ecs.jar:na]
```

Code where NPE is happening, containerInstance must be null here:
https://github.com/spinnaker/clouddriver/blob/release-1.14.x/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java#L244

Must be coming back from the cache as null:
https://github.com/spinnaker/clouddriver/blob/release-1.14.x/clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/TaskHealthCachingAgent.java#L120-L121
