### ISSUE TITLE
Clouddriver Kubernetes V2 Provider Fails Getting Pod Metrics

### ISSUE THREAD

**Issue by JadCham** [spinnaker/spinnaker#4540]
### Issue Summary:
Clouddriver is throwing an exception trying to parse the output the output of `kubectl top pods` 

### Cloud Provider(s):

Kubernetes V2 Provider

### Environment:

Spinnaker 1.14.4

### Feature Area:
Clouddriver

### Description:

```
2019-06-18 07:14:42.804  WARN 1 --- [tionAction-9953] c.n.s.c.k.v2.op.job.KubectlJobExecutor   : Entry [alertmanager-prometheus-operator-alertmanager-0, 1m, 13Mi] does not match column width of [POD, NAME, CPU(cores), MEMORY(bytes)], skipping
2019-06-18 07:14:42.805  WARN 1 --- [tionAction-9953] c.n.s.c.cache.LoggingInstrumentation     : kubernetes:test/KubernetesMetricCachingAgent[2/5] completed with one or more failures

com.netflix.spinnaker.clouddriver.kubernetes.v2.op.job.KubectlJobExecutor$KubectlException: Failure running top on [pod]: null
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.security.KubernetesV2Credentials.runAndRecordMetrics(KubernetesV2Credentials.java:551) ~[clouddriver-kubernetes.jar:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.security.KubernetesV2Credentials.runAndRecordMetrics(KubernetesV2Credentials.java:510) ~[clouddriver-kubernetes.jar:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.security.KubernetesV2Credentials.topPod(KubernetesV2Credentials.java:430) ~[clouddriver-kubernetes.jar:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.caching.agent.KubernetesMetricCachingAgent.lambda$loadData$1(KubernetesMetricCachingAgent.java:78) ~[clouddriver-kubernetes.jar:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_212]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_212]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_212]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_212]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747) ~[na:1.8.0_212]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721) ~[na:1.8.0_212]
	at java.util.stream.AbstractTask.compute(AbstractTask.java:316) ~[na:1.8.0_212]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[na:1.8.0_212]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_212]
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870) ~[na:1.8.0_212]
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467) ~[na:1.8.0_212]
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324) ~[na:1.8.0_212]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405) ~[na:1.8.0_212]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[na:1.8.0_212]
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714) ~[na:1.8.0_212]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:1.8.0_212]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_212]
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.caching.agent.KubernetesMetricCachingAgent.loadData(KubernetesMetricCachingAgent.java:97) ~[clouddriver-kubernetes.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:85) ~[cats-core.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:75) ~[cats-core.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:335) ~[cats-redis.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:305) ~[cats-redis.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
Caused by: java.lang.ArrayIndexOutOfBoundsException: null
```

### Steps to Reproduce:

This issue started happening after using [k8s-prometheus-adapter](https://github.com/DirectXMan12/k8s-prometheus-adapter) to expose `/apis/metrics.k8s.io/v1beta1` metrics.

The Output of `kubectl top pods` looks fine to me:
```
➜  ~ k top pods
NAME   CPU(cores)   MEMORY(bytes)
test-service-deployment-74fbb7f59b-5xltg           0m                 6Mi
test-service-deployment-74fbb7f59b-4bdzv         4m                 38Mi
```

---

**Comment by neelimamanubolu** [comment]
Hi @JadCham ... I have started working on this.

**Comment by neelimamanubolu** [comment]
Hi @JadCham ..
Kindly let me know when u r not able to get  Pod Metrics.. whether setting up the spinnaker, creation or execution of pipeline... pls confirm the details.

**Comment by JadCham** [comment]
I found the issue causing the exception in Spinnaker. It's an inconsistency between how `prometheus-adapter` returns metrics vs `metrics-server`. I don't think this should be fixed in Spinnaker.
