### ISSUE TITLE
SqlCache cannot cache CRDs containing disallowed MySQL characters

### ISSUE THREAD

**Issue by perek** [spinnaker/spinnaker#4591]
### Issue Summary:
All primitive kinds in kubernetes are valid mysql table names as they do not contain "." as a separator. However CRDs do not place such a restriction on the naming, one of the most common cases is the Prometheus kinds `ServiceMonitor.monitoring.coreos.com`. This causes the SQL cache to be unable to create a cats table for this kind, and breaks cache retrieval as well.

### Cloud Provider(s):
CloudSQL

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
CloudDriver/Cats/Sql

### Description:
The SqlCache provider does not handle disallowed characters when building the cache table name. This causes a SqlException, and breaks subsequent cache requests for this kind. I would propose swapping `.` -> `_` to resolve the error.

### Steps to Reproduce:
1.) Onboard a kubernetes cluster with Prometheus installled
2.) Enable SQL caching
3.) Look for errors in Caching agent, as well as the api.

### Additional Details:
Here are some example stack traces/exceptions

```
c.n.spinnaker.cats.sql.cache.SqlCache : Error creating tables for type ServiceMonitor.monitoring.coreos.com
```
```
org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [CREATE TABLE IF NOT EXISTS cats_v1_ServiceMonitor.monitoring.coreos.com LIKE cats_v1_resource_template -- agentClass: my-k8s-account/KubernetesUnregisteredCustomResourceCachingAgent[1/1] putCacheResult]; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.coreos.com LIKE cats_v1_resource_template -- agentClass: my-k8s-account/Kuberne' at line 1 at org.jooq_3.9.6.MYSQL.debug(Unknown Source) ~[na:na] at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:93) ~[spring-jdbc-5.1.6.RELEASE.jar:5.1.6.RELEASE] at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.1.6.RELEASE.jar:5.1.6.RELEASE] at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-5.1.6.RELEASE.jar:5.1.6.RELEASE] at com.netflix.spinnaker.kork.sql.JooqToSpringExceptionTransformer.exception(JooqToSpringExceptionTransformer.kt:32) ~[kork-sql-5.2.6.jar:5.2.6] at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:245) ~[jooq-3.9.6.jar:na] at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:365) ~[jooq-3.9.6.jar:na] at org.jooq.impl.DefaultDSLContext.execute(DefaultDSLContext.java:964) ~[jooq-3.9.6.jar:na] at com.netflix.spinnaker.cats.sql.cache.SqlCache$createTables$1.invoke(SqlCache.kt:846) ~[cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.cache.SqlCache$createTables$1.invoke(SqlCache.kt:48) ~[cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.cache.SqlCacheKt$sam$java_util_function_Supplier$0.get(SqlCache.kt) ~[cats-sql.jar:na] at io.github.resilience4j.retry.Retry.lambda$decorateSupplier$1(Retry.java:225) ~[resilience4j-retry-0.13.2.jar:0.13.2] at io.vavr.control.Try.of(Try.java:75) ~[vavr-0.10.0.jar:na] at io.vavr.control.Try.ofSupplier(Try.java:92) ~[vavr-0.10.0.jar:na] at com.netflix.spinnaker.cats.sql.cache.SqlCache.withRetry(SqlCache.kt:1487) [cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.cache.SqlCache.createTables(SqlCache.kt:845) [cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.cache.SqlCache.mergeAll(SqlCache.kt:131) [cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.SqlProviderCache.cacheDataType(SqlProviderCache.kt:330) [cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.SqlProviderCache.cacheDataType(SqlProviderCache.kt:307) [cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.SqlProviderCache.putCacheResult(SqlProviderCache.kt:215) [cats-sql.jar:na] at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.storeAgentResult(CachingAgent.java:136) [cats-core.jar:na] at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:78) [cats-core.jar:na] at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:335) [cats-redis.jar:na] at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:305) [cats-redis.jar:na] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_212] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_212] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212] at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212] Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.coreos.com LIKE cats_v1_resource_template -- agentClass: my-k8s-account/Kuberne' at line 1 at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.15.jar:8.0.15] at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.15.jar:8.0.15] at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.15.jar:8.0.15] at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:970) ~[mysql-connector-java-8.0.15.jar:8.0.15] at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:387) ~[mysql-connector-java-8.0.15.jar:8.0.15] at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.2.0.jar:na] at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.2.0.jar:na] at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:195) ~[jooq-3.9.6.jar:na] at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:432) ~[jooq-3.9.6.jar:na] at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350) ~[jooq-3.9.6.jar:na]
```

```
org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [select body_hash, id from cats_v1_ServiceMonitor.monitoring.coreos.com where agent = ? -- agentClass: my-k8s-account/KubernetesUnregisteredCustomResourceCachingAgent[1/1] putCacheResult]; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.coreos.com where agent = 'my-k8s-account/KubernetesUnregisteredCustomResourceCa' at line 1 at org.jooq_3.9.6.MYSQL.debug(Unknown Source) ~[na:na] at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:93) ~[spring-jdbc-5.1.6.RELEASE.jar:5.1.6.RELEASE] at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.1.6.RELEASE.jar:5.1.6.RELEASE] at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-5.1.6.RELEASE.jar:5.1.6.RELEASE] at com.netflix.spinnaker.kork.sql.JooqToSpringExceptionTransformer.exception(JooqToSpringExceptionTransformer.kt:32) ~[kork-sql-5.2.6.jar:5.2.6] at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:245) ~[jooq-3.9.6.jar:na] at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:365) ~[jooq-3.9.6.jar:na] at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:315) ~[jooq-3.9.6.jar:na] at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2708) ~[jooq-3.9.6.jar:na] at com.netflix.spinnaker.cats.sql.cache.SqlCache$getHashIds$1.invoke(SqlCache.kt:942) ~[cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.cache.SqlCache$getHashIds$1.invoke(SqlCache.kt:48) ~[cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.cache.SqlCacheKt$sam$java_util_function_Supplier$0.get(SqlCache.kt) ~[cats-sql.jar:na] at io.github.resilience4j.retry.Retry.lambda$decorateSupplier$1(Retry.java:225) ~[resilience4j-retry-0.13.2.jar:0.13.2] at io.vavr.control.Try.of(Try.java:75) ~[vavr-0.10.0.jar:na] at io.vavr.control.Try.ofSupplier(Try.java:92) ~[vavr-0.10.0.jar:na] at com.netflix.spinnaker.cats.sql.cache.SqlCache.withRetry(SqlCache.kt:1498) ~[cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.cache.SqlCache.getHashIds(SqlCache.kt:935) ~[cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.cache.SqlCache.storeAuthoritative(SqlCache.kt:504) ~[cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.cache.SqlCache.mergeAll(SqlCache.kt:150) ~[cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.SqlProviderCache.cacheDataType(SqlProviderCache.kt:330) ~[cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.SqlProviderCache.cacheDataType(SqlProviderCache.kt:307) ~[cats-sql.jar:na] at com.netflix.spinnaker.cats.sql.SqlProviderCache.putCacheResult(SqlProviderCache.kt:215) ~[cats-sql.jar:na] at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.storeAgentResult(CachingAgent.java:136) ~[cats-core.jar:na] at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:78) ~[cats-core.jar:na] at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:335) ~[cats-redis.jar:na] at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:305) ~[cats-redis.jar:na] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212] at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_212] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212] at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212] Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.coreos.com where agent = 'my-k8s-account/KubernetesUnregisteredCustomResourceCa' at line 1 at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.15.jar:8.0.15] at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.15.jar:8.0.15] at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.15.jar:8.0.15] at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:970) ~[mysql-connector-java-8.0.15.jar:8.0.15] at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:387) ~[mysql-connector-java-8.0.15.jar:8.0.15] at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.2.0.jar:na] at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.2.0.jar:na] at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:195) ~[jooq-3.9.6.jar:na] at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:270) ~[jooq-3.9.6.jar:na] at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350) ~[jooq-3.9.6.jar:na]
```

**Comment by perek** [comment]
Looks like we just need to change this line https://github.com/spinnaker/clouddriver/blob/d15d7f775c30056510aca016c712e1d68c16d51a/cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt#L68

to:
```
private val typeSanitization = """[:/\-\.]""".toRegex()
```

**Comment by asher** [comment]
@perek Thanks for the detailed bug report. I'm thinking we should make `typeSanitization` cover NOT [0-9,a-z,A-Z$_] or that plus U+0080-U+FFF for i18n support, to avoid further issues like this.

**Comment by robzienert** [comment]
@asher Why not just `^A-Za-z0-9_`?

**Comment by asher** [comment]
@robzienert that's from https://dev.mysql.com/doc/refman/5.7/en/identifiers.html:

> Permitted characters in unquoted identifiers:
> 
> ASCII: [0-9,a-z,A-Z$_] (basic Latin letters, digits 0-9, dollar, underscore)

but I'm very ok with excluding `$`.

**Comment by perek** [comment]
fixed with my PR
