### ISSUE TITLE
KubernetesServerGroupCachingAgent fails on spinnaker 1.15.1 (works on 1.14.12)

### ISSUE THREAD

**Issue by codertux** [spinnaker/spinnaker#4708]
### Issue Summary:
After upgrading to spinnaker 1.15.1 (from 1.14.12) we've noticed one of our clusters stopped refreshing.

### Cloud Provider(s):
Kubernetes (using the V1 provider)

### Environment:
Spinnaker deployed using halyard on a bare-metal kubernetes cluster.

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
clouddriver

### Description:
After upgrading to 1.15.1 we've noticed some of our pipelines were no longer working. On closer inspection, we saw that spinnaker was no longer refreshing it's cache, showing outdated information.
This bug only affects clusters with HPAs enabled, other clusters are not affected. (clouddriver stack trace below)

### Steps to Reproduce:
1. Enable a HorizontalPodAutoscaler.
2. Upgrade spinnaker to version 1.15.1 (I haven't tried reproducing on 1.15.0)
3. Spinnaker can no longer update it's cache and shows stale information (forever?)

### Additional Details
```
2019-08-01 14:00:11.930  WARN 1 --- [utionAction-114] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.KubernetesV1Provider:mia1/KubernetesServerGroupCachingAgent[1/1] completed with one or more failures

groovy.lang.MissingPropertyException: No such property: currentCPUUtilizationPercentage for class: io.fabric8.kubernetes.api.model.HorizontalPodAutoscalerStatus
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:65) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298) ~[groovy-2.5.7.jar:2.5.7]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.model.KubernetesAutoscalerStatus.<init>(KubernetesAutoscalerStatus.groovy:36) ~[clouddriver-kubernetes.jar:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.model.KubernetesV1ServerGroup.<init>(KubernetesV1ServerGroup.groovy:174) ~[clouddriver-kubernetes.jar:na]
	at sun.reflect.GeneratedConstructorAccessor202.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_212]
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:110) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:273) ~[groovy-2.5.7.jar:2.5.7]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.agent.KubernetesServerGroupCachingAgent$_buildCacheResult_closure31.doCall(KubernetesServerGroupCachingAgent.groovy:429) ~[clouddriver-kubernetes.jar:na]
	at sun.reflect.GeneratedMethodAccessor766.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.7.jar:2.5.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.7.jar:2.5.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.7.jar:2.5.7]
	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.7.jar:2.5.7]
	at groovy.lang.Closure.call(Closure.java:421) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:370) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:317) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.dgm$829.invoke(Unknown Source) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:223) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) ~[groovy-2.5.7.jar:2.5.7]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.agent.KubernetesServerGroupCachingAgent.buildCacheResult(KubernetesServerGroupCachingAgent.groovy:412) ~[clouddriver-kubernetes.jar:na]
	at sun.reflect.GeneratedMethodAccessor1841.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:192) ~[groovy-2.5.7.jar:2.5.7]
	at com.netflix.spinnaker.clouddriver.kubernetes.v1.provider.agent.KubernetesServerGroupCachingAgent.loadData(KubernetesServerGroupCachingAgent.groovy:285) ~[clouddriver-kubernetes.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:85) ~[cats-core.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:75) ~[cats-core.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:335) ~[cats-redis.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:305) ~[cats-redis.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
```

**Comment by maggieneterval** [comment]
Thanks so much for the issue report @codertux, and for the quick fix @mrampton. We've cherry-picked the fix into the 1.15 release branch and it will go out with the next patch release (likely Monday)!
