### ISSUE TITLE
Front50 SQL backend causing Fiat not to start

### ISSUE THREAD

**Issue by battlecow** [spinnaker/spinnaker#4789]
### Issue Summary:
Front50 with sql as the backend causes Fiat to throw an error and is never able to start.

### Cloud Provider(s):
Google

### Environment:
GKE Kubernetes small distributed setup with Fiat enabled.

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Fiat

### Description:
Starting a new Spinnaker instance without migration from another backend (GCS) Fiat is unable to start due to a 404 when requesting all application permissions from Front50 (using SQL).
`2019-08-22 13:56:44.334  INFO 1 --- [ront50Service-1] c.n.s.f.providers.internal.Front50Api    : [] ---> HTTP GET http://spin-front50.spin-services:8080/permissions/applications
2019-08-22 13:56:45.252  WARN 1 --- [ront50Service-1] c.n.s.okhttp.OkHttpMetricsInterceptor    : [] Request GET:http://spin-front50.spin-services:8080/permissions/applications is missing [X-SPINNAKER-USER, X-SPINNAKER-ACCOUNTS] authentication headers and will be treated as anonymous.
Request from: com.netflix.spinnaker.okhttp.MetricsInterceptor.doIntercept(MetricsInterceptor.java:94)
	at com.netflix.spinnaker.okhttp.OkHttpMetricsInterceptor.intercept(OkHttpMetricsInterceptor.java:33)
	at com.netflix.spinnaker.fiat.config.RetrofitConfig$RetryingInterceptor.intercept(RetrofitConfig.java:118)
	at com.netflix.spinnaker.okhttp.MetricsInterceptor.doIntercept(MetricsInterceptor.java:78)
	at com.netflix.spinnaker.okhttp.OkHttpMetricsInterceptor.intercept(OkHttpMetricsInterceptor.java:33)
	at com.netflix.spinnaker.fiat.providers.internal.Front50Service.lambda$getAllApplicationPermissions$0(Front50Service.java:58)
	at com.netflix.spinnaker.fiat.providers.internal.SimpleJava8HystrixCommand.run(SimpleJava8HystrixCommand.java:54)
2019-08-22 13:56:45.261  WARN 1 --- [ront50Service-1] c.n.s.okhttp.OkHttpMetricsInterceptor    : [] Request GET:http://spin-front50.spin-services:8080/permissions/applications is missing [X-SPINNAKER-USER, X-SPINNAKER-ACCOUNTS] authentication headers and will be treated as anonymous.
Request from: com.netflix.spinnaker.okhttp.MetricsInterceptor.doIntercept(MetricsInterceptor.java:94)
	at com.netflix.spinnaker.okhttp.OkHttpMetricsInterceptor.intercept(OkHttpMetricsInterceptor.java:33)
	at com.netflix.spinnaker.fiat.providers.internal.Front50Service.lambda$getAllApplicationPermissions$0(Front50Service.java:58)
	at com.netflix.spinnaker.fiat.providers.internal.SimpleJava8HystrixCommand.run(SimpleJava8HystrixCommand.java:54)
2019-08-22 13:56:45.262  INFO 1 --- [ront50Service-1] c.n.s.f.providers.internal.Front50Api    : [] <--- HTTP 404 http://spin-front50.spin-services:8080/permissions/applications (928ms)
2019-08-22 13:56:45.340  INFO 1 --- [ront50Service-1] c.n.s.f.p.internal.Front50Service        : [] Falling back to application cache. Cause: 404 
2019-08-22 13:56:45.358  WARN 1 --- [           main] c.n.s.f.p.internal.Front50Service        : [] Cache prime failed: 
com.netflix.hystrix.exception.HystrixRuntimeException: getAllApplicationPermissions failed and fallback failed.
	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:832)
	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:807)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:1194)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(OperatorSubscribeOn.java:80)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onError(AbstractCommand.java:1431)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onError(AbstractCommand.java:1362)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: retrofit.RetrofitError: 404 
	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy95.getAllApplicationPermissions(Unknown Source)
	at com.netflix.spinnaker.fiat.providers.internal.Front50Service.lambda$getAllApplicationPermissions$0(Front50Service.java:58)
	at com.netflix.spinnaker.fiat.providers.internal.SimpleJava8HystrixCommand.run(SimpleJava8HystrixCommand.java:54)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	... 26 common frames omitted`

### Steps to Reproduce:
Run Front50 with SQL as the only backend provider, start the cluster and tail Fiat's logs.  Fiat fails to start/be ready because the URL it is attempting to hit to prime its permissions cache doesn't exist on Front50.
Starting with a GCS backend for Front50 allows Fiat to start correctly.
### Additional Details:
The only relevant code I *may* have found is the line: https://github.com/spinnaker/front50/blob/release-1.15.x/front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy#L36
which looks to this non-java dev as not wiring the endpoint when sql is the backend in use.

**Comment by battlecow** [comment]
This should be resolved in https://github.com/spinnaker/front50/pull/579 I think, but would request that it be backported to the 1.15.x series.

**Comment by maggieneterval** [comment]
@battlecow thanks for cherry picking this into 1.15! (PR for reference: https://github.com/spinnaker/front50/pull/580). Going to close this for now but feel free to re-open if you are still seeing the issue after you upgrade to the next patch release of 1.15, which I expect will be early next week.
