### ISSUE TITLE
spin-clouddriver service is not working properly，error msg: Could not get a resource from the pool

### ISSUE THREAD

**Issue by wuzhihui1123** [spinnaker/spinnaker#4858]
### Issue Summary: 
I had a problem when installing spinnaker. It bothered me for a week. I can't find a solution, so I am here to ask for help. Does anyone know how to solve this problem? thank very much for any help!
the spin-clouddriver service always outputs this (only) error message:
```
2019-09-09 15:43:06.906 ERROR 1 --- [gentScheduler-1] c.n.s.c.r.c.ClusteredAgentScheduler      : Unable to run agents
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
    at redis.clients.util.Pool.getResource(Pool.java:53) ~[jedis-2.9.3.jar:na]
    at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226) ~[jedis-2.9.3.jar:na]
    at com.netflix.spinnaker.kork.jedis.telemetry.InstrumentedJedisPool.getResource(InstrumentedJedisPool.java:60) ~[kork-jedis-5.8.2.jar:5.8.2]
    at com.netflix.spinnaker.kork.jedis.telemetry.InstrumentedJedisPool.getResource(InstrumentedJedisPool.java:26) ~[kork-jedis-5.8.2.jar:5.8.2]
    at com.netflix.spinnaker.kork.jedis.JedisClientDelegate.withCommandsClient(JedisClientDelegate.java:45) ~[kork-jedis-5.8.2.jar:5.8.2]
    at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler.acquireRunKey(ClusteredAgentScheduler.java:178) ~[cats-redis.jar:na]
    at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler.acquire(ClusteredAgentScheduler.java:131) ~[cats-redis.jar:na]
    at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler.runAgents(ClusteredAgentScheduler.java:158) ~[cats-redis.jar:na]
    at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler.run(ClusteredAgentScheduler.java:151) ~[cats-redis.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_212]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_212]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_212]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_212]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
    at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
Caused by: java.lang.IllegalStateException: Pool not open
    at org.apache.commons.pool2.impl.BaseGenericObjectPool.assertOpen(BaseGenericObjectPool.java:759) ~[commons-pool2-2.6.2.jar:2.6.2]
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:402) ~[commons-pool2-2.6.2.jar:2.6.2]
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349) ~[commons-pool2-2.6.2.jar:2.6.2]
    at redis.clients.util.Pool.getResource(Pool.java:49) ~[jedis-2.9.3.jar:na]
    ... 15 common frames omitted
```

**I have reinstalled it many times, including trying to use an external redis service. But the problem still exists！**

### Cloud Provider(s):
  kubernetes v2

### Environment:
**halyard version** : 1.23.2
**spinnaker version** : 1.15.0
**kubernetes version** : v1.12.4

### print all spinnaker service 
```
# kubectl  get deployment -n spinnaker | awk '{print $1}'
NAME
spin-clouddriver
spin-deck
spin-echo
spin-fiat
spin-front50
spin-gate
spin-igor
spin-orca
spin-rosco
spin-redis
```

### my spinnaker install script
```
#!/usr/bin/env bash
set -e
​
hal_dir=$HOME/.hal
​
#add Jenkins
hal config ci jenkins enable --no-validate
echo "<hide>" | hal config ci jenkins master add fs-jenkins \
    --address <hide> \
    --username <hide> \
    --password --no-validate
​
# add kubernetes cloudprovider
hal config provider kubernetes enable --no-validate
​
#k8s config
kube_dir=$HOME/.kube
mkdir -p ${kube_dir}
cp kube-conf/* ${kube_dir}/
​
for k8s in k8s01 k8s02
do
    hal config provider kubernetes account add ${k8s} \
        --provider-version v2 \
        --only-spinnaker-managed=true \
        --kubeconfig-file=${kube_dir}/${k8s}-config \
        --namespaces <hide> --no-validate
done
​
hal config deploy edit --type distributed --account-name k8s01 --location spinnaker --no-validate
​
# Configure the installed minio address
echo "<hide>" | hal config storage s3 edit --endpoint http://spinnaker-minio.firstshare:9000 \
    --path-style-access=true \
    --bucket firstshare-spinnaker \
    --access-key-id <hide> \
    --secret-access-key --no-validate
hal config storage edit --type s3 --no-validate
​
​
hal config security ui edit --override-base-url http://172.31.101.246:30000 --no-validate
hal config security api edit --override-base-url http://172.31.101.246:30001 --cors-access-pattern ^http://.*/?$ --no-validate
​
​
hal config version edit --version 1.15.0 --no-validate
hal config edit --timezone Asia/Shanghai --no-validate
hal deploy apply --no-validate
```

**Comment by wuzhihui1123** [comment]
Today I tried the 1.16.0 version of spinnaker, still the same problem！

**Comment by wuzhihui1123** [comment]
I found the cause of the error. The clouddriver has an error I didn't see. The most fundamental reason is because I used the root user in the halyard container to execute the hal command.

**my halyard k8s manifest is** 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-halyard
spec:
  replicas: 1
  selector:
      matchLabels:
        app: spinnaker-halyard
  template:
    metadata:
      labels:
        app: spinnaker-halyard
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: halyard
        image: <f..k GWF>/gcr.io/spinnaker-marketplace/halyard:1.23.2
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTS
            value: "<f..k GWF>"
        ports:
          - containerPort: 8084
          - containerPort: 9000
```

**the error of spin- clouddriver output is**
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-09-11 05:10:39.674 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'configurationRefreshListener' defined in URL [jar:file:/opt/clouddriver/lib/clouddriver-web.jar!/com/netflix/spinnaker/clouddriver/listeners/ConfigurationRefreshListener.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kubernetesV2ProviderSynchronizable': Invocation of init method failed; nested exception is com.netflix.spinnaker.kork.configserver.ConfigFileLoadingException: File "/root/.hal/default/staging/dependencies/1856276698-k8s01-config" not found or is not readable
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:743) ~[spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:390) ~[spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder$run$0.call(Unknown Source) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) [groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) [groovy-2.5.7.jar:2.5.7]
	at com.netflix.spinnaker.clouddriver.Main.main(Main.groovy:78) [clouddriver-web.jar:na]
```
This issue can be closed, thank！

**Comment by scurvydoggo** [comment]
I ran into this and can confirm it's caused by running hal as root.

For some more context, it happens because the `kubeconfig` file gets mounted into the `clouddriver` container at:
```
/root/.hal/default/staging/dependencies/XXX-kubeconfig
```

When it should instead be:
```
/home/spinnaker/.hal/default/staging/dependencies/XXX-kubeconfig
```

This is because the `clouddriver` container runs as the `spinnaker` user, so if the `kubeconfig` is mounted under the `root` user's home, the service freaks out and starts generating this **unreleated** "Pool not open" error.
