### ISSUE TITLE
Replace generic "retrofit error" messages with the actual error message

### ISSUE THREAD

**Issue by gnarea** [spinnaker/spinnaker#4871]
### Issue Summary:

I often get `RetrofitError`s when pipeline executions fail and Deck doesn't provide me with any information that could help me understand what went wrong.

### Cloud Provider(s):

GCP

### Environment:

We're using the solution provided by Google: https://cloud.google.com/docs/ci-cd/spinnaker/spinnaker-for-gcp?hl=en_GB

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

Deck

### Description:

As a consequence of this issue, I also have to check the logs for the different services I think may be relevant, and that's incredibly difficult because -- unless our Spinnaker is misconfigured -- there's no way to correlate logs across services (e.g., Orca, Clouddriver). I'm not sure if I should also create a separate issue for this, but as a user, I'd rather not have to check those logs anyway.

### Steps to Reproduce:

Cause a retrofit error somehow. For example, #4870.

### Additional Details:

Even if I get the trigger source via Deck and inspect the JSON document, I'd get the stack trace but it doesn't tell me what exactly went wrong:

```
java.lang.IllegalStateException: retrofit.RetrofitError: 500 
  at com.netflix.spinnaker.orca.clouddriver.tasks.manifest.DeployManifestTask.lambda$execute$2(DeployManifestTask.java:140)
  at com.netflix.spinnaker.kork.core.RetrySupport.retry(RetrySupport.java:26)
  at com.netflix.spinnaker.orca.clouddriver.tasks.manifest.DeployManifestTask.execute(DeployManifestTask.java:97)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:113)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:69)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withLoggingContext(RunTaskHandler.kt:330)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$withLoggingContext(RunTaskHandler.kt:69)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:112)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:69)
  at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)
  at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:125)
  at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:50)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:69)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:111)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:69)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:195)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:69)
  at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:57)
  at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:41)
  at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:67)
  at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:41)
  at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:76)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:69)
  at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:63)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:69)
  at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:50)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:69)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:188)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:82)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:69)
  at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
  at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
  at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:69)
  at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:69)
  at com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: retrofit.RetrofitError: 500 
  at retrofit.RetrofitError.httpError(RetrofitError.java:40)
  at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
  at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
  at com.sun.proxy.$Proxy111.fetchArtifact(Unknown Source)
  at com.netflix.spinnaker.orca.clouddriver.DelegatingOortService.fetchArtifact(DelegatingOortService.java:128)
  at com.netflix.spinnaker.orca.clouddriver.tasks.manifest.DeployManifestTask.lambda$execute$2(DeployManifestTask.java:100)
  ... 37 more

```

**Comment by gnarea** [comment]
I've upgraded Spinnaker to v1.16 and I've noticed that when I experience #4870, Deck now shows the actual reason why the execution failed.

So maybe we should close this issue now, unless this behaviour in Deck still applies to other errors?

**Comment by emjburns** [comment]
This is something we're slowly working on getting better at in all areas! I'm going to close this, but please feel free to open issues when you see other cases of bad error message propagation.
