### ISSUE TITLE
Deployment result in a NPE

### ISSUE THREAD

**Issue by denysvitali** [spinnaker/spinnaker#4899]
### Issue Summary:
During the "Disabling Manifest" step of a Deployment stage, a Null Pointer exception causes the build to fail, with no specific reason (but a stack-trace):

```
java.lang.NullPointerException at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.handler.KubernetesServiceHandler.getSelector(KubernetesServiceHandler.java:104) at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.handler.KubernetesServiceHandler.detachPatch(KubernetesServiceHandler.java:217) at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.manifest.KubernetesDisableManifestOperation.patchResource(KubernetesDisableManifestOperation.java:43) at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.manifest.AbstractKubernetesEnableDisableManifestOperation.op(AbstractKubernetesEnableDisableManifestOperation.java:92) at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.manifest.AbstractKubernetesEnableDisableManifestOperation.lambda$operate$0(AbstractKubernetesEnableDisableManifestOperation.java:128) at java.util.ArrayList.forEach(ArrayList.java:1257) at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.manifest.AbstractKubernetesEnableDisableManifestOperation.operate(AbstractKubernetesEnableDisableManifestOperation.java:128) at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.manifest.AbstractKubernetesEnableDisableManifestOperation.operate(AbstractKubernetesEnableDisableManifestOperation.java:38) at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate.call(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate.call(Unknown Source) at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy:96) at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy) at sun.reflect.GeneratedMethodAccessor745.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) at groovy.lang.Closure.call(Closure.java:405) at groovy.lang.Closure.call(Closure.java:399) at com.netflix.spinnaker.clouddriver.metrics.TimedCallable$ClosureWrapper.call(TimedCallable.groovy:55) at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82) at java_util_concurrent_Callable$call.call(Unknown Source) at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy:95) at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy) at sun.reflect.GeneratedMethodAccessor743.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) at groovy.lang.Closure.call(Closure.java:405) at groovy.lang.Closure.call(Closure.java:399) at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:127) at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
```

### Cloud Provider(s):
K8s V2

### Environment:
```
dvitali@Denyss-MacBook-Pro:k8s/dev ‹master*›$ kubectl --namespace=spinnaker describe deployments | grep Image
    Image:      gcr.io/spinnaker-marketplace/clouddriver:6.3.0-20190904130744
    Image:      gcr.io/spinnaker-marketplace/deck:2.11.0-20190903213256
    Image:      gcr.io/spinnaker-marketplace/echo:2.7.0-20190904112813
    Image:      gcr.io/spinnaker-marketplace/fiat:1.7.0-20190904130744
    Image:      gcr.io/spinnaker-marketplace/front50:0.19.0-20190904130744
    Image:      gcr.io/spinnaker-marketplace/gate:1.11.0-20190904112813
    Image:      gcr.io/spinnaker-marketplace/igor:1.5.0-20190904155640
    Image:      gcr.io/spinnaker-marketplace/orca:2.9.0-20190904130744
    Image:      gcr.io/kubernetes-spinnaker/redis-cluster:v2
    Image:      gcr.io/spinnaker-marketplace/rosco:0.14.0-20190904130744
```

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Orca ?

### Description:
During 

### Steps to Reproduce:
I'm not able to reproduce the issue anymore. The "Deploy Manifest" stage described by the following JSON caused the issue:
```json
{
  "account": "k8s-staging",
  "cloudProvider": "kubernetes",
  "expectedArtifacts": [],
  "manifests": [
    {
      "apiVersion": "v1",
      "kind": "Service",
      "metadata": {
        "name": "deployment-test-1-${BRANCH}-staging"
      },
      "spec": {
        "ports": [
          {
            "name": "http",
            "port": 3000,
            "protocol": "TCP",
            "targetPort": 3000
          }
        ],
        "selector": {
          "app": "deployment-test-1-${BRANCH}",
          "env": "staging"
        },
        "type": "NodePort"
      }
    },
    {
      "apiVersion": "traefik.containo.us/v1alpha1",
      "kind": "IngressRoute",
      "metadata": {
        "name": "route-deployment-test-1-${BRANCH}-staging"
      },
      "spec": {
        "entryPoints": [
          "https"
        ],
        "routes": [
          {
            "kind": "Rule",
            "match": "Host(`*******`)",
            "priority": 12,
            "services": [
              {
                "name": "deployment-test-1-${BRANCH}-staging",
                "port": 3000
              }
            ]
          }
        ],
        "tls": {
          "certResolver": "default"
        }
      }
    },
    {
      "apiVersion": "apps/v1",
      "kind": "ReplicaSet",
      "metadata": {
        "labels": {
          "app": "deployment-test-1-${BRANCH}",
          "env": "staging"
        },
        "name": "rs-deployment-test-1-${BRANCH}-staging",
        "namespace": "default"
      },
      "spec": {
        "replicas": 2,
        "selector": {
          "matchLabels": {
            "env": "staging"
          }
        },
        "template": {
          "metadata": {
            "labels": {
              "app": "deployment-test-1-${BRANCH}",
              "env": "staging"
            }
          },
          "spec": {
            "containers": [
              {
                "image": "${IMAGE}",
                "name": "deployment-ctr-${BRANCH}-staging",
                "ports": [
                  {
                    "containerPort": 3000
                  }
                ]
              }
            ],
            "imagePullSecrets": [
              {
                "name": "regcred"
              }
            ]
          }
        }
      }
    }
  ],
  "moniker": {
    "app": "deployment-test-1"
  },
  "name": "Deploy to Staging",
  "notifications": [
    {
      "address": "#devops",
      "level": "stage",
      "type": "slack",
      "when": [
        "stage.complete",
        "stage.starting"
      ]
    }
  ],
  "requiredArtifactIds": [],
  "requiredArtifacts": [],
  "sendNotifications": true,
  "skipExpressionEvaluation": false,
  "source": "text",
  "trafficManagement": {
    "enabled": true,
    "options": {
      "enableTraffic": true,
      "namespace": "default",
      "services": [
        "service deployment-test-1-master-staging"
      ],
      "strategy": "redblack"
    }
  },
  "type": "deployManifest"
}
```

**Comment by ezimanyi** [comment]
Thanks for opening this issue! I've never seen this error before when running deployment stages---I'm wondering if somehow maybe your service got deleted between when the stage started running and when it tried to detach the workload from the service.  It looks like this is not reproducible on your end either.  If this does happen again and you're able to capture your clouddriver logs, please re-open the issue and we can see whether there are any clues in those logs.
