### ISSUE TITLE
Unicode characters breaks prometheus monitoring-daemon

### ISSUE THREAD

**Issue by perek** [spinnaker/spinnaker#4980]
### Issue Summary:
The metrics endpoint exports the metrics to prometheus with the pipeline name in the tags, it seems that the metrics reader code attempts to decode unicode

### Cloud Provider(s):
n/a

### Environment:
n/a

### Feature Area:
monitoring-daemon/kork

### Description:
We noticed that orca monitoring daemon went bad, after debugging we found orca was up but the monitoring daemon had the following logs. 
```
Traceback (most recent call last): File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock self.process_request(request, client_address) File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request self.finish_request(request, client_address) File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request self.RequestHandlerClass(request, client_address, self) File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__ self.handle() File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle self.handle_one_request() File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request method() File "/opt/spinnaker-monitoring/bin/http_server.py", line 114, in do_GET handler(self, path, parameters, fragment) File "/opt/spinnaker-monitoring/bin/prometheus_service.py", line 332, in process_web_request request.respond(200, {'ContentType': CONTENT_TYPE_LATEST}, output) File "/opt/spinnaker-monitoring/bin/http_server.py", line 77, in respond body = body.encode('utf-8') UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 94112: ordinal not in range(128)
```
This was caused by a user naming a pipeline with the  'â' . charactor (from an accidental copy paste)
### Steps to Reproduce:
1.) turn on metrics daemon prometheus integration
2.) add a pipeline with 'â' in the name
3.) watch failure on monitoring daemon

**Comment by ezimanyi** [comment]
@spinnakerbot :cherries: :pick: 1.16

**Comment by ezimanyi** [comment]
Sorry, @spinnakerbot, I realize you can't cherry-pick issues...I'll ask you to cherry-pick the actual PR instead.
