### ISSUE TITLE
Exception ( Wait For Manifest To Stabilize )

### ISSUE THREAD

**Issue by gtpark** [spinnaker/spinnaker#5062]
### Issue Summary:
Sometimes Deployment fails

### Cloud Provider(s):
* Kubernetes

### Environment:
* Spinnaker 1.16.0
* Spinnaker 1.16.2

### Feature Area:
* CloudDriver?
* Wait For Manifest To Stabilize

### Description:
Sometimes Deployment fails. I have written 10 BlueGreen deployment pipelines. 
Performing a deployment sometimes ends within one minute, but sometimes fails to deploy. Looking at the failed task, it seems that the 'When you do a deployment' steps fail.

The spinnaker is considered a failure and will not proceed anymore, but replicaSets are actually distributed on Kubernetes.

I checked the log of cloud-driver and orca. But did not find the exact cause. In some cases where an error occurred, the following error occurred:

spin-orca
```
[    handlers-20] c.n.s.o.c.t.m.WaitForManifestStableTask  : [anonymous] Unable to read manifest 'pod service-test-connection-v000' in 'default' for account stella-service-dev-context
retrofit.RetrofitError: 404
	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy111.getManifest(Unknown Source)
```

spin-clouddriver
```
2019-10-25 02:12:22.420 DEBUG 1 --- [0.0-7002-exec-4] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@3b89535f:org.apache.tomcat.util.net.NioChannel@30cbf5ac:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:7002 remote=/0:0:0:0:0:0:0:1:44120]], Read from buffer: [0]
2019-10-25 02:12:22.420 DEBUG 1 --- [0.0-7002-exec-4] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header

java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1239) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1139) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:735) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:353) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:294) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]

2019-10-25 02:12:22.421 DEBUG 1 --- [0.0-7002-exec-4] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@3b89535f:org.apache.tomcat.util.net.NioChannel@30cbf5ac:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:7002 remote=/0:0:0:0:0:0:0:1:44120]], Status in: [OPEN_READ], State out: [CLOSED]
2019-10-25 02:12:22.421 DEBUG 1 --- [0.0-7002-exec-4] org.apache.tomcat.util.net.NioEndpoint   : Calling [org.apache.tomcat.util.net.NioEndpoint@20a3118].closeSocket([org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@3b89535f:org.apache.tomcat.util.net.NioChannel@30cbf5ac:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:7002 remote=/0:0:0:0:0:0:0:1:44120]])

java.lang.Exception: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doClose(NioEndpoint.java:1165) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.SocketWrapperBase.close(SocketWrapperBase.java:394) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.NioEndpoint$Poller.cancelledKey(NioEndpoint.java:667) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
```

Spinnaker 
```
Exception ( Wait For Manifest To Stabilize )
WaitForManifestStableTask of stage Deploy (Manifest) timed out after 30 minutes 1 second. pausedDuration: 0 seconds, elapsedTime: 30 minutes 1 second, timeoutValue: 30 minutes
```

### Steps to Reproduce:
* install Spinnaker 1.16.x
* write pipeline for blue green deployment [link] (https://www.spinnaker.io/guides/user/kubernetes-v2/traffic-management/)
* execution deployment

**Comment by maggieneterval** [comment]
Hi @gtpark, I'm sorry to hear that your deployments have been sporadically timing out.

It looks like the Wait for Manifest to Stabilize task is failing after 30 minutes, which is the [configured timeout](https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/WaitForManifestStableTask.java#L57) for this task. Based on the ["Unable to read manifest..." warnings](https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/WaitForManifestStableTask.java#L96) in your logs, Orca is never getting a successful response from Clouddriver when it makes requests for the deployed resource in order to check its status.

I'm not sure what could cause the Tomcat errors you are seeing in Clouddriver. Are you able to successfully curl your Clouddriver endpoint at `/manifests/{account}/{location}/{manifest_name}` or does that produce the same error? Have you experienced any other issues with connectivity among your Spinnaker services that could shed light on this?

Other avenues of seeking help with this that I would recommend are the [Spinnaker Kubernetes SIG](https://www.spinnaker.io/community/governance/sigs/#existing-sigs), and the #kubernetes, #sig-kubernetes, and #dev channels in [Spinnaker Slack](https://join.spinnaker.io/).

**Comment by gtpark** [comment]
@maggieneterval 
Thank you for answer.

My deployment either occurs during the Force Cache Refresh or fails during the manifest stabilization phase. In particular, errors often occur during the manifest stabilization phase

I don't know exactly how spinnaker works, but I guess from the log as below:

#### 1) Spinnaker retrieves the manifest of the service to deploy from clouddriver.
```http
ex) http: //spin-clouddriver.default:7002/manifests/dev-context/default/service% 20company-service? includeEvents = false
```
#### 2) Spinnaker retrieves the test-connection manifest of the target service.
```http
http://spin-clouddriver.default:7002/manifests/dev-context/default/pod%20company-service-test-connection-v000?includeEvents=false
```

The problem occurs in step 2). The manifest could not be found because the test-connection pod does not exist. In certain situations, a test-connection pod is created, but in sometimes it is not created.

* I need a hint to solve this problem. For what purpose is a pod such as xxx-test-connection-v000 created and by whom the lifecycle is managed? 
* What happens if I shut down the test-connection-v000 pod?
* Sometimes this pod remains in k8s with an error state.


<br />
<br />

Please help me.

thank you.

### cloud-driver log
```log
019-11-04 10:00:12.029  INFO 1 --- [     handlers-8] c.n.s.orca.clouddriver.OortService       : [] <--- HTTP 200 http://spin-clouddriver.default:7002/manifests/dev-context/default/service%20company-service?includeEvents=false (10ms)
2019-11-04 10:00:12.030  INFO 1 --- [     handlers-8] c.n.s.orca.clouddriver.OortService       : [] ---> HTTP GET http://spin-clouddriver.default:7002/manifests/dev-context/default/pod%20company-service-test-connection-v000?includeEvents=false
2019-11-04 10:00:12.039  WARN 1 --- [     handlers-8] c.n.s.okhttp.OkHttp3MetricsInterceptor   : [] Request GET:http://spin-clouddriver.default:7002/manifests/dev-context/default/pod%20company-service-test-connection-v000?includeEvents=false is missing [X-SPINNAKER-USER] authentication headers and will be treated as anonymous.
Request from: com.netflix.spinnaker.okhttp.MetricsInterceptor.doIntercept(MetricsInterceptor.java:94)
	at com.netflix.spinnaker.okhttp.OkHttp3MetricsInterceptor.intercept(OkHttp3MetricsInterceptor.java:32)
	at com.netflix.spinnaker.orca.clouddriver.DelegatingOortService.getManifest(DelegatingOortService.java:48)
	at com.netflix.spinnaker.orca.clouddriver.tasks.manifest.WaitForManifestStableTask.execute(WaitForManifestStableTask.java:94)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:113)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:69)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withLoggingContext(RunTaskHandler.kt:318)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$withLoggingContext(RunTaskHandler.kt:69)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:112)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:69)
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)
	at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:127)
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:51)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:69)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:111)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:69)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:196)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:69)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:57)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:41)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:67)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:41)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:76)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:69)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:63)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:69)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:50)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:69)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:189)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:82)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:69)
	at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:69)
	at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:69)
	at com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82)
```

**Comment by gtpark** [comment]
I found the cause of the problem.

I created a chart using 'helm init' and tests directory and test-connection pod were automatically created. The spinnaker caused confusion in monitoring due to the pod and was resolved by removing it.

thank you.

**Comment by maggieneterval** [comment]
Hey @gtpark, thanks for posting the solution to your issue! Will be helpful if another user hits the same problem. Going to close this issue :+1:

**Comment by costimuraru** [comment]
We're seeing the same issue, though we would like to keep the test-connection pod.
The pod gets created just fine (checked via kubectl), but spinnaker times out waiting for it.

**Comment by karanmagdani1** [comment]
@costimuraru did you find any way around this issue? I would like to keep the test-connection pod as well. but the pipeline fails to stabilize.
