### ISSUE TITLE
Deck UI Information Panel Not Visible When Moving to MySQL

### ISSUE THREAD

**Issue by PsychoSid** [spinnaker/spinnaker#5121]
### Issue Summary:
Information Panel Not Visible When Moving to MySQL

### Cloud Provider(s):
Kubernetes v2

### Environment:
All this is in v1.17.0 and also v1.17.1 (previous versions not tried).

### Feature Area:
Deck

### Description:
500 errors issued when clicking on resources in UI

### Steps to Reproduce:
Enable MySQL click on UI resources (no AuthN/AuthZ) no details. Logs show stack traces, browser dev console shows 500 errors from securityGroups endpoint.

### Additional Details:
```
2019-11-12 08:59:32.116  INFO 1 --- [rix-security-10] c.n.s.g.s.internal.ClouddriverService    : ---> HTTP GET http://spin-clouddriver-ro.spinnaker:7002/securityGroups
2019-11-12 08:59:32.147  INFO 1 --- [rix-security-10] c.n.s.g.s.internal.ClouddriverService    : <--- HTTP 500 http://spin-clouddriver-ro.spinnaker:7002/securityGroups (30ms)
2019-11-12 08:59:32.149 ERROR 1 --- [.0-8084-exec-70] c.n.s.g.s.c.AbstractHystrixCommand       : Downstream exception encountered (group: 'security', command: 'getAllSecurityGroups')

retrofit.RetrofitError: 500 Internal Server Error
```
 
And
```
2019-11-12 09:05:12.465 ERROR 1 --- [0.0-7002-exec-1] c.n.s.c.c.SecurityGroupController        : Unable to list security groups

java.lang.NullPointerException: null
        at com.netflix.spinnaker.clouddriver.kubernetes.v2.caching.view.model.KubernetesV2SecurityGroup.inboundRules(KubernetesV2SecurityGroup.java:118) ~[clouddriver-kubernetes-v2.jar:na]
        at com.netflix.spinnaker.clouddriver.kubernetes.v2.caching.view.model.KubernetesV2SecurityGroup.fromCacheData(KubernetesV2SecurityGroup.java:103) ~[clouddriver-kubernetes-v2.jar:na
```

Also
```
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.netflix.spinnaker.clouddriver.kubernetes.v2.caching.view.provider.KubernetesV2SecurityGroupProvider.class
        at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73) ~[rxjava-1.3.8.jar:1.3.8]
```

**Comment by maggieneterval** [comment]
Hey @PsychoSid, thanks for opening this issue -- we'll patch a fix into the next release of 1.17.
