### ISSUE TITLE
Pod/Replica Set details not listing in Spinnaker 1.17.2

### ISSUE THREAD

**Issue by raghunandanbs** [spinnaker/spinnaker#5217]
### Issue Summary:
Under infrastructure tab, when cluster details (Say Pod or a replica set) are clicked, No information is shown in the right pane. It works well in Spinnaker 1.16.3. 

### Cloud Provider(s):
Kubernetes V2 , Cluster version being GKE v1.13.11 stable release.

### Environment:
Local Debian

### Additional Details:
I also see below shown logs in clouddriver. 
```
2019-12-10 02:17:25.436 ERROR 32361 --- [0.1-7002-exec-9] c.n.s.c.c.SecurityGroupController        : Unable to list security groups
java.lang.NullPointerException: null
        at com.netflix.spinnaker.clouddriver.kubernetes.v2.caching.view.model.KubernetesV2SecurityGroup.lambda$inboundRules$0(KubernetesV2SecurityGroup.java:119) ~[clouddriver-kubernetes-v2-6.4.1-20191111102213.jar:6.4.1-20191111102213]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_222]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_222]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_222]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_222]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_222]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_222]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[na:1.8.0_222]
        at com.netflix.spinnaker.clouddriver.kubernetes.v2.caching.view.model.KubernetesV2SecurityGroup.inboundRules(KubernetesV2SecurityGroup.java:121) ~[clouddriver-kubernetes-v2-6.4.1-20191111102213.jar:6.4.1-20191111102213]
        at com.netflix.spinnaker.clouddriver.kubernetes.v2.caching.view.model.KubernetesV2SecurityGroup.fromCacheData(KubernetesV2SecurityGroup.java:103) ~[clouddriver-kubernetes-v2-6.4.1-20191111102213.jar:6.4.1-20191111102213]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_222]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_222]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[na:1.8.0_222]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272) ~[na:1.8.0_222]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_222]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_222]
        at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_222]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_222]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_222]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_222]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_222]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_222]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[na:1.8.0_222]
        at com.netflix.spinnaker.clouddriver.kubernetes.v2.caching.view.provider.KubernetesV2SecurityGroupProvider.getAll(KubernetesV2SecurityGroupProvider.java:62) ~[clouddriver-kubernetes-v2-6.4.1-20191111102213.jar:6.4.1-20191111102213]
        at com.netflix.spinnaker.clouddriver.kubernetes.v2.caching.view.provider.KubernetesV2SecurityGroupProvider.getAll(KubernetesV2SecurityGroupProvider.java:36) ~[clouddriver-kubernetes-v2-6.4.1-20191111102213.jar:6.4.1-20191111102213]
        at com.netflix.spinnaker.clouddriver.model.SecurityGroupProvider$getAll.call(Unknown Source) ~[na:na]
        at com.netflix.spinnaker.clouddriver.controllers.SecurityGroupController$_list_closure1.doCall(SecurityGroupController.groovy:50) ~[clouddriver-web-6.4.1-20191111102213.jar:6.4.1-20191111102213]
        at sun.reflect.GeneratedMethodAccessor357.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_222]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.7.jar:2.5.7]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.7.jar:2.5.7]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.7.jar:2.5.7]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.7.jar:2.5.7]
        at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.7.jar:2.5.7]
        at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50) ~[groovy-2.5.7.jar:2.5.7]
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:122) ~[groovy-2.5.7.jar:2.5.7]
        at com.sun.proxy.$Proxy232.call(Unknown Source) ~[na:na]
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastPath(OnSubscribeFromIterable.java:173) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:86) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.Subscriber.setProducer(Subscriber.java:211) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34) [rxjava-1.3.8.jar:1.3.8]
        at rx.Observable.unsafeSubscribe(Observable.java:10327) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.3.8.jar:1.3.8]
        at rx.Observable.unsafeSubscribe(Observable.java:10327) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:45) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:30) [rxjava-1.3.8.jar:1.3.8]
        at rx.Observable.unsafeSubscribe(Observable.java:10327) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeReduceSeed.call(OnSubscribeReduceSeed.java:40) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeReduceSeed.call(OnSubscribeReduceSeed.java:24) [rxjava-1.3.8.jar:1.3.8]
        at rx.Observable.unsafeSubscribe(Observable.java:10327) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.3.8.jar:1.3.8]
        at rx.Observable.subscribe(Observable.java:10423) [rxjava-1.3.8.jar:1.3.8]
        at rx.Observable.subscribe(Observable.java:10390) [rxjava-1.3.8.jar:1.3.8]
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443) [rxjava-1.3.8.jar:1.3.8]
        at rx.observables.BlockingObservable.first(BlockingObservable.java:166) [rxjava-1.3.8.jar:1.3.8]
        at rx.observables.BlockingObservable$first.call(Unknown Source) [rxjava-1.3.8.jar:1.3.8]
        at com.netflix.spinnaker.clouddriver.controllers.SecurityGroupController.list(SecurityGroupController.groovy:49) [clouddriver-web-6.4.1-20191111102213.jar:6.4.1-20191111102213]
        at com.netflix.spinnaker.clouddriver.controllers.SecurityGroupController$$FastClassBySpringCGLIB$$acf9f4df.invoke(<generated>) [clouddriver-web-6.4.1-20191111102213.jar:6.4.1-20191111102213]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) [spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69) [spring-security-core-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) [spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at com.netflix.spinnaker.clouddriver.controllers.SecurityGroupController$$EnhancerBySpringCGLIB$$d3afff7f.list(<generated>) [clouddriver-web-6.4.1-20191111102213.jar:6.4.1-20191111102213]
        at sun.reflect.GeneratedMethodAccessor352.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_222]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-embed-core-9.0.22.jar:9.0.22]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.22.jar:9.0.22]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.22.jar:...

```

**Comment by ezimanyi** [comment]
@raghunandanbs : Have you tried this on Spinnaker 1.17.3?  You may be running into the issues fixed in either spinnaker/clouddriver#4172 or spinnaker/clouddriver#4182 which both landed in 1.17.3.

**Comment by raghunandanbs** [comment]
@ezimanyi Thanks for the pointers, I will try it on 1.17.3 and let you know.

**Comment by costimuraru** [comment]
Also, can you look at the deployment pipeline (Edit as JSON) and look for the JSON field named: `moniker`. Make sure it matches the application name from spinnaker.

**Comment by raghunandanbs** [comment]
> Also, can you look at the deployment pipeline (Edit as JSON) and look for the JSON field named: `moniker`. Make sure it matches the application name from spinnaker.

Okay.

**Comment by raghunandanbs** [comment]
@ezimanyi I applied the latest update (1.17.4) and the issue seem to have been fixed. Thank you.
@costimuraru I confirmed that `moniker` field had application name that matched.
