### ISSUE TITLE
spin-clouddriver fails with no default access to namespace api k8s v2

### ISSUE THREAD

**Issue by bernadinm** [spinnaker/spinnaker#5255]
### Issue Summary:

Clouddriver fails to start properly on k8s clusters that do not allow the default service account to list namespace resource
### Cloud Provider(s):

```
Kubernetes 1.15.2
```
### Environment:

```
AWS / Kubernetes V2
```
```
Spinnaker: 1.16.1
Hal: 1.28.0
```

### Feature Area:

- Cloud Driver
### Description:

Fails to start properly default service account with preconfigured RBAC is used. `Failed to read [namespace] from : Error from server (Forbidden): namespaces is forbidden: User "system:serviceaccount:team-automation:halyard" cannot list resource "namespaces" in API group "" at the cluster scope`

###### Cloud Driver Logs

These logs below loop infinitely.

```
2019-12-19 09:28:50.418  INFO 1 --- [ecutionAction-2] k.v.c.a.KubernetesV2OnDemandCachingAgent : global-bitmex/KubernetesUnregisteredCustomResourceCachingAgent[1/1]: agent is starting
2019-12-19 09:29:19.418  INFO 1 --- [ecutionAction-1] s.c.k.v.c.a.KubernetesMetricCachingAgent : global-bitmex/KubernetesMetricCachingAgent[1/1]: agent is starting
2019-12-19 09:29:19.418  INFO 1 --- [ecutionAction-2] k.v.c.a.KubernetesV2OnDemandCachingAgent : global-bitmex/KubernetesCoreCachingAgent[1/1]: agent is starting
2019-12-19 09:29:19.570 ERROR 1 --- [ecutionAction-1] c.n.s.c.k.v.s.KubernetesV2Credentials    : Could not list namespaces for account global-bitmex: Failed to read [namespace] from : Error from server (Forbidden): namespaces is forbidden: User "system:serviceaccount:team-automation:halyard" cannot list resource "namespaces" in API group "" at the cluster scope

2019-12-19 09:29:20.418  INFO 1 --- [ecutionAction-2] c.n.s.c.k.v.c.a.KubernetesV2CachingAgent : global-bitmex/KubernetesNamespaceCachingAgent[1/1]: agent is starting
2019-12-19 09:29:20.566  WARN 1 --- [ecutionAction-2] c.n.s.c.cache.LoggingInstrumentation     : kubernetes:global-bitmex/KubernetesNamespaceCachingAgent[1/1] completed with one or more failures

com.netflix.spinnaker.clouddriver.kubernetes.v2.op.job.KubectlJobExecutor$KubectlException: Failed to read [namespace] from : Error from server (Forbidden): namespaces is forbidden: User "system:serviceaccount:team-automation:halyard" cannot list resource "namespaces" in API group "" at the cluster scope

	at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.job.KubectlJobExecutor.list(KubectlJobExecutor.java:421) ~[clouddriver-kubernetes.jar:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.security.KubernetesV2Credentials.lambda$list$18(KubernetesV2Credentials.java:481) ~[clouddriver-kubernetes.jar:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.security.KubernetesV2Credentials.runAndRecordMetrics(KubernetesV2Credentials.java:636) ~[clouddriver-kubernetes.jar:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.security.KubernetesV2Credentials.runAndRecordMetrics(KubernetesV2Credentials.java:626) ~[clouddriver-kubernetes.jar:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.security.KubernetesV2Credentials.list(KubernetesV2Credentials.java:476) ~[clouddriver-kubernetes.jar:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.caching.agent.KubernetesNamespaceCachingAgent.loadPrimaryResourceList(KubernetesNamespaceCachingAgent.java:62) ~[clouddriver-kubernetes.jar:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.caching.agent.KubernetesV2CachingAgent.loadData(KubernetesV2CachingAgent.java:136) ~[clouddriver-kubernetes.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:85) ~[cats-core.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:75) ~[cats-core.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:335) ~[cats-redis.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:305) ~[cats-redis.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]

2019-12-19 09:29:21.418  INFO 1 --- [ecutionAction-2] k.v.c.a.KubernetesV2OnDemandCachingAgent : global-bitmex/KubernetesUnregisteredCustomResourceCachingAgent[1/1]: agent is starting
```
---

The RBAC used is this: https://www.spinnaker.io/setup/install/providers/kubernetes-v2/#optional-configure-kubernetes-roles-rbac

**Comment by justinrlee** [comment]
+1 on this.  I think this was introduced with the v2 refactor?

**Comment by ethanfrogers** [comment]
If I understand this correctly, the service account used for Spinnaker doesn't have access to read all namespaces and, I assume, only has access to individual namespaces via a `Role` and `RoleBinding` in those namespaces? If this is the case, have you explicitly defined those namespaces in the account? If you don't, Clouddriver will attempt to figure out what namespaces it has access to and is where we've historically seen this bug.

So, my main question is this - do you have namespaces explicitly configured? Knowing that should help us determine whether this is a regression or expected based on config!

If this was introduced in the V2 refactor then it's definitely a bug. Part of the goal for that refactor was to make Clouddriver tolerant to these types of failures.

**Comment by ethanfrogers** [comment]
Just spoke w/ @justinrlee about this briefly - he says that this behavior is present even when configured with explicit namespaces. It looks like the bug comes from here - https://github.com/spinnaker/clouddriver/blob/b03a28a4837d64ea41d86b0266f252f59c78bc08/clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesNamespaceCachingAgent.java#L57-L62.

According to the above, even if we've explicitly configured namespaces we _still_ make a live call to list namespaces and then filter out anything extra. I assume this is so we can get all of the metadata about the namespace itself.

We should certainly handle this more gracefully. cc @ezimanyi
