### ISSUE TITLE
kubeconfig storing sensitive files fails trying to create new file

### ISSUE THREAD

**Issue by vijay-sapient** [spinnaker/spinnaker#5305]
Hi All,
I enabled secret management for kubeconfig file using https://www.spinnaker.io/reference/halyard/secrets/gcs-secrets/#storing-sensitive-files.
once i enabled it. i see the below error, when doing a hal deploy apply
Problems in Global:
! ERROR Unable to write the kubeconfig file to the staging area.
 This may be a user permissions issue.
- Failed to deploy Spinnaker.

Looked here:- https://github.com/spinnaker/halyard/blob/master/halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/KubernetesV2ClouddriverProfileFactory.java

I think the problem is that its always trying to create the file rather pulling . 
Seems like a bug. 

Other secrets and json file works fine. Only issue with kubeconfig files

### Cloud Provider(s):
GCP
halyard version = 1.28.0
spinnaker version = 1.17.2

 ### Steps to reproduce: 
1. generate and move kubeconfig to bucket and enable https://www.spinnaker.io/reference/halyard/secrets/gcs-secrets/#storing-sensitive-files.
2. hal deploy apply

**Comment by german-muzquiz** [comment]
@vijay-sapient can you provide Halyard logs to see if there are more details about the error? Usually you can find them in `/var/log/spinnaker/halyard/halyard.log`, or if running Halyard as a docker container, they're in the logs of the container.
I was able to run `hal deploy apply` with Halyard `1.29.0` and Spinnaker `1.17.2` successfully, specifying the kubeconfig as a GCS secret:
```
kubeconfigFile: encrypted:gcs!b:test-bucket!f:my-kubecfg
```
This error:
```
! ERROR Unable to write the kubeconfig file to the staging area.
```
Probably means that the file was correctly downloaded, but Halyard process doesn't have write permissions to `~/.hal/<profile name>/staging`.

**Comment by vijay-sapient** [comment]
Hi @german-muzquiz ,

Haven't tried 1.29.0. Are you seeing the same problem with 1.28.0?

I see the below trace when its failing:

severity: "INFO"  
 textPayload: "com.netflix.spinnaker.halyard.core.error.v1.HalException: Unable to write the kubeconfig file to the staging area. This may be a user permissions issue.
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.profile.KubernetesV2ClouddriverProfileFactory.processKubernetesAccount(KubernetesV2ClouddriverProfileFactory.java:137) ~[halyard-deploy.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_232]
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.profile.KubernetesV2ClouddriverProfileFactory.processProviders(KubernetesV2ClouddriverProfileFactory.java:57) ~[halyard-deploy.jar:na]
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.profile.ClouddriverProfileFactory.setProfile(ClouddriverProfileFactory.java:86) ~[halyard-deploy.jar:na]
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.profile.ProfileFactory.getProfile(ProfileFactory.java:88) ~[halyard-deploy.jar:na]
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.service.ClouddriverService.getProfiles(ClouddriverService.java:85) ~[halyard-deploy.jar:na]
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.service.distributed.kubernetes.v2.KubernetesV2ClouddriverService.getProfiles(KubernetesV2ClouddriverService.java:74) ~[halyard-deploy.jar:na]
	at com.netflix.spinnaker.halyard.deploy.services.v1.GenerateService.generateConfig(GenerateService.java:142) ~[halyard-deploy.jar:na]
	at com.netflix.spinnaker.halyard.deploy.services.v1.DeployService.deploy(DeployService.java:294) ~[halyard-deploy.jar:na]
	at com.netflix.spinnaker.halyard.controllers.v1.DeploymentController.lambda$deploy$14(DeploymentController.java:228) ~[halyard-web.jar:na]
	at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:123) ~[halyard-core.jar:na]
	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]


Once this failed, i switch back to kubeconfig on the file system and its working fine.

**Comment by german-muzquiz** [comment]
Ohh I see the problem now, you're using a `kubeconfig` file with GCP auth. 
Halyard detects this and tries to modify the file _in place_ for adding a `cmd-path: gcloud` section to the user auth in the kubeconfig. 

Sadly the code didn't detect that this is a secret reference instead of a file in the local file system, so really it's not possible (or desired) for Halyard to modify the original kubeconfig file. Thankfully this seems to be a small fix, Halyard simply should not try to modify the file because in practice, clouddriver will download it again anyway at startup instead of using the Halyard supplied version.

**Comment by vijay-sapient** [comment]
Hi @german-muzquiz, am using the latest 1.31.0 but still see the same issue. is this available in any newer versions?

**Comment by german-muzquiz** [comment]
@vijay-sapient I tested with hal version `1.31.1-20200207105616` and was able to successfully do a `hal deploy apply` with the kubeconfig stored in GCS. Are you still getting the same error? Can you post halyard logs?

**Comment by vijay-sapient** [comment]
@german-muzquiz still the same issue even with 1.37.0

    "problems" : {
      "problems" : [ {
        "message" : "Unable to write the kubeconfig file to the staging area. This may be a user permissions issue.",
        "remediation" : null,
        "options" : null,
        "severity" : "FATAL",
        "location" : "Global"
      } ]
    },
    "responseCode" : 409,
    "message" : "Unable to write the kubeconfig file to the staging area. This may be a user permissions issue.",
    "suppressed" : [ ],
    "localizedMessage" : "Unable to write the kubeconfig file to the staging area. This may be a user permissions issue."
  },
  "runningJobs" : [ ]
- Apply deployment
  Failure

	at com.netflix.spinnaker.halyard.cli.services.v1.OperationHandler.get(OperationHandler.java:44)
	at com.netflix.spinnaker.halyard.cli.command.v1.AbstractRemoteActionCommand.runRemoteAction(AbstractRemoteActionCommand.java:49)
	at com.netflix.spinnaker.halyard.cli.command.v1.AbstractRemoteActionCommand.executeThis(AbstractRemoteActionCommand.java:102)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.safeExecuteThis(NestableCommand.java:222)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:172)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:175)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:175)
	at com.netflix.spinnaker.halyard.cli.Main.main(Main.java:46)
Caused by: java.lang.Exception: Unable to write the kubeconfig file to the staging area. This may be a user permissions issue.
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.profile.KubernetesV2ClouddriverProfileFactory.processKubernetesAccount(KubernetesV2ClouddriverProfileFactory.java:113)
	at java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.profile.KubernetesV2ClouddriverProfileFactory.processProviders(KubernetesV2ClouddriverProfileFactory.java:67)
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.profile.ClouddriverProfileFactory.setProfile(ClouddriverProfileFactory.java:80)
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.profile.ProfileFactory.getProfile(ProfileFactory.java:88)
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.service.ClouddriverService.getProfiles(ClouddriverService.java:85)
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.service.distributed.kubernetes.v2.KubernetesV2ClouddriverService.getProfiles(KubernetesV2ClouddriverService.java:74)
	at com.netflix.spinnaker.halyard.deploy.services.v1.GenerateService.generateConfig(GenerateService.java:142)
	at com.netflix.spinnaker.halyard.deploy.services.v1.DeployService.deploy(DeployService.java:293)
	at com.netflix.spinnaker.halyard.controllers.v1.DeploymentController.lambda$deploy$14(DeploymentController.java:230)
	at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:123)
	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48)
	at java.lang.Thread.run(Thread.java:834)
command terminated with exit code 1

**Comment by german-muzquiz** [comment]
@vijay-sapient Can you test specifying `encryptedFile` prefix for kubeconfigs instead of `encrypted`?
```
kubeconfigFile: encryptedFile:gcs!b:test-bucket!f:my-kubecfg
```
Our docs need to be updated, there was a change since the initial implementation to use `encrypted` prefix only for secret values and `encryptedFile` for secret files like kubeconfig.

**Comment by vijay-sapient** [comment]
@german-muzquiz yeah this one works thanks a lot. I can raise a PR to fix the documentation

**Comment by german-muzquiz** [comment]
It's on the works: https://github.com/spinnaker/spinnaker.github.io/pull/1995
