### ISSUE TITLE
DualExecutionRepository for Orca doesn't work since InstrumentedProxy introduced

### ISSUE THREAD

**Issue by dragon3** [spinnaker/spinnaker#5381]
### Issue Summary:

DualExecutionRepository for Orca doesn't work since InstrumentedProxy introduced.
( Orca can't start with correct `DualExecutionRepository` config. )

### Cloud Provider(s):

The issue is not related to any Cloud Providers.

### Environment:

Spinnaker `1.18.1` on Kubernetes (GKE), use halyard to deploy it.

### Feature Area:

Orca

### Description:

Orca always failed to start if `DualExecutionRepository` is used.

We can reproduce the issue with `orca-local.yml` like this:
```yaml
sql:
  enabled: true
  connectionPool:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/orca
    user: orca_service
    password: "xxx"
    connectionTimeout: 5000
    maxLifetime: 30000
    maxPoolSize: 50
  migration:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/orca
    user: orca_migrate
    password: "xxx"

executionRepository:
  dual:
    enabled: true
    primaryClass: com.netflix.spinnaker.orca.sql.pipeline.persistence.SqlExecutionRepository
    previousClass: com.netflix.spinnaker.orca.telemetry.RedisInstrumentedExecutionRepository
  sql:
    enabled: true
  redis:
    enabled: true

monitor:
  activeExecutions:
    redis: false

pollers:
  orchestrationMigrator:
    enabled: true
    intervalMs: 1800000
  pipelineMigrator:
    enabled: true
    intervalMs: 1800000
```

The documentation (https://www.spinnaker.io/guides/operator/orca-redis-to-sql/#enable-dualexecutionrepository) says `primaryClass: com.netflix.spinnaker.orca.sql.telemetry.SqlInstrumentedExecutionRepository`, but it was already deleted in https://github.com/spinnaker/orca/commit/98ec5389ca4d5e65df3fb48a7007ca670991051c so I use `com.netflix.spinnaker.orca.sql.pipeline.persistence.SqlExecutionRepository` instead.

Even I use the correct class name,  Orca can't start with the error `No ExecutionRepository bean of class com.netflix.spinnaker.orca.sql.pipeline.persistence.SqlExecutionRepository found`:

<details><summary>All error messages</summary>

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-02-04 18:26:49.585 ERROR 38847 --- [           main] o.s.boot.SpringApplication               : [] Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'redisOrcaQueueConfiguration': Unsatisfied dependency expressed through method 'redisQueueObjectMapper' parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'taskResolver' defined in com.netflix.spinnaker.orca.config.OrcaConfiguration: Unsatisfied dependency expressed through method 'taskResolver' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dependsOnExecutionTask' defined in file [/Users/dragon3/dev/spinnaker/orca/orca-core/out/production/classes/com/netflix/spinnaker/orca/pipeline/tasks/DependsOnExecutionTask.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dualExecutionRepository' defined in file [/Users/dragon3/dev/spinnaker/orca/orca-core/out/production/classes/com/netflix/spinnaker/orca/pipeline/persistence/DualExecutionRepository.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.pipeline.persistence.DualExecutionRepository]: Constructor threw exception; nested exception is java.lang.IllegalStateException: No ExecutionRepository bean of class com.netflix.spinnaker.orca.sql.pipeline.persistence.SqlExecutionRepository found
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:723)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:116)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at com.netflix.spinnaker.kork.plugins.spring.SpinnakerApplication.initialize(SpinnakerApplication.java:59)
	at com.netflix.spinnaker.kork.plugins.spring.SpinnakerApplication.initialize(SpinnakerApplication.java:44)
	at com.netflix.spinnaker.kork.plugins.spring.SpinnakerApplication$initialize.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:143)
	at com.netflix.spinnaker.orca.Main.main(Main.groovy:103)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'taskResolver' defined in com.netflix.spinnaker.orca.config.OrcaConfiguration: Unsatisfied dependency expressed through method 'taskResolver' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dependsOnExecutionTask' defined in file [/Users/dragon3/dev/spinnaker/orca/orca-core/out/production/classes/com/netflix/spinnaker/orca/pipeline/tasks/DependsOnExecutionTask.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dualExecutionRepository' defined in file [/Users/dragon3/dev/spinnaker/orca/orca-core/out/production/classes/com/netflix/spinnaker/orca/pipeline/persistence/DualExecutionRepository.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.pipeline.persistence.DualExecutionRepository]: Constructor threw exception; nested exception is java.lang.IllegalStateException: No ExecutionRepository bean of class com.netflix.spinnaker.orca.sql.pipeline.persistence.SqlExecutionRepository found
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:715)
	... 24 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dependsOnExecutionTask' defined in file [/Users/dragon3/dev/spinnaker/orca/orca-core/out/production/classes/com/netflix/spinnaker/orca/pipeline/tasks/DependsOnExecutionTask.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dualExecutionRepository' defined in file [/Users/dragon3/dev/spinnaker/orca/orca-core/out/production/classes/com/netflix/spinnaker/orca/pipeline/persistence/DualExecutionRepository.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.pipeline.persistence.DualExecutionRepository]: Constructor threw exception; nested exception is java.lang.IllegalStateException: No ExecutionRepository bean of class com.netflix.spinnaker.orca.sql.pipeline.persistence.SqlExecutionRepository found
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1503)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1467)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1358)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1245)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	... 37 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dualExecutionRepository' defined in file [/Users/dragon3/dev/spinnaker/orca/orca-core/out/production/classes/com/netflix/spinnaker/orca/pipeline/persistence/DualExecutionRepository.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.pipeline.persistence.DualExecutionRepository]: Constructor threw exception; nested exception is java.lang.IllegalStateException: No ExecutionRepository bean of class com.netflix.spinnaker.orca.sql.pipeline.persistence.SqlExecutionRepository found
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:314)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:295)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	... 54 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.pipeline.persistence.DualExecutionRepository]: Constructor threw exception; nested exception is java.lang.IllegalStateException: No ExecutionRepository bean of class com.netflix.spinnaker.orca.sql.pipeline.persistence.SqlExecutionRepository found
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:216)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310)
	... 68 common frames omitted
Caused by: java.lang.IllegalStateException: No ExecutionRepository bean of class com.netflix.spinnaker.orca.sql.pipeline.persistence.SqlExecutionRepository found
	at com.netflix.spinnaker.orca.pipeline.persistence.DualExecutionRepository$findExecutionRepositoryByClass$1.invoke(DualExecutionRepository.kt:68)
	at com.netflix.spinnaker.orca.pipeline.persistence.DualExecutionRepository$findExecutionRepositoryByClass$1.invoke(DualExecutionRepository.kt:44)
	at com.netflix.spinnaker.orca.pipeline.persistence.DualExecutionRepository$findExecutionRepository$1.invoke(DualExecutionRepository.kt:75)
	at com.netflix.spinnaker.orca.pipeline.persistence.DualExecutionRepository$findExecutionRepository$1.invoke(DualExecutionRepository.kt:44)
	at com.netflix.spinnaker.orca.pipeline.persistence.DualExecutionRepository.<init>(DualExecutionRepository.kt:79)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:152)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at org.springframework.beans.BeanUtils$KotlinDelegate.instantiateClass(BeanUtils.java:792)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:188)
	... 70 common frames omitted

Process finished with exit code 1
```

</details>

It seems that https://github.com/spinnaker/orca/commit/98ec5389ca4d5e65df3fb48a7007ca670991051c broke the behavior of the `DualExecutionRepository`:
```java
    val findExecutionRepositoryByClass = { className: String ->
      val repositoryClass = Class.forName(className)
      allRepositories.find { repo ->
        repositoryClass.isInstance(repo) ||
          (repo is DelegatingExecutionRepository<*> && repositoryClass.isInstance(repo.getDelegate()))
      } ?: throw IllegalStateException("No ExecutionRepository bean of class $className found")
    }
```

Since `SqlExecutionRepository` is now "wrapped" by `InstrumentedProxy`, the ` allRepositories.find` never find SqlExecutionRepository object.

<img width="1258" alt="Screen_Shot_2020-02-04_at_18_36_52" src="https://user-images.githubusercontent.com/20374/73732371-66d5e780-477d-11ea-8a58-ccae98374d10.png">

### Steps to Reproduce:

- Setup MySQL instance
- Use `orca-local.yml` in Description of this issue

### Additional Details:

It works properly if I revert the change https://github.com/spinnaker/orca/commit/98ec5389ca4d5e65df3fb48a7007ca670991051c

**Comment by cfieber** [comment]
recently support was added to look up the executionRepositories by beanName

this should work:
```
executionRepository:
  dual:
    enabled: true
    primaryName: sqlExecutionRepository
    previousName: redisExecutionRepository
```

**Comment by cfieber** [comment]
with the given workaround I'm not sure someone will jump on this urgently

**Comment by dragon3** [comment]
@cfieber 
Thank you for the reply.

> recently support was added to look up the executionRepositories by beanName
> 
> this should work:
> 
> ```
> executionRepository:
>   dual:
>     enabled: true
>     primaryName: sqlExecutionRepository
>     previousName: redisExecutionRepository
> ```

Yeah, the workaround works!

Note: the bean names come from:
- `sqlExecutionRepository`: https://github.com/spinnaker/orca/blob/31e15e7ed501f6e2b965d01a07e2160a2d5e3371/orca-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt#L56
- `redisExecutionRepository`: https://github.com/spinnaker/orca/blob/31e15e7ed501f6e2b965d01a07e2160a2d5e3371/orca-redis/src/main/java/com/netflix/spinnaker/orca/config/RedisConfiguration.java#L46-L48

---

Are you going to deprecate (remove) `primaryClass` and `secondaryClass` config?
If so, I'm happy to create a pull request to remove them from DualExecutionRepository. ( update [the documentation](https://www.spinnaker.io/guides/operator/orca-redis-to-sql/#enable-dualexecutionrepository) as well )

What do you think?

**Comment by dragon3** [comment]
I've just created a pull request to update the documentation 👉 https://github.com/spinnaker/spinnaker.github.io/pull/1700
