### ISSUE TITLE
"java.net.SocketTimeoutException: timeout" error

### ISSUE THREAD

**Issue by mrothroc** [spinnaker/spinnaker#5415]
### Issue Summary:
(This is related to issue 5114, where @maggieneterval asked to open a new ticket if we could help troubleshoot.)
I get a java.net.SocketTimeoutException intermittently.  The end user impact manifests in several ways.  The easiest is when I try to view the details of a deployment.  In this case, I get a spinner in the UI in the detail pane that never resolves.  There is an error and several stack traces in the log.  Sometimes, once that happens, my server groups no longer show in the UI.  They eventually return, where I can repeat this again.  It is 100% reproducible for me.

### Cloud Provider(s):
GKE on GCP

### Environment:
Spinnaker 1.18.1 deployed to Kubernetes (V2) GKE cluster via halyard

### Feature Area:
kubernetes

### Description:
It is always a SocketTimeoutException, followed by a long chain of cascading errors with stack traces.  It starts like this:

**NOTE: look at the timestamps, the oldest entries in each pasted section are at the bottom!!!**
`	2020-02-08 10:27:03	
at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
2020-02-08 10:27:03	
at okio.Okio$4.newTimeoutException(Okio.java:232)
2020-02-08 10:27:03	
2020-02-08 18:27:03.399 INFO 1 --- [rix-manifests-1] c.n.s.g.s.internal.ClouddriverService : java.net.SocketTimeoutException: timeout
2020-02-08 10:27:03	
2020-02-08 18:27:03.397 INFO 1 --- [rix-manifests-1] c.n.s.g.s.internal.ClouddriverService : ---- ERROR http://spin-clouddriver.spinnaker:7002/manifests/stage/app/deployment%20snapshoting
2020-02-08 10:27:03	
10.101.16.49 - - [08/Feb/2020:18:27:01 +0000] "GET /gate/applications/notificationms/serverGroups HTTP/1.1" 200 2
2020-02-08 10:27:03	
2020-02-08 18:27:03.109 INFO 1 --- [-applications-8] c.n.s.g.s.internal.Front50Service : <--- HTTP 200 http://spin-front50.spinnaker:8080/v2/applications?restricted=false (53ms)
2020-02-08 10:27:03	
2020-02-08 18:27:03.108 INFO 1 --- [serverGroups-10] c.n.s.g.s.internal.ClouddriverService : <--- HTTP 200 http://spin-clouddriver.spinnaker:7002/applications/notificationms/serverGroups?expand=false (1510ms)
2020-02-08 10:27:03	
2020-02-08 18:27:03.056 INFO 1 --- [-applications-5] c.n.s.g.s.internal.ClouddriverService : ---> HTTP GET http://spin-clouddriver.spinnaker:7002/applications?restricted=false&expand=true
`

this is followed by a stack trace followed by (note timestamp order):
`	2020-02-08 10:27:03	
at retrofit.RetrofitError.networkError(RetrofitError.java:27) ~[retrofit-1.9.0.jar:na]
2020-02-08 10:27:03	
retrofit.RetrofitError: timeout
2020-02-08 10:27:03	
2020-02-08 10:27:03	
2020-02-08 18:27:03.414 ERROR 1 --- [.0-8084-exec-39] c.n.s.g.s.c.AbstractHystrixCommand : Downstream exception encountered (group: 'manifests', command: 'getManifest-kubernetes')
2020-02-08 10:27:03	
2020-02-08 18:27:03.403 INFO 1 --- [rix-manifests-1] c.n.s.g.s.internal.ClouddriverService : ---- END ERROR
`

and another stack trace, followed by:
`	2020-02-08 10:27:03	
at com.netflix.spinnaker.gate.services.commands.AbstractHystrixCommand.handleDownstreamException(AbstractHystrixCommand.groovy:110) ~[gate-core.jar:na]
2020-02-08 10:27:03	
com.netflix.spinnaker.gate.services.commands.ServerErrorException: Internal Server Error
2020-02-08 10:27:03	
2020-02-08 10:27:03	
2020-02-08 18:27:03.421 ERROR 1 --- [.0-8084-exec-39] c.n.s.k.w.e.GenericExceptionHandlers : Internal Server Error
`

Note that, once the deployments become visible in the UI again, I now see this in the logs:
`	2020-02-08 10:46:52	
2020-02-08 18:46:52.110 ERROR 1 --- [.0-8084-exec-50] c.n.s.k.w.e.GenericExceptionHandlers : Service Unavailable
2020-02-08 10:46:52	
2020-02-08 18:46:52.068 ERROR 1 --- [.0-8084-exec-50] c.n.s.g.s.c.AbstractHystrixCommand : (Circuit breaker open| Response Timeout | Semaphore rejected) for group: 'manifests', command: 'getManifest-kubernetes'
2020-02-08 10:46:52	
2020-02-08 18:46:52.068 ERROR 1 --- [.0-8084-exec-50] c.n.s.g.s.c.AbstractHystrixCommand : Downstream exception encountered (group: 'manifests', command: 'getManifest-kubernetes')
`

### Steps to Reproduce:
This error came from trying to view the cluster/deployment details.  I see these errors in my logs when I do other things, too.  I can't tell you those exact steps, though.

### Additional Details:
One interesting thing that may or may not be relevant: this issue happens when I attempt to view an old deployment that has been associated with the wrong application.  It was originally deployed without any labels, so I'm not sure how it ended up in this application.  Anyway, I added the appropriate moniker to my manifests and now the new versions appear in the correct place in the UI.  The old version is still visible in the UI in the old application.

I over allocated resources for clouddriver, just to make sure it's not some kind of performance thing:
    resources:
      limits:
        cpu: 1500m
        memory: 5Gi
      requests:
        cpu: "1"
        memory: 3Gi

Happy to provide whatever other info you want on this.

**Comment by mrothroc** [comment]
More info that may help: I was watching the **spin-gate** logs during a deployment and everything was going well until it had this error:

`2020-02-11 05:19:16.034  INFO 1 --- [rix-manifests-4] c.n.s.g.s.internal.ClouddriverService   
 : ---- ERROR http://spin-clouddriver.spinnaker:7002/manifests/stage/app/Deployment%20filter-s
ervice
2020-02-11 05:19:16.038  INFO 1 --- [rix-manifests-4] c.n.s.g.s.internal.ClouddriverService   
 : java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:224)
        at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)`
(stack trace continues)

I think (but am not positive) that's the very first error that cascades through the system.  The first error I see in the **clouddriver** logs is this one, which has a later timestamp:

`2020-02-11 05:20:25.053  WARN 1 --- [cutionAction-12] c.n.s.c.cache.LoggingInstrumentation    
 : kubernetes:stage/KubernetesMetricCachingAgent[1/1] completed with one or more failures
com.netflix.spinnaker.clouddriver.kubernetes.v2.op.job.KubectlJobExecutor$KubectlException: Co
uld not read metrics: Unable to connect to the server: context deadline exceeded (Client.Timeo
ut exceeded while awaiting headers)
        at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.job.KubectlJobExecutor.topPod(Ku
bectlJobExecutor.java:614) ~[clouddriver-kubernetes-v2.jar:na]
        at com.netflix.spinnaker.clouddriver.kubernetes.v2.security.KubernetesV2Credentials.la`
(stack trace continues)

I don't understand gate well enough to know what connection is timing out.  Everything is running on a k8s cluster and should be able to talk to each other.

**Comment by mrothroc** [comment]
I realized one other piece of info that may be useful: spinnaker is running in a cluster that is different from the cluster it is deploying to.  Not sure if it's relevant but I thought I'd share that, just in case.

**Comment by mrothroc** [comment]
I have resolved this issue in my cluster by switching to cloud redis.  I had verified that the cluster redis was working and successfully connected to it from a shell in the clouddriver pod.  I don't know why spinnaker couldn't connect, but I'm putting this here for future searchers.

Also, it would be useful for the error messages to make it very clear that the components can't connect to redis instead of a generic "SocketTimeoutException" message.  It would save a LOT of time in troubleshooting.

**Comment by maggieneterval** [comment]
Thanks for the detailed report and resolution, @mrothroc! This will be super helpful if other users run into a similar issue. We would definitely accept a pull request clarifying the error messaging here as well. Thanks again!

**Comment by mrothroc** [comment]
It turns out this was not the root cause.  Maybe restarting the containers to change the pointer to the cloud redis reset things for a while, but now the error has returned.

I did notice a couple of things in the log, though.  First, note the pattern of memory usage in the attached graph.  I've given cloud driver 5 gig and in hits that limit.  I have verified this:
JAVA_OPTS:               -XX:+UseContainerSupport -XX:MaxRAMPercentage=40.0
so it shouldn't be doing that.

I also noticed this errors with the readiness probe.  My guess is that the original "SocketTimeoutException" is a red herring.  Instead, k8s marks cloud driver as unready, which means it has no ready workloads for the service.  Connections to the service would fail immediately, probably with a 502.  I could see how this might be incorrectly reported as a timeout if there is a bug in the exception handler.

It looks like the ready probe is failing because it runs out of memory.  I see things like "failed to spawn thread" and "socket accept failed out of memory" in the logs, so basically Bad Things are happening and it's hard to tell the root cause here.

Any ideas on how I can find who is sucking up all the memory?  I don't have much, maybe < 20 apps over three accounts.
![Screen Shot 2020-02-14 at 2 25 28 PM](https://user-images.githubusercontent.com/5827718/74573630-faee3e80-4f35-11ea-8148-f6a328948e58.png)

**Comment by iiro** [comment]
This is very weird... How does your CPU usage look when this happens? Clouddriver loves CPU sometimes even moer than memory...

**Comment by mrothroc** [comment]
The CPU stays pretty constant--the second graph in the screenshot is representative.  I've allocated 1500m and it stays pegged pretty close to that.  It's doing that now, even though the system is idle.
<img width="1604" alt="Screen Shot 2020-02-16 at 10 33 00 AM" src="https://user-images.githubusercontent.com/5827718/74612277-b6d77700-50b8-11ea-8e24-54b52df8d6e5.png">

**Comment by ezimanyi** [comment]
It looks based on this that your clouddriver (or one of the other microservices) may not be appropriately sized for the workloads you're running.  Given that this doesn't appear to be a bug in Spinnaker, I'd suggest reaching out to other operators on Slack or join a meeting of the Kubernetes SIG for more help with this.
