### ISSUE TITLE
Docker repository validation fails if no tags

### ISSUE THREAD

**Issue by kskewes** [spinnaker/spinnaker#5439]
### Issue Summary:

Halyard config validation fails if Docker repository has no images/tags.

### Cloud Provider(s):

Docker Hub - may affect other

### Environment:

Halyard latest stable docker image running locally.

### Feature Area:

Halyard

### Description:

Expect Halyard to check permissions to access Docker Repository and to succeed even if there are no images in the repository (empty tag list `404` is different from permission denied?).

### Steps to Reproduce:

1. Create a new Docker Hub repository and setup permissions for Spinnaker but don't push images.
2. Add a new docker repository to a Docker Hub account in `.hal/config`. 
3. run `hal config` or `hal deploy`

### Additional Details:

```
bash-5.0$ hal config                                                                                
+ Get current deployment                                                                     
  Success                                                    
- Get deployment configuration                                    
  Failure                                                                                 
Validation in                                                                                    
  default.provider.dockerRegistry.dockerhub-myaccount:     
! ERROR Unable to fetch tags from the docker repository:                  
  myorg/myimage, 404 Not Found                                       
? Can the provided user access this repository?    

bash-5.0$ hal --version
Unknown
```

```
$ docker images | grep halyard
gcr.io/spinnaker-marketplace/halyard                                                stable                                20569b6d34ec        5 days ago          567MB
```

**Comment by kskewes** [comment]
```
2020-02-12 19:59:16.114  INFO 1 --- [      Thread-11] c.n.s.h.core.tasks.v1.DaemonTaskHandler  : Message by [Get deployment configuration] (762cc209-eb4f-42a9-bbeb-3b7c1f149e06) - RUNNING: Validating telemetry with HalconfigValidator                                                                                                                                                                                             
2020-02-12 19:59:16.114  INFO 1 --- [      Thread-11] c.n.s.h.c.services.v1.ValidateService    : Ran 2 validators for node "telemetry" with class "Telemetry"                                                      2020-02-12 19:59:16.123 ERROR 1 --- [      Thread-11] c.n.s.halyard.core.DaemonResponse        : Unknown exception encountered:                                                                                    
                                                                                                                                                                                                                   com.netflix.spinnaker.halyard.core.error.v1.HalException: Unable to fetch tags from the docker repository: myorg/my-image, 404 Not Found                                                
        at com.netflix.spinnaker.halyard.core.problem.v1.ProblemSet.throwifSeverityExceeds(ProblemSet.java:104) ~[halyard-core.jar:na]                                                                                     at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:116) ~[halyard-core.jar:na]                                                                            
        at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core.jar:na]                                                                                   at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_242]                                                                                                                                                   
                                                                                                                                                                                                                   2020-02-12 19:59:16.124  INFO 1 --- [      Thread-11] c.n.s.h.core.tasks.v1.TaskRepository     : Task [Get deployment configuration] (762cc209-eb4f-42a9-bbeb-3b7c1f149e06) - RUNNING failed with HalException:    
                                                                                                                                                                                                                   com.netflix.spinnaker.halyard.core.error.v1.HalException: Unable to fetch tags from the docker repository: myorg/my-image, 404 Not Found                                                
        at com.netflix.spinnaker.halyard.core.problem.v1.ProblemSet.throwifSeverityExceeds(ProblemSet.java:104) ~[halyard-core.jar:na]                                                                                     at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:116) ~[halyard-core.jar:na]                                                                            
        at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core.jar:na]                                                                                   at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_242]      
```

**Comment by ezimanyi** [comment]
@kskewes : This isn't great, though it is documented [here](https://www.spinnaker.io/setup/install/providers/docker-registry/#prerequisites).  (Though it looks like the documentation states it's a warning rather than an error...)

In general the plan for Halyard is to replace it with a combination of a new tool called `kleat` and using `kustomize` to deploy, allowing better integration into the kubernetes ecosystem.  Along with those changes, we will be doing much lighter validation to avoid cases like this where overzealous validation blocks workflows.  The RFC for that project is [here](https://github.com/spinnaker/governance/blob/master/rfc/halyard-lite.md).

So all that to say, I'd happily review a PR if there is an easy way to short-circuit this, but am focusing my efforts now on the new pathway.  You should also be able to get pas the warning/error by passing the `--no-validate` flag to Halyard.

**Comment by kskewes** [comment]
Thanks Eric, must admit hadn't checked docs for update, sorry.
Plans sound great, have been following RFC.
