### ISSUE TITLE
Pipeline permissions broken in 1.18.2 

### ISSUE THREAD

**Issue by adityaparamesh** [spinnaker/spinnaker#5466]
### Issue Summary:
After 1.18.2 upgrade , we are unable to add pipeline permissions . It always errors out with "There was an error saving your pipeline: Access denied to application  - required authorization: EXECUTE."

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker 1.18.2 running on Kubernetes

### Feature Area:
Pipelines , Pipeline permissions 

### Description:
Adding a LDAP group as pipeline permissions fails even though the group at the application level has  read, write and execute permissions . However I can see that  a managed service account has been created (curl -v http://<FRONT50 IP>:8080/serviceAccounts) . When trying to do a fiat sync , there are a bunch of errors like the one below which makes me think a ldap search is being done for a managed service account which doesnt look right 

**Fiat Logs during sync**
```
2020-02-19 06:21:00.394 ERROR 1 --- [0.0-7003-exec-2] c.n.s.f.r.ldap.LdapUserRolesProvider     : [] Unable to find a single user entry
org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 0
```

**FRONT50 logs:**

```
INFO 1 --- [0.0-8080-exec-3] c.n.spinnaker.fiat.shared.FiatService    : <--- HTTP 404 http://spin-fiat.infra-spinnaker:7003/authorize/6cf375c6-8491-4e0d-97e4-e74c84001cc3%40managed-service-account (4ms)
2020-02-19 06:43:20.607 ERROR 1 --- [0.0-8080-exec-3] c.n.s.f.shared.FiatPermissionEvaluator   : Cannot get whole user permission for user 6cf375c6-8491-4e0d-97e4-e74c84001cc3@managed-service-account, reason: 404  (fallbackAccounts: '')
2020-02-19 06:43:20.607 ERROR 1 --- [0.0-8080-exec-3] c.n.s.f.c.AuthorizationSupport           : Service account 6cf375c6-8491-4e0d-97e4-e74c84001cc3@managed-service-account does not have access to application testmp
2020-02-19 06:43:20.609 ERROR 1 --- [0.0-8080-exec-3] n.s.f.s.FiatAccessDeniedExceptionHandler : Encountered exception while processing request POST:/pipelines with headers={content-length=5851, x-spinnaker-execution-id=01E1E2YXS87CQCW8380N87FYFP:01E1E2YXS8C652E9RPPSY49WD4:2, x-spinnaker-request-id=01E1E2YXS87CQCW8380N87FYFP:01E1E2YXS8C652E9RPPSY49WD4:2:00e2daa1-3c9f-40ab-a395-0698bc1111ee, x-spinnaker-application=testmp, host=spin-front50.infra-spinnaker:8080, content-type=application/json; charset=UTF-8, connection=Keep-Alive
```

This works seamlessly on 1.17.x 

### Steps to Reproduce:
Configure LDAP for AuthZ and try adding pipeline permission on spinnaker 1.18.2

**Comment by rrijkse** [comment]
I am getting the same issue on `master-latest-unvalidated` with Google Oauth enabled for our regular users. After turning debugging on for fiat this is what it is returning:

```2020-03-26 16:05:45.595  INFO 1 --- [0.0-7003-exec-2] c.n.s.f.p.RedisPermissionsRepository     : [USR@DOMAIN.COM] Resource: ACCOUNT; map size: 1
2020-03-26 16:05:45.595  INFO 1 --- [0.0-7003-exec-2] c.n.s.f.p.RedisPermissionsRepository     : [USR@DOMAIN.COM] Resource: APPLICATION; map size: 2
2020-03-26 16:05:45.595  INFO 1 --- [0.0-7003-exec-2] c.n.s.f.p.RedisPermissionsRepository     : [USR@DOMAIN.COM] Resource: SERVICE_ACCOUNT; map size: 3
2020-03-26 16:05:45.596  INFO 1 --- [0.0-7003-exec-2] c.n.s.f.p.RedisPermissionsRepository     : [USR@DOMAIN.COM] Resource: ROLE; map size: 4
2020-03-26 16:05:45.596  INFO 1 --- [0.0-7003-exec-2] c.n.s.f.p.RedisPermissionsRepository     : [USR@DOMAIN.COM] Resource: BUILD_SERVICE; map size: 5
2020-03-26 16:05:45.596 DEBUG 1 --- [0.0-7003-exec-2] c.n.s.f.controllers.AuthorizeController  : [USR@DOMAIN.COM] Returning fallback permissions (user: 9e6f8249-c617-494a-97b9-5f25139997cf@managed-service-account, accounts: [], roles: [])```

The service account is definitely present in Front50 ```{"name":"9e6f8249-c617-494a-97b9-5f25139997cf@managed-service-account","lastModified":1585238742000,"lastModifiedBy":"USR@DOMAIN.COM","memberOf":["spinnaker-devops"]}```

**Comment by anton-yurchenko** [comment]
We have a similar issue right after an upgrade to 1.19.1 (sorry I do not remember the previous version) with GitHub authz.

Adding a group on a pipeline fails with: 
```
Could not save pipeline.

Reason: Pipeline save operation did not succeed: 01E4CDSZ1DVCN328W3AQ0EPCHR (status: TERMINAL)
```

**front50 logs**:
```
2020-03-26 22:01:38.858  INFO 1 --- [0.0-8080-exec-1] c.n.spinnaker.fiat.shared.FiatService    : ---> HTTP GET http://spin-fiat.spinnaker:7003/authorize/<username>
2020-03-26 22:01:38.866  INFO 1 --- [0.0-8080-exec-1] c.n.spinnaker.fiat.shared.FiatService    : <--- HTTP 200 http://spin-fiat.spinnaker:7003/authorize/<username> (7ms)
2020-03-26 22:01:39.923  INFO 1 --- [0.0-8080-exec-7] c.n.spinnaker.fiat.shared.FiatService    : ---> HTTP GET http://spin-fiat.spinnaker:7003/authorize/f3887a37-62f7-482c-bba9-350c4f34ab43%40managed-service-account
2020-03-26 22:01:39.931  INFO 1 --- [0.0-8080-exec-7] c.n.spinnaker.fiat.shared.FiatService    : <--- HTTP 404 http://spin-fiat.spinnaker:7003/authorize/f3887a37-62f7-482c-bba9-350c4f34ab43%40managed-service-account (7ms)
2020-03-26 22:01:39.932 ERROR 1 --- [0.0-8080-exec-7] c.n.s.f.shared.FiatPermissionEvaluator   : Cannot get whole user permission for user f3887a37-62f7-482c-bba9-350c4f34ab43@managed-service-account, reason: 404  (fallbackAccounts: '')
2020-03-26 22:01:39.932 ERROR 1 --- [0.0-8080-exec-7] c.n.s.f.c.AuthorizationSupport           : Service account f3887a37-62f7-482c-bba9-350c4f34ab43@managed-service-account does not have access to application <app-name>
2020-03-26 22:01:39.936 ERROR 1 --- [0.0-8080-exec-7] n.s.f.s.FiatAccessDeniedExceptionHandler : Encountered exception while processing request POST:/pipelines with headers={content-length=2459, x-spinnaker-execution-id=01E4CDSZ1DVCN328W3AQ0EPCHR:01E4CDSZ1J99G84FS21F6ECAHG:2, x-spinnaker-request-id=01E4CDSZ1DVCN328W3AQ0EPCHR:01E4CDSZ1J99G84FS21F6ECAHG:2:bdc469df-a83b-4491-91c4-53ce80458ed0, x-spinnaker-application=<app-name>, host=spin-front50.spinnaker:8080, content-type=application/json; charset=UTF-8, connection=Keep-Alive, x-spinnaker-user=<username>, x-spinnaker-accounts=<account-1>,<account-2>,<account-3>,<account-4>,<account-5>, accept-encoding=gzip, user-agent=Spinnaker-unknown/1.0}
```

Syncing, however, succedes at our case, but service-account does not seem to be synced.
**fiat**:
```
➜ curl http://localhost:7003/authorize/f3887a37-62f7-482c-bba9-350c4f34ab43@managed-service-account
{
  "timestamp" : 1585260139492,
  "status" : 404,
  "error" : "Not Found",
  "message" : "No message available"
}
```
**front50**:
```
➜ curl http://localhost:8080/serviceAccounts
[...]
  {
    "name": "f3887a37-62f7-482c-bba9-350c4f34ab43@managed-service-account",
    "lastModified": 1585259148000,
    "lastModifiedBy": "<username>",
    "memberOf": [
      "<group-1>"
    ]
  },
[...]
```
---
Copying a pipeline with an already configured permissions results in exactly the same behavior but a slight difference that a service account is not found by `curl http://localhost:8080/serviceAccounts`

**Comment by ealebed** [comment]
We have a similar issue after an upgrade to 1.19.2, in our case we use authz File:
```
    authz:
      groupMembership:
        service: FILE
        file:
          roleProviderType: FILE
          path: /home/spinnaker/.hal/userrole.yaml
      enabled: true
```

**Comment by jaredstehler** [comment]
I'm seeing the same issue on upgrading from 1.18.6 to 1.19.2 as @anton-yurchenko ; seeing 404 in the logs for service account users:

```
2020-03-27 20:58:14.170  INFO 1 --- [oScheduler-3562] c.n.spinnaker.fiat.shared.FiatService    : ---> HTTP GET http://spin-fiat.spinnaker:7003/authorize/ci-service-account%40spinnaker.ops
2020-03-27 20:58:14.178  INFO 1 --- [oScheduler-3562] c.n.spinnaker.fiat.shared.FiatService    : <--- HTTP 404 http://spin-fiat.spinnaker:7003/authorize/ci-service-account%40spinnaker.ops (7ms)
2020-03-27 20:58:14.270  WARN 1 --- [oScheduler-3562] c.n.s.f.shared.FiatPermissionEvaluator   : getUserPermission for ci-service-account@spinnaker.ops failed. Retrying in 1125ms

retrofit.RetrofitError: 404 
        at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
        at com.sun.proxy.$Proxy186.getUserPermission(Unknown Source) ~[na:na]
        at com.netflix.spinnaker.fiat.shared.FiatPermissionEvaluator.lambda$null$3(FiatPermissionEvaluator.java:283) ~[fiat-api-1.14.0.jar:1.14.0]
        at com.netflix.spinnaker.fiat.shared.FiatPermissionEvaluator$ExponentialBackoffRetryHandler.retry(FiatPermissionEvaluator.java:99) ~[fiat-api-1
.14.0.jar:1.14.0]
        at com.netflix.spinnaker.fiat.shared.FiatPermissionEvaluator.lambda$null$4(FiatPermissionEvaluator.java:281) ~[fiat-api-1.14.0.jar:1.14.0]
        at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:92) ~[kork-security-7.25.1.jar:7.25.1]
        at com.netflix.spinnaker.fiat.shared.FiatPermissionEvaluator.lambda$getPermission$5(FiatPermissionEvaluator.java:298) ~[fiat-api-1.14.0.jar:1.1
```

**Comment by dbrougham** [comment]
I have been able to observe this issue moving from 1.18.8 to 1.19.0.

I am trying to use the spin cli tool to save a pipeline. The pipeline has a trigger with no runAsUser. In 1.18.8, when spin save is run for the first time for the pipeline a managed service account is generated behind the scenes and the runAsUser is updated to this new managed service account.

My guess is that something is going wrong generating this service account? Using the API I have checked and can see that it hasn't been generated.

**Comment by tiggerlee2** [comment]
It seems that fiat can not sync serviceAccounts to Redis.

**Comment by al-jamf** [comment]
Stumbled upon this change this morning which I think should fix the issue https://github.com/spinnaker/fiat/commit/b47aef41582d3ca404dd5f63baab568b5596a8d8.

As a fix rolled back our imageVariant to JAVA8 per the release notes https://www.spinnaker.io/community/releases/versions/1-19-0-changelog

**Comment by tiggerlee2** [comment]
Hi @aformyname, only 1.18.1 fix this issue?

**Comment by sofam** [comment]
We are also hit by this.

**Comment by danopia** [comment]
The 1.19.6 release includes a fix for fiat's service account creation: https://www.spinnaker.io/community/releases/versions/1-19-6-changelog

**Comment by adityaparamesh** [comment]
I can confirm that this is working on 1.19.6

**Comment by bcornils** [comment]
@adityaparamesh are you ok to close this?

**Comment by rrijkse** [comment]
@bcornils I can confirm this is working in 1.20.0 as well.

**Comment by adityaparamesh** [comment]
@bcornils Yes this can be closed . Thanks everyone
