### ISSUE TITLE
Plugins should allow the use of common subprojects between services

### ISSUE THREAD

**Issue by claymccoy** [spinnaker/spinnaker#5471]
### Issue Summary:
This plugin (https://github.com/spinnaker-plugin-examples/pf4jPluginWithoutExtensionPoint) uses the bundler and has SecretEngine extension points for both orca and clouddriver. The code is the same in both places. I tried creating another subproject that both could depend on and had most of the common code, but got NoClassDef errors when trying to run Orca with the plugin zip.
I tried to share PF4J stuff in the common project first, and then just some of the basic stuff that wasn't core to Pf4J. It looked like it produced a reasonable bundle as long as I defined the extension point and plugin in the service projects, even if they extended base classes with the real functionality. the Manifests, .idx files where there and Orca could find the plugins. But the NoClassDef kept it from starting. Not sure if this could be fixed with the bundler or modifying the way kork loads projects.
If this worked, then it would also be nice if debug mode using plugin refs allowed me to change code in the common subproject and see the change reflected in the running service. I didn't get far enough to test this since the plugin doesn't load.
It would be nice to be able to share code between service modules, especially for endpoints like SecretEngine that span services and should be consistent.

### Cloud Provider(s):
none

### Environment:
local dev

### Feature Area:
plugins

### Steps to Reproduce:
Take a multi service plugin like https://github.com/spinnaker-plugin-examples/pf4jPluginWithoutExtensionPoint. Make another subproject with some shared code. Make the orca and clouddriver modules depend on it. Release the bundle and run the zip in Orca. When the plugin starts, that shared code will cause a NoClassDef error.

**Comment by claymccoy** [comment]
@cfieber @robzienert

**Comment by claymccoy** [comment]
@jonsie I created this repo to show the problem with trying to share a common subproject. When you load the plugin in Orca you get this:
```
java.lang.NoClassDefFoundError: io/armory/secrets/silly/AbstractSillySecretEngine
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:112)
	at com.netflix.spinnaker.kork.plugins.ExtensionBeanDefinitionRegistryPostProcessor.postProcessBeanFactory(ExtensionBeanDefinitionRegistryPostProcessor.kt:103)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:130)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at org.springframework.boot.builder.SpringApplicationBuilder$run$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at com.netflix.spinnaker.orca.Main.main(Main.groovy:104)
```

**Comment by claymccoy** [comment]
Fixed here: https://github.com/spinnaker/spinnaker-gradle-project/pull/123
