### ISSUE TITLE
Unable to load GCE healthchecks to configure Autohealing in spinnaker pipeline

### ISSUE THREAD

**Issue by anilvasi** [spinnaker/spinnaker#5472]
### Issue Summary:
Spinnaker pipeline not able to load all healthchecks to configure for autohealing for GCE instance groups. 

Error:
2020-02-19 19:01:42.803  WARN 1 --- [tionAction-1863] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.google.provider.GoogleInfrastructureProvider:<projectid>/GoogleHealthCheckCachingAgent completed with one or more failures

java.lang.IllegalArgumentException: null
	at sun.reflect.GeneratedMethodAccessor847.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.7.jar:2.5.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.7.jar:2.5.7]
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2754) ~[groovy-2.5.7.jar:2.5.7]
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3809) ~[groovy-2.5.7.jar:2.5.7]
	at com.netflix.spinnaker.clouddriver.google.model.GoogleHealthCheck.setProperty(GoogleHealthCheck.groovy) ~[clouddriver-google.jar:na]
	at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:213) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:496) ~[groovy-2.5.7.jar:2.5.7]
	at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHealthCheckCachingAgent$_loadHealthChecks_closure6.doCall(GoogleHealthCheckCachingAgent.groovy:166) ~[clouddriver-google.jar:na]
	at sun.reflect.GeneratedMethodAccessor1161.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.7.jar:2.5.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.7.jar:2.5.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.7.jar:2.5.7]
	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.7.jar:2.5.7]
	at groovy.lang.Closure.call(Closure.java:421) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2330) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2315) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2356) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.dgm$186.invoke(Unknown Source) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) ~[groovy-2.5.7.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) ~[groovy-2.5.7.jar:2.5.7]
	at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHealthCheckCachingAgent.loadHealthChecks(GoogleHealthCheckCachingAgent.groovy:149) ~[clouddriver-google.jar:na]
	at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHealthCheckCachingAgent.loadData(GoogleHealthCheckCachingAgent.groovy:57) ~[clouddriver-google.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:85) ~[cats-core.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:75) ~[cats-core.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:335) ~[cats-redis.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:305) ~[cats-redis.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212

### Environment:
Spinnaker version: 1.17.6 
Deployed using halyard in GKE

- The SA being used by spinnaker has permissions to get all Healthchecks available in the project.

**Comment by anilvasi** [comment]
Anyone faced similar issue ?

**Comment by cfieber** [comment]
@plumpy not sure how you folks typically triage GCE issues, any suggestions here

**Comment by maggieneterval** [comment]
Hi @anilvasi, thanks for taking the time to open this issue and apologies for the delayed reply. I have a few followup questions to help us pinpoint the issue here.

> Spinnaker pipeline not able to load all healthchecks to configure for autohealing for GCE instance groups.

How exactly is this manifesting? Is the configure server group wizard failing to populate any health checks at all, or are there a specific subset that you noticed are missing from the available options? Are any network requests failing? Are there any browser console errors?

Based on the excerpt you shared from your Clouddriver logs, perhaps the caching agent responsible for GCE health checks is failing to read the `port` on an HTTP health check ([Here is the line in the code your logs point to](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/GoogleHealthCheckCachingAgent.groovy#L166).). Perhaps one of your health checks is not of the shape the caching agent expects. It would be helpful if we could pinpoint the specific health check causing this error; would it be possible for you to attach a remote debugger to Clouddriver with a breakpoint in the caching agent in order to identify the problematic health check?

Thanks!

**Comment by anilvasi** [comment]
Hi @maggieneterval , 
Thanks for looking into the issue. I tried to check issue in another spinnaker instance but able to reproduce there as well.  Spinnaker(1.17.8) is setup with halyard(1.28.0) on GKE. 

The GCE account config in hal config 
      - name: <name>
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        project: <projectname>
        jsonPath: "<serviceaccount json location.json>"
        alphaListed: false
        imageProjects:
        - <projectname>
        consul:
          enabled: false
          agentEndpoint: localhost
          agentPort: 8500
          datacenters: []

Same error is coming as mentioned early. There are no legacy healthchecks in this project and all are of type TCP and HTTP. In the new spinnaker instance we are not seeing any healthchecks being loaded and i see previously loaded health checks for different old project. Not sure if any versions upgrades created this issue.

What is the criteria for health check in order to be loaded? and which is causing illegal argument exception is not clear for me. I never triaged with remote debugging to any of spinnaker services before, can you provide any instructions on this? Thanks.

**Comment by maggieneterval** [comment]
Hi @anilvasi, thanks for the additional information!

> In the new spinnaker instance we are not seeing any healthchecks being loaded and i see previously loaded health checks for different old project.

This issue is likely unrelated to the exception you're seeing in the Clouddriver logs. Could you please try clearing your browser's local storage cache? If you are using Chrome, you can do this by opening the browser console, navigating to the Application tab, and right clicking on Local Storage (under the Storage header on the left-hand side) and clicking "Clear." Once you've cleared the local storage cache, try refreshing the page with the Network tab open to ensure that a fresh request is being made for health checks. This should look something like: `http://{your_gate_endpoint}/search?allowShortQuery=true&pageSize=500&q=&type=healthChecks`. Does that response now include the expected health checks?

> There are no legacy healthchecks in this project and all are of type TCP and HTTP.

Thanks for checking on this. I was able to reproduce the exact exception you are seeing by having the code artificially set the HTTP health checks' `port` to `null`. Would you mind checking your project's HTTP health checks to ensure that each has an integer `port` as expected? You could do this either in the GCP UI (Under Compute Engine --> Health Checks, filter by `HTTP` and scan the `port` column to ensure there are no missing/non-integer values there), or the [gcloud CLI](https://cloud.google.com/sdk/gcloud/reference/compute/health-checks/list) if that's easier. I thought this might be an easier first step to quickly check to make sure none of the HTTP health checks are obviously malformed, since setting up a remote debugger is a bit of work.

Thanks; hope all is well!

**Comment by anilvasi** [comment]
Hi @maggieneterval , 

Thanks. I have verified both before itself.  Have created busybox in the spinnaker namespace and ran 
https://spin-gate:8084/search?allowShortQuery=true&pageSize=500&q=&type=healthChecks
which is not giving health checks of the newly added project.  Is it the call which actually initiates call to load compute healthchecks? or it is only to pull from cache.  Also host headers are not mandatory for http health checks right for clouddriver to pull ?

Also all health checks have valid port numbers.  

Thanks,
Anil

**Comment by maggieneterval** [comment]
Hi @anilvasi, thanks for the update.

> Have created busybox in the spinnaker namespace and ran
https://spin-gate:8084/search?allowShortQuery=true&pageSize=500&q=&type=healthChecks
which is not giving health checks of the newly added project.

Just to clarify, is it returning health checks that are associated with a project whose account you have since removed from Spinnaker? Did updating your credentials coincide with the first manifestation of this issue? Or was this working on a previous version of Spinnaker, and this issue began to occur after upgrading?

> Is it the call which actually initiates call to load compute healthchecks? or it is only to pull from cache. 

The `/search` call reads from Clouddriver's cache (Clouddriver periodically polls GCE in order to write to the cache, but the `/search` call is not doing a live lookup.). I'm wondering if you've somehow ended up with stale data in your cache that needs to be cleared. Would you feel comfortable flushing Clouddriver's cache and tailing the logs while it re-populates to see if we encounter any errors?

> Also host headers are not mandatory for http health checks right for clouddriver to pull ?

Right, I do not think host headers are mandatory. Per the docs, `If omitted, the IP address of the load balancer's forwarding rule is used.` My dev Spinnaker is successfully caching health checks without host heads so I don't think this is the issue.

**Comment by anilvasi** [comment]
Hi @maggieneterval ,

Thanks for the response. It is returning health checks for the project whose account was added many days back(older spinnaker version). I did not try updating credentials as it has compute admin, compute load balancer admin roles.  I am suspecting it is because new version of spinnaker as i am seeing this issue for almost all new projects i added. 

I have added new accounts for which no cache exist and seeing issue. Do you mean clearing clouddriver's cache of old accounts is needed here to check the issue?  how can we flush clouddriver's cache of particular account?  

Have you verified by creating multiple healthchecks of http, tcp type and able to fetch during pipeline setup for autohealing policy for gce deploy stage? 
<img width="779" alt="Screen Shot 2020-03-30 at 11 15 01 AM" src="https://user-images.githubusercontent.com/1965928/77946803-ca5d2c80-7277-11ea-9e08-b5ec20a2132a.png">

Thanks,
Anil V

**Comment by maggieneterval** [comment]
Hi @anilvasi, thanks for the reply.

>  It is returning health checks for the project whose account was added many days back(older spinnaker version).

Sorry, just to make sure I'm understanding here, has this account since been removed from your halconfig? Are the steps to reproduce the following:
1) add account A,
2) add account B, 
3) observe that only health checks from account A are returned (in which case, the singular issue is the omission of account B's health checks)

Or was there an additional step of removing account A from your halconfig, in which case, there are two issues: 1) that account A's health checks haven't been purged from the cache, and 2) the omission of account B's health checks.

> Have you verified by creating multiple healthchecks of http, tcp type and able to fetch during pipeline setup for autohealing policy for gce deploy stage?

Yep, I've created multiple health checks of each type and all are populating as expected. That said, I haven't experimented with adding/removing multiple accounts so based on your answer to my question I can attempt to reproduce again.

One other question: are you using a MySQL or Redis backend for Clouddriver? If MySQL, there was actually an opt-in cleanup agent added with Spinnaker 1.18 (instructions for configuring in our [changelog](https://www.spinnaker.io/community/releases/versions/1-18-0-changelog#clouddriver-cache-cleanup-agent)). As far as I'm aware this was only tested with AWS and Kubernetes but you could give upgrading and enabling that a try next if you're using the MySQL backend.

Thanks!

**Comment by anilvasi** [comment]
Hi @maggieneterval ,

sorry for the delay. Account has not been removed after adding it.  Account A was added few months back for which i am seeing health checks without issue.    We added new account Account B for which we are not seeing health checks loaded and getting above issue. 

Steps to reproduce: 
Just add new account and see health checks are being displayed for autohealing policy drop down in GCE deploy stage. 
Spinnaker version :  1.19.2(have upgraded to latest to see if it fixes but no luck)
clouddriver : 6.7.1-20200319123809
halyard: 1.32.0

Error:
2020-04-09 01:15:58.904  WARN 1 --- [tionAction-8884] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.google.provider.GoogleInfrastructureProvider:<project>/GoogleHealthCheckCachingAgent completed with one or more failures

java.lang.IllegalArgumentException: null
	at jdk.internal.reflect.GeneratedMethodAccessor752.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.9.jar:2.5.9]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.9.jar:2.5.9]
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2754) ~[groovy-2.5.9.jar:2.5.9]
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3809) ~[groovy-2.5.9.jar:2.5.9]
	at com.netflix.spinnaker.clouddriver.google.model.GoogleHealthCheck.setProperty(GoogleHealthCheck.groovy) ~[clouddriver-google.jar:na]
	at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:213) ~[groovy-2.5.9.jar:2.5.9]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:496) ~[groovy-2.5.9.jar:2.5.9]
	at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHealthCheckCachingAgent$_loadHealthChecks_closure6.doCall(GoogleHealthCheckCachingAgent.groovy:166) ~[clouddriver-google.jar:na]
	at jdk.internal.reflect.GeneratedMethodAccessor1045.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.9.jar:2.5.9]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.9.jar:2.5.9]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.9.jar:2.5.9]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.9.jar:2.5.9]
	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.9.jar:2.5.9]
	at groovy.lang.Closure.call(Closure.java:421) ~[groovy-2.5.9.jar:2.5.9]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2330) ~[groovy-2.5.9.jar:2.5.9]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2315) ~[groovy-2.5.9.jar:2.5.9]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2356) ~[groovy-2.5.9.jar:2.5.9]
	at org.codehaus.groovy.runtime.dgm$186.invoke(Unknown Source) ~[groovy-2.5.9.jar:2.5.9]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244) ~[groovy-2.5.9.jar:2.5.9]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) ~[groovy-2.5.9.jar:2.5.9]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) ~[groovy-2.5.9.jar:2.5.9]
	at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHealthCheckCachingAgent.loadHealthChecks(GoogleHealthCheckCachingAgent.groovy:149) ~[clouddriver-google.jar:na]
	at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHealthCheckCachingAgent.loadData(GoogleHealthCheckCachingAgent.groovy:57) ~[clouddriver-google.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:85) ~[cats-core.jar:na]
	at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:75) ~[cats-core.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:338) ~[cats-redis.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:308) ~[cats-redis.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

Thanks,
Anil

**Comment by maggieneterval** [comment]
Hey @anilvasi hope all is well! Unfortunately I'm still not able to reproduce the issue you're experiencing; would you mind sending over the result of running `gcloud compute health-checks list --format json --project {your_problematic_account's_project}`? That stack trace makes me think we may have some malformed health check in the mix. Thanks!

**Comment by maggieneterval** [comment]
Going to close this issue for now since I haven't heard back for quite a while, but please feel free to re-open if you're still experiencing this issue and can provide the additional information I requested in my last comment. Thank you!

**Comment by qllb** [comment]
I've had the same issue

Some of the health checks in list `gcloud compute health-checks list --format json --project {your_problematic_account's_project}
` had empty "port", but  "portSpecification": "USE_SERVING_PORT" instead.

The issue disappeared after I explicitly set port number in every health check of the project.
