### ISSUE TITLE
Gate: ERR unknown command `CONFIG`

### ISSUE THREAD

**Issue by axot** [spinnaker/spinnaker#5517]
We are trying to use GCP MemoryStore as external Redis.

Here is the error, is it possible to remove `CONFIG` command which MemoryStore does not support.

```
spin-gate-6c5557cb6c-ncnnw gate Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: ERR unknown command `CONFIG`, with args beginning with: `get`, `notify-keyspace-events`, ; nested exception is redis.clients.jedis.exceptions.JedisDataException: ERR unknown command `CONFIG`, with args beginning with: `get`, `notify-keyspace-events`,
```

**Comment by dpolicastro** [comment]
Same problem here using ElastiCache
```
java.lang.IllegalStateException: Unable to configure Redis to keyspace notifications. See https://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisindexedsessionrepository-sessiondestroyedevent
	at org.springframework.session.data.redis.config.ConfigureNotifyKeyspaceEventsAction.getNotifyOptions(ConfigureNotifyKeyspaceEventsAction.java:83) ~[spring-session-data-redis-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.session.data.redis.config.ConfigureNotifyKeyspaceEventsAction.configure(ConfigureNotifyKeyspaceEventsAction.java:57) ~[spring-session-data-redis-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at com.netflix.spinnaker.gate.config.PostConnectionConfiguringJedisConnectionFactory.postProcessConnection(PostConnectionConfiguringJedisConnectionFactory.java:68) ~[gate-web.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:479) ~[spring-data-redis-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:738) ~[spring-data-redis-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: ERR unknown command `CONFIG`, with args beginning with: `get`, `notify-keyspace-events`, ; nested exception is redis.clients.jedis.exceptions.JedisDataException: ERR unknown command `CONFIG`, with args beginning with: `get`, `notify-keyspace-events`,
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:69) ~[spring-data-redis-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:42) ~[spring-data-redis-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) ~[spring-data-redis-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42) ~[spring-data-redis-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:135) ~[spring-data-redis-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.data.redis.connection.jedis.JedisServerCommands.convertJedisAccessException(JedisServerCommands.java:530) ~[spring-data-redis-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.data.redis.connection.jedis.JedisServerCommands.getConfig(JedisServerCommands.java:299) ~[spring-data-redis-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.getConfig(DefaultedRedisConnection.java:1319) ~[spring-data-redis-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.session.data.redis.config.ConfigureNotifyKeyspaceEventsAction.getNotifyOptions(ConfigureNotifyKeyspaceEventsAction.java:76) ~[spring-session-data-redis-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	... 5 common frames omitted
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR unknown command `CONFIG`, with args beginning with: `get`, `notify-keyspace-events`,
	at redis.clients.jedis.Protocol.processError(Protocol.java:132) ~[jedis-3.1.0.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:166) ~[jedis-3.1.0.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:220) ~[jedis-3.1.0.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318) ~[jedis-3.1.0.jar:na]
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:270) ~[jedis-3.1.0.jar:na]
	at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:264) ~[jedis-3.1.0.jar:na]
	at redis.clients.jedis.Jedis.configGet(Jedis.java:2736) ~[jedis-3.1.0.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisServerCommands.getConfig(JedisServerCommands.java:297) ~[spring-data-redis-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	... 7 common frames omitted
```

**Comment by dpolicastro** [comment]
I solved my issue by adding this code to the `gate-local.yml`
```
# profiles/gate-local.yml
redis:
  configuration:
    secure: true
```

**Comment by axot** [comment]
Thank you for sharing the workaround, here is the document https://www.spinnaker.io/setup/productionize/caching/externalize-redis/
