### ISSUE TITLE
Spinnaker Artifact Rewrite: Helm inputArtifacts "account" field not getting populated

### ISSUE THREAD

**Issue by justinrlee** [spinnaker/spinnaker#5533]
### Issue Summary:

If you have the following setup:

* Artifact Rewrite turned on (`hal config features edit --artifacts-rewrite true`)
* GitHub artifact account set up
* HTTP default artifact turned on

And you do the following:

* Set up a helm stage with the HTTP artifact account
* Add a git trigger with an artifact for the values file
* Go to the helm stage and add the values artifact

Then the 'account' field in the Helm stage doesn't get populated, and the stage fails.

I'm not sure if this is incorrect UI behavior (the field should be populated by the UI) or incorrect Rosco behavior (it shouldn't need the field to be populated), but either way, the stage fails with:

```
Failed to fetch helm template: Failed to download artifact: Artifact(type=github/file, customKind=false, name=path/values.yml, version=d5f74200ce577923f30f1478ab8219595c158093, location=null, reference=https://api.github.com/repos/justinrlee/workspace/contents/path/values.yml, metadata=null, artifactAccount=, provenance=null, uuid=null). Error: 500
```

And this is in clouddriver logs:
```
2020-03-03 16:14:45.750 ERROR 1 --- [0.0-7002-exec-6] c.n.s.k.w.e.GenericExceptionHandlers     : Internal Server Error

java.lang.IllegalArgumentException: An artifact account must be supplied to download this artifact:
	at com.netflix.spinnaker.clouddriver.artifacts.ArtifactCredentialsRepository.getCredentials(ArtifactCredentialsRepository.java:55)
	at com.netflix.spinnaker.clouddriver.artifacts.ArtifactDownloader.download(ArtifactDownloader.java:33)
	at com.netflix.spinnaker.clouddriver.controllers.ArtifactController.lambda$fetch$0(ArtifactController.java:65)
	at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:97)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:327)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Generated stage JSON (see `.inputArtifacts[1].account` is equal to `""`)

```
{
  "inputArtifacts": [
    {
      "account": "no-auth-http-account",
      "artifact": {
        "artifactAccount": "no-auth-http-account",
        "id": "330ed6d9-08e9-45a3-90a9-3ab4960917d7",
        "reference": "https://armory-sales-justin-public.s3-us-west-2.amazonaws.com/sample-helm.tgz",
        "type": "http/file"
      }
    },
    {
      "account": "",
      "id": "72cd3220-e032-49df-8471-c398ea8695a8"
    }
  ],
  "name": "Bake (Manifest)",
  "namespace": "spinnaker",
  "outputName": "test",
  "overrides": {},
  "templateRenderer": "HELM2",
  "type": "bakeManifest"
}
```

I'm *pretty* sure this is not related: https://github.com/spinnaker/deck/pull/7989

### Cloud Provider(s):

* Kubernetes
* Helm

### Environment:

* Spinnaker 1.18.2

### Feature Area:

* Artifacts, UI

### Description:

![Screen Shot 2020-03-03 at 11 19 57 AM](https://user-images.githubusercontent.com/4943268/75802786-4765b680-5d4b-11ea-9efb-ac1472a8aa3f.png)

### Additional Details:

Video of reproduction: https://s.armory.io/p9uKwBYg

**Comment by maggieneterval** [comment]
Thanks for reporting, @justinrlee. A fix will be backported to the next patch release of each supported version (1.17, 1.18, 1.19).
