### ISSUE TITLE
Triggering a pipeline with Artifactory for a Helm chart fails with error 500

### ISSUE THREAD

**Issue by angelcervilla** [spinnaker/spinnaker#5554]
### Issue Summary:
Recently we updated our Spinnaker instance to 1.18.4, as we were very interested to trigger pipelines when a new chart gets into Artifactory.

So, after setting up:
- A Helm artifact repository with its credentials called _virtual-helm-test_
- An Artifactory repository search called _artifactory2_
- And enabling the _artifacts_rewrite_  option for the UI

Then we created a basic pipeline, which contains a trigger, and a Bake stage (to check the functionality). When we upload a helm chart, the pipeline gets successfully triggered, but it fails after some seconds, returning a 500 error.

After further investigation we can see this in Clouddriver:
```java
2020-03-09 11:51:11.405 ERROR 1 --- [0.0-7002-exec-8] c.n.s.k.w.e.GenericExceptionHandlers     : Internal Server Error

java.lang.IllegalArgumentException: An artifact account must be supplied to download this artifact:
        at com.netflix.spinnaker.clouddriver.artifacts.ArtifactCredentialsRepository.getCredentials(ArtifactCredentialsRepository.java:55) ~[clouddriver-artifacts.jar:na]
        at com.netflix.spinnaker.clouddriver.artifacts.ArtifactDownloader.download(ArtifactDownloader.java:33) ~[clouddriver-artifacts.jar:na]
        at com.netflix.spinnaker.clouddriver.controllers.ArtifactController.lambda$fetch$0(ArtifactController.java:65) ~[clouddriver-web.jar:na]
        at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:110) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:97) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:327) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_242]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_242]
```
I'm sure that this is related to #5533, where when you set up the trigger in the UI, you cannot select an artifact account. 
However, I added the Helm artifact account manually in the pipeline, tried again, and now fails with another message:
```java
2020-03-09 12:36:05.363 ERROR 1 --- [0.0-7002-exec-7] c.n.s.k.w.e.GenericExceptionHandlers     : Internal Server Error

java.lang.IllegalArgumentException: Artifact credentials 'virtual-helm-test' cannot handle artifacts of type 'helm/file'
        at com.netflix.spinnaker.clouddriver.artifacts.ArtifactCredentialsRepository.getCredentials(ArtifactCredentialsRepository.java:61) ~[clouddriver-artifacts.jar:na]
        at com.netflix.spinnaker.clouddriver.artifacts.ArtifactDownloader.download(ArtifactDownloader.java:33) ~[clouddriver-artifacts.jar:na]
        at com.netflix.spinnaker.clouddriver.controllers.ArtifactController.lambda$fetch$0(ArtifactController.java:65) ~[clouddriver-web.jar:na]
        at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:110) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:97) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:327) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_242]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_242]
```
This is how the Bake stage looks like:
```json
{
  "expectedArtifacts": [
    {
      "defaultArtifact": {
        "customKind": true,
        "id": "a0fcd3cb-c9fd-42fa-81fc-7da2190a8145"
      },
      "displayName": "manifest",
      "id": "b6d69cc1-8990-46b7-8546-8ca96e1a647e",
      "matchArtifact": {
        "artifactAccount": "embedded-artifact",
        "id": "25df2fdd-7355-4540-8659-7b1140b6d401",
        "name": "manifest",
        "type": "embedded/base64"
      },
      "useDefaultArtifact": false,
      "usePriorArtifact": false
    }
  ],
  "inputArtifacts": [
    {
      "account": "virtual-helm-test",
      "id": "d2914457-8f79-48bd-913d-08ac29acb95a"
    }
  ],
  "name": "Bake (Manifest)",
  "namespace": "firebird",
  "outputName": "sc-nginx",
  "overrides": {},
  "rawOverrides": false,
  "templateRenderer": "HELM2",
  "type": "bakeManifest"
}
```

### Cloud Provider(s):
Kubernetes 1.15
Helm

### Environment:
Halyard 1.31.1 
Spinnaker 1.18.4 running in Kubernetes

### Feature Area:
UX/Clouddriver

**Comment by rhysm** [comment]
I think this may be due the changes implemented in https://github.com/spinnaker/igor/pull/556 which creates the Helm artifact as type `helm/file` [(source)](https://github.com/spinnaker/igor/blob/d459a677635f9f23461957b8858e292ab6c91f3c/igor-monitor-artifactory/src/main/java/com/netflix/spinnaker/igor/artifactory/model/ArtifactoryItem.java#L88). The other parts of Spinnaker use `helm/chart` [(source)](https://github.com/spinnaker/clouddriver/blob/3730d669001d0655eafc296edf3f725c716f3956/clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/helm/HelmArtifactCredentials.java#L39) as the artifact type.

I was able to modify the pipeline JSON to have `helm/file` as the expected artifact type but this failed in the bake stage trying to download the artifact. The link generated by the ArtifactoryItem [(source)](https://github.com/spinnaker/igor/blob/d459a677635f9f23461957b8858e292ab6c91f3c/igor-monitor-artifactory/src/main/java/com/netflix/spinnaker/igor/artifactory/model/ArtifactoryItem.java#L82) is not a direct download link to the chart but instead a link to view the artifact within Artifactory.

I am thinking that the Artifact type should be changed to match other places and the Artifact link updated to a direct download link.

@sirigithub as the one who made these changes can you comment on whether you think this would cause any side effects?

**Comment by sirigithub** [comment]
@rhysm thanks for reaching out. I think the change of Helm artifact type to helm/chart and the url of the helm artefact to the direct link should be fine. The later was probably a miss on my part.

**Comment by angelcervilla** [comment]
Thank you @rhysm for the PR and @sirigithub for the input. Let me know how I can test that out once is merged

**Comment by gal-yardeni** [comment]
@angelcervilla was this issue resolved? let us know if you need any additional help or if we can close this. Thank you!

**Comment by angelcervilla** [comment]
hi @gal-yardeni 
Thanks for letting me know. Until now I didn't see the PR moving forward, I saw that it was merged. I'll be delighted to try it out, but I need to know how can I do it, so any instruction there would be appreciated

**Comment by gal-yardeni** [comment]
tagging @rhysm - can you take a look at @angelcervilla request? Thanks!

**Comment by rhysm** [comment]
@gal-yardeni the PR at https://github.com/spinnaker/igor/pull/664 still needs to be reviewed and merged.

**Comment by angelcervilla** [comment]
hi @rhysm 
I see that the PR was finally reviewed and merged, and I'd like to try it out, is there any way?
Thanks in advance for your help

**Comment by rhysm** [comment]
Hi @angelcervilla 

You would need to grab a nightly build of igor and deploy it to your environment in order to test.

In the `expectedArtifacts.matchArtifact.version` field you can specify a regex to only trigger the pipeline when a specific version pattern is published to Artifactory. For example:

```
  "expectedArtifacts": [
    {
      "defaultArtifact": {
        "artifactAccount": "virtual-helm-test",
        "id": "0e0dd403-0ab9-444f-9556-300cb1c3d316",
        "name": "helm-chart",
        "type": "helm/chart",
        "version": "0.0.1"
      },
      "displayName": "helm-chart",
      "id": "d2dea6d3-3a74-4c4b-975a-57e763e8366b",
      "matchArtifact": {
        "artifactAccount": "virtual-helm-test",
        "id": "3f39a209-2721-4918-b318-4cd1b0dcdd55",
        "name": "helm-chart",
        "type": "helm/chart",
        "version": "^(\\d+)\\.(\\d+)\\.(\\d+)$"
      },
      "useDefaultArtifact": true,
      "usePriorArtifact": true
    }
  ],
```

And use a trigger like this:

```
  "triggers": [
    {
      "artifactorySearchName": "artifactory2",
      "enabled": true,
      "expectedArtifactIds": [
        "d2dea6d3-3a74-4c4b-975a-57e763e8366b"
      ],
      "type": "artifactory"
    }
  ],
```

The bake stage JSON you pasted at the start of this issue should work as is.
