### ISSUE TITLE
Occassional failure after switching to MySQLed Orca

### ISSUE THREAD

**Issue by atyutyunnik** [spinnaker/spinnaker#5571]
### Issue Summary:

Pipeline once in a while fails with an exception "Metric name collision detected between methods 'public abstract void". The failing Deploy Manifest stage is preceeded with two "Find Image from Tags" stages

### Cloud Provider(s):
AWS

### Environment:
Spinnaker 1.18.5

### Feature Area:
MySQL-backed Orca

### Description:
This started happening when I switched to using MySQL as a DB engine for Orca:
com.netflix.spinnaker.kork.telemetry.InstrumentedProxy$MetricNameCollisionException: Metric name collision detected between methods 'public abstract void com.netflix.spinnaker.orca.pipeline.persistence.ExecutionRepository.addStage(com.netflix.spinnaker.orca.pipeline.model.Stage)' and 'public abstract void com.netflix.spinnaker.orca.pipeline.persistence.ExecutionRepository.addStage(com.netflix.spinnaker.orca.pipeline.model.Stage)' in 'SqlExecutionRepository'
	at com.netflix.spinnaker.kork.telemetry.InstrumentedProxy.addInstrumentedMethod(InstrumentedProxy.java:216)
	at com.netflix.spinnaker.kork.telemetry.InstrumentedProxy.getMethodMetrics(InstrumentedProxy.java:181)
	at com.netflix.spinnaker.kork.telemetry.InstrumentedProxy.invoke(InstrumentedProxy.java:98)
	at com.sun.proxy.$Proxy135.addStage(Unknown Source)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler$plan$$inlined$let$lambda$1.invoke(StartStageHandler.kt:172)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler$plan$$inlined$let$lambda$1.invoke(StartStageHandler.kt:59)
	at com.netflix.spinnaker.orca.q.StageDefinitionBuildersKt.buildBeforeStages(StageDefinitionBuilders.kt:97)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.plan(StartStageHandler.kt:171)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.access$plan(StartStageHandler.kt:59)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:96)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1$1.invoke(StartStageHandler.kt:59)
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt)
	at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:127)
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:51)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withAuth(StartStageHandler.kt:59)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:78)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler$handle$1.invoke(StartStageHandler.kt:59)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:67)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:41)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:76)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withExecution(StartStageHandler.kt:59)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:63)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.withStage(StartStageHandler.kt:59)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:76)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.handle(StartStageHandler.kt:59)
	at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
	at com.netflix.spinnaker.orca.q.handler.StartStageHandler.invoke(StartStageHandler.kt:59)
	at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:69)
	at com.netflix.spinnaker.q.QueueProcessor$callback$1$1.run(QueueProcessor.kt:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Steps to Reproduce:
- difficult to reproduce; usually, happens only when running a Spinnaker-based deployment demo

**Comment by ajordens** [comment]
I spot checked our logs and noticed a few instances of this as well -- @robzienert is going to find some time to take a look.

**Comment by atyutyunnik** [comment]
Is turning off the telemetry a work around?

**Comment by robzienert** [comment]
@atyutyunnik It doesn't look like our `InstrumentedProxy` implementation actually supports being disabled at this current time: This would be a good addition.
