### ISSUE TITLE
Orca Pod Fails to Startup for 1.19.x

### ISSUE THREAD

**Issue by bholat** [spinnaker/spinnaker#5583]
### Issue Summary:
Orca Pod Fails to Startup for 1.19.x.
Orca with MySQL config works fine on 1.18.x or earlier versions

### Steps to Reproduce:
Upgrade to Spin 1.19.x with orca configured to use MySQL

### Additional Details:
**Sample orcal-local.yml**
<pre><code>
pollers:
  oldPipelineCleanup:
    enabled: true
    intervalMs: 3600000
    thresholdDays: 21
    minimumPipelineExecutions: 5
tasks:
  daysOfExecutionHistory: 21
okHttpClient:
  readTimeoutMs: 1200000
sql:
  enabled: true
  connectionPool:
    jdbcUrl: jdbc:mysql://test:3306/orca
    user: orca_service
    password: test
    connectionTimeout: 5000
    maxLifetime: 30000
    maxPoolSize: 50
  migration:
    jdbcUrl: jdbc:mysql://test:3306/orca
    user: orca_migrate
    password: test
executionRepository:
  sql:
    enabled: true
  redis:
    enabled: false
monitor:
  activeExecutions:
    redis: false`
</code></pre>
**Stack trace:**
<pre><code>
020-03-17 00:35:17.289  INFO 1 --- [           main] c.n.s.o.n.NotificationClusterLock        : [] Configured class com.netflix.spinnaker.orca.notifications.SqlNotificationClusterLock for NotificationClusterLock
2020-03-17 00:35:17.293  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : [] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'oldPipelineCleanupPollingNotificationAgent' defined in URL [jar:file:/opt/orca/lib/orca-sql.jar!/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgent.class]: Unexpected exception during bean creation; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'sql.partition-name' in value "${sql.partition-name}"
2020-03-17 00:35:17.300  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : [] default - Shutdown initiated...
2020-03-17 00:35:17.312  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : [] default - Shutdown completed.
2020-03-17 00:35:17.318  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : [] Shutting down ExecutorService 'applicationEventTaskExecutor'
2020-03-17 00:35:17.325  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : [] Stopping service [Tomcat]
2020-03-17 00:35:17.354  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : []

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-03-17 00:35:17.358 ERROR 1 --- [           main] o.s.boot.SpringApplication               : [] Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'oldPipelineCleanupPollingNotificationAgent' defined in URL [jar:file:/opt/orca/lib/orca-sql.jar!/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgent.class]: Unexpected exception during bean creation; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'sql.partition-name' in value "${sql.partition-name}"
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:530)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at org.springframework.boot.builder.SpringApplicationBuilder$run$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at com.netflix.spinnaker.orca.Main.main(Main.groovy:104)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'sql.partition-name' in value "${sql.partition-name}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:178)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:236)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:908)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1228)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	... 17 common frames omitted
2020-03-17 00:35:17.383 ERROR 1 --- [pool-2-thread-1] c.n.s.o.s.t.SqlActiveExecutionsMonitor   : [] Unable to refresh active execution gauges
org.springframework.jdbc.UncategorizedSQLException: jOOQ; uncategorized SQLException for SQL [select (select count(*) from orchestrations where (status = ? and ? = ?)) as `orchestrations`, (select count(*) from pipelines where (status = ? and ? = ?)) as `pipelines` from dual]; SQL state [null]; error code [0]; HikariDataSource HikariDataSource (default) has been closed.; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (default) has been closed.
	at org.jooq_3.12.3.MYSQL.debug(Unknown Source)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at com.netflix.spinnaker.kork.sql.JooqToSpringExceptionTransformer.exception(JooqToSpringExceptionTransformer.kt:33)
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:261)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:383)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:501)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:470)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:484)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:653)
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2887)
	at com.netflix.spinnaker.orca.sql.pipeline.persistence.SqlExecutionRepository.countActiveExecutions(SqlExecutionRepository.kt:559)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.netflix.spinnaker.kork.telemetry.InstrumentedProxy.invoke(InstrumentedProxy.java:102)
	at com.sun.proxy.$Proxy150.countActiveExecutions(Unknown Source)
	at com.netflix.spinnaker.orca.sql.telemetry.SqlActiveExecutionsMonitor.refreshGauges(SqlActiveExecutionsMonitor.kt:69)
	at com.netflix.spinnaker.orca.sql.telemetry.SqlActiveExecutionsMonitor$1.run(SqlActiveExecutionsMonitor.kt:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (default) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:226)
	at com.sun.proxy.$Proxy129.getMetaData(Unknown Source)
	at com.netflix.spinnaker.kork.sql.config.DefaultSqlConfiguration$dataSourceConnectionProvider$1.acquire(DefaultSqlConfiguration.kt:149)
	at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:647)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:331)
	... 20 common frames omitted
</code></pre>

**Comment by marchello2000** [comment]
cherry-picked into 1.19 https://github.com/spinnaker/orca/pull/3528
