### ISSUE TITLE
Clouddriver throws SQL Exception with 1.19.x upgrade from 1.18.5

### ISSUE THREAD

**Issue by bholat** [spinnaker/spinnaker#5587]
### Issue Summary:
Clouddriver throws SQL Exception with 1.19.x upgrade from 1.18.5

### Description:
**Exception**
<pre><code>
2020-03-17 00:34:08.006  WARN 1 --- [cutionAction-15] c.n.s.c.cache.LoggingInstrumentation     : com.netflix.spinnaker.clouddriver.core.provider.CoreProvider:SqlEventCleanupAgent completed with one or more failures

org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [select aggregate_type, aggregateId from event_aggregates where timestampdiff(microsecond, current_timestamp(), last_change_timestamp) / 1000 > ?]; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'aggregateId' in 'field list'
	at org.jooq_3.12.3.MYSQL.debug(Unknown Source) ~[na:na]
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:93) ~[spring-jdbc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at com.netflix.spinnaker.kork.sql.JooqToSpringExceptionTransformer.exception(JooqToSpringExceptionTransformer.kt:33) ~[kork-sql-7.25.1.jar:7.25.1]
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:261) ~[jooq-3.12.3.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:383) ~[jooq-3.12.3.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:353) ~[jooq-3.12.3.jar:na]
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2693) ~[jooq-3.12.3.jar:na]
	at com.netflix.spinnaker.clouddriver.sql.event.SqlEventCleanupAgent$run$1.run(SqlEventCleanupAgent.kt:62) ~[clouddriver-sql.jar:na]
	at com.netflix.spectator.api.SwapTimer.record(SwapTimer.java:52) ~[spectator-api-0.75.0.jar:0.75.0]
	at com.netflix.spinnaker.clouddriver.sql.event.SqlEventCleanupAgent.run(SqlEventCleanupAgent.kt:56) ~[clouddriver-sql.jar:na]
	at com.netflix.spinnaker.cats.agent.RunnableAgent$RunnableAgentExecution.executeAgent(RunnableAgent.java:32) ~[cats-core.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:338) ~[cats-redis.jar:na]
	at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:308) ~[cats-redis.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'aggregateId' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:372) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.4.2.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.2.jar:na]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209) ~[jooq-3.12.3.jar:na]
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3928) ~[jooq-3.12.3.jar:na]
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:294) ~[jooq-3.12.3.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:368) ~[jooq-3.12.3.jar:na]
	... 13 common frames omitted
</pre></code>
### Steps to Reproduce:
Upgrade to Spin 1.19.x with cloudriver configured to use MySQL

### Additional Details:
**Sample clouddriver-local.yml**
<pre><code>
sql:
  enabled: true
  unknown-agent-cleanup-agent:
    enabled: true
  taskRepository:
    enabled: true
  cache:
    enabled: true
    readBatchSize: 500
    writeBatchSize: 300
  scheduler:
    enabled: false
  connectionPools:
    default:
      default: true
      jdbcUrl: jdbc:mysql://test:3306/clouddriver
      user: clouddriver_service
      password: test
    tasks:
      user: clouddriver_service
      jdbcUrl: jdbc:mysql://test:3306/clouddriver
      password: test
  migration:
    user: clouddriver_migrate
    jdbcUrl: jdbc:mysql://test:3306/clouddriver
    password: test

redis:
  enabled: true
  connection: redis://test:6379
  cache:
    enabled: false
  scheduler:
    enabled: true
  taskRepository:
    enabled: false
</pre></code>

**Comment by marchello2000** [comment]
this was fixed here https://github.com/spinnaker/clouddriver/pull/4414

**Comment by marchello2000** [comment]
cherry-picked https://github.com/spinnaker/clouddriver/pull/4446
