### ISSUE TITLE
Illegal access of private field AmazonInstance#extraAttributes and AmazonServerGroup#extraAttributes

### ISSUE THREAD

**Issue by pdk27** [spinnaker/spinnaker#5632]
### Issue Summary:
A recent commit changed the way a property can be accessed from public field to getter. But, not all references of that field wasfixed. 

### Cloud Provider(s):
AWS

### Environment:
I am trying to create a server group on Deck using AWS as cloud provider   

### Feature Area:
clouddriver-aws

### Description:
A recent commit changed the way a property can be accessed from public field to getter. But, not all references of that field wasfixed. 

### Steps to Reproduce:
1. sync from upstream:master
2. Create a Servergroup with aws provider on Deck
3. Clouddriver logs should show logs like:
```
2020-03-23 16:40:47.808 ERROR 30838 --- [0.1-7002-exec-9] c.n.s.k.w.e.GenericExceptionHandlers  : Internal Server Errorgroovy.lang.MissingMethodException: No signature of method: com.netflix.spinnaker.clouddriver.aws.model.AmazonServerGroup.extraAttributes() is applicable for argument types: () values: []
Possible solutions: getExtraAttributes()
 at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70) ~[groovy-2.5.9.jar:2.5.9]
 at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:49) ~[groovy-2.5.9.jar:2.5.9]
 at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) ~[groovy-2.5.9.jar:2.5.9]
 at com.netflix.spinnaker.clouddriver.aws.provider.view.AmazonLoadBalancerProvider.createLoadBalancerServerGroup(AmazonLoadBalancerProvider.groovy:203) ~[clouddriver-aws.jar:na]
```

### Additional Details:
n/a

**Comment by pdk27** [comment]
I am working on a fix for this issue.

**Comment by pdk27** [comment]
False alarm. I wasn't running the latest.
