### ISSUE TITLE
Rosco Issue on Fresh Ubuntu 14.04 Installation

### ISSUE THREAD

**Issue by slb350** [spinnaker/spinnaker#565]
Hello, thought I'd give this a shot today. Encountered this in the log:

2015-11-17 00:33:36.812  INFO 14401 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8087 (http)
2015-11-17 00:33:36.814  INFO 14401 --- [           main] com.netflix.spinnaker.rosco.Main         : Started Main in 28.405 seconds (JVM running for 30.027)
---- ERROR http://localhost:8085/tasks
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:100)
	at com.squareup.okhttp.Connection.connect(Connection.java:155)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:174)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:131)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:312)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:235)
	at com.squareup.okhttp.Call.getResponse(Call.java:262)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at retrofit.client.OkClient.execute(OkClient.java:53)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
	at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
	at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
	at retrofit.RxSupport$2.run(RxSupport.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at retrofit.Platform$Base$2$1.run(Platform.java:94)
	at java.lang.Thread.run(Thread.java:745)

---- END ERROR
2015-11-17 00:33:37.460  WARN 14401 --- [pool-1-thread-1] c.n.s.r.rush.health.RushHealthIndicator  : Unhealthy

com.netflix.spinnaker.rosco.rush.health.RushHealthIndicator$RushIOException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:186)
	at com.netflix.spinnaker.rosco.rush.health.RushHealthIndicator.checkHealth(RushHealthIndicator.groovy:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by tomaslin** [comment]
Rosco depends on a component called rush. It looks like Rush at http://localhost:8085 is unavailable.

Can you tell us which install method you tried?

**Comment by slb350** [comment]
bash <(curl --silent https://spinnaker.bintray.com/scripts/InstallSpinnaker.sh) from the docs. I see rush is running :

2015-11-17 00:40:25.050  INFO 2158 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8085 (http)
2015-11-17 00:40:25.052  INFO 2158 --- [           main] com.netflix.spinnaker.rush.Application   : Started Application in 31.505 seconds (JVM running for 33.172)

**Comment by slb350** [comment]
I see this for netstat:

tcp        0      0 127.0.0.1:7000          0.0.0.0:*               LISTEN      1422/java       
tcp        0      0 127.0.0.1:46750         0.0.0.0:*               LISTEN      1422/java       
tcp        0      0 127.0.0.1:7199          0.0.0.0:*               LISTEN      1422/java       
tcp        0      0 127.0.0.1:9160          0.0.0.0:*               LISTEN      1422/java       
tcp6       0      0 127.0.0.1:8087          :::*                    LISTEN      2124/java       
tcp6       0      0 127.0.0.1:8089          :::*                    LISTEN      2044/java       
tcp6       0      0 127.0.0.1:7002          :::*                    LISTEN      2032/java       
tcp6       0      0 127.0.0.1:8080          :::*                    LISTEN      2022/java       
tcp6       0      0 127.0.0.1:9042          :::*                    LISTEN      1422/java       
tcp6       0      0 127.0.0.1:8083          :::*                    LISTEN      2107/java       
tcp6       0      0 127.0.0.1:8084          :::*                    LISTEN      2074/java       
tcp6       0      0 127.0.0.1:8085          :::*                    LISTEN      2158/java  

Cassandra is in there, and some of the Spinnaker ports as well.

**Comment by slb350** [comment]
All other services besides Igor seem ok as well.

**Comment by tomaslin** [comment]
is http://localhost:8087/ running for you? in that case it would just mean the health check failed temporalily

**Comment by tomaslin** [comment]
if rush is running correctly, you should be able to go to http://localhost:8087/health and not see an error

**Comment by slb350** [comment]
http://localhost:8087/ connection refused. Added to my ssh config as well.

**Comment by tomaslin** [comment]
@ewiseblatt @duftler ^^^ any ideas?

**Comment by slb350** [comment]
from Rush log - not much other than its started:

2015-11-17 00:40:25.050  INFO 2158 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8085 (http)
2015-11-17 00:40:25.052  INFO 2158 --- [           main] com.netflix.spinnaker.rush.Application   : Started Application in 31.505 seconds (JVM running for 33.172)
2015-11-17 00:45:24.249  INFO 2158 --- [0.1-8085-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2015-11-17 00:45:24.249  INFO 2158 --- [0.1-8085-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2015-11-17 00:45:24.261  INFO 2158 --- [0.1-8085-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 12 ms

**Comment by tomaslin** [comment]
and you're able to hit the http://localhost:8085/tasks endpoint?

**Comment by slb350** [comment]
No joy there either:

from apache logs:

localhost:9000 127.0.0.1 - - [17/Nov/2015:00:44:51 +0000] "GET /f2558c5a9e8fb9d3c022c6d27a62a239.woff HTTP/1.1" 200 124862 "http://localhost:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"
localhost:9000 127.0.0.1 - - [17/Nov/2015:00:44:51 +0000] "GET /448c34a56d699c29117adc64c43affeb.woff2 HTTP/1.1" 200 18289 "http://localhost:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"
localhost:9000 127.0.0.1 - - [17/Nov/2015:00:44:51 +0000] "GET /788a2bcde2b05619551257e5f2053278.woff HTTP/1.1" 200 133654 "http://localhost:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"
localhost:9000 127.0.0.1 - - [17/Nov/2015:00:44:51 +0000] "GET /3bfca25c56db239ceab5a0c4940f1f24.woff HTTP/1.1" 200 136131 "http://localhost:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"
localhost:9000 127.0.0.1 - - [17/Nov/2015:00:44:51 +0000] "GET /favicon.ico HTTP/1.1" 200 15387 "http://localhost:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"

**Comment by slb350** [comment]
On the box:

 curl localhost:8087/health
{
  "status" : "UP"
}

**Comment by slb350** [comment]
May just be an issue with me then, as I can login to the app - besides the error message in Rosco.

**Comment by tomaslin** [comment]
that indicates that rosco should be ready to rosc

**Comment by slb350** [comment]
I can close this out then, thanks for taking a look :)

**Comment by tomaslin** [comment]
the message you're seeing is a failed healthcheck.

**Comment by duftler** [comment]
This was most likely an initial failed health check as the services can
start in any order and the first health check was before rush was ready.

Thanks,
-Matt

**Comment by duftler** [comment]
Yup, it definitely was, as evidenced by the timestamps:

Rosco trying to ping Rush (first of the scheduled heath checks):
`2015-11-17 00:33:37.460 WARN 14401 --- [pool-1-thread-1] c.n.s.r.rush.health.RushHealthIndicator : Unhealthy`

and

Rush coming online:
`2015-11-17 00:40:25.052 INFO 2158 --- [ main] com.netflix.spinnaker.rush.Application : Started Application in 31.505 seconds (JVM running for 33.172)`
