### ISSUE TITLE
Spinnaker cannot fetch artifacts from Git (bitbucket) using SSH

### ISSUE THREAD

**Issue by sramek5** [spinnaker/spinnaker#5650]
### Issue Summary:
I am trying to set up spinnaker to fetch helm chart from our bitbucket stash repository. When I make the repo public, spinnaker can successfully fetch from it (https://bitbucket.org/scm/project/repository.git) and deploy it to kubernetes.

The secure way in our organization is to fetch it using SSH.

### Cloud Provider(s):
Cloudinfrastack

### Environment:
Kubernetes V2
S3-Minio

### Description:
When I try to use SSH secure way, in spinnaker I define id_rsa in pem format:

```
    gitrepo:
      enabled: true
      accounts:
      - name: spinnaker
        sshPrivateKeyFilePath: /Users/<user>/.ssh/spinnaker/id_rsa
        sshTrustUnknownHosts: true
```
Public id_rsa.pub is pasted into repository **Access keys**.

Unfortunately, I always get error during the bake stage :
```
Exception ( Create Bake )
Failed to fetch helm template: Failed to download artifact: Artifact(type=git/repo, customKind=false, name=null, version=master, location=null, reference=ssh://git@bitbucket.org:7999/project/repository.git, metadata={subPath=kafka/}, artifactAccount=spinnaker, provenance=null, uuid=null). Error: 500
```
Same error I get for using https://bitbucket.org/scm/project/repository.git. 
I have no idea what I am doing wrong, am I missing anything?
Thank you for advices in advance!

**Comment by gal-yardeni** [comment]
hi @sramek5 , would you be interested to join our sig meeting tomorrow and discuss it? you can find more details on #sig-ci channel.

**Comment by sramek5** [comment]
Any tips about that? I am stuck there.

**Comment by gal-yardeni** [comment]
tagging @cfieber and @dreynaud -- can you please take a look? thanks!

**Comment by sramek5** [comment]
I also try to provide same things to the clouddriver-local.yaml and in logs it looks like this:
```
2020-04-29 12:33:37.873  INFO 1 --- [         task-2] c.n.s.c.a.g.GitRepoArtifactCredentials   : Cloning git/repo ssh://git@bitbucket.lmc.cz:7999/nrw/spinnaker-test.git into /tmp/96007790-ce3d-459f-aaf1-736c9574ad33
2020-04-29 12:33:37.961 ERROR 1 --- [.0-7002-exec-10] c.n.s.k.w.e.GenericExceptionHandlers     : Internal Server Error
java.io.IOException: Failed to clone or archive git/repo ssh://git@bitbucket.lmc.cz:7999/nrw/spinnaker-test.git: ssh://git@bitbucket.lmc.cz:7999/nrw/spinnaker-test.git: UnknownHostKey: bitbucket.lmc.cz. RSA key fingerprint is bc:31:67:84:3e:85:6a:32:74:30:2a:2a:15:c0:28:9a
	at com.netflix.spinnaker.clouddriver.artifacts.gitRepo.GitRepoArtifactCredentials.download(GitRepoArtifactCredentials.java:122) ~[clouddriver-artifacts.jar:na]....
```

**Comment by sramek5** [comment]
New update, today I tried to go around and made my own image, consistent from dockerfile:
```
FROM dcreg.service.consul/prod/clouddriver:6.7.3-20200401190525
USER spinnaker
RUN apk update \
    && apk add openssh git
```
I also updated clouddriver-local.yml :
  ```
clouddriver-local.yml: |-
    artifacts:
      gitRepo:
        enabled: true
        accounts:
        - name: git
          sshPrivateKeyPassPath: /home/spinnaker/.ssh/id_rsa
          sshKnownHostsFilePath: /home/spinnaker/.ssh/known_hosts
```
Provided RSA key and known hosts…And It works, but ONLY manually inside the container spin-clouddriver. In the container It will succesfully clone repository. But during running pipeline it fails at Auth fail:
```
2020-05-04 09:00:53.211  INFO 1 --- [         task-6] c.n.s.c.a.g.GitRepoArtifactCredentials   : Cloning git/repo ssh://git@bitbucket.lmc.cz:7999/nrw/spinnaker-test.git into /tmp/03875f78-9cd0-4d4b-a625-6628744bceee
2020-05-04 09:00:53.567 ERROR 1 --- [0.0-7002-exec-7] c.n.s.k.w.e.GenericExceptionHandlers     : Internal Server Error
java.io.IOException: Failed to clone or archive git/repo ssh://git@bitbucket.lmc.cz:7999/nrw/spinnaker-test.git: ssh://git@bitbucket.lmc.cz:7999/nrw/spinnaker-test.git: Auth fail
	at com.netflix.spinnaker.clouddriver.artifacts.gitRepo.GitRepoArtifactCredentials.download(GitRepoArtifactCredentials.java:122) ~[clouddriver-artifacts.jar:na]
	at com.netflix.spinnaker.clouddriver.artifacts.ArtifactDownloader.download(ArtifactDownloader.java:34) ~[clouddriver-artifacts.jar:na]
	at com.netflix.spinnaker.clouddriver.controllers.ArtifactController.lambda$fetch$0(ArtifactController.java:65) ~[clouddriver-web.jar:na]
	at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:111) ~[spring-webmvc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:98) ~[spring-webmvc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:328) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```
Common, I bet some developer would know what is going on :-)

**Comment by gal-yardeni** [comment]
@ethanfrogers as you worked on `GitRepoArtifactCredentials`, do you might have an idea about this^?

**Comment by sramek5** [comment]
Hi again!

Today I solved the issue.

Recent versions of OpenSSH generate keys in new OpenSSH format by default, which start with:
-----BEGIN OPENSSH PRIVATE KEY-----
and JSch (Git in Java) does not support this key format.

I used ssh-keygen to convert the key to the classic OpenSSH format:
`ssh-keygen -C "spinnaker" -p -f <file> -m pem -P <passphrase> -N <passphrase>`

which then starts with:
-----BEGIN RSA PRIVATE KEY-----

and it worsk like a charm!

**Comment by gal-yardeni** [comment]
Great! thank you for reporting back! Let me know if we can close this issue :)

**Comment by sramek5** [comment]
The most important thing is that in version 1.20.4 was improved logs. The clouddriver logs were more accurate, that is why I got this idea.
Thanks, you can close this issue :-)

**Comment by billstark** [comment]
@sramek5 Hi sorry for bothering, I am working on `gitRepo` provider as well and I got exactly the same issue as you have had: the pipeline fails due to error `UnknownHostKey: xxx. RSA key fingerprint is xxx`. My spinnaker version is 1.19.3 and I have tried your method to generate key with RSA header but still does not seem to work. Do you have any ideas about this? Thank!
