### ISSUE TITLE
Spinnaker unable to fetch tags from AWS ECR since 04/04/2020

### ISSUE THREAD

**Issue by jibinjohnbabu** [spinnaker/spinnaker#5651]
### Issue Summary:
Spinnaker (Armory installation on EKS https://docs.armory.io/spinnaker-install-admin-guides/install-on-aws/ ) unable to fetch tags from AWS ECR  and populate the dropdown for Image in UI since 04/04/2020, 

At configuration step of Spinnaker pipeline, trigger for Docker Registry (ECR in our case) doesn't fetch image tags all on a sudden.

<img width="1142" alt="Screen Shot 2020-04-07 at 12 54 28 PM" src="https://user-images.githubusercontent.com/40275773/78697841-6d90f000-78cf-11ea-9026-d46c1986e88c.png">

### Environment:
Spinnaker runs as an EKS service. Halyard machine and ECR on same AWS account and EKS on different account with all cross account policies set right as this was working perfectly until last Fridayish (04/03/2020)

NOTE: No change to Spinnaker docker image (armory/halyard-armory:1.8.0) since two months, no network or config change in our settings too..

clouddriver pod logs:

2020-04-06 16:29:23.511  WARN 1 --- [ecutionAction-5] c.n.s.c.d.r.a.v.c.DockerRegistryClient   : Registry https://ecr.dkr.ecr.us-east-1.amazonaws.com returned status 400 for request 'retrieve-address-api' without a WWW-Authenticate header
2020-04-06 16:29:23.517 ERROR 1 --- [ecutionAction-5] **.d.r.p.a.DockerRegistryImageCachingAgent : Could not load tags for xxx-xxx-api in https://<ecr-name>.dkr.ecr.us-east-1.amazonaws.com**
 
retrofit.RetrofitError: 400 Bad Request
        at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
        at com.sun.proxy.$Proxy170.getTags(Unknown Source) ~[na:na]
        at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$DockerRegistryService$getTags.call(Unknown Source) ~[na:na]
        at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$_getTags_closure11.doCall(DockerRegistryClient.groovy:357) ~[clouddriver-docker-6.5.1-2f123de-stable2.jar:na]
        at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$_getTags_closure11.doCall(DockerRegistryClient.groovy) ~[clouddriver-docker-6.5.1-2f123de-stable2.jar:na]
 

### Cloud Provider(s):
AWS EKS

###Additional details:
 There has been information from Spinnaker Slack channels saying deleting ECR end points (which we also have in our set up) fixed the issue. We are trying that method as I'm typing this in our environment. But I would prefer keeping the ECR end point in tact for security reasons..

Not a frequent incident creator here. I can give more details to anyone who needs it, upon request!

Thank you 

---

**Comment by jibinjohnbabu** [comment]
This issue is resolved without us doing any change. Waiting for an RCA from AWS ECS team.

**Comment by allisaurus** [comment]
Sounds this was related to an API issue on the AWS side, which has been resolved. Follow up convos on slack indicate folks are unblocked. Closing.
