### ISSUE TITLE
Errors when adding server group

### ISSUE THREAD

**Issue by daanemanz** [spinnaker/spinnaker#573]
While following the tutorial on the [Getting Started](http://spinnaker.io/documentation/getting_started.html) page, I run into an error in step 4: *Create a pipeline*.

When selecting *Add server group* and *Continue without a template*, I just see a spinner that never ends, and I found the following error in `/var/log/spinnaker/clouddriver/clouddriver.log`:
```
2015-11-17 20:04:31.177  INFO 2441 --- [0.1-7002-exec-7] c.n.s.c.controllers.SearchController     : Fetching search results for example, platform: , type: [securityGroups], pageSize: 1000, pageNumber: 1, filter: null
2015-11-17 20:04:31.177  INFO 2441 --- [0.1-7002-exec-7] c.n.s.c.cache.CatsSearchProvider         : Querying [securityGroups] for term: example
2015-11-17 20:04:31.179  INFO 2441 --- [0.1-7002-exec-7] c.n.s.c.cache.CatsSearchProvider         : Paginating 1 results; page number: 1, items per page: 1000
2015-11-17 20:04:31.186 ERROR 2441 --- [0.1-7002-exec-3] c.n.s.o.c.ApplicationsController         : Unable to fetch application (example)

com.netflix.spinnaker.oort.controllers.ApplicationsController$ApplicationNotFoundException: null
	at sun.reflect.GeneratedConstructorAccessor144.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$NoParamSite.callConstructor(ConstructorSite.java:120)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
	at com.netflix.spinnaker.oort.controllers.ApplicationsController.get(ApplicationsController.groovy:62)
	at sun.reflect.GeneratedMethodAccessor788.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:295)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at javax.servlet.FilterChain$doFilter.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at javax.servlet.FilterChain$doFilter.call(Unknown Source)
	at com.netflix.spinnaker.clouddriver.filters.SimpleCORSFilter.doFilter(SimpleCORSFilter.groovy:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at javax.servlet.FilterChain$doFilter.call(Unknown Source)
	at com.netflix.spinnaker.filters.AuthenticatedRequestFilter.doFilter(AuthenticatedRequestFilter.groovy:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.ShallowEtagHeaderFilter.doFilterInternal(ShallowEtagHeaderFilter.java:82)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at javax.servlet.FilterChain$doFilter.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at javax.servlet.FilterChain$doFilter.call(Unknown Source)
	at com.netflix.spinnaker.clouddriver.filters.SimpleCORSFilter.doFilter(SimpleCORSFilter.groovy:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:102)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:68)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

Is there anything I might be missing in the setup that causes this error?

**Comment by tomaslin** [comment]
It's a terrible looking error but should actually be ok to ignore. It just means you have an application but when we tried getting the clusters, it failed.

**Comment by tomaslin** [comment]
which makes sense because you probably don't have any server groups deployed

**Comment by daanemanz** [comment]
@tomaslin thanks for the explanation -- is that related to the never ending spinner when I'm trying to add a server group?

**Comment by tomaslin** [comment]
look into your developer console on your browser. that should give you a hint of why the spinner never ends. I suspect it might not have anything to do with the clouddriver log error

**Comment by daanemanz** [comment]
I think I found the real issue, thanks for the hint! Somehow it tries to look in us-west-2 where we don't have anything set up:

```
TypeError: Cannot read property 'availabilityZones' of undefined
    at http://localhost:8081/app.js:100298:77
    at processQueue (http://localhost:8081/app.js:24031:29)
    at http://localhost:8081/app.js:24047:28
    at Scope.$eval (http://localhost:8081/app.js:25275:29)
    at Scope.$digest (http://localhost:8081/app.js:25086:32)
    at Scope.$apply (http://localhost:8081/app.js:25383:25)
    at HTMLButtonElement.<anonymous> (http://localhost:8081/app.js:32840:24)
    at HTMLButtonElement.jQuery.event.dispatch (http://localhost:8081/app.js:4497:10)
    at HTMLButtonElement.elemData.handle (http://localhost:8081/app.js:4183:29) undefined(anonymous function) @ app.js:21763
app.js:21763 TypeError: Cannot read property 'us-west-2' of undefined
    at http://localhost:8081/app.js:100304:82
    at processQueue (http://localhost:8081/app.js:24031:29)
    at http://localhost:8081/app.js:24047:28
    at Scope.$eval (http://localhost:8081/app.js:25275:29)
    at Scope.$digest (http://localhost:8081/app.js:25086:32)
    at Scope.$apply (http://localhost:8081/app.js:25383:25)
    at HTMLButtonElement.<anonymous> (http://localhost:8081/app.js:32840:24)
    at HTMLButtonElement.jQuery.event.dispatch (http://localhost:8081/app.js:4497:10)
    at HTMLButtonElement.elemData.handle (http://localhost:8081/app.js:4183:29) undefined(anonymous function) @ app.js:21763
```

For the first stage in the tutorial pipeline I've selected `us-east-1`, which is where I've set up the VPC, load balancers, etc. Is `us-west-2` a default somewhere I haven't looked? In the setup I definitely selected `us-east-1` as my region, which shows in `/etc/default/spinnaker` and the config files in `/opt/spinnaker/config/` as well.

**Comment by tomaslin** [comment]
what do you see when you hit localhost:9000/settings.js? If it is not corresponding to your spinnaker-local.yml, you might want to regenerate this

**Comment by duftler** [comment]
Great, thanks for the confirmation.
