### ISSUE TITLE
Sonatype Nexus Integration as - Docker Registry

### ISSUE THREAD

**Issue by amulyamalla** [spinnaker/spinnaker#5791]
Facing issue while integrating private hosted nexus as a docker registry  : 
```
Halyard version : 1.5.0-20180713143726
Spinnaker : 1.19.9

Configuration: 

    dockerRegistry:
      enabled: true
      accounts:
      - name: spin-dockerhub
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        address: http://192.168.1.50:8083
        username: admin
        password: admin123
        email: fake_email@gmail.com
        cacheIntervalSeconds: 30
        clientTimeoutMillis: 60000
        cacheThreads: 1
        paginateSize: 100
        sortTagsByDate: false
        trackDigests: false
        insecureRegistry: false
        repositories:
        - 192.168.1.50:8083/spin-app

Getting Error :
+ Get current deployment
  Success
- Prep deployment
  Failure
Problems in default.security:
- WARNING Your UI or API domain does not have override base URLs
  set even though your Spinnaker deployment is a Distributed deployment on a
  remote cloud provider. As a result, you will need to open SSH tunnels against
  that deployment to access Spinnaker.
? We recommend that you instead configure an authentication
  mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker
  securely, and then register the intended Domain and IP addresses that your
  publicly facing services will be using.

Problems in default.provider.dockerRegistry.spin-dockerhub:
! ERROR Unable to reach repository: 400 Bad Request.

- Failed to prep Spinnaker deployment
 
Logs : 
2020-05-26 00:47:48.383  INFO 9 --- [       Thread-6] c.n.s.h.c.services.v1.ValidateService    : Ran 2 validators for node "security" with class "Security"
2020-05-26 00:47:48.392 ERROR 9 --- [       Thread-6] c.n.s.halyard.core.DaemonResponse        : Unknown exception encountered:

com.netflix.spinnaker.halyard.core.error.v1.HalException: Unable to reach repository: 400 Bad Request.
	at com.netflix.spinnaker.halyard.core.problem.v1.ProblemSet.throwifSeverityExceeds(ProblemSet.java:102) ~[halyard-core-1.5.0-20180713143726.jar:1.5.0-20180713143726]
	at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:120) ~[halyard-core-1.5.0-20180713143726.jar:1.5.0-20180713143726]
	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core-1.5.0-20180713143726.jar:1.5.0-20180713143726]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]

2020-05-26 00:47:48.393  INFO 9 --- [       Thread-6] c.n.s.h.core.tasks.v1.TaskRepository     : Task [Prep deployment] (ef9dd638-1fe7-467b-a207-d252d61a5cfe) - RUNNING failed with HalException:

com.netflix.spinnaker.halyard.core.error.v1.HalException: Unable to reach repository: 400 Bad Request.
	at com.netflix.spinnaker.halyard.core.problem.v1.ProblemSet.throwifSeverityExceeds(ProblemSet.java:102) ~[halyard-core-1.5.0-20180713143726.jar:1.5.0-20180713143726]
	at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:120) ~[halyard-core-1.5.0-20180713143726.jar:1.5.0-20180713143726]
	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core-1.5.0-20180713143726.jar:1.5.0-20180713143726]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]

2020-05-26 00:47:48.393  INFO 9 --- [       Thread-6] c.n.s.halyard.core.tasks.v1.DaemonTask   : [Prep deployment] (ef9dd638-1fe7-467b-a207-d252d61a5cfe) - FAILED killing all jobs created by this task
2020-05-26 00:47:48.393  INFO 9 --- [       Thread-6] c.n.s.h.core.tasks.v1.TaskRepository     : Task [Prep deployment] (ef9dd638-1fe7-467b-a207-d252d61a5cfe) - FAILED completed
2020-05-26 00:48:47.232  INFO 9 --- [       Thread-7] c.n.s.h.core.tasks.v1.TaskRepository     : Interrupter has no work to do, [Prep deployment] (ef9dd638-1fe7-467b-a207-d252d61a5cfe) - FAILED already completed.

**Comment by amulyamalla** [comment]
issue resolved  after modifying configuration 

Configuration: 

    dockerRegistry:
      enabled: true
      accounts:
      - name: spin-dockerhub
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        address: http://192.168.1.50:8083
        username: admin
        password: admin123
        email: fake_email@gmail.com
        cacheIntervalSeconds: 30
        clientTimeoutMillis: 60000
        cacheThreads: 1
        paginateSize: 100
        sortTagsByDate: false
        trackDigests: false
        insecureRegistry: true
        repositories:
        - spin-app 
        - rack-app
