### ISSUE TITLE
Concourse 6.1.0+ breaks existing igor auth

### ISSUE THREAD

**Issue by jaredstehler** [spinnaker/spinnaker#5797]
### Steps to Reproduce: Igor logs show following errors:
```
2020-05-23 19:16:31.265 ERROR 1 --- [RxIoScheduler-4] c.n.s.i.concourse.ConcourseBuildMonitor  : Failed to upda
te monitor items for monitor=ConcourseBuildMonitor:partition=wna-build

retrofit.RetrofitError: 404 Not Found
        at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
        at com.sun.proxy.$Proxy169.userInfo(Unknown Source) ~[na:na]
        at com.netflix.spinnaker.igor.concourse.service.ConcourseService.refreshTokenIfNecessary(ConcourseServi
ce.java:366) ~[igor-web.jar:na]
```

### Additional Details: required changes are detailed here: https://github.com/concourse/concourse/discussions/5649#discussioncomment-18268

Basically, the `/sky/token` endpoint changed to `/sky/issuer/token` and `access_token` is replaced by `id_token` in the response. Also, `/sky/userinfo` went away, but I was able to use `/api/v1/user` to the same effect.

The `/api/v1/info` endpoint returns a response:
```
{
    "cluster_name": "wna",
    "external_url": "https://my.ci.host",
    "version": "6.1.0",
    "worker_version": "2.2"
}
```

I will submit a PR for this.

**Comment by gal-yardeni** [comment]
@jaredstehler I see that you've submitted a fix, but it's in your fork. Are you planning to open a PR against Igor so we can review it?

**Comment by jaredstehler** [comment]
Did I do this incorrectly? I’ve opened https://github.com/spinnaker/igor/pull/762

**Comment by gal-yardeni** [comment]
oops my fault! I missed the Igor PR :) let me see who can help with reviewing it.

**Comment by gal-yardeni** [comment]
closing this ticket as a fix for it was merged.
