### ISSUE TITLE
Intermittent Bake(Manifest) Issue

### ISSUE THREAD

**Issue by bfarrell** [spinnaker/spinnaker#5835]
### Issue Summary:
We are seeing an intermittent failure when using the Bake(Manifest) stage.  It seems that the correct renderer type of HELM3 is not always being sent.  

java.lang.IllegalArgumentException: Cannot bake manifest with template renderer type: helm
	at com.netflix.spinnaker.rosco.controllers.V2BakeryController.lambda$doBake$1(V2BakeryController.java:38) ~[rosco-web.jar:na]
	at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
	at com.netflix.spinnaker.rosco.controllers.V2BakeryController.doBake(V2BakeryController.java:36) ~[rosco-web.jar:na]

Please see the gist for the full exception.

### Cloud Provider(s):
Kubernetes

### Environment:
Running 1.19 in an on-prem K8s cluster deployed with Halyard

### Feature Area:
Kubernetes Manifest Bake Rosco

### Description:
The expected result is to successfully build the manifest from the template.

### Steps to Reproduce:

1. Setup Kubernetes v2 provider
2. Create a chart repo in git 
3. Setup an artifact account for helm pointing to git
3. Add a chart to the git repo
4. Create a pipeline 
5.  For the pipeline config, add the artifact
6. Create a Bake Manifest stage
7. Run the pipeline
8.  Observe intermittent failures

### Additional Details:
Here is the pipeline execution with the failure.  It shows the template renderer is HELM3.  Also included there is the full stack trace.
https://gist.github.com/bfarrell/9d1acb3fa3364ff6fd301a8e4a389476

**Comment by evansb** [comment]
Hi, do you mind attaching logs from Rosco as well? The actual error will actually be there

**Comment by evansb** [comment]
That is odd, the error comes from this code: https://github.com/spinnaker/rosco/blob/190f5ef2ee1ed5fdb6438ea7bb8b94705937ba78/rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/V2BakeryController.java#L29

However, `type` here should be either `HELM2` or `HELM3` and not just `helm`.

It seems to indicate that you have 1 or more instance of old Orca still running around which is quite dangerous:
Orca passes `helm` **before** this commit (released on 1.16) https://github.com/spinnaker/orca/commit/2a39bb844ecaba0337765596c4a7af7a91a7632a

Which means you have 1 or more Orca pod running 1.15.x.

**Comment by bfarrell** [comment]
@evansb Thanks for the info.  We looked at the entire cluster to make sure we arent missing any orca pods.  Halyard is deploying this and we are running 19.11.  If I describe my two orca pods, they are both pointing at this sha:
gcr.io/spinnaker-marketplace/orca@sha256:0d299e30ff3b105a7901649070d0d2c1d7e4b03d036a08885fd2a974ff5c5d0e

or this container image
gcr.io/spinnaker-marketplace/orca:2.13.5-20200505065831

https://console.cloud.google.com/gcr/images/spinnaker-marketplace/GLOBAL/orca@sha256:0d299e30ff3b105a7901649070d0d2c1d7e4b03d036a08885fd2a974ff5c5d0e/details?tab=info

Is that incorrect?  Should it be using one of the 1.19 release tags instead?  Regardless, they are both using the same.  So, im not sure why it would work half the time.

**Comment by bfarrell** [comment]
Here is what I am seeing in Orca for a failed bake.  You can see the renderer is HELM3.  On a successful, after StartTask I see the call to rosco.  In the case of failure, I dont even see it make the call.  However, rosco is throwing the error.

2020-06-16 15:16:19.004  INFO 1 --- [0.0-8083-exec-5] c.n.s.o.c.OperationsController           : [bfarrell] Started pipeline 01EAYV7N647MMZGSGH3TSPFT5E based on request body {"application":"adereporting","name":"dummy_bf","id":"59518e9b-a795-4cce-b3e7-8b34cc1194b8","executionId":"01EAYV7N647MMZGSGH3TSPFT5E","spelEvaluator":"v4","parallel":false,"disabled":false,"limitConcurrent":true,"keepWaitingPipelines":false,"plan":false,"respectQuietPeriod":false,"triggers":[],"stages":[{"expectedArtifacts":[{"defaultArtifact":{"customKind":true,"id":"9f139d66-12cc-406b-a0b5-b852eb0b0ba8"},"displayName":"grumpy-turkey-43","id":"3e3ab7cb-d6ce-4b43-bb71-5ebfe21dbde0","matchArtifact":{"id":"fe6fb6cf-ff02-481a-8e24-829d5e18bcdc","type":"embedded/base64"},"useDefaultArtifact":false,"usePriorArtifact":false}],"inputArtifacts":[{"account":"helm-ade","id":"14476fbc-50d9-4f35-8957-e38ce40b8654"}],"name":"Bake (Manifest)","outputName":"tsa","overrides":{},"refId":"1","requisiteStageRefIds":[],"templateRenderer":"HELM3","type":"bakeManifest"}],"notifications":[],"receivedArtifacts":[{"type":"helm/chart","customKind":false,"name":"ade-reporting","version":"83","metadata":{"id":"5fcfa8af-c3c6-4dfc-a76c-da0d75e40a10"},"artifactAccount":"helm-ade"}],"expectedArtifacts":[{"matchArtifact":{"type":"helm/chart","customKind":false,"name":"ade-reporting","version":"83","metadata":{"id":"5fcfa8af-c3c6-4dfc-a76c-da0d75e40a10"},"artifactAccount":"helm-ade"},"usePriorArtifact":true,"useDefaultArtifact":false,"defaultArtifact":{"customKind":true,"metadata":{"id":"9c195667-f554-4be9-b2ba-a194d2a63990"}},"id":"14476fbc-50d9-4f35-8957-e38ce40b8654"}],"trigger":{"type":"manual","enabled":false,"executionId":"01EAYV7N647MMZGSGH3TSPFT5E","user":"brfarrel","rebake":false,"dryRun":false,"artifacts":[{"type":"helm/chart","customKind":false,"name":"ade-reporting","version":"83","metadata":{"id":"5fcfa8af-c3c6-4dfc-a76c-da0d75e40a10"},"artifactAccount":"helm-ade"}],"eventId":"3d8e3ee8-a549-4bd6-bb35-60f459b49e83"}}
2020-06-16 15:16:19.011  INFO 1 --- [    scheduler-4] com.netflix.spinnaker.q.QueueProcessor   : [] Received message StartStage(executionType=pipeline, executionId=01EAYV7N647MMZGSGH3TSPFT5E, application=adereporting, stageId=01EAYV7NAGP1XGYCS7DYX5VJTJ)
2020-06-16 15:16:19.020  INFO 1 --- [   scheduler-10] com.netflix.spinnaker.q.QueueProcessor   : [] Received message StartTask(executionType=pipeline, executionId=01EAYV7N647MMZGSGH3TSPFT5E, application=adereporting, stageId=01EAYV7NAGP1XGYCS7DYX5VJTJ, taskId=1)
2020-06-16 15:16:19.022  INFO 1 --- [       events-8] c.n.spinnaker.orca.echo.EchoService      : [brfarrel] ---> HTTP POST http://spin-echo.spinnaker:8089/
2020-06-16 15:16:19.032  INFO 1 --- [       events-8] c.n.spinnaker.orca.echo.EchoService      : [brfarrel] <--- HTTP 200 http://spin-echo.spinnaker:8089/ (10ms)
2020-06-16 15:16:19.064  INFO 1 --- [    scheduler-4] com.netflix.spinnaker.q.QueueProcessor   : [] Received message CancelStage(executionType=pipeline, executionId=01EAYV7N647MMZGSGH3TSPFT5E, application=adereporting, stageId=01EAYV7NAGP1XGYCS7DYX5VJTJ)
2020-06-16 15:16:19.064  INFO 1 --- [    scheduler-4] com.netflix.spinnaker.q.QueueProcessor   : [] Received message CompleteExecution(executionType=pipeline, executionId=01EAYV7N647MMZGSGH3TSPFT5E, application=adereporting)

**Comment by evansb** [comment]
That seems to be correct Orca version indeed (you can always check with `hal version bom 1.19.11` or download the BOM directly from https://storage.googleapis.com/halconfig/bom/1.19.11.yml

> In the case of failure, I dont even see it make the call. However, rosco is throwing the error.
This seems to be different from our behavior as well, we still see HTTP request trace even if the downstream service (Rosco) returns 500.

Your Orca log should show `RunTask(executionType=pipeline, executionId=01EAYV7N647MMZGSGH3TSPFT5E, application=adereporting, stageId=01EAYV7NAGP1XGYCS7DYX5VJTJ, taskId=1,  taskType=class com.netflix.spinnaker.orca.bakery.tasks.manifests.CreateBakeManifestTask)` which indicates that the task is being attempted by the Orca instance, if it's missing that means the task is processed by some stray Orca instance

**Comment by bfarrell** [comment]
Your thought process makes sense.  I am just struggling to be able to find any rogue orca instance.  The spin-orca service is just pointing at the pods created by the deployment at version 1.19.11.  I cant find a version another orca pod in any namespace.  I tried scaling the orca deployment to zero and I couldnt kick off a pipeline.  So, it doesnt seem that any other orca is picking up the work tasks.

**Comment by evansb** [comment]
>  I tried scaling the orca deployment to zero and I couldnt kick off a pipeline
In this case because the Gate -> Orca connection is broken, Orca is both backend API and background job executor.

Since you just mentioned you have the ability to scale it to zero, one simple way to verify you have rogue executor is to do the following:

1. Start a pipeline that does 1 stage:`wait` for XX minutes (pick a reasonably large time like 600s/10 minutes). Note the Execution ID.
2. Scale-in your Orca to 0.
3. After 10 minutes, don't reactivate Orca yet, check the pipeline state in Orca backing storage (e.g SQL - `pipelines` table/Redis - not sure) depending on your setup. If there are rogue Orca instances the pipeline status should be `SUCCEEDED`.

**Comment by bfarrell** [comment]
Thanks @evansb !! We wound up going node to node and found an orphaned orca container with docker commands.  Appreciate your help.  Closing this issue.
