### ISSUE TITLE
NullPointerException in Echo: KubernetesManifestAnnotater.getTraffic

### ISSUE THREAD

**Issue by atyutyunnik** [spinnaker/spinnaker#5843]
### Issue Summary:
Getting NPE:
```
"Orchestration failed: KubernetesDisableManifestOperation | NullPointerException: [java.lang.NullPointerException
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.description.manifest.KubernetesManifestAnnotater.getTraffic(KubernetesManifestAnnotater.java:225)
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.manifest.AbstractKubernetesEnableDisableManifestOperation.determineLoadBalancers(AbstractKubernetesEnableDisableManifestOperation.java:67)
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.manifest.AbstractKubernetesEnableDisableManifestOperation.operate(AbstractKubernetesEnableDisableManifestOperation.java:128)
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.manifest.AbstractKubernetesEnableDisableManifestOperation.operate(AbstractKubernetesEnableDisableManifestOperation.java:38)
	at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate.call(Unknown Source)
	at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy:114)
	at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor4715.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at com.netflix.spinnaker.clouddriver.metrics.TimedCallable$ClosureWrapper.call(TimedCallable.groovy:55)
	at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy:113)
	at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor4713.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:92)
	at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.groovy:82)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
]
```

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker 1.20.4

### Feature Area:
echo

### Description:
Kubernetes Manifest deploys just fine, but previous replica isn't getting removed and a nice looking NPE is displayed during "Disable Manifest" step

**Comment by ezimanyi** [comment]
@atyutyunnik : Thanks for reporting this!  To clarify though, this is in `clouddriver` (which it appears to be from the stack trace)?

What appears to be happening here is that when the "Disable Manifest" stage is running, it looks for the manifest that it is supposed to disable, but doesn't find it in the cluster.  (Obviously we should fix that error message to be more clear than an NPE and indicate the problem.)

I'd like to try to figure out why it is unable to find the manifest.

The following:
* In the execution details, look under `stages`
* Find the `disableManifest` stage that failed
* In the `context` for that stage there should be keys `manifest.name` and `manifest.location` which indicates the manifest that it was looking for.  The `manifest.name` will have both the kubernetes kind and the name, while the `location` will be the namespace.
For some reason, when it tried to `kubectl get` the manifest corresponding to the above it did not find it.

A couple of questions:
* Did this happen once (so maybe a race condition) or is this consistently reproducible on the pipeline?
* Is this a separate "Disable Manifest" stage or are you using the "Spinnaker Manages Traffic" checkbox in the "Deploy Manifest" stage?
* (In the case of separate "Disable" stage) Are you using "Choose target statically" or "Choose target dynamically?

**Comment by atyutyunnik** [comment]
> @atyutyunnik : Thanks for reporting this! To clarify though, this is in `clouddriver` (which it appears to be from the stack trace)?
I was at first confused and also thought it was clouddriver's. Somehow that stack trace appeared in the echo only. The issue was consistently reproducible when the following value was wrong in the manifest:
```    traffic.spinnaker.io/load-balancers: '["service or-xecrt-svc"]'```
