### ISSUE TITLE
Igor discards all data on 500 error received from Travis

### ISSUE THREAD

**Issue by costimuraru** [spinnaker/spinnaker#5850]
### Issue Summary:

When Igor fetches the job list from Travis, it makes multiple HTTP requests to the Travis API, using pagination.
For our ORG, there are 86 pages (~8600 jobs). For some unknown reasons, Travis returns 500 errors pages 20 to 24 (it works well pages 25+ and 19-). [1]

Right now, when Igor receives the first 500 error [2], it will stop and discard all the data. As such, for our ORG, no jobs are stored in the cache from Travis.

A better way would be to just skip the failed pages and just use the data available.

### Feature Area:
Igor (Travis)

### Steps to Reproduce:

Setup Travis in Igor, with a big org and a big number of jobs.

```yaml
travis:
  enabled: true
  masters:
    - name: expedge
      permissions: {}
      address: https://api.travis-ci.com
      baseUrl: https://travis-ci.com
      githubToken: my-token
      numberOfJobs: 10000
      buildResultLimit: 10
```

### Additional Details:

[1] 

https://api.travis-ci.com/jobs?state=passed%2Cstarted%2Cerrored%2Cfailed%2Ccanceled&include=job.build%2Cbuild.log_complete&limit=100&offset=2000

Response:
```
< HTTP/2 500
Sorry, we experienced an error.
```

https://api.travis-ci.com/jobs?state=passed%2Cstarted%2Cerrored%2Cfailed%2Ccanceled&include=job.build%2Cbuild.log_complete&limit=100&offset=2500

Response:
```
< HTTP/2 200
{
  "@type": "jobs",
...
```

[2]
```
2020-06-17 16:33:43.151  WARN 1 --- [ravis-expedge-9] c.n.s.igor.travis.service.TravisService  : An error occurred while fetching new jobs from Travis.

retrofit.RetrofitError: 500 Internal Server Error
	at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[retrofit-1.9.0.jar:na]
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[retrofit-1.9.0.jar:na]
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
	at com.sun.proxy.$Proxy157.jobs(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.igor.travis.service.TravisService.lambda$getJobs$6(TravisService.java:313) ~[igor-web.jar:na]
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[na:na]
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[na:na]
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at com.netflix.spinnaker.igor.travis.service.TravisService.lambda$getJobs$8(TravisService.java:323) ~[igor-web.jar:na]
	at com.netflix.spinnaker.hystrix.SimpleJava8HystrixCommand.run(SimpleJava8HystrixCommand.java:52) ~[kork-hystrix-7.41.0.jar:na]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294) ~[hystrix-core-1.4.21.jar:1.4.21]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289) ~[hystrix-core-1.4.21.jar:1.4.21]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:517) ~[hystrix-core-1.4.21.jar:1.4.21]
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:495) ~[hystrix-core-1.4.21.jar:1.4.21]
	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100) ~[rxjava-1.3.8.jar:1.3.8]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) ~[hystrix-core-1.4.21.jar:1.4.21]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) ~[hystrix-core-1.4.21.jar:1.4.21]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) ~[hystrix-core-1.4.21.jar:1.4.21]
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.3.8.jar:1.3.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

---

**Comment by costimuraru** [comment]
Opened an issue on Travis: https://travis-ci.community/t/travis-consistently-returns-500-errors-when-trying-to-fetch-some-jobs-pages/9041
