### ISSUE TITLE
Igor cannot parse concourse 6.2.x builds due to decimal build numbers

### ISSUE THREAD

**Issue by bartlettt** [spinnaker/spinnaker#5932]
### Issue Summary:
Concourse 6.2.0 introduced a build re-run feature. Re run builds get a decimal build number. I.e. build 5 rerun produces build 5.1. Igor cannot parse decimal build numbers. See exception below

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker 1.21.1 running on Kubernetes. Installed using helm chart. Using igor image: gcr.io/spinnaker-marketplace/igor:1.11.1-20200721201355

### Feature Area:
Pipelines

### Description:
I expect to be able to add a concourse build trigger to my pipeline. Instead the "Teams" drop down is not populated, so I cannot create the trigger.

### Steps to Reproduce:
Enable concourse integration with commands:
```
hal config ci concourse enable
hal config ci concourse master add ${concourse.url} --url ${concourse.url} --username ${concourse.username} --password ${concourse.password}
```

Create a new application in Spinnaker. Create a new pipeline and attempt to add a build trigger of type Concourse. The exception below is thrown by igor when attempting to select a team.

### Additional Details:
Igor log output:
```
java.lang.NumberFormatException: For input string: "262.5"                                                            
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:na]                            at java.base/java.lang.Integer.parseInt(Integer.java:652) ~[na:na]
        at java.base/java.lang.Integer.parseInt(Integer.java:770) ~[na:na]                                                   
        at com.netflix.spinnaker.igor.concourse.client.model.Build.getNumber(Build.java:33) ~[igor-web.jar:na]                 
        at com.netflix.spinnaker.igor.concourse.service.ConcourseService.getGenericBuild(ConcourseService.java:150) ~[igor-web.
jar:na]                                                                                                                 
        at com.netflix.spinnaker.igor.concourse.ConcourseBuildMonitor.lambda$jobDelta$3(ConcourseBuildMonitor.java:134) ~[igor-web.jar:na] 
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]                                at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]                           
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]                               at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na] 
        at com.netflix.spinnaker.igor.concourse.ConcourseBuildMonitor.jobDelta(ConcourseBuildMonitor.java:136) ~[igor-web.jar:n
a]                                                                                                                             
        at com.netflix.spinnaker.igor.concourse.ConcourseBuildMonitor.lambda$generateDelta$2(ConcourseBuildMonitor.java:96) ~[i
gor-web.jar:na]                                                                                              
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]      
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
        at com.netflix.spinnaker.igor.concourse.ConcourseBuildMonitor.generateDelta(ConcourseBuildMonitor.java:98) ~[igor-web.j
ar:na]
        at com.netflix.spinnaker.igor.concourse.ConcourseBuildMonitor.generateDelta(ConcourseBuildMonitor.java:52) ~[igor-web.j
ar:na]
        at com.netflix.spinnaker.igor.polling.CommonPollingMonitor.internalPollSingle(CommonPollingMonitor.java:170) ~[igor-cor
e.jar:na]
        at com.netflix.spinnaker.igor.polling.CommonPollingMonitor.pollSingle(CommonPollingMonitor.java:145) ~[igor-core.jar:na
]
        at com.netflix.spinnaker.igor.concourse.ConcourseBuildMonitor.poll(ConcourseBuildMonitor.java:213) ~[igor-web.jar:na]
        at com.netflix.spinnaker.igor.polling.CommonPollingMonitor.lambda$onApplicationEvent$0(CommonPollingMonitor.java:95) ~[
igor-core.jar:na]
        at io.micrometer.core.instrument.AbstractTimer.record(AbstractTimer.java:160) ~[micrometer-core-1.3.5.jar:1.3.5]
        at com.netflix.spectator.micrometer.MicrometerTimer.record(MicrometerTimer.java:47) ~[spectator-reg-micrometer-0.103.0.
jar:0.103.0]
        at com.netflix.spinnaker.igor.polling.CommonPollingMonitor.lambda$onApplicationEvent$1(CommonPollingMonitor.java:92) ~[
igor-core.jar:na]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) ~[spring-context-5.
2.4.RELEASE.jar:5.2.4.RELEASE]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:
304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by gal-yardeni** [comment]
hi @bartlettt , we have a similar issue https://github.com/spinnaker/spinnaker/issues/5895. Can you please take a look? for #5895 there is an open PR waiting for review.

**Comment by bartlettt** [comment]
Hi @gal-yardeni I didn't realise there was a similar issue already reported. Is it possible for someone to merge the two issues? I don't think I have the permissions to do that.

**Comment by gal-yardeni** [comment]
sure, I'll close it.

Closing as it's duplicate to issue #5895.
