### ISSUE TITLE
[rosco] Error on bake v1.22.0

### ISSUE THREAD

**Issue by awsiv** [spinnaker/spinnaker#5998]
### Issue Summary:
After upgrading to `1.22.0`, our pipelines are failing during bake with:

```
Aug 25 10:26:27 ip-.... rosco[23291]: 2020-08-25 10:26:27.304 ERROR 23291 --- [RxIoScheduler-2] c.n.spinnaker.rosco.executor.BakePoller  : Update Polling Error:
Aug 25 10:26:27 ip-.... rosco[23291]: groovy.lang.ReadOnlyPropertyException: Cannot set readonly property: name for class: com.netflix.spinnaker.kork.artifacts.model.Artifact
Aug 25 10:26:27 ip-.... rosco[23291]:         at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2773) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3809) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:217) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:496) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at com.netflix.spinnaker.rosco.executor.BakePoller$_completeBake_closure3.doCall(BakePoller.groovy:228) ~[rosco-core-0.21.0-20200817170018.jar:0.21.0-20200817170018]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at groovy.lang.Closure.call(Closure.java:421) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2330) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2315) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2356) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.dgm$186.invoke(Unknown Source) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at com.netflix.spinnaker.rosco.executor.BakePoller.completeBake(BakePoller.groovy:227) ~[rosco-core-0.21.0-20200817170018.jar:0.21.0-20200817170018]
Aug 25 10:26:27 ip-.... rosco[23291]:         at com.netflix.spinnaker.rosco.executor.BakePoller$completeBake.callCurrent(Unknown Source) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at com.netflix.spinnaker.rosco.executor.BakePoller.updateBakeStatusAndLogs(BakePoller.groovy:175) ~[rosco-core-0.21.0-20200817170018.jar:0.21.0-20200817170018]
Aug 25 10:26:27 ip-.... rosco[23291]:         at jdk.internal.reflect.GeneratedMethodAccessor135.invoke(Unknown Source) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at com.netflix.spinnaker.rosco.executor.BakePoller$_onApplicationEvent_closure1$_closure4.doCall(BakePoller.groovy:85) ~[rosco-core-0.21.0-20200817170018.jar:0.21.0-20200817170018]
Aug 25 10:26:27 ip-.... rosco[23291]:         at jdk.internal.reflect.GeneratedMethodAccessor134.invoke(Unknown Source) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:122) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at com.sun.proxy.$Proxy192.call(Unknown Source) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) ~[rxjava-1.3.8.jar:1.3.8]
Aug 25 10:26:27 ip-.... rosco[23291]:         at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[rxjava-1.3.8.jar:1.3.8]
Aug 25 10:26:27 ip-.... rosco[23291]:         at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastPath(OnSubscribeFromIterable.java:173) ~[rxjava-1.3.8.jar:1.3.8]
Aug 25 10:26:27 ip-.... rosco[23291]:         at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:86) ~[rxjava-1.3.8.jar:1.3.8]
Aug 25 10:26:27 ip-.... rosco[23291]:         at rx.Subscriber.setProducer(Subscriber.java:209) ~[rxjava-1.3.8.jar:1.3.8]
Aug 25 10:26:27 ip-.... rosco[23291]:         at rx.Subscriber.setProducer(Subscriber.java:205) ~[rxjava-1.3.8.jar:1.3.8]
Aug 25 10:26:27 ip-.... rosco[23291]:         at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63) ~[rxjava-1.3.8.jar:1.3.8]
Aug 25 10:26:27 ip-.... rosco[23291]:         at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34) ~[rxjava-1.3.8.jar:1.3.8]
Aug 25 10:26:27 ip-.... rosco[23291]:         at rx.Observable.subscribe(Observable.java:10423) ~[rxjava-1.3.8.jar:1.3.8]
Aug 25 10:26:27 ip-.... rosco[23291]:         at rx.Observable.subscribe(Observable.java:10390) ~[rxjava-1.3.8.jar:1.3.8]
Aug 25 10:26:27 ip-.... rosco[23291]:         at rx.Observable.subscribe(Observable.java:10271) ~[rxjava-1.3.8.jar:1.3.8]
Aug 25 10:26:27 ip-.... rosco[23291]:         at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:188) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:143) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at com.netflix.spinnaker.rosco.executor.BakePoller$_onApplicationEvent_closure1.doCall(BakePoller.groovy:81) ~[rosco-core-0.21.0-20200817170018.jar:0.21.0-20200817170018]
Aug 25 10:26:27 ip-.... rosco[23291]:         at com.netflix.spinnaker.rosco.executor.BakePoller$_onApplicationEvent_closure1.doCall(BakePoller.groovy) ~[rosco-core-0.21.0-20200817170018.jar:0.21.0-20200817170018]
Aug 25 10:26:27 ip-.... rosco[23291]:         at jdk.internal.reflect.GeneratedMethodAccessor85.invoke(Unknown Source) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:122) ~[groovy-2.5.11.jar:2.5.11]
Aug 25 10:26:27 ip-.... rosco[23291]:         at com.sun.proxy.$Proxy190.call(Unknown Source) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at rx.internal.schedulers.SchedulePeriodicHelper$1.call(SchedulePeriodicHelper.java:72) ~[rxjava-1.3.8.jar:1.3.8]
Aug 25 10:26:27 ip-.... rosco[23291]:         at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230) ~[rxjava-1.3.8.jar:1.3.8]
Aug 25 10:26:27 ip-.... rosco[23291]:         at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.3.8.jar:1.3.8]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
Aug 25 10:26:27 ip-.... rosco[23291]:         at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

```

Have rolled back to 1.21.3

### Cloud Provider(s):
AWS

### Feature Area:
rosco

**Comment by ezimanyi** [comment]
I will fix this; I broke this by making `Artifact` immutable, but there was a usage of the setter in Groovy that had no tests whatsoever so neither compilation nor tests caught the issue.
