### ISSUE TITLE
Unable to determine the download URL of artifact Artifact

### ISSUE THREAD

**Issue by theRemix** [spinnaker/spinnaker#5999]
### Issue Summary:

Builds fail due to not being able to access manifest from github api

### Cloud Provider(s):

kubernetes v2

### Environment:

Spinnaker on GCP

### Feature Area:

Pipelines

### Description:

k8s manifest exists on `master` and an `develop` branches at path `manifests/develop/deployment.yaml`

Expected pipelines to access manifest via github api.

Actual behavior, builds fail due to these errors:

```
com.netflix.spinnaker.clouddriver.artifacts.exceptions.FailedDownloadException: Unable to determine the download URL of artifact Artifact(type=github/file, customKind=false, name=manifests/develop/deployment.yaml, version=develop, location=null, reference=https://api.github.com/repos/my-org/my-project/contents/manifests/develop/deployment.yaml, metadata={id=...}, artifactAccount=github-artifacts, provenance=null, uuid=null): Received 404 status code from api.github.com
        at com.netflix.spinnaker.clouddriver.artifacts.github.GitHubArtifactCredentials.getDownloadUrl(GitHubArtifactCredentials.java:70) ~[clouddriver-artifacts.jar:na]
        at com.netflix.spinnaker.clouddriver.artifacts.config.SimpleHttpArtifactCredentials.download(SimpleHttpArtifactCredentials.java:44) ~[clouddriver-artifacts.jar:na]
        at com.netflix.spinnaker.clouddriver.artifacts.ArtifactDownloader.download(ArtifactDownloader.java:34) ~[clouddriver-artifacts.jar:na]
        at com.netflix.spinnaker.clouddriver.controllers.ArtifactController.lambda$fetch$0(ArtifactController.java:65) ~[clouddriver-web.jar:na]
        at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:111) ~[spring-webmvc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:98) ~[spring-webmvc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:328) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.io.IOException: Received 404 status code from api.github.com
        at com.netflix.spinnaker.clouddriver.artifacts.config.BaseHttpArtifactCredentials.fetchUrl(BaseHttpArtifactCredentials.java:82) ~[clouddriver-artifacts.jar:na]
        at com.netflix.spinnaker.clouddriver.artifacts.github.GitHubArtifactCredentials.getDownloadUrl(GitHubArtifactCredentials.java:67) ~[clouddriver-artifacts.jar:na]
        ... 11 common frames omitted
```

### Steps to Reproduce:

create a pipeline with Automated Trigger type: Git
branch: `develop`

artifact constraint: github-artifacts
filepath: `manifests/develop/deployment.yaml`

make sure that `manifests/develop/deployment.yaml` exists in the `develop` branch

trigger a manual execution or automated trigger.

### Additional Details:

other related log entries

```
Skipping trigger Trigger(8f9e1ef4-..., git, null, null, null, null, my-org github, develop, null, null, null, null, null, null, null, null, null, null, null, [d47c749e-...], null, null, null, null, null, null, Pipeline(my-pipeline, develop, 762f68cf-...)) as artifact constraints were not satisfied
```
```
Github Webhook event received: githubEvent=push repository=my-org/my-project project=my-org slug=my-project branch=develop hash=b8ee...
2020-08-25 14:30:10.949  INFO 1 --- [0.0-8089-exec-5] c.n.s.e.controllers.WebhooksController   : Webhook git:github:[ref:refs/heads/develop, ...snip...]
2020-08-25 14:30:10.960  INFO 1 --- [IoScheduler-113] c.n.spinnaker.fiat.shared.FiatService    : ---> HTTP GET http://spin-fiat.spinnaker:7003/authorize/anonymous
2020-08-25 14:30:10.973  INFO 1 --- [IoScheduler-113] c.n.spinnaker.fiat.shared.FiatService    : <--- HTTP 200 http://spin-fiat.spinnaker:7003/authorize/anonymous (12ms)
2020-08-25 14:30:10.975  WARN 1 --- [IoScheduler-113] c.n.s.e.p.artifacts.ArtifactMatcher      : Parsed message artifacts (size 2) greater than expected artifacts (size 1), continuing trigger anyway
2020-08-25 14:30:10.975  INFO 1 --- [IoScheduler-113] c.n.s.e.p.artifacts.ArtifactMatcher      : Skipping trigger Trigger(8f9e1ef4-..., git, null, null, null, null, my-org, my-project, github, develop, null, null, null, null, null, null, null, null, null, null, null, [d47c749e-...], null, null, null, null, null, null, Pipeline(my-pipeline, develop, 762f68cf-...)) as artifact constraints were not satisfied
```

**Comment by theRemix** [comment]
the fix was artifact personal github token

The issue I was running into was that the github token used for obtaining artifacts was attached to a user that has been removed from the organization.
Generating a new github artifact token (personal access token) resolved this issue

replacing the token in `/home/halyard/github_artifact_token`

halyard config
```yaml
  artifacts:
    github:
      enabled: true
      accounts:
      - name: github-artifacts
        tokenFile: /home/halyard/github_artifact_token
```

**Comment by mandiiip** [comment]
I am also facing same kind of issue even after adding token file.
this is the only thing i am getting after waiting for 2 minutes.
![image](https://user-images.githubusercontent.com/65283900/91863774-1aa84280-ec8d-11ea-93d8-390fe44088b2.png)

any idea on this?
