### ISSUE TITLE
Jenkins Property File  failed to trigger

### ISSUE THREAD

**Issue by zeyangli** [spinnaker/spinnaker#6041]
Hello, I am configuring jenkins to trigger spinnaker. The error message is as follows

Jenkins:
![image](https://user-images.githubusercontent.com/21000263/92901108-cfdbb700-f452-11ea-9d40-8aab0e901b29.png)

Spinnaker:
![image](https://user-images.githubusercontent.com/21000263/92901250-e8e46800-f452-11ea-928b-fe13e3708213.png)

Application  Permissions
![image](https://user-images.githubusercontent.com/21000263/92901329-fbf73800-f452-11ea-86f1-491a8c679aae.png)

igro log : 

```
2020-09-11 09:16:55.773  INFO 1 --- [0.0-8088-exec-7] c.n.s.igor.jenkins.client.JenkinsClient  : ---> HTTP GET http://jenkins.idevops.site/api/xml?tree=jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name]]]]]]]]]]
2020-09-11 09:16:55.854  WARN 1 --- [0.0-8088-exec-7] c.n.s.okhttp.OkHttp3MetricsInterceptor   : Request GET:http://jenkins.idevops.site/api/xml?tree=jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name,jobs[name]]]]]]]]]] is missing [X-SPINNAKER-USER, X-SPINNAKER-ACCOUNTS] authentication headers and will be treated as anonymous.
Request from: com.netflix.spinnaker.okhttp.MetricsInterceptor.doIntercept(MetricsInterceptor.java:95)
	at com.netflix.spinnaker.okhttp.OkHttp3MetricsInterceptor.intercept(OkHttp3MetricsInterceptor.java:33)
	at com.netflix.spinnaker.igor.jenkins.service.JenkinsService.getJobs(JenkinsService.java:144)
	at com.netflix.spinnaker.igor.build.InfoController.getJobs(InfoController.groovy:105)
	at com.netflix.spinnaker.igor.build.InfoController$$FastClassBySpringCGLIB$$7ed2bc23.invoke(<generated>)
	at com.netflix.spinnaker.igor.build.InfoController$$EnhancerBySpringCGLIB$$f79db3af.getJobs(<generated>)
	at com.netflix.spinnaker.igor.filters.IgorCorsFilter.doFilter(IgorCorsFilter.groovy:43)
	at com.netflix.spinnaker.fiat.shared.FiatAuthenticationFilter.doFilter(FiatAuthenticationFilter.java:65)
	at com.netflix.spinnaker.filters.AuthenticatedRequestFilter.doFilter(AuthenticatedRequestFilter.groovy:144)

```

**Comment by zeyangli** [comment]
is missing [X-SPINNAKER-USER, X-SPINNAKER-ACCOUNTS] authentication headers and will be treated as anonymous.

**Comment by plumpy** [comment]
Thanks for filing this issue. It looks like this might be a request for help rather than a bug. In that case, you're probably better off looking for answers [from our Slack community](https://join.spinnaker.io/), since there is a larger pool of users there. Use the search functionality to find users who have a similar experience, or post a message in `#general` or another related channel.
