### ISSUE TITLE
V1.22.1 Exception ( Deploy Manifest ) Access denied to account default

### ISSUE THREAD

**Issue by zeyangli** [spinnaker/spinnaker#6042]
The pipeline is triggered successfully, but it prompts that there is no permission to deploy.The permission is a bit complicated, please help to check whether it is my configuration problem or a bug? thank

![image](https://user-images.githubusercontent.com/21000263/92931359-e7786700-f475-11ea-963d-365652fba418.png)

### spin-echo.log:
```
2020-09-11 13:19:30.723  INFO 1 --- [eduler_Worker-6] c.n.s.e.s.a.p.PipelineConfigsPollingJob  : Running the pipeline configs polling agent...
2020-09-11 13:19:30.724  INFO 1 --- [eduler_Worker-6] c.n.s.e.s.a.p.PipelineConfigsPollingJob  : Done polling for pipeline configs in 0.001s
2020-09-11 13:19:35.906  INFO 1 --- [RxIoScheduler-3] c.n.spinnaker.fiat.shared.FiatService    : ---> HTTP GET http://spin-fiat.spinnaker:7003/authorize/anonymous
2020-09-11 13:19:35.919  INFO 1 --- [RxIoScheduler-3] c.n.spinnaker.fiat.shared.FiatService    : <--- HTTP 200 http://spin-fiat.spinnaker:7003/authorize/anonymous (12ms)
2020-09-11 13:19:35.922  INFO 1 --- [RxIoScheduler-3] c.n.s.e.p.monitor.TriggerMonitor         : Found matching pipeline pipelinetest:k8sdemo
2020-09-11 13:19:35.922  INFO 1 --- [RxIoScheduler-3] c.n.s.e.p.orca.PipelineInitiator         : Triggering Pipeline(pipelinetest, k8sdemo, f1d7cb97-eea6-442b-845d-2f410f2e35df) due to Trigger(9416f8ef-880f-3a19-9734-8c93c749b203, docker, null, null, null, null, null, null, null, null, null, null, null, null, null, my-harbor-registry, spinnaker02/spinnaker02-nginx-demo, v12, null, null, null, null, null, null, null, null, null, null, Pipeline(pipelinetest, k8sdemo, f1d7cb97-eea6-442b-845d-2f410f2e35df))
2020-09-11 13:19:35.929  INFO 1 --- [pool-2-thread-2] c.n.s.e.p.orca.OrcaService               : ---> HTTP POST http://spin-orca.spinnaker:8083/orchestrate
2020-09-11 13:19:36.000  WARN 1 --- [pool-2-thread-2] c.n.s.okhttp.OkHttpMetricsInterceptor    : Request POST:http://spin-orca.spinnaker:8083/orchestrate is missing [X-SPINNAKER-ACCOUNTS] authentication headers and will be treated as anonymous.
Request from: com.netflix.spinnaker.okhttp.MetricsInterceptor.doIntercept(MetricsInterceptor.java:95)
        at com.netflix.spinnaker.okhttp.OkHttpMetricsInterceptor.intercept(OkHttpMetricsInterceptor.java:34)
        at com.netflix.spinnaker.echo.pipelinetriggers.orca.PipelineInitiator.triggerWithRetries(PipelineInitiator.java:288)
        at com.netflix.spinnaker.echo.pipelinetriggers.orca.PipelineInitiator.lambda$triggerPipelineImpl$2(PipelineInitiator.java:239)
        at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:92)
        at com.netflix.spinnaker.echo.pipelinetriggers.orca.PipelineInitiator.triggerPipelineImpl(PipelineInitiator.java:239)
        at com.netflix.spinnaker.echo.pipelinetriggers.orca.PipelineInitiator.lambda$triggerPipeline$1(PipelineInitiator.java:211)
        at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:92)
2020-09-11 13:19:36.000  INFO 1 --- [pool-2-thread-2] c.n.s.e.p.orca.OrcaService               : <--- HTTP 200 http://spin-orca.spinnaker:8083/orchestrate (70ms)
2020-09-11 13:19:36.002  INFO 1 --- [pool-2-thread-2] c.n.s.e.p.orca.PipelineInitiator         : Successfully triggered Pipeline(pipelinetest, k8sdemo, f1d7cb97-eea6-442b-845d-2f410f2e35df): execution id: /pipelines/01EHYN4FGTV26YDZ3X5TRZM85D
2020-09-11 13:19:37.207  INFO 1 --- [RxIoScheduler-4] c.n.s.echo.telemetry.TelemetryService    : ---> HTTP POST https://stats.spinnaker.io/log
2020-09-11 13:19:37.668  INFO 1 --- [RxIoScheduler-4] c.n.s.echo.telemetry.TelemetryService    : <--- HTTP 200 https://stats.spinnaker.io/log (461ms)


```

### hal config:
```
kubernetes:                         
      enabled: true     
      accounts:                         
      - name: default
        requiredGroupMembership: []
        providerVersion: V2   
        permissions:  
          READ:               
          - yunweizu    
          WRITE:            
          - yunweizu    
        dockerRegistries:   
        - accountName: my-harbor-registry       
          namespaces: []
        context: kubernetes-admin@kubernetes
        configureImagePullSecrets: true
        serviceAccount: true
        cacheThreads: 1
        namespaces: []
        omitNamespaces:            
        - kube-system      
        - devops                   
        - kube-public      
        kinds: []    
        omitKinds: []                 
        customResources: []
        cachingPolicies: []
        oAuthScopes: []                  
        onlySpinnakerManaged: false
      primaryAccount: default     

```

### Application:

![image](https://user-images.githubusercontent.com/21000263/92931086-82247600-f475-11ea-9ab6-247a4c74e57d.png)

### Pipeline trigger
![image](https://user-images.githubusercontent.com/21000263/92931120-91a3bf00-f475-11ea-9574-8a57bc72ed6b.png)

**Comment by plumpy** [comment]
Thanks for filing this issue. It looks like this might be a request for help rather than a bug. In that case, you're probably better off looking for answers [from our Slack community](https://join.spinnaker.io/), since there is a larger pool of users there. Use the search functionality to find users who have a similar experience, or post a message in `#general` or another related channel.
