### ISSUE TITLE
Clouddriver not registering gitrepo credentials

### ISSUE THREAD

**Issue by kaiayang** [spinnaker/spinnaker#6050]
### Issue Summary:
When running a pipeline with a Bake Manifest step, I'm attempting to pull an artifact from a GitLab gitrepo account via HTTPS and access token (which has been tested locally and is working). The stage fails after 20 seconds, and the logs for Clouddriver show this:
```
java.io.IOException: Failed to clone or archive git/repo https://gitlab.com/XXXXXXX/XXXXXXXX.git: https://gitlab.com/XXXXXXX/XXXXXXXX.git: Authentication is required but no CredentialsProvider has been registered
	at com.netflix.spinnaker.clouddriver.artifacts.gitRepo.GitRepoArtifactCredentials.download(GitRepoArtifactCredentials.java:122) ~[clouddriver-artifacts.jar:na]
	at com.netflix.spinnaker.clouddriver.artifacts.ArtifactDownloader.download(ArtifactDownloader.java:34) ~[clouddriver-artifacts.jar:na]
	at com.netflix.spinnaker.clouddriver.controllers.ArtifactController.lambda$fetch$0(ArtifactController.java:65) ~[clouddriver-web.jar:na]
	at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:111) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:98) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:328) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```
This is what `clouddriver.yml` looks like:
```
artifacts:
  gitrepo:                                                                                
    enabled: true                                                                         
    accounts:                                                                             
    - name: XXXXXXX                                                                      
      tokenFile: /home/spinnaker/.hal/default/staging/dependencies/1050390366-gitlab_token
      sshTrustUnknownHosts: false
```
I have also tried configuring the artifact provider using a username+password and an ssh key, but all of them result in the same error.

EDIT: SSH works if you use a PEM key. The username+password and token based methods still do not work.

### Cloud Provider(s):
AWS

### Environment:
Self-managed Kubernetes 1.18.8, Spinnaker 1.22.1 deployed via Helm

### Feature Area:
Clouddriver

### Description:
I expect this to successfully clone the repo, since the credentials provided are valid, but either clouddriver does not see my credentials, or it is not using them.

### Steps to Reproduce:
Set up gitrepo artifact provider on Spinnaker 1.22.1:
```
hal config artifact gitrepo enable
hal config artifact gitrepo account add myaccount --token-file my-token-file
```
Then try to pull an artifact from a GitLab repo in a Bake Manifest pipeline stage.

**Comment by dperezro** [comment]
I'm having that same issue with GitRepo artifacts and trying to use a Github token. 

`Failed to clone or archive git/repo https://github.com/XXX/YYY: https://github.com/XXX/YYY: Authentication is required but no CredentialsProvider has been registered
`
does anybody know a workaround for this?

**Comment by dperezro** [comment]
I've fixed by avoiding using token file as it's not supported. Documentation is wrong, PR https://github.com/spinnaker/spinnaker.github.io/pull/2080, you can check such java class stated in the description and you'll see there's a couple of flags not supported. As a workaround, the command I've used it `hal config artifact gitrepo account add myaccount --token=$(cat my-token-file.txt)`

**Comment by kaiayang** [comment]
Thanks, @dperezro. I'll close the issue.
