### ISSUE TITLE
AWS pubsub in Echo won't let me define aws credentials

### ISSUE THREAD

**Issue by atyutyunnik** [spinnaker/spinnaker#6061]
### Issue Summary:
AWS pubsub in Echo won't let me define aws credentials and throws an exception when attempting to connect to SQS:
```
2020-09-21 21:12:01.353 ERROR 1 --- [pool-3-thread-1] c.n.s.echo.pubsub.aws.SQSSubscriber      : Error initializing queue ARN{arn='arn:aws:sqs:us-east-1:<account-id>:spinnaker-aws-pubsub'}
        at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2207) ~[aws-java-sdk-sqs-1.11.802.jar:na]
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2174) ~[aws-java-sdk-sqs-1.11.802.jar:na]
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2163) ~[aws-java-sdk-sqs-1.11.802.jar:na]
        at com.amazonaws.services.sqs.AmazonSQSClient.executeGetQueueUrl(AmazonSQSClient.java:1201) ~[aws-java-sdk-sqs-1.11.802.jar:na]
        at com.amazonaws.services.sqs.AmazonSQSClient.getQueueUrl(AmazonSQSClient.java:1173) ~[aws-java-sdk-sqs-1.11.802.jar:na]
        at com.amazonaws.services.sqs.AmazonSQSClient.getQueueUrl(AmazonSQSClient.java:1213) ~[aws-java-sdk-sqs-1.11.802.jar:na]
        at com.netflix.spinnaker.echo.pubsub.aws.SQSSubscriber.initializeQueue(SQSSubscriber.java:142) ~[echo-pubsub-aws.jar:na]
        at com.netflix.spinnaker.echo.pubsub.aws.SQSSubscriber.run(SQSSubscriber.java:117) ~[echo-pubsub-aws.jar:na]
```

### Description:
For Spinnaker is running outside of AWS, I define the credentials like it's done for other services in .hal/default/profiles/echo-local.yml:
```pubsub:
  enabled: true
  amazon:
    enabled: true
    accessKeyId: <access_key>
    secretAccessKey: <secret>
```
but they won't help. Code fragment which is typically used to initialize awsCredentialsProvider is simply missing in echo-pubsub-aws\src\main\java\com\netflix\spinnaker\echo\pubsub\aws\SQSSubscriberProvider.java

**Comment by atyutyunnik** [comment]
I am proposing a ```release-19.x``` based patch here. It enables this construct:
```
  enabled: true
  amazon:
    enabled: true
    accessKeyId: <access_key>
    secretAccessKey: <secret>
    subscriptions:
    - name: spinnaker-aws-pubsub-us-east-1

```

it even works: Spinnaker pipelines get triggered from Amazons SNS/SQS

[echo.patch.txt](https://github.com/spinnaker/spinnaker/files/5262501/echo.patch.txt)


However, for some reason this patch won't apply to the master branch. Also, I am not sure how to implement a unit-test for this without providing live account credentials.

Please advise

**Comment by robzienert** [comment]
Strongly recommend against using static AWS credentials. Is this to support a local development scenario or something?

**Comment by atyutyunnik** [comment]
can you please pull this into the master? It's been more than 20 days.

**Comment by cfieber** [comment]
The SDK already supports several way of supplying VM wide credentials

you could, for your process:
```
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
```

or, supply system properties:
```
-Daws.accessKeyId=
-Daws.secretKey=
```

or create an AWS credentials file (~/.aws/credentials):
```
[default]
aws_access_key_id     =
aws_secret_access_key =
```

I'd look at the other examples you supplied as places where we failed to do the right thing, not as a reason we should enable it here

The correct one of those above depends on how you manage your images but in a kubernetes world the right answer would almost certainly be supplying a secrets manifest to the pod and setting those environment variables via a reference to the secret.
