### ISSUE TITLE
deployment on CF fails when routes are defined in manifest

### ISSUE THREAD

**Issue by floriankammermann** [spinnaker/spinnaker#6163]
### Issue Summary:
When providing attribute routes in manifest.yml for cloudfoundry deployment. Deployment fails.

### Cloud Provider(s):
CF

### Environment:
Clouddriver version: 7.0.1
CF API version 3.88.0
Buildpack is preinstalled on CF https://docs.cloudfoundry.org/buildpacks/binary/index.html

### Feature Area:
Deploy CF binary_buildpack with manifest as artifact

### Description:

The following setup
* deploying a binary_buildpack 
* application artifact as zip with one binary inside
* providing the manfiest as artifact, 
* content of the manifest:
```
---
applications:
  - name: rest-error-simulator-baseline
    memory: 1024M
    instances: 1
    command: ./rest-error-simulator-server
    buildpacks:
      - binary_buildpack
    routes:
      - route: rest-error-simulator-baseline.test.com
````
* Pipeline with stage deploy

The execution fails, clouddriver log error:
```
clouddriver[15212]: 2020-11-07 10:14:23.138 INFO 15212 --- [ionProcessor-20] c.n.s.c.data.task.jedis.JedisTask : [ORCHESTRATION] Orchestration failed: DeployCloudFoundryServerGroupAtomicOperation | RuntimeException: [retrofit.converter.ConversionException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.netflix.spinnaker.clouddriver.cloudfoundry.client.model.ErrorDescription$Code`, problem: java.lang.ClassCastException@475042a6
clouddriver[15212]: at [Source: (ByteArrayInputStream); line: 4, column: 11] (through reference chain: com.netflix.spinnaker.clouddriver.cloudfoundry.client.model.ErrorDescription["code"])]
clouddriver[15212]: 2020-11-07 10:14:23.141 ERROR 15212 --- [ionProcessor-20] c.n.s.c.o.DefaultOrchestrationProcessor : java.lang.RuntimeException: retrofit.converter.ConversionException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.netflix.spinnaker.clouddriver.cloudfoundry.client.model.ErrorDescription$Code`, problem: java.lang.ClassCastException@475042a6
clouddriver[15212]: at [Source: (ByteArrayInputStream); line: 4, column: 11] (through reference chain: com.netflix.spinnaker.clouddriver.cloudfoundry.client.model.ErrorDescription["code"])
clouddriver[15212]: at retrofit.RetrofitError.getBodyAs(RetrofitError.java:139)
clouddriver[15212]: at com.netflix.spinnaker.clouddriver.cloudfoundry.client.CloudFoundryClientUtils.safelyCall(CloudFoundryClientUtils.java:51)
clouddriver[15212]: at com.netflix.spinnaker.clouddriver.cloudfoundry.client.Routes.createRoute(Routes.java:184)
clouddriver[15212]: at com.netflix.spinnaker.clouddriver.cloudfoundry.deploy.ops.AbstractCloudFoundryLoadBalancerMappingOperation.mapRoutes(AbstractCloudFoundryLoadBalancerMappingOperation.java:69)
clouddriver[15212]: at com.netflix.spinnaker.clouddriver.cloudfoundry.deploy.ops.DeployCloudFoundryServerGroupAtomicOperation.operate(DeployCloudFoundryServerGroupAtomicOperation.java:107)
clouddriver[15212]: at com.netflix.spinnaker.clouddriver.cloudfoundry.deploy.ops.DeployCloudFoundryServerGroupAtomicOperation.operate(DeployCloudFoundryServerGroupAtomicOperation.java:51)
clouddriver[15212]: at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate.call(Unknown Source)
clouddriver[15212]: at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy:118)
clouddriver[15212]: at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1$_closure2.doCall(DefaultOrchestrationProcessor.groovy)
clouddriver[15212]: at jdk.internal.reflect.GeneratedMethodAccessor630.invoke(Unknown Source)
clouddriver[15212]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
clouddriver[15212]: at java.base/java.lang.reflect.Method.invoke(Method.java:567)
clouddriver[15212]: at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
clouddriver[15212]: at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
clouddriver[15212]: at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
clouddriver[15212]: at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
clouddriver[15212]: at groovy.lang.Closure.call(Closure.java:405)
clouddriver[15212]: at groovy.lang.Closure.call(Closure.java:399)
clouddriver[15212]: at com.netflix.spinnaker.clouddriver.metrics.TimedCallable$CallableWrapper.call(TimedCallable.java:81)
clouddriver[15212]: at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.java:45)
clouddriver[15212]: at java_util_concurrent_Callable$call.call(Unknown Source)
clouddriver[15212]: at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy:117)
clouddriver[15212]: at com.netflix.spinnaker.clouddriver.orchestration.DefaultOrchestrationProcessor$_process_closure1.doCall(DefaultOrchestrationProcessor.groovy)
clouddriver[15212]: at jdk.internal.reflect.GeneratedMethodAccessor627.invoke(Unknown Source)
clouddriver[15212]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
clouddriver[15212]: at java.base/java.lang.reflect.Method.invoke(Method.java:567)
clouddriver[15212]: at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
clouddriver[15212]: at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
clouddriver[15212]: at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
clouddriver[15212]: at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
clouddriver[15212]: at groovy.lang.Closure.call(Closure.java:405)
clouddriver[15212]: at groovy.lang.Closure.call(Closure.java:399)
clouddriver[15212]: at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$wrapCallableForPrincipal$0(AuthenticatedRequest.java:272)
clouddriver[15212]: at com.netflix.spinnaker.clouddriver.metrics.TimedCallable.call(TimedCallable.java:45)
clouddriver[15212]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
clouddriver[15212]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
clouddriver[15212]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
clouddriver[15212]: at java.base/java.lang.Thread.run(Thread.java:835)
clouddriver[15212]: Caused by: retrofit.converter.ConversionException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.netflix.spinnaker.clouddriver.cloudfoundry.client.model.ErrorDescription$Code`, problem: java.lang.ClassCastException@475042a6
clouddriver[15212]: at [Source: (ByteArrayInputStream); line: 4, column: 11] (through reference chain: com.netflix.spinnaker.clouddriver.cloudfoundry.client.model.ErrorDescription["code"])
clouddriver[15212]: at retrofit.converter.JacksonConverter.fromBody(JacksonConverter.java:40)
clouddriver[15212]: at retrofit.RetrofitError.getBodyAs(RetrofitError.java:137)
clouddriver[15212]: ... 37 more
clouddriver[15212]: Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.netflix.spinnaker.clouddriver.cloudfoundry.client.model.ErrorDescription$Code`, problem: java.lang.ClassCastException@475042a6
clouddriver[15212]: at [Source: (ByteArrayInputStream); line: 4, column: 11] (through reference chain: com.netflix.spinnaker.clouddriver.cloudfoundry.client.model.ErrorDescription["code"])
clouddriver[15212]: at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
clouddriver[15212]: at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1758)
clouddriver[15212]: at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1128)
clouddriver[15212]: at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:159)
clouddriver[15212]: at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
clouddriver[15212]: at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
clouddriver[15212]: at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
clouddriver[15212]: at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
clouddriver[15212]: at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3519)
clouddriver[15212]: at retrofit.converter.JacksonConverter.fromBody(JacksonConverter.java:36)
clouddriver[15212]: ... 38 more
clouddriver[15212]: Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@475042a6
clouddriver[15212]: at jdk.internal.reflect.GeneratedMethodAccessor661.invoke(Unknown Source)
clouddriver[15212]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
clouddriver[15212]: at java.base/java.lang.reflect.Method.invoke(Method.java:567)
clouddriver[15212]: at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.callOnWith(AnnotatedMethod.java:116)
clouddriver[15212]: at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:151)
clouddriver[15212]: ... 44 more
clouddriver[15212]: 2020-11-07 10:14:28.925 INFO 15212 --- [0.1-7002-exec-6] java.lang.Class : Fetching search results for resterrorsimulator, platform: null, type: [securityGroups], pageSize: 500, pageNumber: 1, filters: [:]
```

### Steps to Reproduce:
* https://github.com/floriankammermann/rest-error-simulator
* make build-server
* create zip and upload it somewhere, where spinnaker can access it
* take the example manifest and upload it somewhere, where spinnaker can access it
* create a cloudfoundry account
* create a server group
  * set the cloudfoundry account
  * set the zip as artifact
  * set the manifest as artifact

### Additional information
* when I deploy directly to cloudfoundry it works:  `cf push rest-error-simulator.zip -f manifest.yml`
* when I remove the routes section in the manifest.yml then the deployment works.
* I tried to use the form and not manifest. But this fails, because I can not provide the command in the form and I need to do this for the binary_buildpack

**Comment by zachsmith1** [comment]
Fixed by -> https://github.com/spinnaker/clouddriver/pull/5119
