### ISSUE TITLE
Halyard daemon cannot start

### ISSUE THREAD

**Issue by prestonvanloon** [spinnaker/spinnaker#6227]
### Issue Summary:

Halyard daemon cannot start

### Cloud Provider(s):

N/A

### Environment:

Ubuntu 20.04

### Feature Area:

Halyard

### Description:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/netflix/spinnaker/halyard/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

### Steps to Reproduce:

Install halyard and try to run any hal command.

### Additional Details:

I have java 11 jdk installed.
```
sudo apt-get install openjdk-11-jdk
```

Not sure why it's complaining about version up to 52 (java 8).

**Comment by prestonvanloon** [comment]
Also installed `openjdk-11-jre-headless`, same issue.

**Comment by prestonvanloon** [comment]
I tried removing all java version, reinstalling java 11. Ultimately, the following command resolved my issue.
```
update-alternatives --config java
```
Then select java jdk 11.

**Comment by prestonvanloon** [comment]
```
sudo update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                         Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/zulu8/jre/bin/java               1805001   auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java   1111      manual mode
  2            /usr/lib/jvm/zulu8/jre/bin/java               1805001   manual mode

Press <enter> to keep the current choice[*], or type selection number: 1
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/java to provide /usr/bin/java (java) in manual mode
```
