### ISSUE TITLE
front50 is running with error

### ISSUE THREAD

**Issue by neil-yechenwei** [spinnaker/spinnaker#6468]
### Issue Summary:
front50 is running with error after deployed successfully. 

### Error Message:
```
2021-06-29 06:36:12.983 ERROR 13754 --- [0.1-8080-exec-6] c.n.s.k.w.e.GenericExceptionHandlers     : Internal Server Error

java.lang.IllegalStateException: Unable to fetch object (key: xx-xx-xx-xx, group: pipelines)
at com.netflix.spinnaker.front50.model.AzureStorageService.loadObject(AzureStorageService.java:106) ~[front50-azure.jar:na]
at com.netflix.spinnaker.front50.model.StorageServiceSupport.lambda$fetchAllItems$13(StorageServiceSupport.java:406) ~[front50-
core.jar:na]
at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastPath(OnSubscribeFromIterable.java:173) ~[rxjava-1.3.8.jar
:1.3.8]
at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:86) ~[rxjava-1.3.8.jar:1
.3.8]
at rx.Subscriber.setProducer(Subscriber.java:211) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34) ~[rxjava-1.3.8.jar:1.3.8]
at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107) ~[rxjava-1.3.8.jar:1.3.8]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: java.util.HashMap$Node.class
at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73) ~[rxjava-1.3.8.jar:1.3.8]
... 18 common frames omitted
```

### Cloud Provider(s):
Azure

### Environment:
ubuntu 16.04

### Feature Area:
front50

### Steps to Reproduce:
1. hal config version edit --version branch:upstream/master
2. hal deploy apply
3. front50 is running with error (You can check the error message with commad "cat ~/dev/spinnaker/logs/front50.log")

**Comment by neil-yechenwei** [comment]
@mochacat, After investigated, it seems that the failure is caused by the commit https://github.com/spinnaker/front50/pull/1035. Could you help to fix it asap since we're blocked now. Thanks.

**Comment by neil-yechenwei** [comment]
+@ajordens & @dogonthehorizon for awarness.

**Comment by neil-yechenwei** [comment]
Hi @mochacat, kindly ping. Is there any update for the fix?

**Comment by mochacat** [comment]
@neil-yechenwei thanks for reporting. We are aware of the issue and working on a fix now. Will update when the PR is submitted.

**Comment by neil-yechenwei** [comment]
@mochacat , seems front50 is still running with error. Could you help take a look?

Error message:
```
2021-07-14 04:12:20.167 ERROR 26359 --- [0.1-8080-exec-8] c.n.s.k.w.e.GenericExceptionHandlers     : Internal Server Error

java.lang.NullPointerException: null
at com.netflix.spinnaker.front50.model.StorageServiceSupport.buildObjectKey(StorageServiceSupport.java:313) ~[front50-core.jar:
na]
at com.netflix.spinnaker.front50.model.StorageServiceSupport.buildObjectKey(StorageServiceSupport.java:309) ~[front50-core.jar:
na]
at com.netflix.spinnaker.front50.model.StorageServiceSupport.lambda$fetchAllItems$13(StorageServiceSupport.java:408) ~[front50-
core.jar:na]
at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastPath(OnSubscribeFromIterable.java:173) ~[rxjava-1.3.8.jar
:1.3.8]
at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:86) ~[rxjava-1.3.8.jar:1
.3.8]
at rx.Subscriber.setProducer(Subscriber.java:211) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34) ~[rxjava-1.3.8.jar:1.3.8]
at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107) ~[rxjava-1.3.8.jar:1.3.8]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: java.util.HashMap$Node.class
at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118) ~[rxjava-1.3.8.jar:1.3.8]
at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73) ~[rxjava-1.3.8.jar:1.3.8]
... 18 common frames omitted

2021-07-14 04:12:20.981  WARN 26359 --- [    scheduler-9] c.n.s.f.m.pipeline.DefaultPipelineDAO    : DefaultPipelineDAO is unhealthy (l
ag: 1626235940981, populatedCache: false)
```

**Comment by pdk27** [comment]
@mochacat, FYI, facing the same issue on AWS too. Seems like the [new model ](https://github.com/spinnaker/front50/blob/4751d870a4c8e9d81b6a6c892f8138a8887ed7af/front50-api/src/main/java/com/netflix/spinnaker/front50/api/model/pipeline/Pipeline.java) for `Pipeline` might be causing the issue. 

Here is the error I see on init:

```
2021-07-15 17:16:45.195  INFO 1459 --- [           main] c.n.s.f.model.project.DefaultProjectDAO  : Warming Cache
2021-07-15 17:16:45.243  INFO 1459 --- [           main] c.n.s.f.m.pipeline.DefaultPipelineDAO    : Warming Cache
2021-07-15 17:16:45.308 ERROR 1459 --- [           main] c.n.s.f.m.pipeline.DefaultPipelineDAO    : Unable to warm cache: {}

java.lang.IllegalStateException: Unable to deserialize object (key: 49020da9-9228-4646-8c2a-d10900836b70)
	at com.netflix.spinnaker.front50.model.S3StorageService.loadObject(S3StorageService.java:126) ~[front50-s3.jar:na]
	at com.netflix.spinnaker.front50.model.StorageServiceSupport.lambda$fetchAllItems$13(StorageServiceSupport.java:406) ~[front50-core.jar:na]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastPath(OnSubscribeFromIterable.java:173) ~[rxjava-1.3.8.jar:1.3.8]
...
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107) ~[rxjava-1.3.8.jar:1.3.8]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "keepWaitingPipelines" (class com.netflix.spinnaker.front50.api.model.pipeline.Pipeline), not marked as ignorable (19 known properties: "schema", "config", "payloadConstraints", "name", "any", "application", "index", "stages", "lastModifiedBy", "serviceAccount", "type", "id", "email", "roles", "lastModified", "constraints", "triggers", "template", "createdAt"])
 at [Source: (com.amazonaws.services.s3.model.S3ObjectInputStream); line: 1, column: 30] (through reference chain: com.netflix.spinnaker.front50.api.model.pipeline.Pipeline["keepWaitingPipelines"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1582) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3471) ~[jackson-databind-2.11.1.jar:2.11.1]
	at com.netflix.spinnaker.front50.model.S3StorageService.deserialize(S3StorageService.java:334) ~[front50-s3.jar:na]
	at com.netflix.spinnaker.front50.model.S3StorageService.loadObject(S3StorageService.java:117) ~[front50-s3.jar:na]
	... 20 common frames omitted
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: java.util.HashMap$Node.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73) ~[rxjava-1.3.8.jar:1.3.8]
	... 18 common frames omitted

2021-07-15 17:16:45.312  WARN 1459 --- [    scheduler-2] c.n.s.f.m.pipeline.DefaultPipelineDAO    : DefaultPipelineDAO is unhealthy (lag: 1626369405312, populatedCache: false)
```

**Comment by neil-yechenwei** [comment]
@mochacat , kindly ping. Is there any update for this blocking issue?

**Comment by neil-yechenwei** [comment]
Seems the issue has been fixed since I didn't see it anymore.
