### ISSUE TITLE
Healthcheck sync fails on GCE

### ISSUE THREAD

**Issue by miselin** [spinnaker/spinnaker#6610]
### Issue Summary:
We can't use _any_ existing health checks because at least one of them fails to synchronize with an `IllegalArgumentException`.

### Cloud Provider(s):
GCE

### Environment:
We're running latest Spinnaker in GKE. The service account being used has access to the health checks. 

We have a few different categories of health check, e.g.
```
"httpHealthCheck": {
      "portSpecification": "USE_SERVING_PORT",
      "proxyHeader": "NONE",
      "requestPath": "/"
    },
...
"httpHealthCheck": {
      "host": "[domain name]",
      "port": 8080,
      "proxyHeader": "NONE",
      "requestPath": "/healthcheck"
    },
...
"httpHealthCheck": {
      "portName": "http",
      "portSpecification": "USE_NAMED_PORT",
      "proxyHeader": "NONE",
      "requestPath": "/"
    },
```

I suspect that the `USE_NAMED_PORT` and `USE_SERVING_PORT` variants are causing us some problems, but we don't have the ability to modify these as some are coming from GKE's built-in health checks.

### Feature Area:
Pipelines

### Description:
Here's the stack trace:
```
java.lang.IllegalArgumentException: null
    at jdk.internal.reflect.GeneratedMethodAccessor753.invoke(Unknown Source) ~[na:na]
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
    at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.11.jar:2.5.11]
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.11.jar:2.5.11]
    at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2754) ~[groovy-2.5.11.jar:2.5.11]
    at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3809) ~[groovy-2.5.11.jar:2.5.11]
    at com.netflix.spinnaker.clouddriver.google.model.GoogleHealthCheck.setProperty(GoogleHealthCheck.groovy) ~[clouddriver-google.jar:na]
    at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:213) ~[groovy-2.5.11.jar:2.5.11]
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:496) ~[groovy-2.5.11.jar:2.5.11]
    at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHealthCheckCachingAgent.toGoogleHealthCheck(GoogleHealthCheckCachingAgent.groovy:192) ~[clouddriver-google.jar:na]
    at jdk.internal.reflect.GeneratedMethodAccessor1872.invoke(Unknown Source) ~[na:na]
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
    at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.11.jar:2.5.11]
    at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:149) ~[groovy-2.5.11.jar:2.5.11]
    at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:100) ~[groovy-2.5.11.jar:2.5.11]
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:216) ~[groovy-2.5.11.jar:2.5.11]
    at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHealthCheckCachingAgent$_loadHealthChecks_closure6.doCall(GoogleHealthCheckCachingAgent.groovy:151) ~[clouddriver-google.jar:na]
    at jdk.internal.reflect.GeneratedMethodAccessor1871.invoke(Unknown Source) ~[na:na]
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
    at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.11.jar:2.5.11]
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.11.jar:2.5.11]
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.11.jar:2.5.11]
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.11.jar:2.5.11]
    at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.11.jar:2.5.11]
    at groovy.lang.Closure.call(Closure.java:421) ~[groovy-2.5.11.jar:2.5.11]
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3574) ~[groovy-2.5.11.jar:2.5.11]
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3559) ~[groovy-2.5.11.jar:2.5.11]
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3659) ~[groovy-2.5.11.jar:2.5.11]
    at org.codehaus.groovy.runtime.dgm$87.invoke(Unknown Source) ~[groovy-2.5.11.jar:2.5.11]
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244) ~[groovy-2.5.11.jar:2.5.11]
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) ~[groovy-2.5.11.jar:2.5.11]
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) ~[groovy-2.5.11.jar:2.5.11]
    at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHealthCheckCachingAgent.loadHealthChecks(GoogleHealthCheckCachingAgent.groovy:151) ~[clouddriver-google.jar:na]
    at com.netflix.spinnaker.clouddriver.google.provider.agent.GoogleHealthCheckCachingAgent.loadData(GoogleHealthCheckCachingAgent.groovy:57) ~[clouddriver-google.jar:na]
    at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgentWithoutStore(CachingAgent.java:87) ~[clouddriver-api.jar:na]
    at com.netflix.spinnaker.cats.agent.CachingAgent$CacheExecution.executeAgent(CachingAgent.java:77) ~[clouddriver-api.jar:na]
    at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentExecutionAction.execute(ClusteredAgentScheduler.java:340) ~[cats-redis.jar:na]
    at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler$AgentJob.run(ClusteredAgentScheduler.java:310) ~[cats-redis.jar:na]
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
    at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

It'd be nice to be able to filter out the failed health checks and still see the successful ones.

### Steps to Reproduce:
1. Set up a selection of health checks, with various port specifications
2. Try to synchronize them to Spinnaker
3. Note that no health checks are imported

### Additional Details:

Screenshot of health checks missing here:
![image](https://user-images.githubusercontent.com/73127/154593426-33ed533b-f610-4fb1-b170-dad246774138.png)

**Comment by miselin** [comment]
This should be solved with https://github.com/spinnaker/clouddriver/pull/5643 - the "invalid" health checks will log a warning, but the remaining health checks should arrive in this list ready for use.
