### ISSUE TITLE
Deployment started failing at DisableCluster

### ISSUE THREAD

**Issue by c0debreaker** [spinnaker/spinnaker#6629]
### Issue Summary:
Spinnaker has been working so well for months/years and then today, users are unable to deploy their apps since it kept failing at DisableCluster at the 30th minute.

### Cloud Provider(s):
AWS

### Environment:
Dev, Stage, etc

### Feature Area:
Pipeline

### Description:
Normally at this stage, the old EC2 instances are going to get terminated and new instances will be deployed. However, the old EC2 instances were not being terminated.

### Additional Details:
This is how it looks like - https://imgur.com/CeUfMKT

I also saw this from another failed deployment. Maybe this would provide help in debugging
```
{
id: "01FYW76H32DZ011Z8FJ5P7KVM3",
refId: "4<1>1<1",
type: "disableCluster",
name: "disableCluster",
startTime: 1648067036277,
endTime: 1648068866432,
status: "TERMINAL",
context: {
exception: {
exceptionType: "TimeoutException",
shouldRetry: false,
details: {
stackTrace: "com.netflix.spinnaker.orca.exceptions.TimeoutException: WaitForClusterDisableTask of stage disableCluster timed out after 30 minutes 4 seconds. pausedDuration: 0 seconds, elapsedTime: 30 minutes 4 seconds,timeoutValue: 30 minutes
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.checkForTaskTimeout(RunTaskHandler.kt:206)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.checkForTimeout(RunTaskHandler.kt:183)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$checkForTimeout(RunTaskHandler.kt:54)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:80)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:54)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:163)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:54)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:48)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:32)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:58)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:32)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:67)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:54)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:54)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:54)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:41)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:54)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:156)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:66)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:54)
	at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36)
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt)
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:54)
	at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47)
	at com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:83)
	at co.elastic.apm.agent.impl.async.SpanInScopeRunnableWrapper.run(SpanInScopeRunnableWrapper.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
",
error: "Unexpected Task Failure",
errors: [
"WaitForClusterDisableTask of stage disableCluster timed out after 30 minutes 4 seconds. pausedDuration: 0 seconds, elapsedTime: 30 minutes 4 seconds,timeoutValue: 30 minutes"
]
},
operation: "waitForClusterDisable",
timestamp: 1648068866409
}
```

**Comment by c0debreaker** [comment]
I also found out we are unable to destroy server group anymore. It is timing out. Here's a screenshot -https://imgur.com/tBGYvZc

**Comment by c0debreaker** [comment]
I finally fixed it. The fixed was so unusual. Just had to terminate all asgs.
