### ISSUE TITLE
Error encountered during catlog of null

### ISSUE THREAD

**Issue by sarath9985** [spinnaker/spinnaker#6681]
### Cloud Provider(s):
https://docs.armory.io/armory-enterprise/armory-admin/aws/artifacts-ecr-connect/

I've followed all the docs, still, I'm not able to integrate ecr with spinnaker.

retrofit.RetrofitError: 401 Unauthorized
        at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
        at com.sun.proxy.$Proxy177.getCatalog(Unknown Source) ~[na:na]
        at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$DockerRegistryService$getCatalog$0.call(Unknown Source) ~[na:na]
        at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$_getCatalog_closure9.doCall(DockerRegistryClient.groovy:333) ~[clouddriver-docker.jar:na]
        at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$_getCatalog_closure9.doCall(DockerRegistryClient.groovy) ~[clouddriver-docker.jar:na]
        at jdk.internal.reflect.GeneratedMethodAccessor252.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.9.jar:2.5.9]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.9.jar:2.5.9]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.9.jar:2.5.9]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.9.jar:2.5.9]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:37) ~[groovy-2.5.9.jar:2.5.9]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) ~[groovy-2.5.9.jar:2.5.9]
        at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient.request(DockerRegistryClient.groovy:422) ~[clouddriver-docker.jar:na]
        at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$request.callCurrent(Unknown Source) ~[na:na]
        at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient.getCatalog(DockerRegistryClient.groovy:331) ~[clouddriver-docker.jar:na]
        at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient.getCatalog(DockerRegistryClient.groovy) ~[clouddriver-docker.jar:na]
        at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$getCatalog$0.call(Unknown Source) ~[na:na]
        at com.netflix.spinnaker.clouddriver.docker.registry.security.DockerRegistryCredentials.getRepositories(DockerRegistryCredentials.groovy:65) ~[clouddriver-docker.jar:na]
        at jdk.internal.reflect.GeneratedMethodAccessor251.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.9.jar:2.5.9]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.9.jar:2.5.9]
        at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76) ~[groovy-2.5.9.jar:2.5.9]
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.callGroovyObjectGetProperty(GetEffectivePogoPropertySite.java:68) ~[groovy-2.5.9.jar:2.5.9]
        at com.netflix.spinnaker.clouddriver.docker.registry.provider.agent.DockerRegistryImageCachingAgent.loadTags(DockerRegistryImageCachingAgent.groovy:90) ~[clouddriver-docker.jar:na]
        at com.netflix.spinnaker.clouddriver.docker.registry.provider.agent.DockerRegistryImageCachingAgent.loadData(DockerRegistryImageCachingAgent.groovy:74) ~[clouddriver-docker.jar:na]

**Comment by mattgogerly** [comment]
Have you provided a username/passwordCommand? 401 would suggest invalid credentials.

**Comment by sarath9985** [comment]
@mattgogerly
