### ISSUE TITLE
Failed to start Orca

### ISSUE THREAD

**Issue by neil-yechenwei** [spinnaker/spinnaker#6704]
### Issue Summary:
It failed to start Orca and threw below error message after deployed successfully. After investigated, it seems that the failure is caused by the commit https://github.com/spinnaker/orca/pull/4269. @mattgogerly, Could you take a look this issue and fix it asap since we're blocked now? Thanks.

### Error Message:
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-08-12 08:59:45.442 ERROR 9589 --- [           main] o.s.boot.SpringApplication               : [] Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'redisOrcaQueueConfiguration': Unsatisfied dep
endency expressed through method 'redisQueueObjectMapper' parameter 2; nested exception is org.springframework.beans.factory.BeanCreationExcep
tion: Error creating bean with name 'taskResolver' defined in com.netflix.spinnaker.orca.config.OrcaConfiguration: Bean instantiation via fact
ory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca
.TaskResolver]: Factory method 'taskResolver' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyExce
ption: Error creating bean with name 'upsertScalingPolicyTask' defined in URL [jar:file:/home/spintester/dev/spinnaker/orca/orca-clouddriver/b
uild/libs/orca-clouddriver.jar!/com/netflix/spinnaker/orca/clouddriver/tasks/scalingpolicy/UpsertScalingPolicyTask.class]: Unsatisfied depende
ncy expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error cre
ating bean with name 'katoOperationsRunner' defined in com.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration: Unsatisfied dep
endency expressed through method 'katoOperationsRunner' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependen
cyException: Error creating bean with name 'katoService' defined in com.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration: Un
satisfied dependency expressed through method 'katoService' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationExc
eption: Error creating bean with name 'katoDeployService' defined in com.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration: B
ean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [
com.netflix.spinnaker.orca.clouddriver.KatoRestService]: Factory method 'katoDeployService' threw exception; nested exception is java.lang.Nul
lPointerException
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(Aut
owiredAnnotationBeanPostProcessor.java:768)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotation
BeanPostProcessor.java:720)
at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPost
Processor.java:399)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1
425)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:5
93)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516
)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143
)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
at org.springframework.boot.builder.SpringApplicationBuilder$run$0.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
at com.netflix.spinnaker.orca.Main.main(Main.groovy:85)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'taskResolver' defined in com.netflix.spinna
ker.orca.config.OrcaConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiati
onException: Failed to instantiate [com.netflix.spinnaker.orca.TaskResolver]: Factory method 'taskResolver' threw exception; nested exception 
is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'upsertScalingPolicyTask' defined in URL [j
ar:file:/home/spintester/dev/spinnaker/orca/orca-clouddriver/build/libs/orca-clouddriver.jar!/com/netflix/spinnaker/orca/clouddriver/tasks/sca
lingpolicy/UpsertScalingPolicyTask.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springfra
mework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'katoOperationsRunner' defined in com.netflix.spinnaker.orc
a.clouddriver.config.CloudDriverConfiguration: Unsatisfied dependency expressed through method 'katoOperationsRunner' parameter 0; nested exce
ption is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'katoService' defined in com.netflix.
spinnaker.orca.clouddriver.config.CloudDriverConfiguration: Unsatisfied dependency expressed through method 'katoService' parameter 0; nested 
exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'katoDeployService' defined in com.netflix
.spinnaker.orca.clouddriver.config.CloudDriverConfiguration: Bean instantiation via factory method failed; nested exception is org.springframe
work.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.clouddriver.KatoRestService]: Factory method 'katoDep
loyService' threw exception; nested exception is java.lang.NullPointerException
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657)
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:637)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableB
eanFactory.java:1341)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.
java:1181)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:5
56)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516
)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(Aut
owiredAnnotationBeanPostProcessor.java:760)
... 24 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.TaskResolver]: Factory meth
od 'taskResolver' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean w
ith name 'upsertScalingPolicyTask' defined in URL [jar:file:/home/spintester/dev/spinnaker/orca/orca-clouddriver/build/libs/orca-clouddriver.j
ar!/com/netflix/spinnaker/orca/clouddriver/tasks/scalingpolicy/UpsertScalingPolicyTask.class]: Unsatisfied dependency expressed through constr
uctor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'katoOp
erationsRunner' defined in com.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration: Unsatisfied dependency expressed through me
thod 'katoOperationsRunner' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating 
bean with name 'katoService' defined in com.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration: Unsatisfied dependency express
ed through method 'katoService' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean 
with name 'katoDeployService' defined in com.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration: Bean instantiation via factor
y method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.c
louddriver.KatoRestService]: Factory method 'katoDeployService' threw exception; nested exception is java.lang.NullPointerException
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652)
... 37 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'upsertScalingPolicyTask' defined i
n URL [jar:file:/home/spintester/dev/spinnaker/orca/orca-clouddriver/build/libs/orca-clouddriver.jar!/com/netflix/spinnaker/orca/clouddriver/t
asks/scalingpolicy/UpsertScalingPolicyTask.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.s
pringframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'katoOperationsRunner' defined in com.netflix.spinn
aker.orca.clouddriver.config.CloudDriverConfiguration: Unsatisfied dependency expressed through method 'katoOperationsRunner' parameter 0; nes
ted exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'katoService' defined in com.
netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration: Unsatisfied dependency expressed through method 'katoService' parameter 0;
 nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'katoDeployService' defined in com
.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration: Bean instantiation via factory method failed; nested exception is org.spr
ingframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.clouddriver.KatoRestService]: Factory method 
'katoDeployService' threw exception; nested exception is java.lang.NullPointerException
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:799)
at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory
.java:1361)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.
java:1208)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:5
56)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516
)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1525)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1489)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1378)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1265)
at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getIfAvailable(DefaultListableBeanFac
tory.java:1947)
at org.springframework.beans.factory.ObjectProvider.getIfAvailable(ObjectProvider.java:77)
at com.netflix.spinnaker.orca.TaskResolver.<init>(TaskResolver.java:54)
at com.netflix.spinnaker.orca.config.OrcaConfiguration.taskResolver(OrcaConfiguration.java:213)
at com.netflix.spinnaker.orca.config.OrcaConfiguration$$EnhancerBySpringCGLIB$$7e2b2fc3.CGLIB$taskResolver$8(<generated>)
at com.netflix.spinnaker.orca.config.OrcaConfiguration$$EnhancerBySpringCGLIB$$7e2b2fc3$$FastClassBySpringCGLIB$$d7be0d9.invoke(<gener
ated>)
at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:3
31)
at com.netflix.spinnaker.orca.config.OrcaConfiguration$$EnhancerBySpringCGLIB$$7e2b2fc3.taskResolver(<generated>)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
... 38 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'katoOperationsRunner' defined in c
om.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration: Unsatisfied dependency expressed through method 'katoOperationsRunner' 
parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'katoService'
 defined in com.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration: Unsatisfied dependency expressed through method 'katoServi
ce' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'katoDeployService
' defined in com.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration: Bean instantiation via factory method failed; nested exce
ption is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.clouddriver.KatoRestService]:
 Factory method 'katoDeployService' threw exception; nested exception is java.lang.NullPointerException
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:799)
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:540)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableB
eanFactory.java:1341)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.
java:1181)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:5
56)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516
)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886)
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790)
... 66 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'katoService' defined in com.netfli
x.spinnaker.orca.clouddriver.config.CloudDriverConfiguration: Unsatisfied dependency expressed through method 'katoService' parameter 0; neste
d exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'katoDeployService' defined in com.netfl
ix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration: Bean instantiation via factory method failed; nested exception is org.springfra
mework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.clouddriver.KatoRestService]: Factory method 'katoD
eployService' threw exception; nested exception is java.lang.NullPointerException
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:799)
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:540)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableB
eanFactory.java:1341)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.
java:1181)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:5
56)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516
)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886)
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790)
... 80 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'katoDeployService' defined in com.netflix.s
pinnaker.orca.clouddriver.config.CloudDriverConfiguration: Bean instantiation via factory method failed; nested exception is org.springframewo
rk.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.clouddriver.KatoRestService]: Factory method 'katoDeplo
yService' threw exception; nested exception is java.lang.NullPointerException
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657)
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:637)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableB
eanFactory.java:1341)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.
java:1181)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:5
56)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516
)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886)
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790)
... 94 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.orca.clouddriver.KatoRestService
]: Factory method 'katoDeployService' threw exception; nested exception is java.lang.NullPointerException
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652)
... 108 common frames omitted
Caused by: java.lang.NullPointerException: null
at java.base/java.util.Objects.requireNonNull(Objects.java:221)
at com.netflix.spinnaker.config.DefaultServiceEndpoint.<init>(DefaultServiceEndpoint.java:82)
at com.netflix.spinnaker.config.DefaultServiceEndpoint.<init>(DefaultServiceEndpoint.java:59)
at com.netflix.spinnaker.config.DefaultServiceEndpoint.<init>(DefaultServiceEndpoint.java:55)
at com.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration$ClouddriverRetrofitBuilder.buildService(CloudDriverConfigura
tion.java:110)
at com.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration$ClouddriverRetrofitBuilder.buildWriteableService(CloudDriver
Configuration.java:104)
at com.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration.katoDeployService(CloudDriverConfiguration.java:194)
at com.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration$$EnhancerBySpringCGLIB$$5064a91c.CGLIB$katoDeployService$4(<
generated>)
at com.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration$$EnhancerBySpringCGLIB$$5064a91c$$FastClassBySpringCGLIB$$cd
215e81.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:3
31)
at com.netflix.spinnaker.orca.clouddriver.config.CloudDriverConfiguration$$EnhancerBySpringCGLIB$$5064a91c.katoDeployService(<generate
d>)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
... 109 common frames omitted

> Task :orca-web:run FAILED
```

### Cloud Provider(s):
Azure

### Environment:
ubuntu 18.04

### Feature Area:
Orca

### Steps to Reproduce:
1. hal config version edit --version branch:upstream/master
2. hal deploy apply
3. It failed to start Orca

**Comment by mattgogerly** [comment]
What does your orca-local file look like?

**Comment by mattgogerly** [comment]
After deploying master I'm seeing a similar issue, but with FiatService, which wasn't touched by that PR. I'll need to dig more into what's going on.

I'd recommend using a stable release rather than master.

**Comment by neil-yechenwei** [comment]
adding @ajordens for awareness.

Thanks @mattgogerly for investigation, we have to ensure there is no breaking change or blocking issue on master branch otherwise it would bring the bug/issue into stable release. So once the issue is fixed, please let us know.

**Comment by mattgogerly** [comment]
I'm seeing other properties unrelated to the changes made in that PR also not being set properly. Reverting https://github.com/spinnaker/orca/pull/4269 doesn't resolve the issue.

Notably this fix no longer works either https://github.com/spinnaker/kork/pull/860, and I'm also seeing the Fiat URL causing a NPE.

**Comment by mattgogerly** [comment]
Identified that the issue with other properties was unrelated. PR opened to fix the reported issue. Not sure why exactly it doesn't work as is, but hey-ho.

Thanks for reporting this!
