### ISSUE TITLE
Unable to install spinnaker-rosco package on Ubuntu 20.04 or 22.04 LTS

### ISSUE THREAD

**Issue by ashleykleynhans** [spinnaker/spinnaker#6710]
### Issue Summary:

Unable to install spinnaker-rosco package on Ubuntu 20.04 or 22.04 LTS.

### Cloud Provider(s):

N/A

### Environment:

Ubuntu 20.04 LTS and Ubuntu 22.04 LTS VMs running in VirtualBox.
Halyard v1.48.0.

### Feature Area:

Rosco

### Description:

*Expected Behaviour:*
Installing the spinnaker-rosco package using apt should succeed without any errors.

*Actual Behaviour:*
The spinnaker-rosco post installation script fails when installing helm because /usr/local/bin is not in the PATH, thus causing the package installation to fail.

### Steps to Reproduce:

*Long method:*

1. Install a fresh Ubuntu 20.04 or Ubuntu 22.04 VM in VirtualBox.
2. Install Halyard from the spinnaker-community repo.
3. Configure Halyard with storage backend and Spinnaker version.
4. Apply deployment using Halyard.

*Short method:*
```
curl -fsSL https://us-apt.pkg.dev/doc/repo-signing-key.gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=all] https://us-apt.pkg.dev/projects/spinnaker-community apt main"
sudo apt update
sudo apt install spinnaker-rosco
```

### Additional Details:

Works by adding /usr/local/bin to $PATH.

**Comment by ashleykleynhans** [comment]
A new spinnaker-rosco package (1.8.2) was released with the fix in Spinnaker 1.28.0, but unfortunately the installation still fails:

```
Aug 23 06:08:58 spinnaker halyard[6703]: com.netflix.spinnaker.halyard.core.error.v1.HalException: Unable to retrieve profile "rosco.yml": 404 Not Found
Aug 23 06:08:58 spinnaker halyard[6703]: GET https://www.googleapis.com/storage/v1/b/halconfig/o/rosco%2F1.8.2%2Frosco.yml?alt=media
Aug 23 06:08:58 spinnaker halyard[6703]: No such object: halconfig/rosco/1.8.2/rosco.yml
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.profile.RegistryBackedProfileFactory.getBaseProfile(RegistryBackedProfileFactory.java:45) ~[halyard-deploy-1.48.0.jar:1>
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.profile.ProfileFactory.getProfile(ProfileFactory.java:87) ~[halyard-deploy-1.48.0.jar:1.48.0]
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.service.RoscoService.getProfiles(RoscoService.java:86) ~[halyard-deploy-1.48.0.jar:1.48.0]
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.netflix.spinnaker.halyard.deploy.services.v1.GenerateService.generateConfig(GenerateService.java:142) ~[halyard-deploy-1.48.0.jar:1.48.0]
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.netflix.spinnaker.halyard.deploy.services.v1.DeployService.deploy(DeployService.java:291) ~[halyard-deploy-1.48.0.jar:1.48.0]
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.netflix.spinnaker.halyard.controllers.v1.DeploymentController.lambda$deploy$14(DeploymentController.java:230) ~[halyard-web-1.48.0.jar:1.48.0]
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:123) ~[halyard-core-1.48.0.jar:1.48.0]
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core-1.48.0.jar:1.48.0]
Aug 23 06:08:58 spinnaker halyard[6703]:         at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Aug 23 06:08:58 spinnaker halyard[6703]: Caused by: com.google.api.client.http.HttpResponseException: 404 Not Found
Aug 23 06:08:58 spinnaker halyard[6703]: GET https://www.googleapis.com/storage/v1/b/halconfig/o/rosco%2F1.8.2%2Frosco.yml?alt=media
Aug 23 06:08:58 spinnaker halyard[6703]: No such object: halconfig/rosco/1.8.2/rosco.yml
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293) ~[google-http-client-1.41.7.jar:1.41.7]
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118) ~[google-http-client-1.41.7.jar:1.41.7]
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.google.api.client.googleapis.media.MediaHttpDownloader.executeCurrentRequest(MediaHttpDownloader.java:255) ~[google-api-client-1.30.10.jar:1.30.10]
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.google.api.client.googleapis.media.MediaHttpDownloader.download(MediaHttpDownloader.java:201) ~[google-api-client-1.30.10.jar:1.30.10]
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeMediaAndDownloadTo(AbstractGoogleClientRequest.java:684) ~[google-api-client-1.30.10.jar:1.3>
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.google.api.services.storage.Storage$Objects$Get.executeMediaAndDownloadTo(Storage.java:6275) ~[google-api-services-storage-v1-rev141-1.25.0.jar:na]
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.netflix.spinnaker.halyard.core.registry.v1.GoogleProfileReader.getContents(GoogleProfileReader.java:116) ~[halyard-core-1.48.0.jar:1.48.0]
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.netflix.spinnaker.halyard.core.registry.v1.GoogleProfileReader.readProfile(GoogleProfileReader.java:72) ~[halyard-core-1.48.0.jar:1.48.0]
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.netflix.spinnaker.halyard.core.registry.v1.ProfileRegistry.readProfile(ProfileRegistry.java:43) ~[halyard-core-1.48.0.jar:1.48.0]
Aug 23 06:08:58 spinnaker halyard[6703]:         at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.profile.RegistryBackedProfileFactory.getBaseProfile(RegistryBackedProfileFactory.java:40) ~[halyard-deploy-1.48.0.jar:1>
Aug 23 06:08:58 spinnaker halyard[6703]:         ... 8 common frames omitted
```
I see spinnaker-rosco 1.8.2 in the apt-repository at: https://console.cloud.google.com/artifacts/docker/spinnaker-community/us/apt/spinnaker-rosco/1.8.2

So something else must be creating the profile at:
https://www.googleapis.com/storage/v1/b/halconfig/o/rosco%2F1.8.2%2Frosco.yml?alt=media

Neither 1.8.1 nor 1.8.0 can be downloaded but 1.7.5 (Spinnaker 1.27.1) can:
https://www.googleapis.com/storage/v1/b/halconfig/o/rosco%2F1.7.5%2Frosco.yml?alt=media

**Comment by ashleykleynhans** [comment]
@kskewes-sf mentioned on Slack:

> Hmm. GHA does halconfig publish here https://github.com/spinnaker/rosco/blob/a088e784dcbfc6bd55b90b6b632c7f716d91be0f/.github/workflows/release.yml#L74
But looks like missed backport to release-1.28.x branch.
We need to do something like this tomorrow
https://github.com/spinnaker/rosco/pull/873

**Comment by sramek5** [comment]
Same here.

**Comment by dbyron-sf** [comment]
I published version 1.8.3 of rosco after merging https://github.com/spinnaker/rosco/pull/902 and there are [halconfigs in gcs](https://console.cloud.google.com/storage/browser/halconfig/rosco/1.8.3).

**Comment by ashleykleynhans** [comment]
@dbyron-sf Thanks!  How do we get Halyard to install 1.8.3 instead of 1.8.2?
I just tried a fresh install of Spinnaker 1.28.0 using Halyard 1.48.0 and its still trying to install rosco 1.8.2 instead of 1.8.3.

**Comment by dbyron-sf** [comment]
We need to release spinnaker 1.28.1 with rosco 1.8.3...

**Comment by kskewes-sf** [comment]
And 1.28.1 is live with Rosco 1.8.3 - https://spinnaker.io/changelogs/1.28.1-changelog/

**Comment by kskewes-sf** [comment]
Thanks for finding and reporting @ashleykleynhans :rocket:

**Comment by sramek5** [comment]
I can confirm it works! 

Thank you guys.

**Comment by ashleykleynhans** [comment]
I have also confirmed it works, many thanks @kskewes-sf and @dbyron-sf
