### ISSUE TITLE
Clusters tab unable to load after gce account removal 

### ISSUE THREAD

**Issue by SusmithaGundu** [spinnaker/spinnaker#6800]
Issue Summary:
When an account which previously had servergroups associated with is removed , on restarting spinnaker the clusters tab is unable to load. Ideally the clusters tab should display the server groups with the existing account.

Cloud Provider(s): GCE

 Environment: N/A

Feature Area: clouddriver

Description:
 When one of google accounts is removed after a server group is created and spinnaker is restarted, the clusters page shows this error. 
![image](https://user-images.githubusercontent.com/93190458/219678138-f00a0595-1630-4b1e-9e36-886d194aaaa9.png)

Steps to Reproduce:
1. Create server groups with two google accounts.
2. Remove one account and restart spinnaker 
3.  Check clusters tab in UI. The page shows 'error loading clusters'

Additional Details:
clouddriver logs throwing the exception when trying to fetch details of the removed account:
`2023-02-01 16:40:34.793 ERROR 409705 --- [0.1-7002-exec-5] c.n.s.c.c.SecurityGroupController        : Unable to list security groups

java.lang.IllegalArgumentException: Invalid credentials: gcs-src-acc-2
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor178.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80) ~[groovy-2.5.15.jar:2.5.15]
	`

**Comment by SusmithaGundu** [comment]
I have checked by clearing the cache.It does not go away.The data fetched for the account which is removed still exists in cache and when securityGroups are queried the exception is thrown.
Raising a fix PR for this.
