### ISSUE TITLE
Extra /'s in example curls

### ISSUE THREAD

**Issue by jhmartin** [spinnaker/spinnaker#6864]
### Issue Summary:

https://spinnaker.io/docs/reference/api/docs shows curl examples where there is a double-slash between the hostname and the path, which should actually be a single slash.

**Comment by pubudu91** [comment]
@mattgogerly I'd like to give this a try. I had a look around and guessing the API docs are getting generated by the build tool at https://github.com/spinnaker/buildtool right? I tried to locally generate the API docs by running the following commands within the buildtool repo:
```bash
$ ./dev/buildtool.sh build_bom --git_branch master --github_owner spinnaker
$ ./dev/buildtool.sh build_apidocs --bom_path output/build_bom/master-20231029022342.yml --swagger_codegen_cli_jar_path ~/Downloads/swagger-codegen-cli-2.2.3.jar --git_branch master --github_owner spinnaker
```

But running into the following error for the second command:
```
W 04:02:59.513 [MainThread.4156] Monitoring is disabled
I 04:02:59.518 [MainThread.4156] Confirming existing source_code/build_apidocs/spinnaker.io matches expectations
E 04:02:59.520 [MainThread.4156] "build_apidocs" caught exception
Traceback (most recent call last):
  File "/spinnaker/dev/buildtool/command.py", line 150, in __call__
    result = self.metrics.track_and_time_call(
  File "/spinnaker/dev/buildtool/base_metrics.py", line 402, in track_and_time_call
    return self.track_call(
  File "/spinnaker/dev/buildtool/base_metrics.py", line 337, in track_call
    return gauge.track(func, *pos_args, **kwargs)
  File "/spinnaker/dev/buildtool/base_metrics.py", line 97, in track
    return func(*pos_args, **kwargs)
  File "/spinnaker/dev/buildtool/base_metrics.py", line 349, in time_call
    result = time_func(*pos_args, **kwargs)
  File "/spinnaker/./dev/buildtool/apidocs_commands.py", line 105, in _do_command
    self._ensure_templates_directory()
  File "/spinnaker/./dev/buildtool/apidocs_commands.py", line 95, in _ensure_templates_directory
    repository = scm.make_repository_spec(SPINNAKER_IO_REPOSITORY_NAME)
  File "/spinnaker/dev/buildtool/scm.py", line 159, in make_repository_spec
    existing = self.__git.determine_git_repository_spec(git_dir)
  File "/spinnaker/dev/buildtool/git_support.py", line 1216, in determine_git_repository_spec
    git_text = self.check_run(git_dir, "remote -v")
  File "/spinnaker/dev/buildtool/git_support.py", line 826, in check_run
    return check_subprocess(
  File "/spinnaker/dev/buildtool/subprocess_support.py", line 158, in check_subprocess
    retcode, stdout = run_subprocess(cmd, stream=stream, **kwargs)
  File "/spinnaker/dev/buildtool/subprocess_support.py", line 148, in run_subprocess
    process = start_subprocess(cmd, stream=stream, echo=echo, **kwargs)
  File "/spinnaker/dev/buildtool/subprocess_support.py", line 63, in start_subprocess
    process = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'

E 04:02:59.520 [MainThread.4156] "build_apidocs" propagating exception
W 04:02:59.520 [MainThread.4156] Monitoring disabled -- dont push incremental metrics.
W 04:02:59.520 [MainThread.4156] Monitoring disabled -- dont push final metrics.
E 04:02:59.520 [MainThread.4156] "main()" Terminating
E 04:02:59.520 [MainThread.4156] FAILED
```

I'm guessing the issue here is that the Swagger file used for the API doc gen has a `host` field with a trailing `/`. Tried this out with a sample Swagger in the same codegen tool version used in Spinnaker and could reproduce. However, I couldn't figure out where this input Swagger file is coming from for the API doc gen command. I tried out the Swagger gen given at https://github.com/spinnaker/gate/blob/master/swagger/generate_swagger.sh, but couldn't generate the docs for this using the tool. So maybe this is not the one used for the doc gen?

**Comment by jasonmcintosh** [comment]
I've updated the spinnaker release process to publish the openapi specs for the various apis & release them as part of the release process.  This should keep the API docs updated and remove this as an issue.  Thanks and closing this issue now!
