### ISSUE TITLE
UpsertGoogleAutoscalingPolicyAtomicOperation missing Autowired for objectMapper and cacheView

### ISSUE THREAD

**Issue by shlomodaari** [spinnaker/spinnaker#6963]
Spinnaker version 1.34.2

In this [PR](https://github.com/spinnaker/clouddriver/pull/6057/files#diff-77886cd9f754611f6844f38a9d1eaa13a7306a5c311d58aa07fa7aff2ab1de88L67) the   @Autowired for objectMapper and cacheView was removed and wasn't introduce as part of the constructor which result in the following error:

The target release for this PR is 1.33.x

2024-06-20 18:58:43.565 ERROR 1 --- [tionProcessor-1] c.n.s.c.o.DefaultOrchestrationProcessor  : java.lang.NullPointerException: Cannot invoke method writeValueAsString() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at com.netflix.spinnaker.clouddriver.google.deploy.ops.UpsertGoogleAutoscalingPolicyAtomicOperation.updatePolicyMetadata(UpsertGoogleAutoscalingPolicyAtomicOperation.groovy:383)
	at com.netflix.spinnaker.clouddriver.google.deploy.ops.UpsertGoogleAutoscalingPolicyAtomicOperation$updatePolicyMetadata.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at com.netflix.spinnaker.clouddriver.google.deploy.ops.UpsertGoogleAutoscalingPolicyAtomicOperation.operate(UpsertGoogleAutoscalingPolicyAtomicOperation.groovy:201)
	at com.netflix.spinnaker.clouddriver.google.deploy.ops.UpsertGoogleAutoscalingPolicyAtomicOperation.operate(UpsertGoogleAutoscalingPolicyAtomicOperation.groovy)
	at com.netflix.spinnaker.clouddriver.orchestration.AtomicOperation$operate.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)

**Comment by ozkar99** [comment]
Hey folks, i saw the PR and tested them on the `v5.83.4` tag and theres a couple of places were the constructor is used but now its failing due to the additional arguments:

Heres a quick patch to fix that, for anyone also having the issue.

```

diff --git a/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/ResizeGoogleServerGroupAtomicOperationConverter.groovy b/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/ResizeGoogleServerGroupAtomicOperationConverter.groovy
--
index 6c56cf167..a7e1d8339 100644
--- a/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/ResizeGoogleServerGroupAtomicOperationConverter.groovy
+++ b/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/ResizeGoogleServerGroupAtomicOperationConverter.groovy
@@ -16,6 +16,8 @@
 
package com.netflix.spinnaker.clouddriver.google.deploy.converters
 
+import com.fasterxml.jackson.databind.ObjectMapper
+import com.netflix.spinnaker.cats.cache.Cache
import com.google.api.services.compute.model.AutoscalingPolicy
import com.netflix.spinnaker.clouddriver.google.GoogleOperation
import com.netflix.spinnaker.clouddriver.google.deploy.GCEUtil
@@ -53,6 +55,12 @@ class ResizeGoogleServerGroupAtomicOperationConverter extends AbstractAtomicOper
@Autowired
OrchestrationProcessor orchestrationProcessor
 
+  @Autowired
+  Cache cacheView
+
+  @Autowired
+  ObjectMapper objectMapper
+
@Override
AtomicOperation convertOperation(Map input) {
// If the target server group has an Autoscaler configured we need to modify that policy as opposed to the
@@ -61,7 +69,7 @@ class ResizeGoogleServerGroupAtomicOperationConverter extends AbstractAtomicOper
def convertedDescription = convertDescription(input, autoscalingPolicy)
 
if (autoscalingPolicy) {
-      new UpsertGoogleAutoscalingPolicyAtomicOperation(convertedDescription, googleClusterProvider, googleOperationPoller, atomicOperationsRegistry, orchestrationProcessor)
+      new UpsertGoogleAutoscalingPolicyAtomicOperation(convertedDescription, googleClusterProvider, googleOperationPoller, atomicOperationsRegistry, orchestrationProcessor, cacheView, objectMapper)
} else {
new ResizeGoogleServerGroupAtomicOperation(convertedDescription)
}
diff --git a/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/UpsertGoogleAutoscalingPolicyAtomicOperationConverter.groovy b/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/UpsertGoogleAutoscalingPolicyAtomicOperationConverter.groovy
index ba03ddd64..18fecc2c8 100644
--- a/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/UpsertGoogleAutoscalingPolicyAtomicOperationConverter.groovy
+++ b/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/deploy/converters/UpsertGoogleAutoscalingPolicyAtomicOperationConverter.groovy
@@ -16,6 +16,8 @@
 
package com.netflix.spinnaker.clouddriver.google.deploy.converters
 
+import com.fasterxml.jackson.databind.ObjectMapper
+import com.netflix.spinnaker.cats.cache.Cache
import com.netflix.spinnaker.clouddriver.google.GoogleOperation
import com.netflix.spinnaker.clouddriver.google.deploy.GoogleOperationPoller
import com.netflix.spinnaker.clouddriver.google.deploy.description.UpsertGoogleAutoscalingPolicyDescription
@@ -46,9 +48,15 @@ class UpsertGoogleAutoscalingPolicyAtomicOperationConverter extends AbstractAtom
@Autowired
OrchestrationProcessor orchestrationProcessor
 
+  @Autowired
+  Cache cacheView
+
+  @Autowired
+  ObjectMapper objectMapper
+
@Override
AtomicOperation convertOperation(Map input) {
-    new UpsertGoogleAutoscalingPolicyAtomicOperation(convertDescription(input), googleClusterProvider, googleOperationPoller, atomicOperationsRegistry, orchestrationProcessor)
+    new UpsertGoogleAutoscalingPolicyAtomicOperation(convertDescription(input), googleClusterProvider, googleOperationPoller, atomicOperationsRegistry, orchestrationProcessor, cacheView, objectMapper)
}
 
@Override

```

**Comment by shlomodaari** [comment]
@ozkar99 I just created a pr to fix the issue.

**Comment by ozkar99** [comment]
Awesome thanks!

**Comment by kirangodishala** [comment]
@shlomodaari - can you confirm if the issue is fixed?

**Comment by shlomodaari** [comment]
it is fixed, but I will close it whenever it is released.
