### ISSUE TITLE
404 on GET pipeline request for new pipeline.

### ISSUE THREAD

**Issue by himanhsugusain** [spinnaker/spinnaker#6990]
### Issue Summary:
Creating a new pipeline with `mercari/terraform-provider-spinnaker` fails since it reads the created pipeline config just after creating it to verify success of the operation.

### Cloud Provider(s):
Google Cloud

### Environment:
Spinnaker setup from Google marketplace

### Feature Area:
pipeline 

### Description:
Cluster Logs
```
INFO 2024-10-24T08:24:03.767479484Z [resource.labels.containerName: gate] 2024-10-24 08:24:03.767 INFO 1 --- [0-8084-exec-838] c.n.spinnaker.gate.services.TaskService : Creating and waiting for completion: {description=Save pipeline pipeline-x, application=deploy, job=[{type=savePipeline, pipeline=eyJhcHBDb25maWciOnt9
INFO 2024-10-24T08:24:03.820468300Z [resource.labels.containerName: orca] 2024-10-24 08:24:03.820 INFO 1 --- [.0-8083-exec-59] c.n.s.o.c.OperationsController : [xxxx] started execution 01JAYT0AZ4ECX0F2H8FV7TJWYW from requested task: (length: 5590) {"application":"deploy","name":"Save pipeline 'pipeline-x","stages":[{"type":"savePipeline","pipeline":"eyJhcHBDb25maWciOnt9LCJhcHBsaWNhdGlvbiI6ImRlcGxveSIsImRpc2FibGVkIjpmYWxzZSwiZXhwZWN0ZWRBcnRpZmFjdHMiOltdLCJrZWVwV2FpdGluZ1BpcGVsaW5lcyI6ZmFsc2UsImxhc3RNb2RpZmllZEJ5Ijoic3Bpbm5ha2VyLXByaS1hY2MtMTY0ODE1MDQxMkBzY2lvLWVuZ2luZWVyaW5nLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwibGltaXRDb25jdXJyZW50IjpmYWxzZSwibmFtZSI6ImZlLWRlcGxveV9yZWxlYXNlLTIwMjQtMTAtMjQiLCJub3RpZmljYXRpb25zIjpbeyJhZGRyZXNzIjoiZmUtb25jYWxsLXNwYW0iLCJsZXZlbCI6InBpcGVsaW5lIiwibWVzc2FnZSI6eyJwaXBlbGluZS5jb21wbGV0ZSI6eyJ0ZXh0IjoiQlJBTkNIOiAqJHsgcGFyYW1ldGVyc1snYnJhbmNoJ10gfSpcbk9QRVJBVElPTjogKiR7IHBhcmFtZXRlcnNbJ29wZXJhdGlvbiddIH0qIn0sInBpcGVsaW5lLmZhaWxlZCI6eyJ0ZXh0IjoiQlJBTkNIOiAqJHsgcGFyYW1ldGVyc1snYnJhbmNoJ10gfSpcbk9QRVJBVElPTjogKiR7IHBhcmFtZXRlcnNbJ29wZXJhdGlvbiddIH0qIn19LCJ0eXBlIjoic2xhY2siLCJ3aGVuIjpbInBpcGVsaW5lLmZhaWxlZCIsInBpcGVsaW5lLmNvbXBsZXRlIl19LHsiYWRkcmVzcyI6ImZlLW9uY2FsbCIsImxldmVsIjoicGlwZWxpbmUiLCJtZXNzYWdlIjp7InBpcGVsaW5lLmZhaWxlZCI6eyJ0ZXh0IjoiQlJBTkNIOiAqJHsgcGFyYW1ldGVyc1snYnJhbmNoJ10gfSpcbk9QRVJBVElPTjogKiR7IHBhcmFtZXRlcnNbJ29wZXJhdGlvbiddIH0qIn19LCJ0eXBlIjoic2xhY2siLCJ3aGVuIjpbInBpcGVsaW5lLmZhaWxlZCJdfV0sInBhcmFtZXRlckNvbmZpZyI6W3siZGVmYXVsdCI6InJlbGVhc2UtMjAyNC0xMC0yNCIsImRlc2NyaXB0aW9uIjoiYnJhbmNoIHRvIHVzZSB3aGVuIGJ1aWxkaW5nIGFydGlmYWN0cyBmb3IgZGVwbG95bWVudCIsImhhc09wdGlvbnMiOmZhbHNlLCJsYWJlbCI6IiIsIm5hbWUiOiJicmFuY2giLCJwaW5uZWQiOnRydWUsInJlcXVpcmVkIjp0cnVlfSx7ImRlZmF1bHQiOiJXRUJfQ0FOQVJZIiwiZGVzY3JpcHRpb24iOiJXaGljaCBvcGVyYXRpb24gdG8gcGVyZm9ybSwgdXN1YWxseSBmaWxsZWQgYnkgcHVic3ViLCBvbmx5IGZpbGwgbWFudWFsbHkgd2hlbiBwcm9tb3RlIiwiaGFzT3B0aW9ucyI6dHJ1ZSwibGFiZWwiOiIiLCJuYW1lIjoib3BlcmF0aW9uIiwib3B0aW9ucyI6W3sidmFsdWUiOiJXRUJfQ0FOQVJZIn0seyJ2YWx1ZSI6IldFQl9BUFAifV0sInBpbm5lZCI6dHJ1ZSwicmVxdWlyZWQiOnRydWV9XSwic3RhZ2VzIjpbeyJhY2NvdW50IjoiZ2NiLWFjY291bnQiLCJhcHBsaWNhdGlvbiI6ImRlcGxveSIsImJ1aWxkRGVmaW5pdGlvbiI6eyJpbWFnZXMiOltdLCJsb2dzQnVja2V0IjoiZ3M6Ly9zY2lvLWJ1aWxkcy1sb2dzIiwib3B0aW9ucyI6eyJsb2dTdHJlYW1pbmdPcHRpb24iOiJTVFJFQU1fT04iLCJtYWNoaW5lVHlwZSI6IkUyX0hJR0hDUFVfMzIifSwic2VydmljZUFjY291bnQiOiJwcm9qZWN0cy9zY2lvLWVuZ2luZWVyaW5nL3NlcnZpY2VBY2NvdW50cy9zcGlubmFrZXItMS1nY2JAc2Npby1lbmdpbmVlcmluZy5pYW0uZ3NlcnZpY2VhY2NvdW50LmN…
INFO 2024-10-24T08:24:03.854061235Z [resource.labels.containerName: echo] Event details: Event(details=Metadata(source=orca, type=orca:orchestration:starting, created=1729758243841, organization=null, project=null, application=deploy, _content_id=null, attributes=null, requestHeaders={}), content={execution={type=ORCHESTRATION, id=01JAYT0AZ4ECX0F2H8FV7TJWYW, application=deploy, name=null, buildTime=1729758243812, canceled=false, canceledBy=null, cancellationReason=null, limitConcurrent=false, keepWaitingPipelines=false, stages=[{id=01JAYT0AZ44G20XQE7CT68WGNS, refId=0, type=savePipeline, name=savePipeline, startTime=null, endTime=null, startTimeExpiry=null, status=NOT_STARTED, context={pipeline=eyJhcHBDb25maWciOnt9
INFO 2024-10-24T08:24:03.904640098Z [resource.labels.containerName: echo] Event details: Event(details=Metadata(source=orca, type=orca:stage:starting, created=1729758243893, organization=null, project=null, application=deploy, _content_id=null, attributes=null, requestHeaders={}), content={standalone=true, canceled=false, context={pipeline=eyJhcHBDb25maWciOnt9
INFO 2024-10-24T08:24:03.963096564Z [resource.labels.containerName: echo] Event details: Event(details=Metadata(source=orca, type=orca:task:starting, created=1729758243950, organization=null, project=null, application=deploy, _content_id=null, attributes=null, requestHeaders={}), content={standalone=true, canceled=false, context={pipeline=eyJhcHBDb25maWciOnt9
INFO 2024-10-24T08:24:04.159433984Z [resource.labels.containerName: echo] Event details: Event(details=Metadata(source=orca, type=orca:task:complete, created=1729758244139, organization=null, project=null, application=deploy, _content_id=null, attributes=null, requestHeaders={}), content={standalone=true, canceled=false, context={pipeline=eyJhcHBDb25maWciOnt9
INFO 2024-10-24T08:24:04.252900799Z [resource.labels.containerName: echo] Event details: Event(details=Metadata(source=orca, type=orca:task:starting, created=1729758244221, organization=null, project=null, application=deploy, _content_id=null, attributes=null, requestHeaders={}), content={standalone=true, canceled=false, context={pipeline=eyJhcHBDb25maWciOnt9
INFO 2024-10-24T08:24:04.271563225Z [resource.labels.containerName: echo] Event details: Event(details=Metadata(source=orca, type=orca:task:complete, created=1729758244248, organization=null, project=null, application=deploy, _content_id=null, attributes=null, requestHeaders={}), content={standalone=true, canceled=false, context={pipeline=eyJhcHBDb25maWciOnt9
INFO 2024-10-24T08:24:04.316044365Z [resource.labels.containerName: echo] Event details: Event(details=Metadata(source=orca, type=orca:stage:complete, created=1729758244295, organization=null, project=null, application=deploy, _content_id=null, attributes=null, requestHeaders={}), content={standalone=true, canceled=false, context={pipeline=eyJhcHBDb25
INFO 2024-10-24T08:24:04.335025858Z [resource.labels.containerName: echo] Event details: Event(details=Metadata(source=orca, type=orca:orchestration:complete, created=1729758244303, organization=null, project=null, application=deploy, _content_id=null, attributes=null, requestHeaders={}), content={execution={type=ORCHESTRATION, id=01JAYT0AZ4ECX0F2H8FV7TJWYW, application=deploy, name=null, buildTime=1729758243812, canceled=false, canceledBy=null, cancellationReason=null, limitConcurrent=false, keepWaitingPipelines=false, stages=[{id=01JAYT0AZ44G20XQE7CT68WGNS, refId=0, type=savePipeline, name=savePipeline, startTime=1729758243881, endTime=1729758244289, startTimeExpiry=null, status=SUCCEEDED, context={pipeline=eyJhcHBDb25maWciOnt9
INFO 2024-10-24T08:24:04.972562532Z [resource.labels.containerName: gate] 2024-10-24 08:24:04.972 WARN 1 --- [0-8084-exec-855] c.n.s.g.c.ApplicationController : Pipeline config pipeline-x not found for application deploy
INFO 2024-10-24T08:24:04.975953094Z [resource.labels.containerName: gate] com.netflix.spinnaker.kork.web.exceptions.NotFoundException: Pipeline config (id: pipeline-x) not found for Application (id: deploy) at jdk.internal.reflect.GeneratedConstructorAccessor132.newInstance(Unknown Source) ~[na:na] at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na] at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na] at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80) ~[groovy-2.5.11.jar:2.5.11] at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74) ~[groovy-2.5.11.jar:2.5.11] at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84) ~[groovy-2.5.11.jar:2.5.11] at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249) ~[groovy-2.5.11.jar:2.5.11] at com.netflix.spinnaker.gate.controllers.ApplicationController.getPipelineConfig(ApplicationController.groovy:153) ~[gate-web.jar:1.0.0] at com.netflix.spinnaker.gate.controllers.ApplicationController$$FastClassBySpringCGLIB$$dfb3c866.invoke(<generated>) ~[gate-web.jar:1.0.0] at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.5.RELEASE.jar:5.2.5.RELEASE] at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE] at com.netflix.spinnaker.gate.controllers.ApplicationController$$EnhancerBySpringCGLIB$$312489f6.getPipelineConfig(<generated>) ~[gate-web.jar:1.0.0] at jdk.internal.reflect.GeneratedMethodAccessor201.invoke(Unknown Source) ~[na:na] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na] at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na] at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE] at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE] at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.5.RELEASE.jar:5.2.5.RELEASE] at org.springfra…
INFO 2024-10-24T08:24:04.981267476Z [resource.labels.containerName: deck] 35.191.11.232 - - [24/Oct/2024:08:24:04 +0000] "GET /gate/applications/deploy/pipelineConfigs/pipeline-x HTTP/1.1" 404 160
```

### Steps to Reproduce:
Create a new pipeline from terraform-provider.
Intermittent Issue.

### Additional Details:

Gateway
```
INFO 2024-10-24T08:24:04.975953094Z [resource.labels.containerName: gate] com.netflix.spinnaker.kork.web.exceptions.NotFoundException: Pipeline config (id: pipeline-x) not found for Application (id: deploy)
 at jdk.internal.reflect.GeneratedConstructorAccessor132.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80) ~[groovy-2.5.11.jar:2.5.11]
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74) ~[groovy-2.5.11.jar:2.5.11]
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84) ~[groovy-2.5.11.jar:2.5.11]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249) ~[groovy-2.5.11.jar:2.5.11]
	at com.netflix.spinnaker.gate.controllers.ApplicationController.getPipelineConfig(ApplicationController.groovy:153) ~[gate-web.jar:1.0.0]
	at com.netflix.spinnaker.gate.controllers.ApplicationController$$FastClassBySpringCGLIB$$dfb3c866.invoke(<generated>) ~[gate-web.jar:1.0.0]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at com.netflix.spinnaker.gate.controllers.ApplicationController$$EnhancerBySpringCGLIB$$312489f6.getPipelineConfig(<generated>) ~[gate-web.jar:1.0.0]
	at jdk.internal.reflect.GeneratedMethodAccessor201.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springfra… [message truncated due to size]
```

**Comment by jasonmcintosh** [comment]
Sadly this is a problem with the TF provider and not something spinnaker related.  The spinnaker project would be unable to help much.  This looks like (per slack) it's tied to the provider not polling for the save task execution status (which CAN return 404 on a cached result depending on backend & other stuff).  NOT sure if the OLD armory TF provider would be any better (https://github.com/armory-io/terraform-provider-spinnaker )

**Comment by himanhsugusain** [comment]
Fixed this in the provider implementation
https://github.com/gusain-himanshu/terraform-provider-spinnaker/issues/1
