### ISSUE TITLE
can jenkins monitor be configured to wait more time for response from jenkins?

### ISSUE THREAD

**Issue by unicman** [spinnaker/spinnaker#719]
Hi,

I am trying to configure our jenkins server in spinnaker.

After booting up spinnaker containers, first couple of calls bring build definitions. But after that all calls to jenkins start failing with socket timeout.

Is there any way I can configure this timeout to a bigger value?

```
[33;1migor        | [0m2016-02-03 08:17:14.636 ERROR 1 --- [readScheduler-1] c.n.spinnaker.igor.jenkins.BuildMonitor  : failed to update master MyJenkins
[33;1migor        | [0m
[33;1migor        | [0mcom.netflix.hystrix.exception.HystrixRuntimeException: jenkins-MyJenkins
-getProjects failed and no fallback available.
[33;1migor        | [0m	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:801)
[33;1migor        | [0m	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:785)
[33;1migor        | [0m	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:99)
[33;1migor        | [0m	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
[33;1migor        | [0m	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
[33;1migor        | [0m	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
[33;1migor        | [0m	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1514)
[33;1migor        | [0m	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1404)
[33;1migor        | [0m	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:314)
[33;1migor        | [0m	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:306)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:162)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:154)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:162)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:154)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:162)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:154)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:162)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:154)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:162)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:154)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:162)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:154)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:162)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:154)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:162)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:154)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:162)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:154)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:162)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:154)
[33;1migor        | [0m	at rx.Observable.unsafeSubscribe(Observable.java:7710)
[33;1migor        | [0m	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:100)
[33;1migor        | [0m	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
[33;1migor        | [0m	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
[33;1migor        | [0m	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:1005)
[33;1migor        | [0m	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
[33;1migor        | [0m	at rx.internal.operators.OperatorSubscribeOn$1$1$1.onError(OperatorSubscribeOn.java:71)
[33;1migor        | [0m	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
[33;1migor        | [0m	at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onError(AbstractCommand.java:1473)
[33;1migor        | [0m	at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onError(AbstractCommand.java:1369)
[33;1migor        | [0m	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:297)
[33;1migor        | [0m	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:162)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:154)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:162)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:154)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:162)
[33;1migor        | [0m	at rx.Observable$2.call(Observable.java:154)
[33;1migor        | [0m	at rx.Observable.unsafeSubscribe(Observable.java:7710)
[33;1migor        | [0m	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:517)
[33;1migor        | [0m	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:495)
[33;1migor        | [0m	at rx.Observable.unsafeSubscribe(Observable.java:7710)
[33;1migor        | [0m	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
[33;1migor        | [0m	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
[33;1migor        | [0m	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
[33;1migor        | [0m	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
[33;1migor        | [0m	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
[33;1migor        | [0m	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[33;1migor        | [0m	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[33;1migor        | [0m	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[33;1migor        | [0m	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[33;1migor        | [0m	at java.lang.Thread.run(Thread.java:745)
[33;1migor        | [0mCaused by: retrofit.RetrofitError: timeout
[33;1migor        | [0m	at retrofit.RetrofitError.networkError(RetrofitError.java:27)
[33;1migor        | [0m	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
[33;1migor        | [0m	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
[33;1migor        | [0m	at com.sun.proxy.$Proxy66.getProjects(Unknown Source)
[33;1migor        | [0m	at com.netflix.spinnaker.igor.jenkins.client.JenkinsClient$getProjects.call(Unknown Source)
[33;1migor        | [0m	at com.netflix.spinnaker.igor.jenkins.service.JenkinsService$_getProjects_closure1.doCall(JenkinsService.groovy:65)
[33;1migor        | [0m	at com.netflix.spinnaker.igor.jenkins.service.JenkinsService$_getProjects_closure1.doCall(JenkinsService.groovy)
[33;1migor        | [0m	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[33;1migor        | [0m	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[33;1migor        | [0m	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[33;1migor        | [0m	at java.lang.reflect.Method.invoke(Method.java:497)
[33;1migor        | [0m	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[33;1migor        | [0m	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
[33;1migor        | [0m	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
[33;1migor        | [0m	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[33;1migor        | [0m	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:901)
[33;1migor        | [0m	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:884)
[33;1migor        | [0m	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:166)
[33;1migor        | [0m	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeClosure(ScriptBytecodeAdapter.java:572)
[33;1migor        | [0m	at com.netflix.spinnaker.hystrix.SimpleHystrixCommand.run(SimpleHystrixCommand.groovy:53)
[33;1migor        | [0m	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
[33;1migor        | [0m	... 21 common frames omitted
[33;1migor        | [0mCaused by: java.io.InterruptedIOException: timeout
[33;1migor        | [0m	at okio.AsyncTimeout.exit(AsyncTimeout.java:258)
[33;1migor        | [0m	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
[33;1migor        | [0m	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:255)
[33;1migor        | [0m	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:249)
[33;1migor        | [0m	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
[33;1migor        | [0m	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:187)
[33;1migor        | [0m	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
[33;1migor        | [0m	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:791)
[33;1migor        | [0m	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:90)
[33;1migor        | [0m	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:784)
[33;1migor        | [0m	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:645)
[33;1migor        | [0m	at com.squareup.okhttp.Call.getResponse(Call.java:263)
[33;1migor        | [0m	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
[33;1migor        | [0m	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
[33;1migor        | [0m	at com.squareup.okhttp.Call.execute(Call.java:79)
[33;1migor        | [0m	at retrofit.client.OkClient.execute(OkClient.java:53)
[33;1migor        | [0m	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
[33;1migor        | [0m	... 40 common frames omitted
[33;1migor        | [0mCaused by: java.net.SocketException: Socket closed
[33;1migor        | [0m	at java.net.SocketInputStream.read(SocketInputStream.java:203)
[33;1migor        | [0m	at java.net.SocketInputStream.read(SocketInputStream.java:141)
[33;1migor        | [0m	at okio.Okio$2.read(Okio.java:136)
[33;1migor        | [0m	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
[33;1migor        | [0m	... 55 common frames omitted
[33;1migor        | [0m
```

**Comment by cfieber** [comment]
we don't have connectTimeout or readTimeout exposed as configuration options for those currently but it would make sense to add them

**Comment by cfieber** [comment]
would need to configure the OkClient here: https://github.com/spinnaker/igor/blob/master/igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy#L59

**Comment by unicman** [comment]
ok thanks.

I don't have a code checkout of spinnaker right now and haven't worked on groovy too otherwise I would given it a shot.

By any chance, is there any way I can get the timeout related support soon?

**Comment by tomaslin** [comment]
This is fixed in https://github.com/spinnaker/igor/pull/63

**Comment by unicman** [comment]
Wow! That was fast thanks a lot!

Will this reach igor docker image :latest? I can pull it as soon as it has this fix.

**Comment by tomaslin** [comment]
yes, once tag v1.18 is built it will be the image. should be able to have the changes. Note timeout time is in milliseconds.

**Comment by unicman** [comment]
Thanks! I see tag v1.18.0 to spinnaker/igor docker image!
So let me go ahead and give it a try...

BTW I hope the timeout has to be configured in igor-local.yml like,

```
jenkins:
  masters:
    - name:
      ...
      timeout: 30000
```

Or should it be in spinnaker-local.yml?

**Comment by tomaslin** [comment]
it should be 

client:
    timeout: 60000

**Comment by unicman** [comment]
Ok. I hope it should be in igor.yml and not in spinnaker-local.yml.

Thanks!

Regards.

PS:Sent from my mobile.
