### ISSUE TITLE
Unable to start spinnaker services for Development due to Thrift exceptions

### ISSUE THREAD

**Issue by hiradha** [spinnaker/spinnaker#771]
Hi all,
     I am unable to start spinnaker services -  rush and may be others on my Mac OS X using the provided script start_dev.sh
It seems this is due to a cassandra thrift  error in astyanax .
curl localhost:9160 seems to return an empty reply and I enabled thrift via nodetool.
Why is the TTransport class missing from the runtime  classpath?
Is there something else I should add during launch?

Caused by: com.netflix.astyanax.connectionpool.exceptions.TransportException: TransportException: [host=127.0.0.1(127.0.0.1):9160, latency=8(8), attempts=1]org.apache.thrift.transport.TTransportException
	at com.netflix.astyanax.thrift.ThriftConverter.ToConnectionPoolException(ThriftConverter.java:197)
	at com.netflix.astyanax.thrift.AbstractOperationImpl.execute(AbstractOperationImpl.java:65)
	at com.netflix.astyanax.thrift.AbstractOperationImpl.execute(AbstractOperationImpl.java:28)
	at com.netflix.astyanax.thrift.ThriftSyncConnectionFactoryImpl$ThriftConnection.execute(ThriftSyncConnectionFactoryImpl.java:153)
	at com.netflix.astyanax.connectionpool.impl.AbstractExecuteWithFailoverImpl.tryOperation(AbstractExecuteWithFailoverImpl.java:119)
	at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:352)
	at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4.execute(ThriftColumnFamilyQueryImpl.java:538)
	at com.netflix.scheduledactions.persistence.cassandra.ThriftCassandraDao.getGroup(ThriftCassandraDao.java:177)
	... 59 more
Caused by: org.apache.thrift.transport.TTransportException
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
	at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129)
	at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:362)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:284)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:191)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_multiget_slice(Cassandra.java:732)
	at org.apache.cassandra.thrift.Cassandra$Client.multiget_slice(Cassandra.java:716)
	at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4$1.internalExecute(ThriftColumnFamilyQueryImpl.java:544)
	at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4$1.internalExecute(ThriftColumnFamilyQueryImpl.java:541)
	at com.netflix.astyanax.thrift.AbstractOperationImpl.execute(AbstractOperationImpl.java:60)
	... 65 more

==========================

Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.netflix.spinnaker.rush.scripts.ScriptExecutor com.netflix.spinnaker.rush.scripts.ScriptController.executor; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scriptExecutorLocal': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.netflix.spinnaker.rush.scripts.ScriptExecutionRepo com.netflix.spinnaker.rush.local.scripts.ScriptExecutorLocal.executionRepo; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scriptExecutionRepo': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.netflix.astyanax.Keyspace com.netflix.spinnaker.rush.scripts.ScriptExecutionRepo.keyspace; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'keySpace' defined in class path resource [com/netflix/spinnaker/rush/config/CassandraConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.astyanax.Keyspace]: Factory method 'keySpace' threw exception; nested exception is com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/apache/thrift/transport/TTransport
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 19 more

===============================

Caused by: java.lang.NoClassDefFoundError: org/apache/thrift/transport/TTransport
	at com.netflix.astyanax.thrift.ThriftSyncConnectionFactoryImpl.createConnection(ThriftSyncConnectionFactoryImpl.java:89)
	at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.tryOpenAsync(SimpleHostConnectionPool.java:429)
	at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.borrowConnection(SimpleHostConnectionPool.java:194)
	at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.borrowConnection(RoundRobinExecuteWithFailover.java:84)
	at com.netflix.astyanax.connectionpool.impl.AbstractExecuteWithFailoverImpl.tryOperation(AbstractExecuteWithFailoverImpl.java:117)
	at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:338)
	at com.netflix.astyanax.thrift.ThriftKeyspaceImpl.executeOperation(ThriftKeyspaceImpl.java:517)
	at com.netflix.astyanax.thrift.ThriftKeyspaceImpl.describeRing(ThriftKeyspaceImpl.java:209)
	at com.netflix.astyanax.impl.RingDescribeHostSupplier.get(RingDescribeHostSupplier.java:68)
	at com.netflix.astyanax.impl.RingDescribeHostSupplier.get(RingDescribeHostSupplier.java:39)
	at com.netflix.astyanax.connectionpool.impl.NodeDiscoveryImpl.update(NodeDiscoveryImpl.java:107)
	at com.netflix.astyanax.connectionpool.impl.NodeDiscoveryImpl.start(NodeDiscoveryImpl.java:85)
	at com.netflix.astyanax.AstyanaxContext.start(AstyanaxContext.java:244)
	at com.netflix.spinnaker.kork.astyanax.DefaultAstyanaxKeyspaceFactory$2.load(DefaultAstyanaxKeyspaceFactory.java:128)
	at com.netflix.spinnaker.kork.astyanax.DefaultAstyanaxKeyspaceFactory$2.load(DefaultAstyanaxKeyspaceFactory.java:118)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 79 more
Caused by: java.lang.ClassNotFoundException: org.apache.thrift.transport.TTransport
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 98 more

**Comment by tomaslin** [comment]
Did you install cassandra and is it running?

**Comment by hiradha** [comment]
Yes. Cassandra is running. 
The curl reply in the issue indicates that.

**Comment by tomaslin** [comment]
I remember that we bind to cassandra 2.1.11 for some thrift dependencies, are you running 3?

**Comment by hiradha** [comment]
Yes. I am running 3.0.3

**Comment by duftler** [comment]
We require 2.1.11. Our installation scripts pin the cassandra version since the later version of cassandra does not enable thrift by default. You can also explicitly enable thrift and it should work fine.
https://github.com/spinnaker/spinnaker/blob/master/InstallSpinnaker.sh#L390-L391

**Comment by bfarrell** [comment]
This burnt me in the beginning too.  Quick doc update for Mac to save others the pain.

**Comment by hiradha** [comment]
I will try 2.1.11
However doesn't the curl localhost:9160 success already indicate that
thrift is enabled?
Even after I did that on my mac, it doesn't  work with 3.0.3

The ClassNotFoundException probably indicates that rush build is pulling in
some version of Thrift that does not contain the
org/apache/thrift/transport/TTransport
that Astyanax is expecting to be there at runtime  when connecting to 3.0.3.

**Comment by hiradha** [comment]
I believe this is happening because rush seems to be pulling in some old version 0.7.0 of thrift via kork-cassandra-  ; All others ( cloudDriver, front50 etc seems to be using libThrift 0.9.1 or 0.9.2 - however rush seems to be pulling in this because of direct dependency on kork-cassandra.

And Astyanax-thrift seems to expect something newer than 0.7.0 and hence it seems to be failing.

Please look into cleaning up this graph or should I force the resolutionStrategy to use 0.9.1 ?

**Comment by tomaslin** [comment]
you can also submit a PR if you have identified the issue
