### ISSUE TITLE
When I install spinnaker from scratch i cannot create an application

### ISSUE THREAD

**Issue by khebbie** [spinnaker/spinnaker#808]
Hi

I have been looking at spinnaker and it looks good from the docs and the presentations.
However when I install it I get a problem:
I first tried installing it via docker. And when I tried to create an application all I got was a spinner in the web ui.
Then i thought it might be a problem with the docker setup since it is an experimental thing.
So installed it on my dev machine (which i dont really like, since it is now polluted).
I had to change the install script since I am running on linux mint 17.3 which is basically an ubuntu.
The install went smooth but then i had the excact same problem as on the docker setup.

What am i doing wrong?

**Comment by khebbie** [comment]
One more hint in the "infrastructure" tab when I click "refresh cache" it never stops - the spinner just keeps spinning...

**Comment by duftler** [comment]
Can you please `curl localhost:7002/credentials` so we can get a look at what accounts are configured?

**Comment by khebbie** [comment]
curl: (7) Failed to connect to localhost port 7002: Connection refused

**Comment by duftler** [comment]
Ok, so if the backend services aren't up and running, the ui will not be able to do anything productive.

Next step is to find the clouddriver logs.

How exactly did you start up the various services? This will help in figuring out where the logs live.

**Comment by khebbie** [comment]
I ran the following command to install spinnake `./InstallSpinnaker.sh ` as I mentioned before I removed the part that checks for ubuntu .
Everything went on without errors

**Comment by khebbie** [comment]
I got the script from here https://spinnaker.bintray.com/scripts/InstallSpinnaker.sh

**Comment by duftler** [comment]
You mentioned that there were no logs in /var/log/spinnaker, can you please
check in /var/log/upstart?

You will hopefully see clouddriver logs there and maybe an indication of
why clouddriver wouldn't start.

Possible reasons are missing credentials (if managing aws resources), are
malformed yaml in your config files.

**Comment by khebbie** [comment]
from /var/log/upstart/spinnaker
front50 start/running, process 17234
clouddriver start/running, process 17243
echo start/running, process 17256
gate start/running, process 17283
igor start/running, process 17295
orca start/running, process 17319
rosco start/running, process 17352
rush start/running, process 17362

**Comment by duftler** [comment]
Is there a /var/log/upstart/clouddriver.log file?

**Comment by khebbie** [comment]
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/netflix/spinnaker/clouddriver/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/netflix/spinnaker/clouddriver/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by khebbie** [comment]
Sorry I hit "close and comment by mistake"

**Comment by duftler** [comment]
(Sorry, responding from my phone...)

Looks like java version mismatch. Please run Java 8.
On Mar 17, 2016 3:29 PM, "Klaus Hebsgaard" <notifications@github.com> wrote:

Sorry I hit "close and comment by mistake"

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/spinnaker/spinnaker/issues/808#issuecomment-198046836>

**Comment by khebbie** [comment]
Ok, so I removed openjdk 7 from the machine and everything worked.
Maybe this bug should feed a change request for the installer to check for the installed java version.
BTW I now have the same behavior and the log emitted says that I do not have aws credentials setup.
It would be great if the web app emitted this error message.

Thank you for your help!

**Comment by khebbie** [comment]
Ok so I moved further along now.
It seems that the install script creates a spinnaker user.
In this users home directory I had to create a .aws folder and add the credentials to use

**Comment by duftler** [comment]
Glad to hear it worked out.

@ewiseblatt I thought the installation script checked for the java version
at some point (I may just be remembering this wrong). If not, what do you
think about adding it?

**Comment by ewiseblatt** [comment]
The installation script does, but the path is different here. When I read
that last night I was wondering if we should put a check in the startup
scripts.

**Comment by duftler** [comment]
I think that'd be a good idea.

**Comment by khebbie** [comment]
Cool, thanks.
It would also be cool if the web app emitted the error from the log since you have to dig a bit around to find an error that the app probably already knows about

**Comment by ewiseblatt** [comment]
If you have a Google Cloud Platform account, you can see the Spinnaker log
files on the Logging panel of the Google Developer's Console for your
project (the one you deploy Spinnaker into, not the one you are managing).
The console will let you filter and search across all the log files, so you
can easily filter all the warning and error messages to see this type of
thing.

curl -s -q
https://raw.githubusercontent.com/spinnaker/spinnaker/master/google/google_cloud_logging/add_google_cloud_logging.sh
|
bash

If you are running an GCE image we built in the past week or two (e.g.
Click To Deploy), you already have this so just check the Google
Developer's Console.

Otherwise, I just submitted a way to install it from the web which should
work from anywhere (e.g. from AWS).
If you are not on GCP, then you'll need to follow these instructions to
give GCP authorization
https://cloud.google.com/logging/docs/agent/authorization#install_private-key_authorization
.

If you are on GCP then your VM needs logging-write scope. This is there by
default if you created your VM instance from the Google Developer's
Console. However, if you followed our instructions for using gcloud then
you probably wont have it because we only recommended the minimal Compute
Read/Write scope. If you are creating a new instance, I recommend at least
"--scopes=compute-rw,logging-write,monitoring-write" argument for the gcloud
create instance command.

- eric

**Comment by apmalla** [comment]
sudo tail -f clouddriver.log 
	at com.netflix.spinnaker.clouddriver.aws.provider.config.AwsProviderConfig$$EnhancerBySpringCGLIB$$da3a11a3$$FastClassBySpringCGLIB$$ffbad36b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at com.netflix.spinnaker.clouddriver.aws.provider.config.AwsProviderConfig$$EnhancerBySpringCGLIB$$da3a11a3.synchronizeAwsProvider(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)

**Comment by rushins** [comment]
i still have this issue and my JDK is 1.8 ? so what is wrong and i dont see clouddriver ?
