### ISSUE TITLE
Problem creating a new application "could not create application"

### ISSUE THREAD

**Issue by moshe0076** [spinnaker/spinnaker#839]
*Title*

Problem creating a new application "could not create application"

*Cloud Provider*

AWS

*Environment*

`I am running Spinnaker on AWS Ubuntu 14.04 installed with the script "bash <(curl --silent https://spinnaker.bintray.com/scripts/InstallSpinnaker.sh)"

*Feature Area*

Application

*Description*

Creating new application results in "could not create application"

*Steps to Reproduce*

Just create new application
*Additional Details*

The Problem is in Redis:
redis.clients.jedis.exceptions.JedisDataException: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
        at redis.clients.jedis.Protocol.processError(Protocol.java:117)
        at redis.clients.jedis.Protocol.process(Protocol.java:151)
        at redis.clients.jedis.Protocol.read(Protocol.java:205)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
        at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:196)
        at redis.clients.jedis.Jedis.set(Jedis.java:91)
        at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler.acquireRunKey(ClusteredAgentScheduler.java:100)
        at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler.acquire(ClusteredAgentScheduler.java:63)
        at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler.runAgents(ClusteredAgentScheduler.java:81)
        at com.netflix.spinnaker.cats.redis.cluster.ClusteredAgentScheduler.run(ClusteredAgentScheduler.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Workaround:
in redis-cli:
config set stop-writes-on-bgsave-error no

>>>>> But this is not a good  solution for the long run <<<<

**Comment by lwander** [comment]
What version of clouddriver are you running? `dpkg -l | grep clouddriver`

**Comment by bkarakashev** [comment]
I am getting the same error "**Could not create application**"
spinnaker-clouddriver            1.128.0-4

**Comment by bkarakashev** [comment]
I have found my problem.
I have just followed these instructions and it worked fine. [link](http://stackoverflow.com/questions/34788034/unable-to-create-an-application-now-accounts-listed-in-dashed-rectangle-beside)

**Comment by lwander** [comment]
Closing since it sounds like it's fixed!

**Comment by akrymets** [comment]
I just restarted the clouddriver and rosco services right after reconfiguring newly installed spinnaker (http://www.spinnaker.io/v1.0/docs/custom-configuration#section-about-the-different-yaml-files). And it worked. Before the restart of the services I had the "Could not create application" error
