### ISSUE TITLE
Jenkins poller dies when timing out on huge history in redis

### ISSUE THREAD

**Issue by riltsken** [spinnaker/spinnaker#877]
*Jenkins poller dies when timing out on huge history in redis*

*Environment*

Running spinnaker with cassandra and redis.

*Feature Area*

Igor jenkins poller

*Description*

Spinnaker stores meta information about builds it knows about and job information in redis so that it can trigger pipelines. Currently our production jenkins has some jobs with row history in the millions and more. Pulling the meta information out from redis for some of these jobs times out the igor poller, which causes the below exception to be thrown and in turn killing the poller.

*Steps to Reproduce*

If you really need this let me know and I can create some type of test scenario but I imagine just dump millions of rows into redis and forcing the below query to happen.

*Additional Details*

Below exception kills the poller. Can be tracked to this query https://github.com/spinnaker/igor/blob/master/igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsCache.groovy#L37

```
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
        at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:201)
        at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
        at redis.clients.jedis.Protocol.process(Protocol.java:141)
        at redis.clients.jedis.Protocol.read(Protocol.java:205)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
        at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:233)
        at redis.clients.jedis.Jedis.keys(Jedis.java:185)
        at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at com.netflix.spinnaker.igor.jenkins.JenkinsCache.getJobNames(JenkinsCache.groovy:43)
        at com.netflix.spinnaker.igor.jenkins.JenkinsCache$getJobNames.call(Unknown Source)
        at com.netflix.spinnaker.igor.jenkins.BuildMonitor.changedBuilds(BuildMonitor.groovy:139)
        at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:382)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
        at com.netflix.spinnaker.igor.jenkins.BuildMonitor$_onApplicationEvent_closure1_closure9.doCall(BuildMonitor.groovy:110)
        at sun.reflect.GeneratedMethodAccessor112.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1379)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1372)
        at org.codehaus.groovy.runtime.dgm$149.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at com.netflix.spinnaker.igor.jenkins.BuildMonitor$_onApplicationEvent_closure1.doCall(BuildMonitor.groovy:109)
        at com.netflix.spinnaker.igor.jenkins.BuildMonitor$_onApplicationEvent_closure1.doCall(BuildMonitor.groovy)
        at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at groovy.lang.Closure.call(Closure.java:423)
        at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:51)
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:103)
        at com.sun.proxy.$Proxy84.call(Unknown Source)
        at rx.Scheduler$Worker$1.call(Scheduler.java:120)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.net.SocketInputStream.read(SocketInputStream.java:127)
        at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:195)
        ... 62 common frames omitted
```

**Comment by riltsken** [comment]
One other thing I forgot to mention is the igor service is still up. Just the poller thread is dead.

**Comment by gardleopard** [comment]
@riltsken How many jobs do you have in jenkins?
This cache only stores one row for each jenkins job as far as I understand. 
[makeKey] (https://github.com/spinnaker/igor/blob/master/igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsCache.groovy#L83)

Does the poller die immediately or after a while?

**Comment by riltsken** [comment]
Hey @gardleopard Another thing I forgot to add is we have 3 jenkins. The one I assume is causing issues is our oldest one.

1) The poller dies after several days usually. 

2) As for how many jobs I couldn't get an exact count, but somewhere around 400 or more. My `find` command never seems to complete (some directories must be too big as it starts to run really slow). I looked at how many keys we had for "igor:Production:*" and it returned 418 (which is the jenkins I imagine we are having trouble with). Our other jenkins have ~100 keys each in redis.

**Comment by riltsken** [comment]
I assumed it was build information initially because our `Production` jenkins has some jobs with millions of rows of build history.

**Comment by gardleopard** [comment]
@riltsken I think netflix has a lot more jenkins jobs on one of their jenkins masters, so it should not be a problem. I would suspect that the redis server is struggling.

I will take a look at wrapping hysterix around the redis cache so that the poller will survive a timeout from redis, but I'm not sure that it is a good idea.

**Comment by riltsken** [comment]
@gardleopard I think you are right. I was just about to respond with a similar sentiment. The failure here is anecdotal to the real problem.

**Comment by riltsken** [comment]
![image](https://cloud.githubusercontent.com/assets/180066/15023152/672f17e4-11ec-11e6-9164-5744edb26081.png)

For reference some look at stats on the redis node. Unfortunately didn't have these up before the previous failures

**Comment by riltsken** [comment]
If there is nothing you can glean from the stats I will probably just put this on a bigger node in aws. Feel free to close this issue. If I continue to have performance problems I'll bring them up as needed.

**Comment by gardleopard** [comment]
I think the timeout comes from [here] (https://github.com/nok/redis-processing/blob/master/src/redis/clients/jedis/Protocol.java#L24) , so it requires a slow response from redis to happen.

**Comment by gardleopard** [comment]
@riltsken I added a config option to igor that lets you override the redis timeout. https://github.com/spinnaker/igor/commit/08201189676aa4d7a394c946b10d33864a7d4aed

In your spinnaker configuration files you can now override with:
```
redis:
  timeout: 30000
```

**Comment by riltsken** [comment]
Thanks!
