### ISSUE TITLE
Pipeline failing with no error description (web) and log message "Error occurred propagating authentication context"

### ISSUE THREAD

**Issue by nathan-v** [spinnaker/spinnaker#932]
AWS AMI using AWS IAM role for permissions. All functionality (Creating ASGs, ELBs, SGs, etc) is working correctly. I created and configured a pipeline. At the deployment step it appears to successfully read/pull the ASG config and then this line below shows in the logs. At that point the pipeline goes to a fatal state with no useful error message.

```
2016-06-09 22:28:52.300  INFO 21546 --- [  Retrofit-/ops] c.n.s.orca.clouddriver.KatoService       : <--- HTTP 400 http://localhost:7002/ops (45ms)
2016-06-09 22:28:52.301 ERROR 21546 --- [cTaskExecutor-1] c.n.s.security.AuthenticatedRequest      : Error occurred propagating authentication context

retrofit.RetrofitError: 400 Bad Request
    at retrofit.RetrofitError.httpError(RetrofitError.java:40)
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
    at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
    at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
    at retrofit.RxSupport$2.run(RxSupport.java:55)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at retrofit.Platform$Base$2$1.run(Platform.java:94)
    at java.lang.Thread.run(Thread.java:745)

2016-06-09 22:28:52.306  INFO 21546 --- [cTaskExecutor-1] c.n.s.o.kato.tasks.DisableInstancesTask  : Pipeline:4d118ed6-03e2-4f93-8ab2-25286ed8e500 disableInstances TERMINAL -- Batch step id: 28,  Task Outputs: {
  "exception" : {
    "exceptionType" : "RetrofitError",
    "operation" : "pushComplete",
    "details" : {
      "error" : "Validation Failed",
      "errors" : [ "EnableDisableInstanceDiscoveryDescription.credentials.discovery.not.configured" ],
      "responseBody" : "{\n  \"error\" : \"Validation Failed\",\n  \"errors\" : [ \"EnableDisableInstanceDiscoveryDescription.credentials.discovery.not.configured\" ],\n  \"status\" : \"BAD_REQUEST\"\n}",
      "kind" : "HTTP",
      "status" : 400,
      "url" : "http://localhost:7002/ops"
    },
    "shouldRetry" : false
  }
```

**Comment by robertsigler** [comment]
What does your clouddriver.yml configuration look like? Does your aws.account configuration have a 'discovery' URL property? I ran into this issue because I had not failed to configure discovery with my Eureka URL.

**Comment by ajordens** [comment]
Closing due to lack of activity.

Feel free to reach out to the Spinnaker slack if there are continued issues.
